### ISSUE TITLE
 Invalid argument supplied for foreach() CorreiosMethod.php on line 764

### ISSUE THREAD

**Issue by matheusjardimb** [pedro-teixeira/correios#107]
Mais alguém recebendo esse erro com frequência?

2015-08-10T19:04:49+00:00 ERR (3): Warning: Invalid argument supplied for foreach()  in magento\app\code\community\PedroTeixeira\Correios\Model\Carrier\CorreiosMethod.php on line 764

**Comment by jarjar123** [comment]
Olá @matheusjardimb 
Este erro está relacionado à alteração SHA: 91313fe70ec3ace71d443f86a48b580c46a2136a
Verifique se o arquivo `config.xml` foi atualizado corretamente (para suprimir o erro, a variável `add_postmethods` precisa de ao menos um nó filho).

Embora não impeça o funcionamento das cotações, este erro deverá ser corrigido em breve.

**Comment by matheusjardimb** [comment]
Olá @jarjar123, esse fix ainda não está disponível no módulo? 
Estou usando a v4.5 disponível no magento connect, então já deveria ter essa alteração, certo?

**Comment by rafaelpatro** [comment]
Olá @matheusjardimb 
Não. O erro ocorre a partir do commit que mencionei (SHA: 91313fe70ec3ace71d443f86a48b580c46a2136a)
Será resolvido em breve (a iteração sob uma lista vazia dispara o erro).
Aconselho apenas manter o __Developer Mode__ desativado. Assim o erro é registrado no log, mas não interrompe o funcionamento do módulo.

**Comment by rafaelpatro** [comment]
Só pra esclarecer. Eu também sou o usuário @jarjar123

**Comment by pedro-teixeira** [comment]
@jarjar123 esse problema continua aberto?

**Comment by jarjar123** [comment]
Sim. Ainda não foi corrigido. Mas não interfere no funcionamento da loja, apenas gera um log Warning.

**Comment by pedro-teixeira** [comment]
@jarjar123 ok, obrigado!

**Comment by rafa-acioly** [comment]
Como faço para resolver este erro? esta acontecendo comigo também!
