### ISSUE TITLE
Fatal Erro

### ISSUE THREAD

**Issue by mateusvg** [pedro-teixeira/correios#108]
Quando calculo o frete pela cotação de frete antes do cliente fazer o login o seguinte erro aparece!

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in app/code/core/Mage/Core/Model/Resource/Helper/Mysql4.php on line 300

já alterei os seguintes  arquivos:
php.ini.sample
.htaccess
.htaccess.sample
.htaccess08092015

Alterei a memoria de 64MB para 512MB
Quando desativo o modulo e coloco o modulo do magento de frete fixo volta ao normal!!
Uso o magento 1.8.1.0
Obrigado

**Comment by donardo** [comment]
Estou com o mesmo problema.

**Comment by jarjar123** [comment]
Boa tarde
Vc tem acesso SSH?
Se sim, executa esse comando e posta aqui o retorno:

    php -r 'phpinfo();' | grep memory_limit

**Comment by donardo** [comment]
Boa tarde, tenho sim, é uma VPS
Retorno: memory_limit => 256M => 256M

Tenho QUASE certeza que o problema não está vinculado a memória.

**Comment by Veiote** [comment]
Tem memoria ram disponível no vps? Ta rodando um site apenas?

**Comment by donardo** [comment]
O VPS tem 2Gb de espaço dedicado, tenho alguns outros sites rodando, mas nenhum que ocuparia toda a memória.

**Comment by donardo** [comment]
Aproveitando, ainda quando esse erro acontece o processo do PHP fica "pendurado" fica rodando até que ele caia em timeout ou então eu mate o processo.

**Comment by donardo** [comment]
Acabei de simular o erro. A situação é a mesma relatada pelo @mateusvg mas em outro arquivo.

Na url checkout/cart/ ao tentar fazer uma simulação de frete apresenta esse erro:

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /home/duck/public_html/lib/Varien/Db/Select.php on line 415

**Comment by jarjar123** [comment]
Dá uma conferida nos limites do MySQL também.
É bem possível q não esteja relacionado com a extensão. Tem muitos erros como este no Google.
Assim q tiver tempo analiso melhor.

**Comment by donardo** [comment]
Eu também estava pesquisando e realmente encontrei e estou achando que é do MySQL. Vou fazer mais alguns testes, se tiver alguma novidade posto aqui.

**Comment by jarjar123** [comment]
O Magento altera algumas variáveis do PHP durante a execução.
Cria um arquivo qualquer e roda esse trecho, pra conferir as variáveis:

    <?php
    require_once('app/Mage.php');
    Mage::app();
    $inis = ini_get_all();
    print_r($inis);
    ?>

**Comment by donardo** [comment]
https://gist.github.com/donardo/46276a7355ac07609396

**Comment by donardo** [comment]
Também queria comentar, que o módulo funciona, por exemplo utilizo ele em conjunto com o módulo de OCS-Magento-Brasil e funciona perfeitamente nessa tela. O problema mesmo se já só no carrinho para fazer uma consulta do valor do frete.

**Comment by donardo** [comment]
Atualizei o Magento para a última versão 1.9.2.1 e agora está apresentando esse erro.
Fatal error: Maximum execution time of 30 seconds exceeded in /home/duck/public_html/app/code/core/Mage/Core/Model/Config.php on line 1213

Sei que é do tempo de execução, mas isso acontecer porque entra em "loop" o script.

Para outros testes, instalei o módulo em um magento puro, mas no mesmo VPS, para testar e funciona perfeitamente, eliminando então as configurações de servidor. 

Mais alguma ideia do que possa ser?

**Comment by alex-andrade** [comment]
@donardo, se você verificar nos requisitos básicos do Magento, o timeout tem que ser de 1800s, e não 30s. Em tempo, uma vez tive um problema similar com este checkout(estava acertando o ambiente local de desenvolvimento). Se for o que eu estou pensando, pode ser o motivo do erro. No caso, ao digitar o cep neste checkout, são enviados dois requests, um para pegar os dados do cep, como rua, bairro e estado. O outro é calcular o frete em si. Lembro que, devido a demora na busca dos dados do cep, ou seja, o endereço, não sobrava muito tempo livre para executar o calculo do frete, retornando o erro acima. Por isto creio que o erro não acontece no Magento puro, por ele não ter que buscar o endereço numa base externa. Ele simplesmente calcula o frete e não tem que esperar outro script rodar.

**Comment by donardo** [comment]
@alex-andrade fiz o que você sugeriu, mesmo sabendo que não daria certo, e agora estouro a memória.
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 130968 bytes) in /home/duck/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php on line 861

Novamente, isso se da por o script entrar de alguma forma em um "loop infinto".

**Comment by donardo** [comment]
Continuo fazendo alguns testes, e estou começando achar que o problema está nas tabelas do MySQL. Não é programação nem configuração de servidor, mas sim alguma inconsistência em alguma(as) tabelas do DB que está gerando um loop infinito no script.

**Comment by donardo** [comment]
Problema resolvido. Estava na tabelas do MySQL mesmo.
Removi as tabelas flat de produtos e categorias refiz os index e começou a funcionar.
