### ISSUE TITLE
Erro  de peso ao "recomprar" pelo admin  (Lojista: O peso do produto deverá ser maior que zero...)

### ISSUE THREAD

**Issue by davirs** [pedro-teixeira/correios#111]
Olá. Todos os produtos da minha loja são configuráveis.
eu utilizo quilos como forma de medida.
todos os meus produtos tem peso 0.200 kg

pelo frontend tudo funciona normalmente... 
Hoje eu tive que fazer uma recompra de um pedido direto pelo admin do magento e apareceu a seguinte mensagem:

![screenshot_3](https://cloud.githubusercontent.com/assets/4355062/9647201/f49d6e8e-51b0-11e5-9ba4-af408c3388c7.png)

eu verifiquei todos os produtos do pedido e todos eles tem o peso definido...
nenhum erro aparece no console...

será que alguém poderia testar para descobrir-mos se o erro é somente aqui?

Valeu!

**Comment by pedro-teixeira** [comment]
@davirs pode fazer um teste com a versão do master? Tenho quase certeza que esse problema já foi resolvido.
