### ISSUE TITLE
Valor do frete não atualiza

### ISSUE THREAD

**Issue by raulclaudino** [pedro-teixeira/correios#112]
O módulo não soma a quantidade de produtos no carrinho, independentemente se é 1 ou 10 produtos, ele só calcula o custo de 1.

**Comment by jarjar123** [comment]
Olá Raul. Qual o peso e medidas do item em questão? Os Correios trabalham
com faixas de peso. Objetos até 300gr por exemplo tem o mesmo preço.

**Comment by raulclaudino** [comment]
Olá, 

Você tem razão, o meu produto é muito pequeno, cadastrei um pesado e ele calculou corretamente.

Muito obrigado pela ajuda.
