### ISSUE TITLE
Pedroteixeira_correios [101]: Weight zero

### ISSUE THREAD

**Issue by fabisoccol** [pedro-teixeira/correios#117]
Olá pessoal,

Estava usando o módulo sem nenhum problema, porém da semana passada para cá os valores pararam de aparecer e o seguinte erro aparece no Log:

29T16:26:37+00:00 DEBUG (7): pedroteixeira_correios [101]: Weight zero
2015-10-29T16:26:43+00:00 DEBUG (7): pedroteixeira_correios [101]: Weight zero
2015-10-29T16:26:50+00:00 DEBUG (7): pedroteixeira_correios [101]: Weight zero
2015-10-29T16:26:58+00:00 DEBUG (7): pedroteixeira_correios [101]: Weight zero

Já foi avaliar o produto que estava no carrinho e o peso está lá configurado certinho!

O site em testes é www.cozinhandoogalo.com.br

Alguém poderia me ajudar? :-(

#desesperototal

**Comment by jarjar123** [comment]
Olá @fabisoccol, segue algumas sugestões para solucionar seu problema.

* Verifica se o __peso__ que vc está configurando é o atributo correto. Acessa um produto no backend, e inspeciona o campo __peso__ (o `name` deve ser `product[weight]`)
* Não use espaços, vírgulas, letras (kg ou gr) no campo de peso (apenas números, e o __ponto__ como separador decimal).
* Verifique se o Formato do Peso está configurado corretamente como Kilos ou Gramas nas opções da extensão.
* Verifique todas as configurações acima a nível de loja.
* Verifique se o produto que contém o peso é __simples__ ou __pacote__.

**Comment by fabisoccol** [comment]
Olá @jarjar123 , muito obrigada pela ajuda.

Consegui resolver hoje. Foi a formatação do peso no Backend. Estava como Gramas.

Que alívio! :-)
