### ISSUE TITLE
Fatal error: Can't use function return value in write context in 

### ISSUE THREAD

**Issue by labofidea** [pedro-teixeira/correios#119]
Fatal error: Can't use function return value in write context in correios/app/code/community/PedroTeixeira/Correios/Model/Sro.php 116
Erro parece estar ocorrendo por causa do "trim", removi todos e o erro parou de ocorrer.
PHP V 5.3.29

**Comment by jarjar123** [comment]
Realmente, em algumas versões, a função `empty` do PHP deixa de aceitar qualquer coisa, exceto variáveis. O que faz todo sentido.
(apesar de que testei no PHP 5.5.3, e não apresentou erros)
Provavelmente está também relacionado ao `error_reporting` do PHP.
Mas uma correção aqui seria muito bem vinda.

**Comment by pedro-teixeira** [comment]
Corrigido nessa PR: https://github.com/pedro-teixeira/correios/pull/128
