### ISSUE TITLE
E-Sedex com diferença de valores de até 72%

### ISSUE THREAD

**Issue by radamiBR** [pedro-teixeira/correios#120]
O e-sedex por contrato dos correios esta dando porcentagem maior que correios de até 72% e máximo é 25% em alguns Estados, faço simulado da caixa pelo site dos correios da uma valor e no magento da outro.
Pac e Sedex estou usando sem contrato esta com os valores corretos.
Já tentei alterar parâmetro no arquivo CorreiosMethod.php e não tive sucesso, o que pode ser?

**Comment by jarjar123** [comment]
Pode informar os dados que usou no seu teste?
* Medidas da caixa ou produto testado
* Peso
* Ceps de origem e destino

**Comment by radamiBR** [comment]
Os produtos que envio pelo correios são de tamanhos diversos, não uso caixa padronizada.

Tamanho da caixa - Altura: 15 cm - Largura: 18 cm - Comprimento: 24 cm
Peso: 1 Kilo e 230 gramas
CEP Origem: 04110-000
CEP Destino: 57073-212

Simulado dos Correios SEDEX: R$ 53,90
No magento esta dando E-SEDEX: R$ 14,20
No contrato dos Correios o máximo do E-SEDEX é 25% o valor do SEDEX
Teria que dar R$ 40,42

**Comment by jarjar123** [comment]
Serviços iguais tem valores diferentes quando o código for diferente. Ex.:
Sedex pode ser 40010, 40436, etc. Os preços são diferentes para cada
código. Isso vale para as outras modalidades como E-Sedex e PAC. Sugiro
verificar através da url a seguir, usando seu contrato e senha:
http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdEmpresa=&sDsSenha=&sCepOrigem=04110000&sCepDestino=57073212&nVlPeso=1,230&nCdFormato=1&nVlComprimento=24&nVlAltura=15&nVlLargura=18&sCdMaoPropria=n&nVlValorDeclarado=0&sCdAvisoRecebimento=n&nCdServico=40010&nVlDiametro=0&StrRetorno=xml
Em 07/12/2015 18:14, "radamiBR" <notifications@github.com> escreveu:

**Comment by radamiBR** [comment]
Fiz teste da url acima ficou assim:
SEDEX normal R$ 65,50
SEDEX contrato R$ 60,16 de 8%
E-SEDEX contrato R$ 40,32 de 38%

Tem algum local no modulo pedro teixeira mais proximo dessa url acima.

Pois no meu magento correios esta dando valores de até 72% no contrato correios.

Obrigado.

**Comment by jarjar123** [comment]
Radami. Renova o cache dos Correios, caso esteja ativo, e tenta novamente,
com os mesmos itens. Ativa o log do Magento, e coloca aqui oq está sendo
registrado.
Em 08/12/2015 16:08, "radamiBR" <notifications@github.com> escreveu:

**Comment by radamiBR** [comment]
log do magento

2015-12-09T13:53:34+00:00 ERR (3): Notice: Undefined index:  httponly  in /home/httpd/vhosts/.com.br/httpdocs/app/code/core/Mage/Core/Model/Session/Abstract/Varien.php on line 96

2015-12-09T13:53:34+00:00 ERR (3): Notice: Undefined index:  secure  in /home/httpd/vhosts/.com.br/httpdocs/app/code/core/Mage/Core/Model/Session/Abstract/Varien.php on line 98
2015-12-09T13:53:34+00:00 ERR (3): Notice: Undefined index:  domain  in /home/httpd/vhosts/.com.br/httpdocs/app/code/core/Mage/Core/Model/Session/Abstract/Varien.php on line 100

2015-12-09T13:53:35+00:00 DEBUG (7): pedroteixeira_correios [cache]: mode=1 status=write key=40010x81019x41106_04_16_57073212

**Comment by jarjar123** [comment]
@radamiBR, o log está mostrando um peso de 400 gramas (0,4kg). E o peso que vc informou na comparação é de 1230gr. Talvez por isso os valores estejam tão diferentes. Dá uma conferida se os produtos estão com o peso correto.
Tem algum produto não _Simples_ no carrinho? _Configurável, Pacote, Agrupado_?

**Comment by radamiBR** [comment]
Todos os produtos estão cadastrado como Simples, no carrinho foi add alguns produtos que tem pesos variados entre 0,60 gramas cada, fiz outro teste no log saiu isso:

2015-12-10T10:45:37+00:00 DEBUG (7): pedroteixeira_correios [cache]: mode=1 status=write key=40010x81019x41106_31_12_57073212

Coloquei outro modulo do correios para teste o AV5 free, fiz teste com mesmo produto no carrinho e peso deu correto o valor E-SEDEX, já modulo que eu uso do pedro teixeira 4.6, esta dando essa diferença somente no E-SEDEX de até 72% e o normal pelo contrato e até 25%.

LOG AV5
2015-12-10T10:52:46+00:00 DEBUG (7): AV5 Correios: SELECT `tabela_correios`.* FROM `tabela_correios` WHERE ( ( servico in ('40010', '81019', '41106') )  AND (cep_destino_ini <= '40010000' AND cep_destino_fim >= '57073212') AND peso = '1')

**Comment by jarjar123** [comment]
@radamiBR, não entendi muito bem sua última mensagem.
Mas pra fazer uma comparação fidedigna, preciso que faça o seguinte:
*.Realize uma cotação no carrinho de compras
* Tome nota dos preços e do log
* Realize uma cotação através da URL, usando os parâmetros exibidos no log

_Como ler os parâmetros do log:_

    pedroteixeira_correios [cache]: mode=1 status=write key=40010x81019x41106_31_12_57073212

_o parâmetro `key` lê-se: Serviço1xServiço2\_Peso(hectogramas)\_LadoMédio(em cm)\_CEPdestino_

Concluindo, pega esses parâmetros do log, coloca na URL pra cotação, e posta aqui os resultados.
Obs.: Usar o lado médio em altura, largura e comprimento. Converter o peso para quilogramas.

**Comment by radamiBR** [comment]
Criei uma compra com 8 produtos que são pequenos, tamanho da caixa= altura:15cm - largura:18cm - comprimento:24cm - peso 500 gramas.

CEP remetente 04110-000 São Paulo
CEP destino 58042-000 Alagoas
Magento E-SEDEX R$ 16,51
Site dos Correios simulado SEDEX R$ 63,50
No contrato com os correios o E-SEDEX é 25% desconto no valor do SEDEX
Então o E-SEDEX para esse cep sai R$ 47,62

LOG MAGENTO
pedroteixeira_correios [cache]: mode=1 status=write key=40010x81019x41106_05_16_57073

Quando e usado essa mesma compra para CEP de São Paulo tem um diferença também exemplo abaixo

CEP remetente 04110-000 SP Vila Mariana
CEP destino Tatuapé SP Tatuapé
Magento E-SEDEX R$ 5,48
Site dos Correios simulado SEDEX R$ 14,90
Valor do contrato com correios R$ 11,17

**Comment by radamiBR** [comment]
Pelo módulo Pedro Teixeira faz conexão direta com webservice do correios teria como alterar o cálculo do correios  E-SEDEX de 500 gramas que padrão para 300 gramas pelo arquivo CorreiosMethod.php ou config.xml. 

Obrigado

**Comment by jarjar123** [comment]
Olá radami. Não consegui mais estudar seu caso devido a minha mudança de
endereço. Mas assim q puder eu retomo. Espero q consiga resolver logo.
Em 16/12/2015 10:41, "radamiBR" <notifications@github.com> escreveu:
