### ISSUE TITLE
Erro 500 ao inserir CEP de cidade sem PAC GF, quando o produto qualifica somente para tal modalidade.

### ISSUE THREAD

**Issue by brrods** [pedro-teixeira/correios#123]
O módulo na sua versão 4.5 funciona perfeitamente, até que insiro o CEP de Morro de São Paulo, na Bahia, que é: 45428-971.
O produto em teste é uma bicicleta, 15kg, dimensões: 100cm de comprimento, 80cm de altura, 30cm de largura. Produto configurado para PAC GF. Módulo funciona com mesmo produto quando a cidade de entrega é São Paulo, calculando o frete corretamente.
Talvez porque o correio não entregue usando PAC GF em Morro de São Paulo, dê esse erro?
A verificação de dimensões está ligada.
Qualquer ajuda é bem vinda! Valeus

**Comment by jarjar123** [comment]
Sim. Você está correto.
Segundo os Correios, o CEP informado não contempla o serviço de PAC GF.
Porém, caso vc tenha contatado a agência do destino, e verificado pessoalmente que estão aceitando PAC GF, você pode incluir na lista a seguir: https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L215

_Obs.: o tamanho está dentro do aceitável, na validação de dimensões do PAC GF_

**Comment by pedro-teixeira** [comment]
Obrigado pelo suporte @jarjar123

**Comment by brrods** [comment]
O problema não é aceitar ou não PAC GF, e sim a falta de tratamento do erro que faz com que o site simplesmente pare de funcionar para o usuário!

**Comment by brrods** [comment]
@pedro-teixeira , teria como reabrir esse issue levando em conta que quando uma cidade não tem e-sedex, o módulo simplesmente não mostra essa opção. Mas quando a cidade não tem PAC GF o módulo não trata o erro e faz o site inteiro quebrar...

**Comment by brrods** [comment]
Para reproduzir o erro:
http://ciclourbano.web1335.kinghost.net/index.php/teste.html
Adicione o produto acima ao carrinho.
Em seguida vá para a página do carrinho e digite o CEP: 01000001 (São Paulo) para calulcar o frete.
Verá que o módulo funciona.
Depois digite o CEP 45428-971 e peça para recalcular.
Aí acontece o erro, que deixa o site todo fora do ar.
Para corrigir limpe o cache e acesse o site novamente.

**Comment by brrods** [comment]
@jarjar123 , alguma luz? Obrigado!

**Comment by jarjar123** [comment]
Desculpe brrods, estou no meio de uma mudança de empresa e residência aqui.
Espero q consiga resolver em breve. Vou tentar te ajudar assim q tiver uma
brecha.
Em 18/12/2015 19:13, "brrods" <notifications@github.com> escreveu:

**Comment by rafaelpatro** [comment]
Olá @brrods 
Verifiquei que o sistema não valida a falta dos serviços de postagem. Então coloquei uma validação antes de enviar a requisição. O site não mais ficará fora do ar por causa disso. _(Embora eu não tenha conseguido reproduzir tal situação. Comigo simplesmente não exibia Correios, mas continuava aparecendo outros fretes.)_

Também não defini uma mensagem de erro, pois não sei exatamente o que colocar.

**Comment by pedro-teixeira** [comment]
A PR https://github.com/pedro-teixeira/correios/pull/140/files não corrige esse problema também?

**Comment by rafaelpatro** [comment]
Não. A PR #140 corrige aquele outro erro _Invalid argument supplied for foreach()_. É parecido mas não tem relação direta.
Mas já não fiz uma correção pra esse erro 500?! Esqueci a PR?

**Comment by pedro-teixeira** [comment]
Não lembro de ter recebido ela, pode linkar aqui se achar ela?

**Comment by amagen** [comment]
Estou com Erro 500 neste problema mesmo depois de ter atualizado o módulo, como vocês corrigiram o problema?

O CEP destino: 11330670 Qualifica apenas para PACGF o produto que quero enviar, porém é área com restrição de envio, da erro 500 e não grava no error_log do php, dai não consegui identificar onde arrumar o problema. 

Obrigado!

**Comment by rafaelpatro** [comment]
Consegue reproduzir o erro neste link?
http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=CalcPrecoPrazo
