### ISSUE TITLE
Validação de CEP incorreto

### ISSUE THREAD

**Issue by rafaelharus** [pedro-teixeira/correios#124]
Gostaria de saber se há algum tratamento para verificar o CEP digitado. Pois na loja o qual o módulo na versão 4.5.0 ao digitar o CEP: 01800-101 o mesmo valida normalmente, porém no site do Correios mostra como não encontrado na Base de dados.
Utilizo a versão do magento 1.7.2

**Comment by pedro-teixeira** [comment]
@rafaelharus a API de cálculo do frete que faz a validação do CEP, é tudo do lado dos Correios.
