### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by rafa-acioly** [pedro-teixeira/correios#126]
Atualizei o módulo em minha loja 1.9.2 e o seguinte erro é apresentado;

> 2015-12-15T21:58:11+00:00 DEBUG (7): pedroteixeira_correios [cache]: mode=0 status=write key=40010x41106x40215_01_16_07400885
2015-12-15T21:58:11+00:00 ERR (3): Warning: Invalid argument supplied for foreach()  in /home/alinefon/public_html/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php on line 764
2015-12-15T21:58:16+00:00 DEBUG (7): pedroteixeira_correios [cache]: mode=0 status=write key=40010x41106x40215_01_16_07400885
2015-12-15T21:58:16+00:00 ERR (3): Warning: Invalid argument supplied for foreach()  in /home/alinefon/public_html/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMetho d.php on line 764

Este erro impede que o cliente prossiga para o proximo passo na pagina de onepage checkout, apos selecionar o frete (PAC/SEDEX), o mesmo é redirecionado novamente para a pagina do carrinho.

**Comment by Xroy** [comment]
Ocorreu o mesmo comigo, alguma solução para o problema?

**Comment by rafa-acioly** [comment]
@Xroy ainda não recebi e nem consegui resolver, estou no aguardo tambem.

**Comment by Xroy** [comment]
@rafa-acioly 

Reinstalei o módulo e desabilitei o modo de debug do Magento.

Fora isso, adicionei um IF no arquivo /app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php, na linha 756

ficou assim: 

        if ($addMethods) {
            foreach ($addMethods as $configData) {
                $isValid = true;
                $isValid &= $this->_packageWeight >= $configData['from']['weight'];
                $isValid &= $this->_packageWeight <= $configData['to']['weight'];
                $isValid &= $this->_midSize >= $configData['from']['size'];
                $isValid &= $this->_midSize <= $configData['to']['size'];
                $isValid &= $this->_toZip >= $configData['from']['zip'];
                $isValid &= $this->_toZip <= $configData['to']['zip'];

                if ($isValid) {
                    $price   = $configData['price'];
                    $days    = $configData['days'];
                    $method  = $configData['code'];
                    foreach ($cServico as $servico) {
                        if ($servico->Codigo == $method) {
                            if (!empty($price)) {
                                $servico->Valor = number_format($price, 2, ',', '');
                            }
                            if (!empty($days)) {
                                $servico->PrazoEntrega = $days;
                            }
                            $servico->EntregaDomiciliar = 'S';
                            $servico->EntregaSabado     = 'S';
                            $servico->Erro              = '0';
                            $servico->MsgErro           = '<![CDATA[]]>';
                        }
                    }
                }
            } 
        }


Resolveu meu problema! =D

**Comment by fabisoccol** [comment]
Pessoal, eu desisti de tentar arrumar o erro ou encontrá-lo, então instalei o módulo https://www.magentocommerce.com/magento-connect/calculo-de-frete-dos-correios.html e está até mais rápido!

Funcionou corretamente com o OSC 6 e o Magento 1.9.2.x!

**Comment by pedro-teixeira** [comment]
Resolvido na versão em master.
