### ISSUE TITLE
Rastreio do envio dá erro - MageMojo

### ISSUE THREAD

**Issue by albertobraschi** [pedro-teixeira/correios#129]
Na loja de um cliente hospedada na MageMojo não estava aparecendo o rastreio do pedido.
Mas localmente, aparecia.

Apresentava o seguinte erro:
            [carrier] => pedroteixeira_correios
            [carrier_title] => Correios
            [error_message] => Esse método de envio está fora do ar. Por favor entre em contato conosco.

Alterei no Correios/Model/Carrier/CorreiosMethod.php linha 581
	    $client->setAdapter('Zend_Http_Client_Adapter_Curl');

e voltou a funcionar perfeitamente.

**Comment by jarjar123** [comment]
Legal @albertobraschi ! Pena que a _cache_ ficará desativada.
Mas foi por isso que implementei a _cache_ dessa forma. Usando outro _adapter_ vc contorna o problema, e tem mais tempo para resolvê-lo.
Além disso vc pode customizar um _adapter_ pra vc, sem interferir nas outras funções do módulo.

**Comment by albertobraschi** [comment]
Vou checar isso @jarjar123
