### ISSUE TITLE
Validação do Peso

### ISSUE THREAD

**Issue by fcmiao** [pedro-teixeira/correios#130]
Estou tendo dificuldades em relação à validação do peso.
O módulo calcula sedex para produtos com mais de 30Kg, não consegui reproduzir nenhuma invalidação em relação à peso. 
Instalei o módulo numa instalação limpa de magento e o problema persiste.
Está tudo configurado para tratamento em Kilos.
Os amigos teriam alguma sugestão para resolver essa questão?

**Comment by jarjar123** [comment]
Boa tarde @fcmiao 
Verifica se a divisão de pacotes não está ativa nas configurações do módulo.
![image](https://cloud.githubusercontent.com/assets/3688798/12983145/189b1870-d0cf-11e5-8050-b2fcf30a0eb4.png)

Precisa estar desabilitada para funcionar como vc quer.
Espero ter ajudado. Abraço

**Comment by fcmiao** [comment]
Bingo!
Era exatamente isso, muito obrigado @jarjar123 !
Talvez esse caso possa ser tratado numa próxima versão, pois acho que se existe apenas 1 item no carrinho, não deveria haver divisão de pacotes nesse caso.

**Comment by leandromarques** [comment]
Obrigado @jarjar123, ajudou aqui também!
