### ISSUE TITLE
Erro dentro do Administrativo

### ISSUE THREAD

**Issue by fabisoccol** [pedro-teixeira/correios#134]
Olá Pessoal, alguém já teve este erro dentro do Administrativo ao clicar para editar um produto??

Warning: include(PedroTeixeira/Correios/Model/Source/PostMethods.php): failed to open stream: No such file or directory  in /chroot/home/echarmec/echarme.com.br/html/lib/Varien/Autoload.php on line 94

#0 /chroot/home/echarmec/echarme.com.br/html/lib/Varien/Autoload.php(94): mageCoreErrorHandler(2, 'include(PedroTe...', '/chroot/home/ec...', 94, Array)
#1 /chroot/home/echarmec/echarme.com.br/html/lib/Varien/Autoload.php(94): Varien_Autoload::autoload()
#2 [internal function]: Varien_Autoload->autoload('PedroTeixeira_C...')
#3 [internal function]: spl_autoload_call('PedroTeixeira_C...')
#4 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Model/Config.php(1352): class_exists('PedroTeixeira_C...')
#5 /chroot/home/echarmec/echarme.com.br/html/app/Mage.php(463): Mage_Core_Model_Config->getModelInstance('pedroteixeira_c...', Array)
#6 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(383): Mage::getModel('pedroteixeira_c...')
#7 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(203): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()
#8 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tab/Attributes.php(70): Mage_Adminhtml_Block_Widget_Form->_setFieldset(Array, Object(Varien_Data_Form_Element_Fieldset), Array)
#9 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(144): Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Attributes->_prepareForm()
#10 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Form->_beforeToHtml()
#11 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tabs.php(79): Mage_Core_Block_Abstract->toHtml()
#12 /chroot/home/echarmec/echarme.com.br/html/app/code/local/Webtex/Giftcards/Block/Adminhtml/Catalog/Product/Tabs.php(40): Mage_Adminhtml_Block_Catalog_Product_Edit_Tabs->_prepareLayout()
#13 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Block/Abstract.php(293): Webtex_Giftcards_Block_Adminhtml_Catalog_Product_Tabs->_prepareLayout()
#14 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#15 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'product_tabs')
#16 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/catal...', 'product_tabs')
#17 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#18 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#19 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#20 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#21 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(Array, true, true)
#22 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Adminhtml/controllers/Catalog/ProductController.php(250): Mage_Adminhtml_Controller_Action->loadLayout(Array)
#23 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_ProductController->editAction()
#24 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#25 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#26 /chroot/home/echarmec/echarme.com.br/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#27 /chroot/home/echarmec/echarme.com.br/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#28 /chroot/home/echarmec/echarme.com.br/html/index.php(84): Mage::run('', 'store')
#29 {main}

**Comment by pedro-teixeira** [comment]
@fabisoccol provavelmente algum problema na instalação do módulo, conseguiu fazer funcionar?

**Comment by Andrefcp** [comment]
Olá, Acabei de atualizar os arquivos da versão 4.8.0 (baixada pela loja Magento) e deu o seguinte erro ao acessar  a "Forma de Entrega" dentro do ADMIN.
O que pode ser?

a:5:{i:0;s:187:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'turminha_mage1.correios_postmethods' doesn't exist, query was: SELECT `main_table`.* FROM `correios_postmethods` AS `main_table`";i:1;s:3607:"#0 /chroot/home/turminha/turminhakids.com.br/html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /chroot/home/turminha/turminhakids.com.br/html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /chroot/home/turminha/turminhakids.com.br/html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /chroot/home/turminha/turminhakids.com.br/html/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /chroot/home/turminha/turminhakids.com.br/html/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#6 /chroot/home/turminha/turminhakids.com.br/html/lib/Varien/Data/Collection/Db.php(740): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#7 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 /chroot/home/turminha/turminhakids.com.br/html/lib/Varien/Data/Collection/Db.php(572): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 /chroot/home/turminha/turminhakids.com.br/html/lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#10 /chroot/home/turminha/turminhakids.com.br/html/app/code/community/PedroTeixeira/Correios/Model/Source/PostMethods.php(26): Varien_Data_Collection->getIterator()
#11 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(463): PedroTeixeira_Correios_Model_Source_PostMethods->toOptionArray(true)
#12 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#13 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#14 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#15 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#16 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#17 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#18 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#20 /chroot/home/turminha/turminhakids.com.br/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#21 /chroot/home/turminha/turminhakids.com.br/html/index.php(83): Mage::run('', 'store')
#22 {main}";s:3:"url";s:99:"/index.php/turminha_admin/system_config/edit/section/carriers/key/db468938f0d85c7431e275ebc0ef0031/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by rafaelpatro** [comment]
@Andrefcp, a atualização não foi bem sucedida, provavelmente por que sua versão era diferente de 4.7.0.
O número da versão deve ser baixado para 4.7.0 na tabela _core_resource_.
