### ISSUE TITLE
CEP - valores predefinidos

### ISSUE THREAD

**Issue by screamonei** [pedro-teixeira/correios#135]
Olá, quando o usuário vai pra finalização do pedido mesmo sem estar logado, já vem definido os valores de PAC e SEDEX. Ajuda?

**Comment by rafaelpatro** [comment]
Olá @screamonei 
Não sei se consegui entender sua pergunta.
Mas só pra esclarecer...

A cotação de frete __no carrinho__ de compras só é reutilizada __na finalização__ do pedido, se a opção de _cache_ estiver ativa, a opção de _prioridade da cache_ também estiver ativa, e os parâmetros do carrinho permanecerem iguais. Caso contrário, a loja realizará uma nova cotação de frete na finalização do pedido.
