### ISSUE TITLE
Webservice correios descontinuado

### ISSUE THREAD

**Issue by mayconheerdt** [pedro-teixeira/correios#136]
Olá!

Recentemente tivemos o desligamento da API antiga dos correios por um curto período, o que nos levou a entrar em contato com os responsáveis para verificar o motivo. 

Descobrimos que a API será descontinuada, sendo assim, IMPRETERIVELMENTE **APÓS O DIA 04/04/2016** o link antigo estará indisponível.

Acredito que isso afetara a extensão de modo geral, impedindo o rastreamento.

Já há alguma solução para essa alteração na API?

https://groups.google.com/forum/#!msg/magentobr/8znacsF7HZ4/TuH8mxtHHwAJ

QUESTIONAMENTO:
Acredito que os Correios hoje mudaram o link para rastreamento de objetos. Nós utilizávamos o link http://websro.correios.com.br/sro_bin/txect01$.startup?P_LINGUA=001&P_TIPO=001 que agora não existe mais.
O problema é que a minha loja virtual (e todas as outras do país que trabalham com os Correios!) enviam para os seus clientes um link com o rastreamento dos objetos. Hoje, devido à este problema, estamos recebendo diversas reclamações sobre isto.
Qual é o link agora que posso fornecer aos clientes? Tem como resolver isto rápido ou restabelecer o antigo?

---------------------------
RESPOSTA:
O link anterior faz parte de uma plataforma descontinuada, sem o devido suporte.
O novo ambiente tem tamanho e qualidade de informação compatíveis com o que pede o mercado.
Solicitei hoje e IMPRETERIVELMENTE ATÉ O DIA 04/04/2016 o link antigo estará disponível, tendo em vista um intervalo muito grande entre a comunicação (desde 2014) até a execução do desligamento.
Peço que coloquem esse prazo no radar de vocês de forma a ajustarem as aplicações para o novo ambiente para que não tenhamos mais esse tipo de problema!
Novo endereço de parâmetros:
http://webservice.correios.com.br/service/rastro/Rastro.wsdl

**Comment by rafaelpatro** [comment]
Não encontrei informação sobre essa mudança no site dos Correios.

Quanto à atualização automática: O rastreamento via SRO XML continua com o mesmo link no site dos Correios. O manual vigente ainda é de fev/2014. Logo acredito que continuará funcionando. Segue print.
![image](https://cloud.githubusercontent.com/assets/13813964/13829000/5a2584c6-eba3-11e5-8814-a30c5d598809.png)

Já o rastreamento via backend não sei, precisa pesquisar mais.

**Comment by rafaelpatro** [comment]
Nenhum informação no site dos Correios.
Só consegui encontrar o manual no Google: http://www.corporativo.correios.com.br/encomendas/sigepweb/doc/Manual_de_Implementacao_do_Web_Service_SIGEPWEB_Logistica_Reversa.pdf

**Comment by rafaelpatro** [comment]
Infelizmente o manual não descreve o XML de retorno para o rastreamento.
Só encontrei o exemplo da requisição: Rastreamento – Método eventos()

	<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:res="http://resource.webservice.correios.com.br/">
		<soapenv:Header/>
		<soapenv:Body>
		<res:buscaEventosLista>
		<usuario>ECT</usuario>
		<senha>SRO</senha>
		<tipo>L</tipo>
		<resultado>T</resultado>
		<lingua>101</lingua>
		<objetos>TE123456785AA</objetos>
		<objetos>TE123456785AB</objetos>
		</res:buscaEventosLista>
		</soapenv:Body>
	</soapenv:Envelope>

Enfim, não é difícil adaptar essa mudança ao PedroTeixeira_Correios. Mas seria bom saber o que esperar dos métodos no webservice. Apesar de extenso, o manual está bem incompleto.

**Comment by mayconheerdt** [comment]
Certo @rafaelpatro. A informação que tenho é que essa api antiga será descontinuada dia 04/04/2016. Ela foi desligada à alguns dias, porém, por solicitação nossa, foi novamente religada para que possamos ter tempo de ajustar esses itens.

Solicitei a eles algum comunicado ou algo desse tipo, e o único retorno que me derão, foi que a nova API já está ativa desde 2014 e a documentação nova está desde esse ano também no site dos correios.

É possível efetuar essa alteração na extensão antes dessa data?

Valeu!

**Comment by rafaelpatro** [comment]
Estou muito atarefado há semanas, mas a alteração é bem simples. E se eu
conseguir resolver algo, com certeza compartilho aqui.

**Comment by rafaelpatro** [comment]
Oi @mayconheerdt 
Estou atualizando esse branch https://github.com/rafaelpatro/correios/tree/tracking_update
Mas estou com dificuldade para testar, se puder testar e me enviar os logs agradeço.

**Comment by rafaelpatro** [comment]
Só pra constar, o link antigo continua funcionando.

**Comment by JoabMendes** [comment]
Descotinuaram o link hoje. Estou tentando usar o ws deles com SOAP, mas parece que preciso de um usuário e senha pra ter acesso. /:

**Comment by rafaelpatro** [comment]
Olá @JoabMendes ! O módulo já está configurado para utilizar o SOAP, no lugar do websro. Verifique se sua versão é a mais recente.

**Comment by JoabMendes** [comment]
Opa @rafaelstz, eu estava tentando implementar meu próprio módulo em outra linguagem e acabei parando aqui nesse issue.Tentei implementar mas vi que preciso criar um usuário/senha para consumir o serviço.

Você saberia me dizer se existe algum login (usr/pass) público para que isso seja feito?

**Comment by rafaelpatro** [comment]
Sim.
Usuário ECT
Senha SRO

**Comment by JoabMendes** [comment]
@rafaelpatro vou testar, muito obrigado.

**Comment by rodurma** [comment]
Pelo visto a parte de tracking agora somente pode buscar pacote por pacote (antes era permitido buscar muitos pacotes de uma vez) para pegar os eventos de trancking. E pelo que vi está trazendo somente o último evento.

**Comment by rafaelpatro** [comment]
@rodurma, é exatamente o caso da issue #279.
Se quiser continuar monitorando as encomendas, precisa contatar o representante comercial dos Correios, e pedir um usuário e senha para o SRO.
Se não quiser mais o monitoramento automático, basta desativar removendo a [tag crontab](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L1096).

**Comment by chipytux** [comment]
Use o site http://linktrack.mooo.com/ ou faça simplemente http://linktrack.mooo.com/RX704890085CN/html. Ele é bem rápido e faz a consulta direto no site dos correios.
