### ISSUE TITLE
Peso e dimensões predefinidas

### ISSUE THREAD

**Issue by fchiqueto** [pedro-teixeira/correios#142]
Pessoal queria saber se tem como predefinir os valores de peso e dimensões dos produtos para calculo de frete, no caso penso em algo assim sempre que for consultar o frete o modulo carregar os valores predefinidos ignorando os valores cadastrados no produto, tanto para o produto simples e configuráveis. 

Obrigado

**Comment by pedro-teixeira** [comment]
@fchiqueto você pode configurar a altura, comprimento e largura padrão nas configurações do módulo.

**Comment by fchiqueto** [comment]
Olá @pedro-teixeira e o peso teria como deixar ele predefinido? Estou tentando colocar o calculo de frete na página do produto e estou tento erro por causa dos configuráveis então pensei em predefinir um peso para que não de erro.

**Comment by pedro-teixeira** [comment]
@fchiqueto não, o peso é por produto, vou deixar seu issue aberto.

**Comment by fchiqueto** [comment]
Obrigado @pedro-teixeira ! Pensei em uma solução assim porém seria egoísta da minha parte já que só iria servir a mim ou a pouquíssimas pessoas. Consegui fazer o calculo e está funcionando certo menos com os configuráveis.
