### ISSUE TITLE
Esse método de envio está fora do ar. Por favor entre em contato conosco.

### ISSUE THREAD

**Issue by guicavalcant** [pedro-teixeira/correios#143]
Me parece que o problema é ao conectar no webservice do correio. Alguém mais com este problema?

**Comment by fchiqueto** [comment]
Também estou com esse problema @guicavalcant :(

**Comment by ZamoraSOFT** [comment]
Infelizmente o Webservice dos Correios está fora do ar: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdEmpresa=15314910&sDsSenha=&sCepOrigem=04046100&sCepDestino=13806236&nVlPeso=0.4&nCdFormato=1&nVlComprimento=30&nVlAltura=30&nVlLargura=30&sCdMaoPropria=n&nVlValorDeclarado=0&sCdAvisoRecebimento=n&nCdServico=40096,41068&nVlDiametro=0&StrRetorno=xml&nIndicaCalculo=3

**Comment by ZamoraSOFT** [comment]
Pessoal: https://github.com/pedro-teixeira/correios/issues/136

**Comment by agusddt** [comment]
Eu tenho agora esse problema...
