### ISSUE TITLE
Embalagens diferentes no mesmo pedido

### ISSUE THREAD

**Issue by fabiobig** [pedro-teixeira/correios#144]
Ola Pessoal,
  Tenho que enviar duas mercadorias no mesmo pedido as quais possuem embalagens com dimensões diferentes.
  Se as embalagens são de dimensões diferentes o Correio cobra como se fosse dois despachos separados, mesmo que seja para o mesmo endereço, contudo o módulo soma as dimensões de ambas embalagens para verificar o peso volumétrico e o módulo considera como se fosse o despacho de apenas um pacote. Isso gera prejuízo no cálculo do frete.
  Alguém pode me ajudar a respeito ?

  Abraços à todos  

Fábio Bignotto

**Comment by rafaelpatro** [comment]
![image](https://cloud.githubusercontent.com/assets/13813964/14209340/11f2f0b8-f7fa-11e5-8ae1-05915bcabbc3.png)

Nessa questão de múltiplos objetos, a extensão trata da seguinte maneira.

1. O módulo não gerencia objetos, mas o carrinho como um todo.
2. Se você ativar a Divisão de Pacotes:
  1. O carrinho será dividido até se adequar aos limites da ECT Correios.
  2. A extensão considera o quociente como objeto da cotação.
  3. O resultado da cotação é então multiplicado pelo número de objetos.
  4. O valor do frete é como a cotação de diversos objetos enviados separadamente.
3. Um objeto pode ficar maior, mais pesado e mais caro do que o esperado. Porém, inevitavelmente outro objeto ficará menor, mais leve e mais barato. Se as dimensões e peso dos produtos estiverem corretamente cadastradas, dificilmente haverá prejuízo.

**Comment by fabiobig** [comment]
Prezado Rafael,

 

            Primeiramente obrigado pela cordialidade na pronta resposta.

 

Fiz a simulação com produtos que possuem as seguintes características cadastradas 

 

            Produto (1)

                        Dimensões: 29 cm x 29 cm x 42 cm

                        Peso :  2,5 Kg

            Produto (2)

                        Dimensões: 15 cm x 03 cm x 100 cm

                        Peso :  0,058 Kg   58 gr

 

Ativei a divisão de pacotes e obtive os seguintes resultados no carrinho na despesa de PAC de SP Capital  p: SP Capital :

 

Frete informado com compra só do produto (1) :  R$ 17,30

Frete informado com compra só do produto (2) :  R$ 14,80

Frete informado com compra do produto (1) e (2) juntos :  R$ 17,30

 

Conclusão: não esta calculando como se fosse despachos separados. 

 

O correto não seria no último caso resultar o frete de R$17,30 + 14,80 = R$ 32,10  ?

 

 

            Atenciosamente

    

      Fábio Bignotto

 

    logo_print

        fabiobig@kaup.com.br

       www.kaup.com.br <http://www.kaup.com.br/> 

       11 22286339  |  11 97298-3865  

 

 

De: Rafael Patro [mailto:notifications@github.com] 
Enviada em: sexta-feira, 1 de abril de 2016 11:38
Para: pedro-teixeira/correios
Cc: fabiobig
Assunto: Re: [pedro-teixeira/correios] Embalagens diferentes no mesmo pedido (#144)

 

 <https://cloud.githubusercontent.com/assets/13813964/14209340/11f2f0b8-f7fa-11e5-8ae1-05915bcabbc3.png> Imagem removida pelo remetente. image

Nessa questão de múltiplos objetos, a extensão trata da seguinte maneira.

1.	O módulo não gerencia objetos, mas o carrinho como um todo.
2.	Se você ativar a Divisão de Pacotes: 

1.	O carrinho será dividido até se adequar aos limites da ECT Correios.
2.	A extensão considera o quociente como objeto da cotação.
3.	O resultado da cotação é então multiplicado pelo número de objetos.
4.	O valor do frete é como a cotação de diversos objetos enviados separadamente.

3.	Um objeto pode ficar maior, mais pesado e mais caro do que o esperado. Porém, inevitavelmente outro objeto ficará menor, mais leve e mais barato. Se as dimensões e peso dos produtos estiverem corretamente cadastradas, dificilmente haverá prejuízo.

**Comment by rafaelpatro** [comment]
As dimensões q informou não excedem o limite dos Correios. Logo não ativa a
divisão de pacotes.
Em 01/04/2016 14:50, "fabiobig" <notifications@github.com> escreveu:

**Comment by fabiobig** [comment]
Rafael,
  Nesse exemplo o Correio vai cobrar o despacho de 2 envios no valor de R$17,30 + 14,80 = R$ 32,10 e o módulo vai informar o cliente o valor de R$ 17,30. O prejuízo fica grande para ser assumido pela loja.
  Você nos sugere alguma solução nesse caso para chegar mais próximo da realidade ?

**Comment by jarjar123** [comment]
A soma da cubagem funciona assim...

15 x 3 x 100 / 6000
+
29 x 29 x 42 / 6000
=
Acho que dá uns 6...kg/m3

Ou seja o algoritmo de divisão é falho, pois trata os itens do carrinho
como peças iguais. Bom pra grandes quantidades de um item. Mas se vc vender
uma vassoura e uma bola de futebol no mesmo pedido, será péssimo.

1. Uma solução seria alterar o algoritmo para tratar itens com dimensões
diferentes, e melhorar a aproximação do frete. Ótimo.

2. Outra sugestão seria ajustar o frete de itens compridos no preço do
produto. Ruim. Mas melhor q nada

3. Colocarmos uma opção de isolamento no produto. Cotar o frete
separadamente para produtos previamente configurados. Nesse caso vassouras
sempre seriam cotadas isoladamente. Bom.
Em 01/04/2016 22:23, "fabiobig" <notifications@github.com> escreveu:

**Comment by rafaelpatro** [comment]
Esse é o problema que enfrentamos:
https://pt.wikipedia.org/wiki/Problema_da_mochila

**Comment by fabiobig** [comment]
OK pessoal.

**Comment by fabiobig** [comment]
Obrigado pelo retorno  Vou tentar fazer algumas modificações e se tiver um resultado melhor lhes aviso
Grande abraços à todos.

**Comment by rafaelpatro** [comment]
Alguma novidade @fabiobig ?
Não sei se é aplicável aqui, mas pensei em utilizar o algoritmo _guloso_ do problema da mochila, com algumas ressalvas. Como a complexidade desse algoritmo é exponencial, sugiro unir os itens de menor tamanho, afim de diminuir a complexidade a um limite razoável.

Exemplo: Máximo de 10 itens no carrinho

1. Se o carrinho possui mais de 10 itens, os 2 menores itens são convertidos em 1 item com a soma dos volumes.
2. A etapa 1 se repete até haver apenas 10 itens.
3. Calcular todas as possibilidades de tamanho para o carrinho (arranjar os 10 itens 2 a 2, 3 a 3, 4 a 4, etc).
4. Escolher o arranjo de menor volume.

A complexidade pode ser aumentada ou diminuída, de acordo com os recursos de hardware.
Só resta saber como codificar isso, considerando cada item com 3 dimensões. Kkkkk
Alguém afim de contribuir?

**Comment by pedro-teixeira** [comment]
@fabiobig se conseguir uma solução envie uma pull request!
