### ISSUE TITLE
Erro ao  criar/alterar produtos após desinstalação do Módulo

### ISSUE THREAD

**Issue by MichelMoraes** [pedro-teixeira/correios#145]
Bom dia, como corrijo este erro,  instalei o  módulo, apos desinstalá-lo não altero nem crio mais produtos,  instalei o modulo e voltou ao  normal porém não  deixa desabilitá-lo, da um erro "não  pode repetir o atributo tamanho do produto",  como  resolvo isso? E quando vou fazer uma compra  a  entrega PAC fica em branco  ficando  habilitado somente o  botao para TIckar.

**Comment by rafaelpatro** [comment]
Olá @MichelMoraes 
Verifiquei que o erro está ligado a variável _postmethods_ (ou _Serviços de Entrega_).
Basicamente se desinstalar a extensão (via Magento Connect ou remover arquivos), precisa remover também os atributos criados pelo módulo, durante a instalação.

Infelizmente não sei uma solução simples pra isso. Até onde sei, o Magento não permite executar rotinas de desinstalação. Logo, esse problema afeta qualquer extensão que faça uso de novos atributos.

Sugiro apenas desativar o Método de Entrega sem desinstalá-lo, e tudo continua funcionando.
Se tiver coragem, é só remover o atributo no banco de dados do Magento (tabela eav_attribute). Comigo funcionou!

**Comment by MichelMoraes** [comment]
Obrigado @rafaelpatro , vlw pela atenção, a  solução no meu caso  foi começar tudo de novo e não instalar módulos  free e "pernetas" assim  evito  transtornos e trabalho com  ferramentas  de qualidade e suporte especializado. Obrigado .

**Comment by RubensSalles** [comment]
Olá Rafael

Segui suas orientações e Funcionou corretamente.
Basta acessar o banco de dados e na tabela (eav_attribute) Remover a tabela criada pelo Modulo dos Correios.
