### ISSUE TITLE
Não consigo usar - Ajuda!

### ISSUE THREAD

**Issue by apzeiro** [pedro-teixeira/correios#147]
Pessoal, ultimamente eu tenho usado o módulo de frete https://github.com/willstorm/correios
Resolvi voltar a testar esse do Pedro que é super recomendado por todo mundo. Acontece que eu não consigo que o cálculo apareça no carrinho?

Tem alguma mágica, além da configuração padrão? Estou testando no Magento 1.9
No meu carrinho só acusa que o correio está fora do ar, mas acessando os correios parece estar online normalmente:
[TESTE](http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdEmpresa=15314910&sDsSenha=&sCepOrigem=04046100&sCepDestino=13806236&nVlPeso=0.4&nCdFormato=1&nVlComprimento=30&nVlAltura=30&nVlLargura=30&sCdMaoPropria=n&nVlValorDeclarado=0&sCdAvisoRecebimento=n&nCdServico=40096,41068&nVlDiametro=0&StrRetorno=xml&nIndicaCalculo=3
)
Não sei que bola eu estou comendo, mas agradeceria se alguém desse um caminho pra eu verificar.

Obrigado.

**Comment by jarjar123** [comment]
Baixa a última versão
Confere se os serviços estão marcados
![image](https://cloud.githubusercontent.com/assets/3688798/14580540/a57e7750-03a6-11e6-87cd-5222d8e8c193.png)
Desativa o filtro de serviços (se ativar precisa configurar cada produto)
![image](https://cloud.githubusercontent.com/assets/3688798/14580567/5da06366-03a7-11e6-9c34-8583d14513fe.png)

**Comment by apzeiro** [comment]
A versão do módulo instalada é a 4.5.0. Creio que seja a última.
A loja não possui serviços com contrato. Deve-se marcar mesmo assim?
Não funciona ainda.

**Comment by wesleybpereira** [comment]
Acabei de instalar em uma loja do zero e não calcula a estimativa de frete no carrinho de compras. Alguém pode nos ajudar?

**Comment by wesleybpereira** [comment]
Nossa! Acabei de encontrar o "erro". Marquei a opção Mostrar Método Mesmo se Não Aplicável para Sim e funcionou.

Valeu!

**Comment by apzeiro** [comment]
Aqui continua sem funcionar.

**Comment by pedro-teixeira** [comment]
@apzeiro conseguiu fazer funcionar? Com certeza é alguma configuração ou tema. Como não tem indícios de ser um problema no módulo vou fechar a issue.
