### ISSUE TITLE
Dados do Atributo no sql

### ISSUE THREAD

**Issue by richard-nexxus** [pedro-teixeira/correios#149]
Olá, percebi que na versão do magento 1.9.2.2 no banco de dados não é criado as linhas de Altura, Comprimento e Largura na tabela catalog_product_flat_1. Alguem saberia me dizer onde está sendo criado eles?

Agradeço desde já

**Comment by rafaelpatro** [comment]
Olá @richard-nexxus 
Os atributos são inseridos na tabela _eav_attribute_.
Tente reindexar o catálogo de produtos, para que o Magento refaça a tabela _flat_.
As tabelas _flat_ são gerenciadas pelo Magento. Servem para otimizar a constante consulta pelos atributos. O sufixo numérico indica a loja (store), de forma que você pode ativar ou não esse recurso para cada loja.

**Comment by richard-nexxus** [comment]
Deu certo!!

Obrigado
