### ISSUE TITLE
Referência de Quote / Items fora do padrão

### ISSUE THREAD

**Issue by mateus007** [pedro-teixeira/correios#151]
Pedro,
Estava analisando seu módulo em um de meus clientes e detectei que você utiliza o quote da sessão do carrinho do usuário para recuperar os itens no momento do cálculo:

`Mage::getModel('checkout/cart')->getQuote()->getAllVisibleItems();`

De acordo com o padrão do método `collectRates` no Magento, você deve recuperar os itens através da classe `Mage_Shipping_Model_Rate_Request` que vem como parâmetro no método:

```
$items = $request->getAllItems();

// Logicamente o método acima não recupera apenas os itens visíveis, então seria necessário realizar o filtro, algo como:

$allItems = $request->getAllItems();
$items = array();

foreach( $allItems as $item ){
    if( !$item->getParentItemId() ){
        $items[] = $item;
    }
}
```

Estou reportando isto, porque há casos em que o quote do usuário não representa os parâmetros para cálculo do frete, como o cálculo independente na página do produto e cálculo via administrador. Até por isso notei que você fez um if para recuperar os itens do administrador que não são recuperados no primeiro caso:

```
if( count($allItems) == 0 ){
    $items = Mage::getSingleton('adminhtml/session_quote')->getQuote()->getAllVisibleItems();
}
```

Há algum motivo especial para você ter tomando esta abordagem? Em meu ponto de vista você deveria utilizar o $request para recuperar os itens...

PS. Não achei nenhuma issue relacionada, se houver, desculpe incomodar.

**Comment by pedro-teixeira** [comment]
@mateus007 não tem nenhum motivo para ter feito dessa maneira, talvez nas versões antigas do Magento o `Mage_Shipping_Model_Rate_Request` não existia?

De qualquer forma esse seria uma grande melhora para se fazer, quando puder enviar uma pull request será muito bem-vinda.

**Comment by mateus007** [comment]
@pedro-teixeira verifiquei na versão 1.4 e já existe esta implementação:
https://github.com/OpenMage/magento-mirror/blob/magento-1.4/app/code/core/Mage/Sales/Model/Quote/Address.php#L703

Mando um pull request sim, porém antes quero tirar outra dúvida :D

Há um método que recupera o peso de itens nominais `_getNominalWeight`. Pelo o que entendi, este tipo de produto nominal faz parte do Recurring Profile do Magento e vai para o carrinho à parte com os custos de taxa e tal acoplados no valor - ele nem entra no subtotal (talvez eu esteja errado).

Ele é realmente necessário? Não entendi bem o porque do método no contexto dos Correios e como o  `$request` não envia esse tipo de informação (se é nominal ou não) e nem o quote (ele manda apenas produtos), não haveria bem uma "solução padrão" para substituir esse método.

**Comment by pedro-teixeira** [comment]
Pelo que lembro foi o @jarjar123 que enviou essa modificação.

@jarjar123 pode dar uma luz aqui?

**Comment by jarjar123** [comment]
É a PR do matheusjardim
https://github.com/pedro-teixeira/correios/pull/91

Ele queria q o módulo funcionasse para Perfis Recorrentes. Sugeri o código,
e segundo ele ficou ok. Mas não uso Perfis Recorrentes, então não tenho
certeza de como deve funcionar.
Em 15/05/2016 20:18, "Pedro Teixeira" <notifications@github.com> escreveu:

Pelo que lembro foi o @jarjar123 <https://github.com/jarjar123> que enviou
essa modificação.

@jarjar123 <https://github.com/jarjar123> pode dar uma luz aqui?

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/pedro-teixeira/correios/issues/151#issuecomment-219318710>

**Comment by pedro-teixeira** [comment]
@matheusjardimb seria legal ter sua opinião aqui.

**Comment by mateus007** [comment]
Observei mais a fundo e fiz alguns testes também. Quando o request utiliza Perfis Recorrentes, a informação de peso não é enviada, então seria necessário apenas substituir os _items_ no `_getNominalWeight` para utilizar os dados do request e calcular o peso do pacote.

@pedro-teixeira pull request criada. Também brinquei um pouco com o módulo e movi as informações dos correios para uma aba própria, fica mais bonito assim :D
