### ISSUE TITLE
Especificação do model/source_model nos arquivos de configuração

### ISSUE THREAD

**Issue by wyllyan** [pedro-teixeira/correios#152]
Existe algum motivo especial para ser usado o nome da classe nas especificações de model/source_model em vez do padrão “module_name/model_class”  nos arquivos de configuração do módulo?
Desta forma, dificulta um pouco a customização a partir de um rewrite.

**Comment by pedro-teixeira** [comment]
Não sei se entendi sua pergunta, pode dar um exemplo?

**Comment by wyllyan** [comment]
Desculpe não ter exemplificado.
Da seguinte forma, o Magento não identifica um possível rewrite da classe CorreiosMethod:

```
<default> 
	<carriers> 
		<pedroteixeira_correios> 
			<model>PedroTeixeira_Correios_Model_Carrier_CorreiosMethod</model>
		</pedroteixeira_correios>
	</carriers>
</default>
```
Para funcionar, deveria ser assim:

```
<default> 
	<carriers> 
		<pedroteixeira_correios> 
			<model>pedroteixeira_correios/carrier_correiosMethod</model>
		</pedroteixeira_correios>
	</carriers>
</default>
```

Alguns nós “source_model” do system.xml estão da mesma forma.
Claro que isso não afeta o funcionamento do módulo. Só notei porque necessitava customizar um ponto específico do método “_appendShippingReturn”.

**Comment by pedro-teixeira** [comment]
Entendi. Não lembro de ter nenhuma razão específica para isso.

Se quiser enviar uma pull request seria legal, só por favor faça todos os testes para garantir que continua tudo funcionando. Seria legal ver se precisa de alguma migração também, mas acho que não.

**Comment by wyllyan** [comment]
Providenciarei.
Obrigado!
