### ISSUE TITLE
Consulta de CEP não funciona

### ISSUE THREAD

**Issue by StartupHub** [pedro-teixeira/correios#161]
Ao consultar o CEP 13140750 funciona e no Log temos a seguinte informação:

2016-06-18T12:56:10+00:00 DEBUG (7): pedroteixeira_correios [cache]: mode=1 status=write key=40096x41068_12_16_13140750

No entanto, se consulto o CEP 03925000  (ele é existente, já consultei direto no site do correio)...não funciona e não loga nada !!!

Será que o zero a esquerda está influenciando?  Alguem sabe o que pode ser?

**Comment by jarjar123** [comment]
Testei seu cep aqui e funcionou.
Que versão do módulo está usando?

Versões antigas podem não funcionar, pois esse cep está sujeito a condições
especiais de entrega pela ECT.
Em 18/06/2016 10:20, "Gabriel" <notifications@github.com> escreveu:

**Comment by StartupHub** [comment]
Estava com erro na v4.4 e atualizei para a ultima versão v4.7.1. Continuou com erro.  

Basta atualizar pelo Connect? Ou preciso fazer algo a mais?

Está voltando esse XML:

<?xml version="1.0" encoding="ISO-8859-1" ?>
<Servicos><cServico><Codigo>40096</Codigo><Valor>21,96</Valor><PrazoEntrega>8</PrazoEntrega><ValorSemAdicionais>20,11</ValorSemAdicionais><ValorMaoPropria>0,00</ValorMaoPropria><ValorAvisoRecebimento>0,00</ValorAvisoRecebimento><ValorValorDeclarado>1,85</ValorValorDeclarado><EntregaDomiciliar>S</EntregaDomiciliar><EntregaSabado>S</EntregaSabado><Erro>010</Erro><MsgErro><![CDATA[O CEP de destino est� sujeito a condi��es especiais de entrega  pela  ECT e ser� realizada com o acr�scimo de at� 7 (sete) dias ao prazo regular.]]></MsgErro></cServico><cServico><Codigo>41068</Codigo><Valor>14,96</Valor><PrazoEntrega>12</PrazoEntrega><ValorSemAdicionais>12,93</ValorSemAdicionais><ValorMaoPropria>0,00</ValorMaoPropria><ValorAvisoRecebimento>0,00</ValorAvisoRecebimento><ValorValorDeclarado>2,03</ValorValorDeclarado><EntregaDomiciliar>S</EntregaDomiciliar><EntregaSabado>N</EntregaSabado><Erro>010</Erro><MsgErro><![CDATA[O CEP de destino est� sujeito a condi��es especiais de entrega  pela  ECT e ser� realizada com o acr�scimo de at� 7 (sete) dias ao prazo regular.]]></MsgErro></cServico></Servicos>

**Comment by rafaelpatro** [comment]
Vê se essa opção está ativa:
![image](https://cloud.githubusercontent.com/assets/13813964/16171379/e68c43fc-3543-11e6-873b-72a99ab30923.png)

**Comment by StartupHub** [comment]
Está sim...

[image: Imagem inline 1]

2016-06-18 11:00 GMT-03:00 Rafael Patro <notifications@github.com>:

**Comment by rafaelpatro** [comment]
Pode mandar teu `etc/config.xml` pra eu dar uma verificada?

**Comment by rafaelpatro** [comment]
Quais serviços estão ativos? PAC 41068, SEDEX 81019?

**Comment by rafaelpatro** [comment]
Confere em `etc/config.xml`, se `show_errors` está assim:

```xml
<soft_errors>009,010,011</soft_errors>
```

**Comment by StartupHub** [comment]
Serviços ativos: 40096 e 41068

[config.xml.zip](https://github.com/pedro-teixeira/correios/files/321762/config.xml.zip)

**Comment by StartupHub** [comment]
Está som os soft_errors sim !!!

<default>
        <carriers>
            <pedroteixeira_correios>
                
                <active>1</active>
                <model>PedroTeixeira_Correios_Model_Carrier_CorreiosMethod</model>
                <title>Correios</title>
                <postmethods>40010</postmethods>
                <hard_errors>-3,-6,-10,-33,-888,7,99</hard_errors>
                <soft_errors>009,010,011</soft_errors>
                <show_soft_errors>0</show_soft_errors>
                <prazo_entrega>0</prazo_entrega>
                <check_dimensions>1</check_dimensions>
                <min_order_value>0</min_order_value>
                <max_order_value>10000</max_order_value>
                <handling_fee>0</handling_fee>
                <ws_timeout>20</ws_timeout>

**Comment by rafaelpatro** [comment]
Não consegui reproduzir teu problema. Comigo a cotação funcionou.
Teu `config.xml` tá :+1:. Estou sem tempo agora, mas assim que puder analiso com mais cuidado.

Minha sugestão no momento é que tente uma instalação limpa 4.7.1, em um Magento onde nunca tenha sido instalada essa extensão.
* Confere se a compilação está desativada (ou re-compilada após 4.7.1)
* Confere se as caches do Magento estão desativadas (ou atualizada após 4.7.1)

**Comment by StartupHub** [comment]
@rafaelpatro @jarjar123  Consegui !!! Após recompilar e habilitar o "Mostrar Método Mesmo se Não Aplicável"... 

Só que se deixar habilitado, mesmo quando não for área de risco e tiver algum método não disponivel para aquela região, ele vai ficar exibindo...É assim mesmo o comportamento?

Não seria interessante separar o "Mostrar Método Mesmo se Não Aplicável" do Soft_Error  ??

**Comment by rafaelpatro** [comment]
Sim, seria uma boa contribuição.
_A variável showmethod é usada pelo core do Magento. Ao desativá-la, caso haja algum erro na cotação, o método de entrega é ocultado._
CEPs em Área de Risco são classificados como __erro__ pelo webservice dos Correios.

Mas que bom que conseguiu. Bom final de semana.
