### ISSUE TITLE
Utilizar Serviço de Aviso de Recebimento - Aumenta Valor do Frete

### ISSUE THREAD

**Issue by marcosnolasco** [pedro-teixeira/correios#169]
Ao Utilizar Serviço de Aviso de Recebimento o valor do frete está aumentando. Essa funcionalidade seria para modificar o status do pedido quando este for entregue? Se for, não está funcionando, se não for, existe a possibilidade?

**Comment by Veiote** [comment]
Aviso de recebimento (AR) é um serviço adicional dos Correios, custo fixo de R$4,30 por encomenda.
https://www.correios.com.br/para-voce/correios-de-a-a-z/aviso-de-recebimento-ar

**Comment by marcosnolasco** [comment]
Obrigado pelo esclarecimento.

Eu não estou conseguindo fazer funcionar o monitoramento automático, que quando o cliente recebe o produto o stataus muda para completo. Vcocê saberia me ajudar?
