### ISSUE TITLE
Monitoramente automático - Cron Job Erro

### ISSUE THREAD

**Issue by willgoulding** [pedro-teixeira/correios#176]
Olá a todos, fiz a alteração para a ultima versão do módulo 4.7.2 e ativei a opção de monitoramento. Mas estou tendo um log de erro no Cron.

A versão instalada é a mais recente abaixada hoje do GitHub já com a ultima alteração no Sro.php

Alguém pode me ajudar com isso?

Segue o log:

```
Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184
Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184
Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 185
Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 185
Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184
Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184
Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 185
Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 185
Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 164
Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 166
Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 164
Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 166
```

Linhas(183/184/185)

```
 183       $date = $this->_xml->objeto->evento->data;
 184       $hour = $this->_xml->objeto->evento->hora;
 185       $type = $this->_xml->objeto->evento->tipo;
```

```
163        $isValid = false;
164        $evento = $this->_xml->objeto->evento;
165       $hashTypes = explode(',', $this->getConfigData("sro_event_type_{$mode}"));
166        if (in_array($evento->tipo, $hashTypes)) {
167            $type = strtolower($evento->tipo);
168            $hashStatus = explode(',', $this->getConfigData("sro_event_status_{$mode}_{$type}"));
169            $isValid = in_array((int) $evento->status, $hashStatus);
170        }
171        return $isValid;
```

![correiocron](https://cloud.githubusercontent.com/assets/12437790/17313338/aa44ff9e-5828-11e6-87aa-c020604c9c70.png)

**Comment by jarjar123** [comment]
Olá willgolding

Aparentemente o webservice não retornou informação suficiente.
É possível que algum dos seus rastreios não tenha sido registrado/postado
nos Correios?
Sugiro verificar manualmente. Posta aqui se vir algo estranho.

Apesar de não caracterizar um erro PHP, seria interessante tratar esse caso.
Não parece ser muito grave, só exibe alguns Notices, sem travar ou encerrar.

Essa semana será impossível, mas assim que puder eu coloco um tratamento.

Em 01/08/2016 21:44, "willgoulding" <notifications@github.com> escreveu:

**Comment by willgoulding** [comment]
Olá jarjar123,

Primeiramente obrigado pela ajuda.

Conferir todos os pedidos que estão com "Pedido em Transporte" todos estão com estado "Encaminhado" no websro.correios exceto 1 que foi entregue hoje e esta com status de Entrega Efetuada no websro.correios.

Antes de instalar o modulo eu usava outro estado "Ordem Enviada" então dos os pedidos anteriores estão com esse estado.

**Comment by willgoulding** [comment]
Alguém pode ajudar com esse problema?

**Comment by rafaelpatro** [comment]
Olá @willgoulding 
Aparentemente 1 de seus objetos está com problema na resposta XML. Falta a tag `evento`.
Mas repare no log, o que derruba o processo é o _Fatal Error_.

    PHP Fatal error:  The file
    /home/pood8607/public_html/app/code/local/MasterShop/Cielo/Model/Cielo.php cannot be decoded by this version of the ionCube Loader.
    If you are the administrator of this site
    then please install the latest version of the ionCube Loader.
    in Unknown on line 0

Sugiro remover esse módulo Cielo e ver o que acontece.

**Comment by willgoulding** [comment]
Olá @rafaelpatro 

O problema era que o CRON no meu servidor estava rodando PHP 5.3  causando o erro no modulo, troquei para PHP 5.5 usando o comando
`/usr/local/php55/bin/php-cli -f /home/meudominio/public_html/cron.php`

Isso parece que resolveu o problema com o modulo Cielo. Mas ainda não esta corretamente correios_status_check sempre retorna GONE Host "m25.siteground.biz" has not been available for a while now to update the status of this task and the task is not reporting back by itself"" 

![cron3](https://cloud.githubusercontent.com/assets/12437790/17939699/c8a94af2-69f9-11e6-80b7-2db707a82910.png)

**Comment by rafaelpatro** [comment]
É possível que haja algum problema relacionado ao Soap, na linha a seguir.
https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/Model/Sro.php#L74

Testa novamente desativando o cache do WSDL, nas configurações do PHP.

    soap.wsdl_cache_enabled=0 #Algo assim

**Comment by willgoulding** [comment]
Olá @rafaelpatro 

Tentei sua sugestão. Coloquei no arquivo php.ini mas não deu resultado ficou do mesmo jeito.
`soap.wsdl_cache_enabled = 0`

Depois também tentei dentro do arquivo.:
`<?php 
ini_set('soap.wsdl_cache_enabled', '0'); 
ini_set('soap.wsdl_cache_ttl', '0'); 
?> `

Mas tive o seguinte erro:
`Cron error while executing correios_status_check:

exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /home/pood8607/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php:307
Stack trace:
#0 /home/pood8607/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(307): PDO->beginTransaction()
#1 /home/pood8607/public_html/lib/Zend/Db/Adapter/Abstract.php(496): Zend_Db_Adapter_Pdo_Abstract->_beginTransaction()
#2 /home/pood8607/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(234): Zend_Db_Adapter_Abstract->beginTransaction()
#3 /home/pood8607/public_html/app/code/core/Mage/Core/Model/Resource/Abstract.php(76): Varien_Db_Adapter_Pdo_Mysql->beginTransaction()
#4 /home/pood8607/public_html/app/code/core/Mage/Core/Model/Abstract.php(313): Mage_Core_Model_Resource_Abstract->beginTransaction()
#5 /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Observer.php(37): Mage_Core_Model_Abstract->save()
#6 [internal function]: PedroTeixeira_Correios_Model_Observer->sroTrackingJob(Object(Aoe_Scheduler_Model_Schedule))
#7 /home/pood8607/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(213): call_user_func_array(Array, Array)
#8 /home/pood8607/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(605): Aoe_Scheduler_Model_Schedule->runNow(true)
#9 /home/pood8607/public_html/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#10 /home/pood8607/public_html/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#11 /home/pood8607/public_html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#12 /home/pood8607/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#13 /home/pood8607/public_html/cron.php(80): Mage::dispatchEvent('default')
#14 {main}`

**Comment by willgoulding** [comment]
@rafaelpatro e @jarjar123 

O timeout do meu servido é 120 segundos por ser um servidor compartilhado, (SiteGround) isso poderia ter algo em relação?

**Comment by rafaelpatro** [comment]
Não sei dizer quanto ao timeout, mas acho que 120s não é problema.
Consegue testar o método SoapClient contra o webservice dos Correios, isoladamente em um arquivo PHP?

Acho que editar o _php.ini_ não surte efeito se estiver usando o _php-cli_. Tenta algo parecido com isso...

    /usr/local/php55/bin/php-cli -d soap.wsdl_cache_enabled=0 -f /home/meudominio/public_html/cron.php

**Comment by willgoulding** [comment]
Olá @rafaelpatro 

Não funcionou, conversei com o suporte do servidor. Ele fez o seguinte para desabilitar o cache do WSDL. Supostamente esta desabilitado agora.

I have added the following line to your php.ini file located in public_html folder:

Code:
`soap.wsdl_cache_enabled = Off`

I have also added the line 

Code:
`SetEnv PHPRC /home/pood8607/public_html/php.ini`

to the .htaccess file located in the public_html directory so the php.ini file starts to work recursively in the public_html folder. Everything should work now.

Mesmo assim ainda não retorna nada, abaixo o novo log:

```
[26-Aug-2016 00:30:04 UTC] PHP Notice:  Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
[26-Aug-2016 00:30:04 UTC] PHP Notice:  Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
[26-Aug-2016 00:30:04 UTC] PHP Notice:  Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184
[26-Aug-2016 00:30:04 UTC] PHP Notice:  Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184
[26-Aug-2016 00:30:04 UTC] PHP Notice:  Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 185
[26-Aug-2016 00:30:04 UTC] PHP Notice:  Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 185
[26-Aug-2016 00:30:04 UTC] PHP Notice:  Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
[26-Aug-2016 00:30:04 UTC] PHP Notice:  Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
```

**Comment by rafaelpatro** [comment]
Conseguiu testar o SoapClient?

Minhas ideias estão acabando :(
Poder colocar um log para verificarmos a resposta dos Correios?
Arquivo _app/code/community/PedroTeixeira/Correios/Model/Sro.php_ (entre as linhas 78 e 79):

![image](https://cloud.githubusercontent.com/assets/13813964/18004414/314c7f68-6b6a-11e6-99d5-e01926b1ccec.png)

```php
        try {
            $client = new SoapClient($this->getConfigData('url_sro_correios'));
            $response = $client->buscaEventos($params);
            if (empty($response)) {
                throw new Exception("Empty response");
            }

            Mage::log('params: ' . print_r($params, true));
            Mage::log('buscaEventos: ' . print_r($response, true));

            $this->_xml = $response->return;
        } catch (Exception $e) {
            Mage::log("Soap Error: {$e->getMessage()}");
            return false;
        }
```

Coloca aqui o resultado do log. Não esquece de desativar o compilador.

**Comment by willgoulding** [comment]
@rafaelpatro 

Não gerou nenhum log

**Comment by willgoulding** [comment]
@rafaelpatro 

Olha o log do system, 
[system.zip](https://github.com/pedro-teixeira/correios/files/439575/system.zip)

Pelo que olhei ele esta olhando meus primeiros envios: Exemplo abaixo foi o primeiro pacote enviado por correio. Data do envio 2015-06-02 18:00:05 então retorna Objeto não encontrado na base de dados dos Correios. A base dos correios só armazena por 180 dias

```
2016-08-26T15:00:03+00:00 DEBUG (7): buscaEventos: stdClass Object
(
    [return] => stdClass Object
        (
            [versao] => 2.0
            [qtd] => 1
            [objeto] => stdClass Object
                (
                    [numero] => DM555595413BR
                    [erro] => Objeto n�o encontrado na base de dados dos Correios.
                )

        )

)

2016-08-26T15:00:04+00:00 DEBUG (7): params: Array
(
    [usuario] => ECT
    [senha] => SRO
    [tipo] => L
    [resultado] => U
    [lingua] => 101
    [objetos] => DM555595413BR
)

2016-08-26T15:00:04+00:00 DEBUG (7): buscaEventos: stdClass Object
```

**Comment by rafaelpatro** [comment]
Remove esses objetos do monitoramento, para que possamos ver os objetos ainda em rastreamento.
É só colocar o status como _Transação Concluída_ nesses envios antigos.

**Comment by willgoulding** [comment]
@rafaelpatro 

Coloquei o  status como Transação Concluída em todos envios antigos, Só ficou os de 1 mes para ca. Mesmo assim no log ele continua rastreando o primeiro envio.

**Comment by rafaelpatro** [comment]
Acho que o problema está nos status de pedido.
Verifiquei o seu system.log e nenhum dos objetos cadastrados existe no sistema dos Correios. Ou seja nenhum dos objetos pode ser rastreado.

Acredito que o problema esteja nos status dos pedidos.
Verifica se vc tem esses status cadastrados no Magento:
![image](https://cloud.githubusercontent.com/assets/13813964/18018422/29902494-6bad-11e6-867f-4f56c5cf7374.png)
Confirma se os pedidos antigos (já descartados pelos Correios) estão realmente na situação **complete (Transação Concluída)**.
Confirma se os últimos pedidos estão realmente na situação **complete_shipped (Pedido em Transporte)**.

**Comment by willgoulding** [comment]
@rafaelpatro 

![crorreio](https://cloud.githubusercontent.com/assets/12437790/18019405/e811edca-6ba9-11e6-8808-abbbf22c850c.png)

Esta diferente. Sendo que Transação Concluída não existia eu criei quando voce pediu para mudar o status   para Transação Concluída.

Todas as ultimas ordens que foram envidas esta com o estado de Pedido em Transporte.

**Comment by willgoulding** [comment]
@rafaelpatro 

achei o erro e mudei tudo agora. agora todas as ordens antigas estão como Transação Concluida (comple)

![correios_status_check](https://cloud.githubusercontent.com/assets/12437790/18020289/ad766042-6bae-11e6-8be4-4e3351ba32e6.png)

**Comment by rafaelpatro** [comment]
E os objetos Em Transporte, estão sendo monitorados? Conseguiu testar isso?
Caso não tenha conseguido, manda o log novamente.

**Comment by willgoulding** [comment]
@rafaelpatro 

Conferir todos os envios, todos que estava como entregue mudei o estado para Transação Concluída, e verifiquei se todas as ordens estava com rastreamento ok.

No Scheduler continua dando o erro de sempre: Host "m79.siteground.biz" has not been available for a while now to update the status of this task and the task is not reporting back by itself

O novo log:
```
(
    [usuario] => ECT
    [senha] => SRO
    [tipo] => L
    [resultado] => U
    [lingua] => 101
    [objetos] => PI860222514BR
)

2016-08-26T22:15:01+00:00 DEBUG (7): buscaEventos: stdClass Object
(
    [return] => stdClass Object
        (
            [versao] => 2.0
            [qtd] => 1
            [objeto] => stdClass Object
                (
                    [numero] => PI860222514BR
                    [sigla] => PI
                    [nome] => ENCOMENDA PAC
                    [categoria] => ENCOMENDA PAC
                    [evento] => stdClass Object
                        (
                            [tipo] => RO
                            [status] => 01
                            [data] => 22/08/2016
                            [hora] => 17:57
                            [descricao] => Objeto encaminhado 
                            [local] => CTCE BELEM
                            [codigo] => 66113972
                            [cidade] => BELEM
                            [uf] => PA
                            [destino] => stdClass Object
                                (
                                    [local] => CDD SANTAREM
                                    [codigo] => 68005971
                                    [cidade] => Santarem
                                    [bairro] => Centro
                                    [uf] => PA
                                )

                        )

                )

        )

)

2016-08-26T22:15:02+00:00 DEBUG (7): params: Array
(
    [usuario] => ECT
    [senha] => SRO
    [tipo] => L
    [resultado] => U
    [lingua] => 101
    [objetos] => DN372418761BR
)

2016-08-26T22:15:02+00:00 DEBUG (7): buscaEventos: stdClass Object
(
    [return] => stdClass Object
        (
            [versao] => 2.0
            [qtd] => 1
            [objeto] => stdClass Object
                (
                    [numero] => DN372418761BR
                    [sigla] => DN
                    [nome] => ENCOMENDA SEDEX
                    [categoria] => SEDEX
                    [evento] => stdClass Object
                        (
                            [tipo] => RO
                            [status] => 01
                            [data] => 24/08/2016
                            [hora] => 13:09
                            [descricao] => Objeto encaminhado 
                            [local] => CTE FLORIANOPOLIS/GTURN3 (BLUMENAU)
                            [codigo] => 89015971
                            [cidade] => Blumenau
                            [uf] => SC
                            [destino] => stdClass Object
                                (
                                    [local] => CTE BRASILIA
                                    [codigo] => 71206970
                                    [cidade] => BRASILIA
                                    [bairro] => Zona Industrial (Guará)
                                    [uf] => DF
                                )

                        )

                )

        )

)
```

**Comment by rafaelpatro** [comment]
Aparentemente o rastreamento das encomendas PI860222514BR e DN372418761BR foi atualizado e registrado, nos comentários da entrega. Confere?

Pode enviar o log do PHP também?

**Comment by willgoulding** [comment]
@rafaelpatro 

Não :( Já tentei de tudo não sei mais o que fazer hauhauhau estou quase desistindo. 

![14](https://cloud.githubusercontent.com/assets/12437790/18024766/73a79f0c-6be0-11e6-9b2e-e0645a24e3c3.png)
![61](https://cloud.githubusercontent.com/assets/12437790/18024765/73a71b2c-6be0-11e6-89bd-55b141ef130d.png)

Desculpe a ignorância, qual logo do PHP?

**Comment by rafaelpatro** [comment]
Normalmente fica em _/var/log/php_errors.log_ ou _/var/log/php/error.log_

**Comment by willgoulding** [comment]
Bom dia @rafaelpatro 

Acredito que concertei, o problema todo era no cron, mesmo eu colocando no servido o comando /usr/local/php55/bin/php-cli -f /home/pood8607/public_html/cron.php , a configuração do servidor, o script cron.php executa o cron novamente através do arquivo cron.sh, o qual por sua vez escolhe a versão do php que ele bem entende, e que no caso também pode ser uma versão antiga ou com outro ionCube Loader. Isso gerava o erro acredito eu.

-Editei o arquivo magento/cron.php,  que começam com $isShellDisabled (48, 49). Logo após elas, adicionei: $isShellDisabled = true; . Isto impediu que o cron execute o arquivo cron.sh e desta forma usar a versão do php que especifiquei na linha de comando.

Aparentemente ele esta funcionado retornou até nos comentários dos envios. Mas ainda gera esse log a baixo.

```
Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 189

Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 189

Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 190

Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 190

Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 191

Notice: Trying to get property of non-object in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 191

Notice: Undefined property: stdClass::$evento in /home/pood8607/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 189
```
Mas verifiquei todo os envios e em todos houve uma notificação para os cliente.

Uma ultima coisa quando o pedido retorna como entregue não é possível mudar o o estado Transação Concluída de forma automática?

Rafael, muito obrigado pela ajuda o seu suporte ajudou de mais!

**Comment by rafaelpatro** [comment]
Sim, após a entrega o pedido é automaticamente colocado na situação _complete_ (ou Transação Concluída). Já deveria funcionar dessa forma. Caso contrário os pedidos entregues seriam rastreados eternamente.

Quanto as mensagens do log, acredito que deve haver algum objeto inválido ainda. Lembro que o último log que vc enviou continha alguns rastreamentos apenas com números. Sugiro conferir novamente.
