### ISSUE TITLE
Erro 077: Prazo não cadastrado para o trecho informado

### ISSUE THREAD

**Issue by rafaelpatro** [pedro-teixeira/correios#182]
Alguém mais está tendo problemas com os Correios hoje?
Comigo **alguns CEPs** estão sem cotação, pois o webservice está retornando esse erro:

![image](https://cloud.githubusercontent.com/assets/13813964/18057993/b65eaeb2-6de8-11e6-854c-208edb569faa.png)

**Comment by lecosas** [comment]
Oi Rafael, estou com o mesmo problema. No meu só está funcionando, aparentemente, para o mesmo estado. Alguém tem alguma luz?

**Comment by lecosas** [comment]
Engraçado que este erro nem existe no manual. Acredito ser algo referente aquela alteração no PAC. Devem estar cadastrando novos prazos :( :(

**Comment by rafaelpatro** [comment]
Concordo.
O url que usamos é esse _ws.correios.com.br/calculador/CalcPrecoPrazo.aspx_.
Acredito que devemos usar um método diferente, que não informe _prazo_. Pois aparentemente é o _prazo_ que está gerando problemas.
Algo assim _ws.correios.com.br/calculador/CalcPreco.aspx_. Mas esse não existe, então teremos que descobrir.

**Comment by willgoulding** [comment]
Olá @rafaelpatro e @lecosas 

Estou tendo o mesmo problema com o CEP 56330035 - Pernambuco

**Comment by roneclay** [comment]
Mesmo problema aqui.
CEPs de vários Estados.

**Comment by rafaelpatro** [comment]
Estou trabalhando numa correção, mas o prazo já era. A menos que alguém saiba como calcular o prazo de forma independente.

**Comment by philsouza2016** [comment]
No meu caso o erro que está dando é: **Esse método de envio está fora do ar. Por favor entre em contato conosco.** Começou hoje.

**Comment by wdarking** [comment]
Aqui também, 

> Esse método de envio está fora do ar. Por favor entre em contato conosco. Começou hoje

e no log:

> 2016-08-29T01:40:21+00:00 DEBUG (7): pedroteixeira_correios [189]: URL Error, all services return with error

**Comment by lecosas** [comment]
@rafaelpatro  Eu tenho uma alteração no módulo que faz uma busca Off-line, caso o serviço esteja indisponível. Mas é uma alteração usando um outro módulo (sem chance de passar), muito ruim o código. Fiz a alteração agora para quando retornar o 077 usar o Offline também. Creio que deva ser um problema temporário dos Correios, espero.

**Comment by willgoulding** [comment]
Olá A todos,

Acabei de fazer uma simulação no site do correios. Lá esta tendo o mesmo erro.
![correio](https://cloud.githubusercontent.com/assets/12437790/18059467/0bc06ec4-6de7-11e6-8b63-b3391b8c0e51.png)

**Comment by roneclay** [comment]
Parece que voltou a funcionar...
Alguém confirma?

**Comment by willgoulding** [comment]
Sim, aqui voltou!

**Comment by rafaelpatro** [comment]
Aqui voltou também

**Comment by rafaelpatro** [comment]
Consegui implementar uma correção através desse url _ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPreco_. Mas o _prazo_ precisa ficar desabilitado, pois o webservice não retorna essa informação.

Já que os Correios pressionaram _Ctrl + z_, vou deixar essa alteração de lado por enquanto :/

**Comment by lecosas** [comment]
rsrs! Aqui voltou também ;)

**Comment by roneclay** [comment]
@rafaelpatro boa!

**Comment by edumandiba** [comment]
Seria legal se o prazo de entrega pudéssemos colocar na descrição da forma de entrega, nesses casos que o correio passar por manutenção, desabilitaríamos o prazo de entrega no módulo e deixaríamos na descrição da forma de entrega. Ex: PAC - 7 a 15 dias úteis para sua região....isso atende e evitaríamos problemas nessa situação......

**Comment by rafaelpatro** [comment]
Boa ideia, mas e o frete? O problema é que isso não atenderia o ocorrido. Pois os Correios sequer retornaram o preço do frete.
