### ISSUE TITLE
Cannot repeat Magento Product size attributes

### ISSUE THREAD

**Issue by meganovidades** [pedro-teixeira/correios#185]
Após atualização para ultima versão do módulo não estou conseguindo salvar as confirgurações
esta retornando este erro:

Cannot repeat Magento Product size attributes

Alguem pode me ajudar?

**Comment by meganovidades** [comment]
Obrigado pela atenção, problema resolvido.

**Comment by rafaelpatro** [comment]
Nunca vi esse erro, mas que bom que resolveu.
Caso a solução tenha alguma relação com o módulo, compartilha.
