### ISSUE TITLE
Tracking automático conflito

### ISSUE THREAD

**Issue by kinfoxxx** [pedro-teixeira/correios#193]
Olá, utilizamos o hub da plug.to e estamos com conflito entre o modulo de integração deles segue o link do modulo https://bitbucket.org/pluggto/magento/get/master.zip e o modulo dos correios do pedro, ocorre o seguinte erro, quando o modulo da pluggto esta habilitado o modulo dos correios não funciona o Tracking automático, não atualiza o status e as informações de envio, quando desabilitamos o modulo da pluggto o Tracking automático funciona perfeitamente, creio que seja algum conflito entre ambos, já solicitamos ao pessoal da pluggto que esteja analisando porem sem sucesso, nós não temos experiência, se tiver alguém que possa nos dar uma luz agradeço.

Desde já Obrigado

Att, Carlos

**Comment by rafaelpatro** [comment]
Provável problema no _cron_.
O tracking automático utiliza o _cron_ para monitorar as encomendas.
Se o módulo terceiro gera algum erro no _cron_, o restante das tarefas fica "a ver navios".

**Comment by kinfoxxx** [comment]
Bom dia @rafaelpatro , muito obrigado pela ajuda, o cron esta funcionando normalmente, temos aoe scheduler e as tarefas estão sendo executadas perfeitamente, executa até o correios_status_check só que ele não muda ''Tracked 0 objects of 3.'' eu que tenho que ir venda por venda e alterar para completo as entregues, e nenhum status altera.

**Comment by rafaelpatro** [comment]
Ok, descartado problema no _Cron_.
Pela mensagem que descreveu, o tracking identificou apenas 3 pedidos para monitorar. E aparentemente nenhum deles foi movimentado nos Correios, nos últimos 15 minutos.
Está correto? Deveria haver mais pedidos?

Pode conferir o histórico do AOE, e ver se há algo incomum na linha do tempo?

**Comment by kinfoxxx** [comment]
Bom dia, sim só identificou 3 pois só deixamos 3, os outros que já foram entregues já atualizamos manual, os 3 não tiveram alteração nos 15 minutos porem mesmo que tenha alteração aparece ''Tracked 0 objects of 3.'' ,  verifiquei o AOE fica sempre verde como se estivesse normal, verifiquei log dele também consta que o cron acionou o correios_status_check normalmente, se desabilito o modulo da pluggto ai os novos pedidos roda normal, esses que foram ativados o modulo da pluggto continua travado, se aciono o modulo e desligo novamente os pedidos novos trava também.

**Comment by rafaelpatro** [comment]
A mensagem _Tracked 0 objects of 3_ significa que foram rastreados 3 objetos junto aos Correios. E nenhum deles sofreu movimentação nos últimos 15 minutos.

Repare no código, que a requisição é feita na linha 33:
https://github.com/pedro-teixeira/correios/blob/e5dec32013a7d2ccdeef955aa581203156f4b540/app/code/community/PedroTeixeira/Correios/Model/Observer.php#L33

A linha 36 significa que...
...se o último evento registrado é diferente do evento atual, então registra um novo evento, e conta mais um objeto.

**Comment by kinfoxxx** [comment]
Adicionei um novo rastreamento para testar a primeira vez que o cron executa da ''TRIGGER: shutdown function'' e na segunda ''Multiple tasks with the same job code were piling up. Skipping execution of duplicates. '' depois roda em verde ''Tracked 0 objects of 4.''

**Comment by rafaelpatro** [comment]
Tem o código desse módulo, ou um link para o repositório?

**Comment by rafaelpatro** [comment]
Desculpe, vc já havia postado os fontes. Assim que der vou analisar aqui.

**Comment by kinfoxxx** [comment]
ok, desde já agradeço!

**Comment by rafaelpatro** [comment]
Pode enviar também os logs do Magento e PHP?
_pasta-magento/var/log/*_
_/var/log/php_errors.log_
...algo assim

**Comment by kinfoxxx** [comment]
[download.zip](https://github.com/pedro-teixeira/correios/files/539565/download.zip)
Esse log do php_errors.log não tem aqui, no começo do system.log foi quando coloquei alguns códigos no modulo do pedro para fazer o log dos dados, depois tirei os códigos .

**Comment by kinfoxxx** [comment]
[download (2).zip](https://github.com/pedro-teixeira/correios/files/539574/download.2.zip)
esqueci dos outros que tem na pasta log, segue.

**Comment by rafaelpatro** [comment]
@kinfoxxx, não sei se vou poder lhe ajudar. Aparentemente quando um objeto se movimenta nos Correios, e o módulo tenta registrar a movimentação, é bloqueado por algo.
Os logs que enviou identificam algum conflito entre os módulos, mas sem muita precisão. Por exemplo o log do _cron_...
![image](https://cloud.githubusercontent.com/assets/13813964/19539813/42e91d08-963a-11e6-9739-d3b677a22401.png)

O log de exceções:
![image](https://cloud.githubusercontent.com/assets/13813964/19540199/871bfd18-963c-11e6-8529-31e59cf1681b.png)

Outra coisa, teu _system.log_ tá estranho, registrando eventos fora de sequência em vários trechos:
![image](https://cloud.githubusercontent.com/assets/13813964/19540080/cfb015d8-963b-11e6-862f-65b2c82e7863.png)

Nem sei o que dizer, então pesquisei sobre o erro da chave UNQ_SALES_FLAT_SHIPMENT_INCREMENT_ID, e encontrei um questionamento do Alan Storm (o cara é uma referência quando se fala em Magento). http://magento.stackexchange.com/questions/82512/integrity-constraint-violation-1062-duplicate-entry-for-key-unq-sales-flat-inv
E pelo que entendi do tópico, o Magento permite que, nessa tabela, uma transação seja inciada, sem bloqueio à tabela, podendo ocasionar um conflito.

Enfim não tive paciência para ler o Pluggto, pois algumas funções tem mais de mil linhas, o que não é uma boa prática de programação. Dificulta a leitura e o entendimento.

**Sugestão**: o AOE permite reconfiguração da periodicidade das tarefas. Tenta separar os horários de execução das tarefas do Pluggto e Correios. Diminui a periodicidade, e deixa pelo menos uns 10 minutos de distância entre esses módulos.

**Comment by kinfoxxx** [comment]
Olá, obrigado, esse E0000058 realmente nós tinha enviado ele duplicado, nós envia o rastreamento do bling para o magento e apertamos duas vezes para enviar,  o cron do correio esta com 50 minutos e do plugto 5 minutos, muito obrigado pela ajuda, vou quebrando a cabeça aqui, vou acionar novamente os desenvolvedores do pluggto, eles tem que me dar uma solução, alias é o modulo deles que esta dando problema na plataforma .

**Comment by rafaelpatro** [comment]
Repare no trecho de log do Cron que mandei. O pluggto inicia uma tarefa; em seguida o correios inicia e termina; e só então o pluggto termina.
Desconfio do seguinte. O Pluggto está trabalhando nas tabelas, fazendo com que fiquem bloqueadas para escrita, até o término da execução da tarefa.

![image](https://cloud.githubusercontent.com/assets/13813964/19539813/42e91d08-963a-11e6-9739-d3b677a22401.png)

**Comment by kinfoxxx** [comment]
Essa linha ocorre sempre que adiciono um novo envio e rastreamento, pode ver que esse trecho tinha adicionado para os correios atualizar a cada 1 minuto pois estava testando, quando adicionei o rastreamento gerou o locked e depois aparece que esta indo normal porem não atualiza nada, possivelmente o pluggto esta bloqueando a tabela, mais não entendo quase nada, não sei se tem como desbloquear e nem como fazer algum teste.

**Comment by kinfoxxx** [comment]
Acredito que quando adiciono um novo rastreamento o pluggto e o correio já executa a tarefa por isso estão executando juntos, teria alguma maneira de executar somente via cron?

**Comment by rafaelpatro** [comment]
Por enquanto o Correios só monitora os rastreamentos via cron. E somente de
15 em 15 minutos. Pode aumentar a periodicidade no AOE.
Em 20/10/2016 1:25 PM, "kinfoxxx" <notifications@github.com> escreveu:

**Comment by kinfoxxx** [comment]
Nada ainda, o conflito persiste.

**Comment by mvsucupira** [comment]
@kinfoxxx estou com mesma situação desde que instalei o plugg.to na loja. O pessoal te deu algum retorno, ou mesmo vc conseguiu contornar de alguma forma?
Obrigado.

**Comment by pluggto** [comment]
@kinfoxxx @mvsucupira O problema que causava a incompatibilidade foi resolvido no do [http:/plugg.to](http:/plugg.to), podem testar? a versão corrigida pode ser baixada em https://bitbucket.org/pluggto/magento/get/master.zip  ... a demora foi causada pela necessidade de debugar o módulo Pedro Teixeira para entender onde o erro ocorria pois o módulo do Plugg.To não tem nenhum cron de atualização de pedidos como apontado como possível causa do problema.

Qualquer dúvida, podem entrar em contato direto conosco pelo email suporte@plugg.to

Atenciosamente,
Equipe Plugg.To

**Comment by mvsucupira** [comment]
Olá @pluggto , instalei o novo módulo ontem e me parece que algumas atualizações aconteceram, mas ainda há pedidos que deveriam ser atualizados e ainda não ocorreu. Vou acompanhar por mais 2 dias para verificar se resolveu ou não.

**Comment by kinfoxxx** [comment]
resolvido, obrigado pessoal da pluggto.
