### ISSUE TITLE
SRO mostrando apenas último registro

### ISSUE THREAD

**Issue by lecosas** [pedro-teixeira/correios#197]
Fala pessoal,

Alguém está tendo problemas com o SRO. Estou usando através do Webservice para exibir o rastreamento e desde ontem (pelo que percebi), só está mostrando a última interação do rastreamento. Não mostra o histórico, apenas a última ação. 

<img width="611" alt="rastro" src="https://cloud.githubusercontent.com/assets/3909842/20386745/19bcf51e-aca4-11e6-8ade-9df1962fcf0a.png">

O correto seria:

<img width="652" alt="rastro2" src="https://cloud.githubusercontent.com/assets/3909842/20386791/64e32fa4-aca4-11e6-8736-ea01a4ac34f2.png">

**Comment by rafaelpatro** [comment]
Estou com o mesmo problema (Magento 1.9.3).
Qual sua versão do Magento e do módulo? Fez upgrade recentemente?

**Comment by lecosas** [comment]
Magento 1.9.2.4  - Rodei a, mas faz uns 10 dias já
Correios 4.5.0 - mas bem modificado

@rafaelpatro  tô achando que algo foi alterado no Webservice ou está com algum erro momentâneo.

**Comment by rafaelpatro** [comment]
Soap Test: http://webservice.correios.com.br/service/rastro/Rastro.wsdl

![image](https://cloud.githubusercontent.com/assets/13813964/20397596/70c2b1fa-acd1-11e6-8412-9d2d3743e024.png)

![image](https://cloud.githubusercontent.com/assets/13813964/20397617/86425f44-acd1-11e6-9caa-48147bc457cf.png)

Ou seja, o webservice só está retornando o último evento mesmo.

**Comment by rafaelpatro** [comment]
De acordo com o manual...
![image](https://cloud.githubusercontent.com/assets/13813964/20397864/69e7cc66-acd2-11e6-9637-df17723f1208.png)

Enviei alterando a tag _resultado_ também, mas o resultado foi o mesmo, apenas o último evento.
```xml
    <resultado>T</resultado>
```

**Comment by lecosas** [comment]
É pau no Webservice então, certo?

**Comment by lecosas** [comment]
Ah! Pela função RastroJson está funcionando :(

**Comment by rafaelpatro** [comment]
Aqui voltou a funcionar normalmente.

**Comment by lecosas** [comment]
Meu também voltou @rafaelpatro ! Correios, correios, correios ... :(

**Comment by willbraga** [comment]
Minha loja apresenta o mesmo problema, já atualizei e nada, só mostra o ultimo registro do rastreamento, uso o Magento 1.9.xx, e o está passando no parâmetro o T para mostrar tudo.  O de vocês voltou a funcionar sem fazer nada? Pq aqui o problema já está faz mais de 1 mÊs.

**Comment by arthemus** [comment]
Também estou tendo o mesmo problema ultimamente... @lecosas pode dizer como você fez o teste com a função rastroJson?

**Comment by lecosas** [comment]
@arthemus Na verdade este é um erro causado por não informar o usuário e senha corretos do contrato. Antigamente funcionava com o usuário e senha padrão, porém a partir de algum momento em 2017, parou de exibir os rastreamentos, apenas o último status. Você ou seu cliente que tem o contrato, deverá solicitar um usuário e senha para usar o SRO. Geralmente, vocês conseguem com o contato comercial dos Correios.

**Comment by arthemus** [comment]
Realmente o problema era o usuário/senha mesmo. Pegando novos dados com os Correios voltou a funcionar normalmente, sem precisar mexer me nada na chamada do serviço.
