### ISSUE TITLE
URL Error - Read timed out after 20 seconds - Mais alguém?

### ISSUE THREAD

**Issue by wdarking** [pedro-teixeira/correios#198]
2016-12-08T13:44:51+00:00 DEBUG (7): pedroteixeira_correios [337]: URL Error - Read timed out after 20 seconds

Começou faz 1h, mais alguém está recebendo este erro?

**Comment by rafaelpatro** [comment]
Sim, o Webservice está muito lento hoje.
É só alterar o parâmetro _ws_timeout_ no arquivo _etc/config.xml_.
Coloca uns 60 segundos pelo menos.
