### ISSUE TITLE
Opção para Retirada na Loja no campo "Serviço Para Entrega Gratuita".

### ISSUE THREAD

**Issue by dcomm** [pedro-teixeira/correios#20]
Possibilidade de criar na opção de "Serviço Para Entrega Gratuita" poderia ter mais um item de opção "Retirada na Loja". Acredito que ia ajudar muito, como forma de frete grátis, para fazer a restrição pelo sales rules do Magento. Abraço e obrigado! Alessandro.

**Comment by pedro-teixeira** [comment]
Essa feature deveria ser um módulo de entrega separado já que não tem relação com os Correios.
