### ISSUE TITLE
Erro no Sedex com contrato

### ISSUE THREAD

**Issue by brunohrp** [pedro-teixeira/correios#200]
A consulta de Sedex com contrato não está retornando, apenas a consulta do PAC com contrato.

**Comment by rafaelpatro** [comment]
Olá @brunohrp 
Aparece alguma mensagem de alerta ou erro? Verificou o log do Magento?

Verifica se as medidas do produto estão corretas. Peso, altura, largura e comprimento.
Confere também se as unidades de medidas (kg ou gr) estão corretas nas configurações do módulo.

**Comment by brunohrp** [comment]
Sem Contrato PAC e SEDEX aparecem normalmente. Porém com o contrato apenas o PAC aparece normal, e não aparece nenhum erro ou alerta referente ao Sedex.
Segue log do Magento:
2016-12-16T10:26:11+00:00 ERR (3): Warning: Invalid argument supplied for foreach()  in D:\WebServer\Apache24\htdocs\includes\src\PedroTeixeira_Correios_Model_Carrier_CorreiosMethod.php on line 764

Ao meu ver as unidades de medidas estão corretas.

**Comment by rafaelpatro** [comment]
Pode dar uns prints na tela de configurações do módulo? Só ocultar o número
do contrato e senha.

Em 16 de dez de 2016 8:27 AM, "brunohrp" <notifications@github.com>
escreveu:

**Comment by brunohrp** [comment]
Claro, Segue:

![sem titulo](https://cloud.githubusercontent.com/assets/19653229/21260998/fc3f1e12-c36f-11e6-99a2-eb9204f19da9.png)

![sem titulo2](https://cloud.githubusercontent.com/assets/19653229/21261036/3347ef60-c370-11e6-9340-6b1505a2ee22.png)

![sem titulo3](https://cloud.githubusercontent.com/assets/19653229/21261057/51356c6e-c370-11e6-984a-06bc29631f46.png)

**Comment by rafaelpatro** [comment]
É possível que esteja utilizando o código de serviço errado.
Faz um teste no link a seguir. Só substitui os campos _nCdEmpresa_ e _sDsSenha_ pelo seus.

http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdEmpresa=1234567&sDsSenha=12345678&sCepOrigem=90020022&sCepDestino=92025490&nVlPeso=0.4&nCdFormato=1&nVlComprimento=30&nVlAltura=30&nVlLargura=30&sCdMaoPropria=n&nVlValorDeclarado=0&sCdAvisoRecebimento=n&nCdServico=40096,40436,41068&nVlDiametro=0&StrRetorno=xml&nIndicaCalculo=3

**Comment by brunohrp** [comment]
Retorno:

`<Servicos>
<cServico>
<Codigo>40096</Codigo>
<Valor>0,00</Valor>
<PrazoEntrega>0</PrazoEntrega>
<ValorSemAdicionais>0,00</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,00</ValorValorDeclarado>
<EntregaDomiciliar/>
<EntregaSabado/>
<Erro>-38</Erro>
<MsgErro>
<![CDATA[
Serviço indisponivel para este código administrativo.
]]>
</MsgErro>
</cServico>
<cServico>
<Codigo>40436</Codigo>
<Valor>13,82</Valor>
<PrazoEntrega>3</PrazoEntrega>
<ValorSemAdicionais>13,82</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,00</ValorValorDeclarado>
<EntregaDomiciliar>S</EntregaDomiciliar>
<EntregaSabado>S</EntregaSabado>
<Erro>0</Erro>
<MsgErro/>
</cServico>
<cServico>
<Codigo>41068</Codigo>
<Valor>8,72</Valor>
<PrazoEntrega>7</PrazoEntrega>
<ValorSemAdicionais>8,72</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,00</ValorValorDeclarado>
<EntregaDomiciliar>S</EntregaDomiciliar>
<EntregaSabado>N</EntregaSabado>
<Erro>0</Erro>
<MsgErro/>
</cServico>
</Servicos>`

**Comment by brunohrp** [comment]
retorno:

<Servicos>
<cServico>
<Codigo>40096</Codigo>
<Valor>0,00</Valor>
<PrazoEntrega>0</PrazoEntrega>
<ValorSemAdicionais>0,00</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,00</ValorValorDeclarado>
<EntregaDomiciliar/>
<EntregaSabado/>
<Erro>-38</Erro>
<MsgErro>
<![CDATA[
Serviço indisponivel para este código administrativo.
]]>
</MsgErro>
</cServico>
<cServico>
<Codigo>40436</Codigo>
<Valor>13,82</Valor>
<PrazoEntrega>3</PrazoEntrega>
<ValorSemAdicionais>13,82</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,00</ValorValorDeclarado>
<EntregaDomiciliar>S</EntregaDomiciliar>
<EntregaSabado>S</EntregaSabado>
<Erro>0</Erro>
<MsgErro/>
</cServico>
<cServico>
<Codigo>41068</Codigo>
<Valor>8,72</Valor>
<PrazoEntrega>7</PrazoEntrega>
<ValorSemAdicionais>8,72</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,00</ValorValorDeclarado>
<EntregaDomiciliar>S</EntregaDomiciliar>
<EntregaSabado>N</EntregaSabado>
<Erro>0</Erro>
<MsgErro/>
</cServico>
</Servicos>

**Comment by brunohrp** [comment]
Segue no retorno

![sem titulo](https://cloud.githubusercontent.com/assets/19653229/21262057/4fd95cf8-c376-11e6-887c-b512edc1c6e3.png)

**Comment by rafaelpatro** [comment]
Então, seu contrato prevê o serviço SEDEX 40436.
É só selecionar este serviço nas configurações do módulo.
_Obs.: Se esta opção não estiver disponível, é provável que sua versão do módulo esteja desatualizada. Atualize, e irá aparecer o serviço SEDEX 40436._

**Comment by brunohrp** [comment]
Ok, Obrigado. Vou atualizar e verificar

**Comment by brunohrp** [comment]
@rafaelpatro deu certo, obrigado
