### ISSUE TITLE
erro - system.log na versão 4.7.2

### ISSUE THREAD

**Issue by marcospaf** [pedro-teixeira/correios#210]
olá pessoal, venho pedir ajuda.

recentemente eu pulei da versão 4.2 para 4.7 para me manter atualizado, mas começou a aparecer os seguintes erros. Estes erros é relacionado ao monitoramento automático ? É possível desligar se for?

2017-03-13T12:29:54+00:00 DEBUG (7): pedroteixeira_correios [cache]: mode=0 status=write key=40096x81019x41068_01_16_42802280
2017-03-13T12:30:02+00:00 ERR (3): Notice: Undefined property: stdClass::$evento  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
2017-03-13T12:30:02+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
2017-03-13T12:30:02+00:00 ERR (3): Notice: Undefined property: stdClass::$evento  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184
2017-03-13T12:30:02+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184
2017-03-13T12:30:02+00:00 ERR (3): Notice: Undefined property: stdClass::$evento  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 185
2017-03-13T12:30:02+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 185

**Comment by marcospaf** [comment]
@pedro-teixeira @rafaelpatro , pessoal não sei se vocês podem me dar um ajuda. Vou até explicar meu caso. Eu recentemente na minha loja eu estava usando a versão 4.2 do modulo e estava tudo ok, porém resolvi atualizar para ter algo melhor, porém estou me deparando com este problema acima.

Não acredito que seja algo grave, pois estão entrando vendas, mas após fazer algumas atualizações o "magentão" deu uma bugada e começou a pular números de pedidos , isso ocorreu depois que fiz o seguinte:

1 - Atualizei o modulo de vocês
2 -  instalei o modulo zendesk support 
3 -  instalei o modulo ricardo martins de pagamento

Estou desabilitando um por um para testar, vocês acham que estes erros de alguma maneira poderiam ocasionar estes pulos? pode ser tb um problema de servidor , mas aconteceu logo após fazer as modificações. 

o problema que no meu system. log , só tenho este problema.

se puderem me ajudar eu agradeço muito

att

marcos

Esse monitoramento automático como faço para desligar ele?

**Comment by rafaelpatro** [comment]
Bom dia. O Magento pode pular numeros de pedidos eventualmente. Isso pode
ocorrer normalmente em casos de falha na finalização do pedido. As falhas
mais comuns são por problemas no pagamento, como cartão não autorizado,
inválido, etc.

Em 14 de mar de 2017 10:17 AM, "Marcos" <notifications@github.com> escreveu:

**Comment by marcospaf** [comment]
OPa Rafale beleza? Então isso nunca ocorreu. Realmente já me falaram isso, mas está uma constante agora e começou a ocorrer após estas instalações e atualizações. Meu site está hospedado da magemojo já tem anos. De fato até pode ser isso , mas estou estranhando porque foi logo após eu atualizar.

Outra duvida rafael estes erros que aparecem do modulo é referente ao cron ?

**Comment by marcospaf** [comment]
Mesmo assim agradeço e vou investigar aqui

**Comment by rafaelpatro** [comment]
Os pulos na numeração dos pedidos funcionam assim... (exemplo)

_O cliente vai para o checkout, preenche o cadastro, escolhe o frete, preenche os dados do cartão, e clica em Finalizar._

Ao clicar em finalizar o Magento já reserva um número de pedido.

Caso operadora do cartão recuse a transação (motivos: nº segurança inválido, data de validade inválida, etc), o Magento pára o processo e permite que o cliente volte a etapa anterior, para corrigir o problema, ou escolher outra forma de pagamento, sem perder o carrinho.

Alguns módulos de pagamento não tem esse recurso, e acabam criando um pedido já cancelado.
O cliente então precisa começar tudo do zero.
Particularmente prefiro que o Magento pule alguns números, do que registar vários pedidos cancelados no backend.

**Comment by marcospaf** [comment]
Entendi.

Poxa eu só estou com este erro agora no modulo do pedro, não sei se consegue me ajudar:

ainda não tirei o cron, será que é relacionado a ele?

2017-03-14T22:29:02+00:00 DEBUG (7): pedroteixeira_correios [cache]: mode=0 status=write key=40096x81019x41068_01_16_21310310
2017-03-14T22:29:02+00:00 DEBUG (7): pedroteixeira_correios [cache]: mode=0 status=write key=40096x81019x41068_01_16_21310310
2017-03-14T22:29:40+00:00 DEBUG (7): pedroteixeira_correios [cache]: mode=0 status=write key=40096x81019x41068_01_16_21310310
2017-03-14T22:30:02+00:00 ERR (3): Notice: Undefined property: stdClass::$evento  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
2017-03-14T22:30:02+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 183
2017-03-14T22:30:02+00:00 ERR (3): Notice: Undefined property: stdClass::$evento  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184
2017-03-14T22:30:02+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184
2017-03-14T22:30:02+00:00 ERR (3): Notice: Undefined property: stdClass::$evento  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 185
2017-03-14T22:30:02+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/lojabusc/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 185

**Comment by rafaelpatro** [comment]
Eu não me preocuparia com esse erro. É bem comum. Alguma encomenda ainda
não foi atualizada nos Correios, e a extensão ainda não lida muito bem com
o erro.
O importante é que isso não impede o monitoramento das outras encomendas.
Só ainda não foi corrigido por que não é crítico. Mas daqui a pouco alguém
posta uma correção.

Em 14 de mar de 2017 7:36 PM, "Marcos" <notifications@github.com> escreveu:

**Comment by marcospaf** [comment]
Show

**Comment by marcospaf** [comment]
Fala ai @rafaelpatro  beleza?  poxa se der me tira uma duvida:

Eu vi que já atualizaram o modulo para os novos códigos. já mandei meu contrato, mas ainda não liberaram. Se eu atualizar o modulo ainda consigo usar com os códigos antigos de contrato? 
Fiquei com esta dúvida.

Outra coisa , o pedro vai subir ele lá no magento Connect? 

valeu meu amigo

**Comment by rafaelpatro** [comment]
@marcospaf, se atualizar o módulo, os códigos antigos serão descartados. O módulo exibe apenas alguns códigos sem contrato.
Assim que liberarem seu contrato, e vc tiver um usuário e senha para acesso ao SIGEP Web, você poderá baixar os códigos de serviço disponíveis para seu contrato.

Se preferir pode atualizar o módulo, e inserir os códigos antigos manualmente no banco de dados. É só localizar a tabela _correios_postmethods_, e mandar ver.

**Comment by marcospaf** [comment]
@rafaelpatro  valeu rafael agora vou te falar eu to conseguindo calcular o frete com os dois códigos o antigo e o novo ... tem código que o pac aumentou R$ 20,00 , não sei se reparou --- do cep 21310310 para o cep 68638000 , o pac no código 41068 custava - 26,61 , no cdigo 04669 passou para apenas 44,20. quem vai comprar ? complicado em

**Comment by marcospaf** [comment]
@rafaelpatro, rapaz desculpe ai te perturbar, eu estou tentando errar o mínimo possível aqui na instalação. Eu posso instalar por cima via ftp a versão 4.8.0 ou tenho que tomar algum cuidado? estou com a 4.7.2 . Cada hora que mexemos no site é fogo. valeu meu amigo .

**Comment by marcospaf** [comment]
só ressaltando que a senha do sigepweb master , eu tb já solicitei. Como nunca usei o sigepweb, nem me preocupei.

**Comment by rafaelpatro** [comment]
Se seu release é 4.7.2, precisará alterá-lo para 4.7.0. Tome cuidado para
não acessar a loja, e nem o backend. Em seguida copie os arquivos do último
release, e agora sim acesse a loja.

Em 9 de mai de 2017 4:33 PM, "Marcos" <notifications@github.com> escreveu:

**Comment by marcospaf** [comment]
@rafaelpatro  , para trocar para a 4.7.0 , basta alterar o número da versão para 4.7.0 na tabela core_resource , certo? e depois instalo. e os clientes podem acessar a loja , ou tenho que deixar a loja off-line no processo? fiquei nesta duvida . valeu

**Comment by rafaelpatro** [comment]
Se sua loja tiver o compilador ativo, e todas as caches ativas, sim pode
manter on-line. Depois de alterar o release, copiar os arquivos, é só
recompilar e atualizar a cache.

Em 9 de mai de 2017 5:22 PM, "Marcos" <notifications@github.com> escreveu:

**Comment by marcospaf** [comment]
opa @rafaelpatro  cara consegui instalar e ta funcionando a principio, porém preciso de sua ajuda no código do E-sedex que não veio. O sigepWeb estou sem a senha master  ai não vou conseguir baixar. Como faço para inserir o código do E-sedex?  

Cara fiz como tu falou , deu certo. deu um erro no inicio , mas limpei o cache e foi de boa.

**Comment by marcospaf** [comment]
lembrei você tinha me falado - " Se preferir pode atualizar o módulo, e inserir os códigos antigos manualmente no banco de dados. É só localizar a tabela correios_postmethods, e mandar ver. " vou tentar

**Comment by rafaelpatro** [comment]
Então, pode inserir direto no banco sim. Mas há um motivo pro e-Sedex não
aparecer. Ele foi removido dos novos contratos. Talvez até funcione a
cotação, mas quando realizar a postagem na agência poderá ter problemas.

Em 9 de mai de 2017 8:35 PM, "Marcos" <notifications@github.com> escreveu:

**Comment by marcospaf** [comment]
@rafaelpatro  E-sedex continua valendo normal, até cair a liminar. quando mudei meu contrato a assinatura foi feita mantendo o E-sedex até ficar a liminar. eu sei que esta liminar vai cair , está na cara.

Eu fiz assim no banco - http://prnt.sc/f60kd0
Porém no calculo está aparecendo assim >>> http://imgur.com/a/fGHHM

Tinha que aparecer só E-sedex , como faço

**Comment by rafaelpatro** [comment]
Ok. Boa notícia!
Altera o arquivo de tradução: https://github.com/pedro-teixeira/correios/blob/master/app/locale/pt_BR/PedroTeixeira_Correios.csv

**Comment by marcospaf** [comment]
@rafaelpatro  , acho que é algo que você poderia avisar para a galera ai do E-sedex e poderia continuar tendo , só vai sair se sair a liminar , beleza:? vou fazer aqui
