### ISSUE TITLE
Alteração de códigos dos serviços 

### ISSUE THREAD

**Issue by rodolfovs** [pedro-teixeira/correios#212]
Boa tarde,

Fui informado pelos correios que haverá mudança nos códigos dos serviços de SEDEX CONTRATO e PAC CONTRATO. É possível incluir esses novos códigos no plugin, ou mesmo alterar os antigos? De acordo com os correios esses novos códigos começam a valer a partir de 05/04/2017.

Att.

Rodolfo

**Comment by rodolfovs** [comment]
Outra coisa, fui informado que o serviço de PAC não será mais oferecido para localidades do mesmo estado, por exemplo, eu que sou de São Paulo não conseguirei enviar para para São Paulo Capital e interior, somente SEDEX. Se meu sistema está configurado para ter o serviço de PAC como frete grátis, nessas regiões que não tem PAC automaticamente o serviço de frete grátis será o SEDEX?

**Comment by marcospaf** [comment]
olá @rodolfovs  rapaz o problema que eu não sei se os códigos serão iguais para todo mundo , para que vai ter desconto para cada cliente pelo que eu entendi

eu recebi este códigos
SEDEX CONTRATO 0416-2 
PAC CONTRATO 0466-9

verifica se são iguais aos seus. Ainda estou tentando entender as tabelas , mas creio que tudo aumentou como sempre. 

O e-sedex vai acabar parece que vão derrubar a limitar .... vai ser um sufoco só isso ....  
Essa informação de não poder mandar pac para a mesma região eu não recebi, novidade para mim

**Comment by rodolfovs** [comment]
Olá Marcos,

Os códigos são os mesmos que os meus. Pelo que eu entendi na tabela que recebi é que as localidades que não terão mais o PAC vão ser atendidas pelo SEDEX com preço de E-Sedex. Por exemplo, dentro do estado de origem, no meu caso São Paulo, não poderei fazer envio de PAC, mas meus envios de SEDEX são os da coluna L1 até L4, que eles chamam de envios locais, que inicia com o valor de R$7,78.

Eu imagino que a questão dos códigos de serviço até não deve ser difícil de resolver, eu testei ontem o cálculo de frete no webservice dos correios e calculou, só os preços que ainda não estão parametrizados. A grande questão é que, no meu caso ofereço frete grátis acima de R$150,00 pelo PAC, mas em destinos dentro do meu estado não haverá mais o PAC, e desta forma aparecerá somente o SEDEX sem estar com o valor zerado.

**Comment by marcospaf** [comment]
rapaz isso realmente não sei , somente o @pedro-teixeira para falar , mas pleo que perguntei esse será o nosso procedimento para as lojas virtuais .. vamos ver

**Comment by rodolfovs** [comment]
Qual procedimento você está falando?

**Comment by rodolfovs** [comment]
Considerar mais de um serviço como frete grátis, quando um não estiver disponível?

**Comment by cfgalvani** [comment]
Olá pessoal. Alguma novidade sobre essa questão? Sabem se o 40096 (Sedex com contrato) e 41068 (Pac com contrato) vão deixar de funcionar ou se os novos (SEDEX CONTRATO 0416-2 e PAC CONTRATO 0466-9) são modos adicionais?

**Comment by rodolfovs** [comment]
Olá cfgalvani,

Sim, os serviços de PAC contrato e SEDEX contrato serão extintos, segundo o gerente do meu contrato informou. Informou também que esses serviços sem contrato, SEDEX à vista e PAC à vista também serão extintos.

Esta mudança estava prevista para amanhã, mas recebi um telegrama informando a prorrogação do processo para 05/05, o que nos dá um tempo maior para adaptarmos nossos sistemas, mas ainda estou aguardando retorno, talvez do Pedro, para ver qual será a melhor forma.

**Comment by marcospaf** [comment]
Pessoal , acabei de vir da agencia . @rodolfovs  @cfgalvani @rafaelstz @pedro-teixeira . o que foi informado o seguinte a principio os serviços de contrato SEDEX contrato 40096 e pac contrato 41068 serão extintos  no dia 05/05/2017.  Todos terão de assinar o novo contrato, pode acontecer que isso seja prorrogado , mas não há certeza.

Outro fato , o serviço E-sedex , será subistituido pelo serviço E-commerce , este serviço não sei o código, mas só entrará quando a liminar do e-sedex for derrubada e será.

Os serviços serão substituídos pelos ´já comentados:

SEDEX CONTRATO 0416-2
PAC CONTRATO 0466-9

o grande problema é que as tabelas são totalmente diferentes dos antigos serviços, ou seja , toda a maneira de calculo deveria ser reescrita. no caso não sei se o Super pedro ou alguém fará esta atualização, mas o atual sistema do pedrão não vai contemplar o contrato.

Vale ressaltar tb, que o serviço de balcão PAC e SEDEX, tb terá outra codificação , pois exemplo : RJ para RJ , SP para SP , não terá mais pac somente sedex ou E-sedex (futuro Recomece) 

VAI SER FLORIDA!!! cara é cada problema que é absurdo. O pedrão ai não tem culpa ele só ajuda, mas será que alguém conseguirá mudar em tempo hábil ?

na assinatura do contrato parece que os correios vai disponibilizar um script para por no site, mas não sei como vai ser adaptado ai no magento

**Comment by rodolfovs** [comment]
Olá Marcos, 

Realmente vai ser complicado, principalmente com o tempo curto que temos. Sobre esta questão de não calcular os novos códigos, eu acredito que vai funcionar, porque neste link dos Correios http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx você consegue simular, e ele retorna da mesma forma os códigos antigos e os novos, então imagino que a estrutura seja a mesma.

O grande problema é que ainda não constam os preços no webservice, somente o prazo, então até os Correios lançarem os valores dos novos códigos no webservice, não conseguiremos testar. 

E para piorar, como não vai existir mais PAC local, de SP para SP, RJ para RJ e etc, como vamos definir um serviço de frete grátis? Porque se definirmos o PAC como frete grátis, quando for local não vai aparecer esta opção. 

Eu estou esperando um retorno do Pedro porque ele mais do que ninguém tem uma visão profunda de como funciona o módulo, e talvez consiga pensar em alguma solução que eu ainda não encontrei. A melhor solução seria cadastrar 2 serviços como frete grátis, um principal e um secundário, e quando o principal não estiver disponível automaticamente o secundário seria o frete grátis.

**Comment by rodolfovs** [comment]
Ou também utilizar o serviço de frete grátis padrão do magento, mas neste caso ele não calcula frete, se conseguíssemos que este serviço mostrasse o prazo do PAC já resolveria.

**Comment by marcospaf** [comment]
opa @rodolfovs então,
deixa eu explicar:
Eu mandei um email para o consultor la da central dos correios , mas se vocês tiverem alguma duvida e quiserem tirar me manda que eu pergunto.

Pelo que a menina da agencia me informou , quando assinado o contrato eles vão fornecer um script para que seja colocado no site .

as tabelas mudaram muito, porque agora tem um tal "corredor" e mudou a maneira de calcular.

O que foi informado, não sei se é verdade, é que eles baixaram os preços. desta forma você terá um sedex grátis , porque o valor do sedex e o valor do pac seriam os mesmos , entende? por isso não terá mais o pac.

eu sei que isso vai dar uma "M" das grandes.  Se vocês quiserem tirar alguma duvida me fala que vou perguntar.

**Comment by rodolfovs** [comment]
Olá Marcos, 

Eu imagino que esse script seja para calcular da mesma forma que você calcula no site dos Correios, mas não imagino o script integrado com o magento para somar o valor do frete ao pedido e registrar no pedido o prazo também.

No final de semana vou fazer alguns testes no módulo, utilizando os novos códigos e informo sobre os resultados. Caso surjam novos pontos sobre este assunto vai postando que vamos acompanhando.

**Comment by rodolfovs** [comment]
Se você puder perguntar qual a previsão dos novos valores estarem no Webservice dos Correios seria bom para começarmos a pensar em como alterar, já com opção de testar valores e prazos.

**Comment by marcospaf** [comment]
Eu tenho algumas tabelas , de qualquer forma no final de semana vou tentar digitalizar e disponibilizar tb.

**Comment by rodolfovs** [comment]
As tabelas eu tenho, pelo que conversamos antes, deve ser a mesma tabela, pois nossos códigos são iguais. Eu acho até que os códigos iniciais serão os mesmos para todos, somente depois de ter um volume maior e enquadrar em outra tabela talvez os códigos mudem.

**Comment by marcospaf** [comment]
Se os códigos são iguais , são as mesmas tabelas mesmo. Agora você tem o código de E-commerce?

Ela informou que o E-sedex vai virar o E-commerce, mas não tenho esta tabela e nem o código. Estou perguntando tb a ele

**Comment by rodolfovs** [comment]
Olha, sobre esse serviço eu não tive informação. Como o valor do Sedex local na nova tabela está praticamente o valor do e-sedex, estava pensando que não haveriam outros serviços. Vou tentar me informar sobre este serviço de e-commerce.

**Comment by alex-andrade** [comment]
Curiosidade, serviço de ecommerce não seria aquele que os Correios fechou parceria com o Bling, no qual as mercadorias ficam em posse dos Correios, em armazéns especiais deles e quando tem a venda, o próprio Correios embala a mercadoria e despacha?(claro, que tem um custo maior!)

**Comment by rodolfovs** [comment]
Boa pergunta, nem sabia que existia essa parceria dos Correios com o Bling rs.

**Comment by alex-andrade** [comment]
Para não aparecer um doido falando que é mentira, segue informação direto do blog oficial dos Correios!
http://blog.correios.com.br/correios/?p=26021

**Comment by rodolfovs** [comment]
Interessante, vou me informar mais, apesar de achar que para mim não vai servir, acho que será mais para grandes lojas, mas é sempre bom saber. Obrigado pela informação.

**Comment by marcospaf** [comment]
Esse serviço ai é meio complicado . pessoal de qualquer forma tenho uma má noticia. Acabei de tirar um reverso e olha só :  http://imgur.com/IiN52jP

Hoje , fica claro que os serviços vão ser interrompidos no dia 06/05 , ou seja , daqui a 30 dias não teremos mais funcionalidades com este código.

Hoje é isso , pode ser que mude depois.

**Comment by camilobcribeiro** [comment]
Pessoal alguem já conseguiu implementar os novos contratos dos correios neste modulo ?
sedex 04162
pac 04669 (Fora de São Paulo)

**Comment by diogodaluz** [comment]
Alguém sabe como procedemos para alterar os códigos dos serviços para contratos com os correios? Bastante importante este tópico.

Sedex e Pac Alteraram (conforme citado acima):

sedex 04162
pac 04669

**Comment by marcospaf** [comment]
@rodolfovs  e ai beleza? o meu consultor respondeu.

Só vai existir PAC e SEDEX  e o E-sedex (enquanto existir a liminar) . ASSINOU O CONTRATO já está valendo as novas tabelas.

Eu entrei em contato com o pessoal da Frenet , falei sobre isso e já implementaram os novos códigos no sistema, talez seja uma alternativa para nós enquanto não conseguimos atualizar aqui.

Agora só ressaltando que eles já conseguiram fazer , então provavelmente já está no webservice .

**Comment by marcospaf** [comment]
Acabei de ligar e assim que o contrato for assinado os códigos não valem mais .... é isso ai !! Brasil!!!!

Alguem já assinou ? vou deixar para assinar em cima do laço !!!absurdo

**Comment by QualiMO** [comment]
Boa tarde! 
Alguém já sabe o que precisamos fazer? 
@tamnil alterou o código, criando as linhas abaixo. Alguém saberia dizer se bastaria incluir naquela relação os novos códigos das tabelas dos correios (0416-2 SEDEX / 0466-9 PAC), para que o plugin funcione com as novas tabelas? 
Se a questão for mais complicada que isso, teria alguém que se disponha a fazer a atualização, mediante pagamento? Neste caso, minha sugestão é fazermos uma "vaquinha" entre os usuários do sistema.
@pedro-teixeira Poderia nos ajudar? 
Obrigado. Segue código.

`public function getAllowedMethods()
      {
        return array($this->_code => $this->getConfigData('title'),
            '40019' =>'sedex(40019)',
            '40096' =>'sedex(40096)',
            '40436' =>'sedex(40436)',
            '81019' =>'E-sedex(81019)',
            '41106' =>'PAC(41106)',
            '41068' =>'PAC(41068)',
            '40215' =>'sedex 10(40215)',
            '40290' =>'sedex hoje(40290)',
            '40045' =>'sedex a cobrar(40045)',
            '41300' =>'PAC GF(41300)',
            '10065' =>'Carta comercial(10065)',
            '10138' =>'Carta comercial registrada(10138)'
 );
      }
`

**Comment by rodolfovs** [comment]
Olá Marcos.

Obrigado pela informação. Eu já assinei, vou ter que correr com isso. Não consegui fazer os testes que queria no fds.

**Comment by camilobcribeiro** [comment]
Pessoal, com o prazo curto acabei editando o modulo, substituindo o contrato sedex  de 40096 para 04162 e pac de 41068 para 04669, simplesmente fiz replace em todo o módulo substituindo os itens, e no banco de dados na tabela core_config_data setei os novos números de contratos.  Para achar na tabela só usar o select abaixo:
SELECT * FROM .core_config_data where path = 'carriers/pedroteixeira_correios/postmethods'

Espero ter ajudado =) !!!Vlw galera

**Comment by rodolfovs** [comment]
Mas está funcionando normalmente Camilo?

**Comment by rodolfovs** [comment]
Você já tinha assinado o contrato? Porque eu não assinei e o cálculo não aparece no meu contrato ainda.

**Comment by camilobcribeiro** [comment]
Sim, meu cliente já assinou o contrato e já está vigente e a API dos correios já está respondendo pelo novo número de contrato, pode fazer testes aqui: http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=CalcPreco
Está funcionando normal sim Rodolfo, porém após fazer a alteração no banco, não recomendo alterar as configurações dos tipos de frete pelo admin do magento !
Abs

**Comment by rodolfovs** [comment]
Certo, obrigado pela informação Camilo. 

Quando você diz novo número de contrato, mudou esse número de contrato do seu cliente?

E sobre o PAC não estar disponível localmente, você sabe dizer se aparece cotação de PAC no mesmo estado do seu cliente? ou nesse caso só aparece SEDEX?

**Comment by camilobcribeiro** [comment]
Exatamente rodolfo, o numero de contrato !
Sobre o PAC, como você pode testar no link que passei acima dos correios, caso você coloque  um cep de sp para sp ele retorna erro, e no modulo do pedro teixeira já tem a tratativa de erros, ele apenas não apresenta o valor no e-commerce, trazendo apenas o Sedex ou outro frete que você tenha configurado em sua loja.

**Comment by rodolfovs** [comment]
Mas seu cliente oferece frete grátis? Se sim como ele faz, SEDEX ou PAC? Porque se ele optar por oferecer frete grátis pelo PAC, quando for envio local não vai ter opção de PAC, e vai aparecer somente SEDEX com valor.

**Comment by camilobcribeiro** [comment]
Rodolfo, não utilizo o PAC como frete grátis, e sim o "Flate Rate" ou em portugues "Valor Fixo" do próprio magento se não me engano para frete grátis. Espero ter ajudado !Abraço

**Comment by rodolfovs** [comment]
Obrigado Camilo, pensei em usar esse serviço, mas ele não oferece prazo, não é o ideal, mas acredito que será a melhor opção no formato atual do módulo.

**Comment by andregugliotti** [comment]
Meus caros,
Vou tentar ajudá-los nisso aqui.

O @pedro-teixeira não trabalha mais com Magento há uns bons quatro anos. Portanto, não adianta esperar que ele resolva o problema. É por isso que o módulo é gratuito e aberto, para que todos possam contribuir. Não estava sabendo desse problema dos Correios, mas vou ver o que posso fazer nos próximos dias.

Em relação a como é possível solucionar, eis as ideias:

a) os códigos dos Correios no módulo servem para "guiar a resposta". Provavelmente, o novo webservice da belíssima empresa brasileira de entregas manterá o mesmo esquema. Eles mandam um retorno para os códigos de envio solicitados (e possíveis erros). Então, se os novos códigos forem incluídos, eles devem retornar um valor ou um erro/info
b) o tratamento dos erros é um pouco chato, pois algumas vezes a belíssima empresa retorna um código de erro quando na verdade é apenas uma mensagem informativa (exemplo, entrega em área de risco). No manual deles, há uma extensa e confusa lista de erros, será o caso de individuar o erro e tratá-lo
c) o frete grátis: esse será o maior problema! O módulo atual habilita o frete grátis apenas se a opção escolhida é retornada. O que pode ser feito aqui em um modo grosseiro é um IF para "se método X não está disponível na consulta, use método Y como frete grátis". Outra possibilidade é refatorar o campo de frete grátis e passá-lo para comportamento. Quero dizer, algo como "habilitar apenas PAC", "primeiro PAC, depois SEDEX"
d) pra concluir, esse novo método E-Commerce provavelmente dependerá de parâmetros adicionais. Se a belíssima empresa fez a coisa certa, eles vão precisar de infos como os produtos no carrinho, quantidade, armazém de origem. Nada disso existe no módulo atual e não é coisa rápida de implementar.

Se não me engano, o @pedro-teixeira segue acompanhando as pull requests, então quem quiser fazer as modificações e submeter a PR, creio que ele possa inclui-la no módulo.

**Comment by Litiano** [comment]
Pessoal, fiz uma PR (https://github.com/pedro-teixeira/correios/pull/216)
Se quiserem testar https://github.com/Litiano/correios

**Comment by andregugliotti** [comment]
Prezados,
Resolvi colocar uma versão do meu módulo dos Correios aqui no Github. Ela está disponível em https://github.com/Diamix/magento1_correios

Fiz a atualização com os novos códigos dos Correios e com o frete grátis. Os testes que fiz com o usuário padrão dos Correios funcionaram normalmente. Quem quiser se basear pra fazer o restante das alterações no módulo do Pedro, fique à vontade.

**Comment by rodolfovs** [comment]
Olá @andregugliotti 

Uma pergunta, a questão de oferecer uma segunda opção de frete grátis quando a primeira não estiver disponível você conseguiu implementar em seu módulo?

**Comment by andregugliotti** [comment]
@rodolfovs 
Sim, implementei o comportamento de first PAC, then Sedex. Está no Helper/Data.php, no momento da decisão do Free Shipping. Quando ele não encontra o PAC, dá o Sedex (mas atenção, pois isso vale também para os identificadores antigos, que em teoria não devem ser habilitados simultaneamente com os novos).

**Comment by rodolfovs** [comment]
@andregugliotti Interessante, vou instalar seu módulo e ver como funciona, e também tentar implementar esta solução no módulo do Pedro. Obrigado por compartilhar conosco.

**Comment by marcospaf** [comment]
ta complicado mesmo, vou assinar o meu agora ...ta fogo!!!

**Comment by marcospaf** [comment]
@Litiano  beleza ?  tá funcionando legal ?  assim vou assinar meu contrato essa semana. é fogo

**Comment by marcospaf** [comment]
@rodolfovs  já conseguiu testar? vou mandar segunda-feira o contrato assinado . Me falaram que o preços diminuíram , realidade? kkkk eu não acredito.

**Comment by Litiano** [comment]
@marcospaf eu gostaria que vocês testassem e dessem um retorno e avaliação para que o @pedro-teixeira  possa aceitar o ajuste.

**Comment by edumandiba** [comment]
Amigos será necessário mudar os códigos no xml?? Se sim,  Quais linhas devem ser alteradas???

**Comment by rafaelpatro** [comment]
Olá @edumandiba 
Sim, você precisará alterar dois arquivos.
Se não souber como fazer, sugiro baixar a PR #216 do @Litiano. Ele já alterou os arquivos necessários.
