### ISSUE TITLE
Erro instalação commit 9d813b5 

### ISSUE THREAD

**Issue by kinfoxxx** [pedro-teixeira/correios#219]
Atualizei para a nova versão do modulo porem não entra nas configurações Formas de Entrega , da erro 

a:5:{i:0;s:178:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c4192.correios_postmethods' doesn't exist, query was: SELECT `main_table`.* FROM `correios_postmethods` AS `main_table`";i:1;s:3321:"#0 /var/www/clients/client4/web5/web/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/clients/client4/web5/web/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /var/www/clients/client4/web5/web/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/clients/client4/web5/web/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /var/www/clients/client4/web5/web/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /var/www/clients/client4/web5/web/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#6 /var/www/clients/client4/web5/web/lib/Varien/Data/Collection/Db.php(740): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#7 /var/www/clients/client4/web5/web/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 /var/www/clients/client4/web5/web/lib/Varien/Data/Collection/Db.php(572): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 /var/www/clients/client4/web5/web/lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#10 /var/www/clients/client4/web5/web/app/code/community/PedroTeixeira/Correios/Model/Source/PostMethods.php(26): Varien_Data_Collection->getIterator()
#11 /var/www/clients/client4/web5/web/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(463): PedroTeixeira_Correios_Model_Source_PostMethods->toOptionArray(true)
#12 /var/www/clients/client4/web5/web/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#13 /var/www/clients/client4/web5/web/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#14 /var/www/clients/client4/web5/web/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#15 /var/www/clients/client4/web5/web/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#16 /var/www/clients/client4/web5/web/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#17 /var/www/clients/client4/web5/web/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#18 /var/www/clients/client4/web5/web/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /var/www/clients/client4/web5/web/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#20 /var/www/clients/client4/web5/web/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#21 /var/www/clients/client4/web5/web/index.php(83): Mage::run('', 'store')
#22 {main}";s:3:"url";s:90:"/index.php/asus2/system_config/edit/section/carriers/key/bccae352c40d59344020d44760fed69a/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}
![2017-04-27](https://cloud.githubusercontent.com/assets/19422479/25466586/07baa7de-2ae0-11e7-8bfa-c6b1378d8634.png)

**Comment by rafaelpatro** [comment]
Aparentemente a tabela _correios_postmethods_ não foi inserida na atualização.
Acesse a tabela _core_resource_, e atualize o número da versão para 4.7.0.

**Comment by pedro-teixeira** [comment]
@rafaelpatro estranho, não? Talvez algum problema com a migração?

**Comment by rafaelpatro** [comment]
Talvez ele estivesse com um release diferente.
Coloquei a última versão como 4.7.3 e fiz o upgrade apenas entre 4.7.0 e 4.7.3:
https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/sql/pedroteixeira_correios_setup/upgrade-4.7.0-4.7.3.php

**Comment by kinfoxxx** [comment]
Boa tarde, deu certo, abaixei na tabela para 4.7.0 e atualizei o modulo novamente, provavelmente deu algum erro na primeira atualização. Obrigado

**Comment by marceloberwanger** [comment]
Resolvido. Para registro, ocorreu que foi utilizada uma base de dados que já possuía o módulo dos Correios instalado em uma instalação nova. Foi realizado o upload dos arquivos manualmente, o cache foi limpo, novo login na administração e ao tentar acessar as configurações da extensão obtive o mesmo erro. A versão que constava na base era a 4.2.0 e a que foi instalada foi a 4.9.0. O mesmo erro ocorreu na 4.8.1 em uma tentativa anterior.

Segui o procedimento informado e resolveu.

Obrigado!
