### ISSUE TITLE
Nova versão

### ISSUE THREAD

**Issue by kinfoxxx** [pedro-teixeira/correios#220]
Boa noite, na versão nova quem não tiver contrato com os correios não vai conseguir utiliza-la ?

**Comment by rafaelpatro** [comment]
@kinfoxxx
Realmente, não vai funcionar sem contrato.
Mas é bem simples de resolver. É só adicionar os registros na tabela _correios_postmethods_ durante o setup.

Pode fazer direto no banco também.

    method_code | method_title
    40010 | SEDEX SEM CONTRATO
    41106 | PAC SEM CONTRATO
    40215 | SEDEX 10 SEM CONTRATO
    40045 | SEDEX A COBRAR SEM CONTRATO

Vou tentar enviar uma correção assim que der.

**Comment by rafaelpatro** [comment]
@pedro-teixeira essa questão é importante. Sugiro não fechar release sem isso corrigido.

**Comment by pedro-teixeira** [comment]
@rafaelpatro sim, vou segurar até termos uma solução pra isso
