### ISSUE TITLE
Rastreamento em Branco

### ISSUE THREAD

**Issue by cfgalvani** [pedro-teixeira/correios#222]
Alguns pedidos ficam sem os dados dos correios na tela de rastreamento:

[erro](http://imgur.com/a/BSAYU)

Em exception.log e system.log não aparece nenhum erro. Quando copio o código que está no site e peço pra rastrear direto no site dos correios, mostra diversas informações de acompanhamento do pedido.

**Comment by rafaelpatro** [comment]
O webservice de consulta de rastreamento, e o site dos Correios não trabalham juntos. Eventualmente um deles cai e o outro continua funcionando. Se for o caso de instabilidade, seu rastreamento deve funcionar hoje.

Se o problema persistir, talvez seja algo com o _stream_context_, que foi adicionado na última PR. Nesse caso, sugiro fazer o seguinte...

https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php#L590

Na linha destacada, substitui o parâmetro `Mage::helper('pedroteixeira_correios')->getStreamContext()` por `array()`.

Não esquece de limpar a cache, e recompilar.

**Comment by cfgalvani** [comment]
@rafaelpatro, fiz a alteração que me sugeriu e mesmo assim o problema persiste. A não ser que agora esteja certo mas que hoje haja alguma instabilidade como disse.

**Comment by cfgalvani** [comment]
Consegui descobrir o que era. O status do pedido era atualizado automaticamente pelo Bling que também colocava o código de rastreamento. O problema é que o Bling estava configurado para preencher o Shipping Carrier como custom, e não pedroteixeira_correios. Fiz a alteração no Bling e no banco de dados do Magento para alterar todos que estavam com shipping carrier custom para o do pedro teixeira.
