### ISSUE TITLE
Usuário e Senha

### ISSUE THREAD

**Issue by DaviSiqueira** [pedro-teixeira/correios#224]
Boa noite!

Atualizei o módulo e percebi que existe novas opções na configuração "Usuário" e "Senha"

Eu coloquei as informações que uso para acessar https://apps.correios.com.br/idCorreios
está correto?

Quando clico no botão Atualizar (Atualizar Serviços) recebo o erro: Cant receive postmethods! A autenticacao de meu_usuario falhou!

O que estou fazendo de errado?

Obrigado

**Comment by rafaelpatro** [comment]
@DaviSiqueira sugiro verificar com seu representante comercial dos Correios, se você tem um usuário e senha exclusivos para acesso ao SIGEP Web.
Se preferir você pode manter a tabela de postagens manualmente. Basta cadastrar os códigos de postagem que você usa na tabela _correios_postmethods_. Ex.:

```sql
INSERT INTO correios_postmethods (method_code, method_title)
VALUES
    ('40010', 'SEDEX SEM CONTRATO'),
    ('41106', 'PAC SEM CONTRATO'),
    ('40215', 'SEDEX 10 SEM CONTRATO'),
    ('40045', 'SEDEX A COBRAR SEM CONTRATO');
```

**Comment by DaviSiqueira** [comment]
@rafaelpatro Acabei de instalar o módulo em uma loja zerada, ao acessar as configurações do módulo recebo o erro:

`a:5:{i:0;s:183:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'qpugrrpsnn.correios_postmethods' doesn't exist, query was: SELECT `main_table`.* FROM `correios_postmethods` AS `main_table`";i:1;s:3893:"#0 `

Eu não entendo nada de programação mas acredito que a tabela "correios_postmethods" não foi criada, correto?

Pode ser por isso que estou recebendo o erro:

`Cant receive postmethods! A autenticacao de meu_usuario falhou!`

na outra loja?

**Comment by rafaelpatro** [comment]
Acredito que os erros que descreveu não tem relação alguma.

1. `Base table or view not found`
  Aparentemente a tabela _correios_postmethods_ não foi inserida na instalação.
  Tente criar a tabela manualmente:
```sql
  CREATE TABLE IF NOT EXISTS qpugrrpsnn.correios_methods (
      method_id int(11) unsigned NOT NULL auto_increment,
      method_code varchar(5) NOT NULL default '0',
      method_title varchar(255) NOT NULL default '',
      PRIMARY KEY (method_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```


2. `Cant receive postmethods! A autenticacao falhou!`
  Você não possui usuário e senha para usar o SIGEP Web, ou seu usuário e senha estão incorretos.

**Comment by DaviSiqueira** [comment]
Deu certo @rafaelpatro adicionei a tabela correios_postmethods. (o código que você me passou faltou o "post")

Sobre o usuário e senha, eu estava fazendo confusão, peguei as informações da minhas configurações do Bling e deu certo, puxou os métodos de pagamento.

Só tenho mais uma dúvida, eu não tenho os atributos largura, altura, comprimento... saberia me informar qual os atributos necessários ?

**Comment by rafaelpatro** [comment]
@DaviSiqueira, sugiro que tente reinstalar o módulo. Deve ter ocorrido algum problema durante a sua instalação. Há mais campos além das dimensões. E se não for instalado corretamente, pode lhe causar problemas.
Certifique que o número da [versão seja 4.8.0](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L18), e que tenha o [arquivo de instalação](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/sql/pedroteixeira_correios_setup/install-4.8.0.php#L141).

**Comment by willgoulding** [comment]
@DaviSiqueira você sabe me informa aonde consigo a informação do usuário e senha? tentei colocar o no lugar do usuario  o Código administrativo e a senha que uso para entrar no SIGEP mas retorna A autenticacao de ****** falhou!

**Comment by DaviSiqueira** [comment]
@willgoulding entra em contato com a agência dos correios que abriu o contrato pra você, solicita um usuário para usar o SIGEP

**Comment by willgoulding** [comment]
Obrigado @DaviSiqueira consegui resolver!

**Comment by tarsogarcia** [comment]
Boa tarde,
Instalei mas esta dando esse erro, sera que pode ser o problema com o usuario dos correios?
Utilizei o usuario e senha que acessamos o sistema de logistica reversa, mas continua dando erro ou a conexão cai, poderiam me ajudar?
Estou usando a ultima versão do modulo.

Cant receive postmethods! A autenticacao de null falhou!

**Comment by rafaelpatro** [comment]
Após preencher o usuário e senha, salve as configurações. E só então clique em Atualizar.
Se o erro persistir é pq seu usuário e senha estão incorretos.

**Comment by tarsogarcia** [comment]
@rafaelpatro obrigado! Funcionou
