### ISSUE TITLE
Cod. Serviço 05/05/2017

### ISSUE THREAD

**Issue by valiati100** [pedro-teixeira/correios#227]
Parece que o correio atualizou o cod. de serviço para pac e sedex.

Pac: Codigo de servico invalido. Desde 05/05/2017 ele foi substituido pelo 04510.
Sedex: Codigo de servico invalido. Desde 05/05/2017 ele foi substituido pelo 04014.

**Comment by MrHerickS** [comment]
Isto está causando vários erros em websites que usam o webservice. Gostaria de um help para atualizar nesse plugin :(

**Comment by mvsucupira** [comment]
Onde posso trocar esta informação no código?

**Comment by valiati100** [comment]
Estou tentando alterar pelo php, porém sem sucesso. O site fica muito lento.

**Comment by alantavares** [comment]
Pessoal é só realizar a troca por esses códigos mesmo? 
Tem algum link ou e-mail dos correios anunciando essa mudança?
Vi que apenas o PAC e Sedex sem contrato que estão sendo afetados.

**Comment by MrHerickS** [comment]
Galera, resolvi temporariamente usando uma gambiarra enquanto o autor ainda não corrige!

No **app/code/community/PedroTeixeira/Correios/Model/Carrier** busquem por:

$client->setParameterGet('nCdServico', $this->_postMethods);
e troquem por $client->setParameterGet('nCdServico', $this->_postMethods.',04014,04510');

Agora busquem por

$content = $client->request()->getBody();

E após essa linha insiram

$content = str_replace('04014', '40010', $content);
$content = str_replace('04510', '41106', $content);

Espero ter ajudado enquanto não sai atualização. <3

**Comment by valiati100** [comment]
Opa. Legal a solução. Resolveu para mim também

**Comment by fchiqueto** [comment]
Obrigado @MrHerickS aqui funcionou também!

**Comment by JoaoHenriqueVale** [comment]
Obrigado @MrHerickS!

**Comment by gabstv** [comment]
Top! @MrHerickS!

Este é o Cinco de Mayo dos correios...

**Comment by ryaanx** [comment]
Obrigado, funcionou

**Comment by mvnp** [comment]
No meu Magento 1.9.3.1 e 1.9.2.3 não está funcionando pra mim. Podem mostrar o passo a passo e falar se foram estas as versões que usaram?

**Comment by kinfoxxx** [comment]
Aqui deu ''Dimensões dos produtos fora do permitido pelos Correios. ''

**Comment by MrHerickS** [comment]
@mvnp estou usando a versão 1.9.2.2 do Magento.
Podem postar no pastebin o seu CorreiosMethod.php com as modificações que fez?

**Comment by esxbr** [comment]
Funcionou pra mim!

Segue pastebin ... pesquise por FIX que vai achar onde ajustei.

https://pastebin.com/N9rvE3S4

**Comment by MrHerickS** [comment]
Perfeito @esxbr @

**Comment by kinfoxxx** [comment]
Deu certo agora, eu tinha alterado na tabela o código mais não deu certo, voltei o código antigo na tabela e fiz o procedimento informado.

**Comment by lucasPiovesan** [comment]
Para mim essa tratativa também não funcionou, minha versão do magento é 1.9.2. 

O retorno dos correios está vindo vazio, por mais que eu faça as requisições na "mão".

**Comment by marlon-micrologi** [comment]
Galera, 

Acabei de atualizar na minha loja, tive que alterar alguns locais, estou disponibilizando a pasta "PedroTeixeira" para trocar em "/app/code/community/PedroTeixeira".

No meu caso foi necessário um UPDATE também na base, mas caberia um select antes para ver se realmente é necessário para vocês: 
UPDATE core_config_data SET value='04014,04510' WHERE path='carriers/pedroteixeira_correios/postmethods';
UPDATE core_config_data SET value='04510' WHERE path='carriers/pedroteixeira_correios/free_method'; 

Link para download da pasta corrigida: [https://app.box.com/s/cq3u57u1i2k2yo5m5qey1wttymb1s784](https://app.box.com/s/cq3u57u1i2k2yo5m5qey1wttymb1s784)

**LEMBRANDO:** 
>>> BACKUP DA PASTA E DO BANCO DE DADOS ANTES DE QUALQUER COISA <<<
>>> ISSO É TEMPORÁRIO ATÉ O AUTOR CORRIGIR O MÓDULO <<<
>>> CASO CONTINUE NÃO FUNCIONANDO, RETORNEM O BACKUP ;) <<<

**Comment by rfbastos** [comment]
Vejam a Issue #229

**Comment by mvnp** [comment]
Pessoal, estou com a seguinte mensagem: 
Dimensões dos produtos fora do permitido pelos Correios

Porém os produtos estão dentro das dimensões mínimas e máximas. O que pode ser?

**Comment by lmarquine** [comment]
Aqui ainda está aparecendo Não há formas de entregas disponíveis para este pedido no momento. Mesmo após a alteração e cache limpo.

**Comment by rafaelpatro** [comment]
Pessoal, fiz uma PR #229 para corrigir este problema, mas é importante destacar alguns pontos.

1. Até o momento não foi feito merge, então quiser a correção agora precisará baixar os [arquivos aqui](https://github.com/rafaelpatro/correios/tree/bugfix_new_codes).
2. Se sua versão já é 4.8.0, precisará alterar esse número para 4.7.0.
2.1. O número da versão deve ser baixado manualmente na tabela _core_resource_. E obviamente isto precisa ser feito antes de instalar a correção.
3. Se sua versão é inferior a 4.7.0, pode atualizar sem alterar o release.
4. Após a atualização, acesse as configurações do módulo, e reajuste os serviços de postagem.
4.1. Se utiliza os _Serviços por Produto_, precisa reconfigurar os produtos também.
5. Quem possui contrato, e possui usuário e senha no SIGEP Web, precisa reconfigurar o módulo, e atualizar os códigos de serviços.

**Comment by lmarquine** [comment]
Rafael, desculpe minha pergunta, mas quando altero a versão no banco de dados ele quebra a loja. Se volto para a versão 4.8.0 aparece Pac: Codigo de servico invalido. Desde 05/05/2017 ele foi substituido pelo 04510.

a:5:{i:0;s:344:"Error in file: "/home/webviewc/public_html/tina/app/code/community/PedroTeixeira/Correios/sql/pedroteixeira_correios_setup/install-4.8.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY', query was: INSERT INTO `correios_postmethods` (`method_id`, `method_code`, `method_title`) VALUES (?, ?, ?)";i:1;s:1004:"#0 /home/webviewc/public_html/tina/app/code/core/Mage/Core/Model/Resource/Setup.php(644): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /home/webviewc/public_html/tina/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '4.8.0')
#2 /home/webviewc/public_html/tina/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('4.8.0')
#3 /home/webviewc/public_html/tina/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /home/webviewc/public_html/tina/app/code/core/Mage/Core/Model/App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /home/webviewc/public_html/tina/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#6 /home/webviewc/public_html/tina/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /home/webviewc/public_html/tina/index.php(83): Mage::run('', 'store')
#8 {main}";s:3:"url";s:6:"/tina/";s:11:"script_name";s:15:"/tina/index.php";s:4:"skin";s:7:"default";}

**Comment by rafaelpatro** [comment]
Sim. Precisa limpar a tabela _correios_postmethods_ antes de atualizar. Vou adicionar isso no esclarecimento que passei agora há pouco.

**Comment by lmarquine** [comment]
Rs, agora aparece o erro "Cant receive postmethods! A autenticacao de falhou!"

**Comment by rafaelpatro** [comment]
Então agora está funcionando! Precisa pedir acesso ao SIGEP Web.
Se seus códigos de serviço não estiverem na lista padrão do módulo, precisará adicioná-los diretamente no banco.

**Comment by tuliooov** [comment]
Galeraa nao consegui arrumar o meu ainda, por favor alguem manda mais soluções.
Versão Magento 1.9.2.

**Comment by rodrigocvaz** [comment]
Alguém conseguiu resolver o problema do rastreamento?

**Comment by irineujunior** [comment]
Para aquela loja legada marota, o jeito mais fácil de resolver é trocar:

`$this->_postMethods = $this->getConfigData('postmethods');`

por

`$this->_postMethods = str_replace('40010', '04014', str_replace('41106', '04510', $this->getConfigData('postmethods')));`

**Comment by rafaelpatro** [comment]
Então Irineu, só avisando que essa solução é emergencial, e resolve o
problema momentaneamente. Mas poderá ter problemas com a validação, e com
pacotes maiores, que precisam ser divididos. Sugiro baixar o último release.

Em 7 de mai de 2017 8:53 AM, "Irineu Martins Junior" <
notifications@github.com> escreveu:

**Comment by reinaldomendes** [comment]
A solução é simples

Copie o arquivo **app/code/community/PedroTeixeira/Model/Source/PostMethods** para
**app/code/local/PedroTeixeira/Model/Source/PostMethods**  e substitua os códigos, como no exemplo abaixo.

Não se esqueça de utilizar as (") aspas, pois no PHP um número que começa com 0(zero) sem as aspas será tratado como notação octal.




```php
<?php
/**
 * Pedro Teixeira
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the New BSD License.
 * It is also available through the world-wide-web at this URL:
 * http://www.pteixeira.com.br/new-bsd-license/
 *
 * @category   PedroTeixeira
 * @package    PedroTeixeira_Correios
 * @copyright  Copyright (c) 2011 Pedro Teixeira (http://www.pteixeira.com.br)
 * @author     Pedro Teixeira <pedro@pteixeira.com.br>
 * @license    http://www.pteixeira.com.br/new-bsd-license/ New BSD License
 */

class PedroTeixeira_Correios_Model_Source_PostMethods
{

    public function toOptionArray()
    {
        return array(
            //array('value'=>40010, 'label'=>Mage::helper('adminhtml')->__('Sedex Sem Contrato (40010)')),
            array('value'=>'04014', 'label'=>Mage::helper('adminhtml')->__('Sedex Sem Contrato [alt 05/05/2017] (04014)')),
            
            
            array('value'=>40096, 'label'=>Mage::helper('adminhtml')->__('Sedex Com Contrato (40096)')),
            array('value'=>81019, 'label'=>Mage::helper('adminhtml')->__('E-Sedex Com Contrato (81019)')),
            //array('value'=>41106, 'label'=>Mage::helper('adminhtml')->__('PAC Sem Contrato (41106)')),
            array('value'=>'04510', 'label'=>Mage::helper('adminhtml')->__('PAC Sem Contrato [alt 05/05/2017](04510)')),
            
            array('value'=>41068, 'label'=>Mage::helper('adminhtml')->__('PAC Com Contrato (41068)')),
            array('value'=>40215, 'label'=>Mage::helper('adminhtml')->__('Sedex 10 (40215)')),
            array('value'=>40290, 'label'=>Mage::helper('adminhtml')->__('Sedex HOJE (40290)')),
            array('value'=>40045, 'label'=>Mage::helper('adminhtml')->__('Sedex a Cobrar (40045)')),
        );
    }

}

**Comment by vhesquisato** [comment]
Pessoal, eu tinha o módulo instalado via Magento Connect e tentando resolver desinstalei para jogar outra versão. Porém, instalei manualmente via FTP e me parece que as tabelas e registros na base que foram apagados quando desinstalei no magento connect não são criados novamente. Eu tenho acesso ao módulo no admin do magento mas na loja não é listado nem mesmo para dar o erro. Chequei a base e realmente parece que faltam tabelas e registros do módulo. Alguém consegue me ajudar? Obrigado!

**Comment by rafatriolo** [comment]
pra mim resolveu tbm, valeu @MrHerickS

**Comment by MrHerickS** [comment]
Vale lembrar que a solução que eu dei foi apenas emergencial! 
Atualmente **já foi lançada** uma correção oficial para este problema!

**Comment by rafatriolo** [comment]
e onde eu baixo essa correção oficial ? pq eu atualizei o modulo a semana passada.

**Comment by MrHerickS** [comment]
@rafatriolo só baixar o último release.

**Comment by wiranunes** [comment]
@MrHerickS Pior que pra mim ainda aparece a mensagem não há meio de envio disponível :(

**Comment by wiranunes** [comment]
@MrHerickS você pode me dar uma ajuda?

**Comment by wiranunes** [comment]
@rafaelpatro @MrHerickS CONSEGUIIIIIIIIIIIIIIIIIIIIIIIIIII 

OBRIGADÃAAAOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by pedrocaka** [comment]
socorro pessoal! eu fui no magento connect e desinstalei o módulo 4.7 e instalei o módulo 4.8 mas agora estou com um erro pior! 
Class 'PedroTeixeira_Correios_Block_Adminhtml_System_Config_Form_Button' not found
o que eu fiz de errado? me ajudem please!

**Comment by rafatriolo** [comment]
ja limpou o cache? Provavelmente vc instalei o modulo com a compilação habilitada, ve isso.

**Comment by pedrocaka** [comment]
o que vc fala em limpar o cache é atualizar todos aquels tipos de cache no admin se for eu acabei de fazer isso e não deu certo! inclusive habilitou e atualizou o banco de cotação dos correios! mas continua com o fatal erro: Class 'PedroTeixeira_Correios_Block_Adminhtml_System_Config_Form_Button' not found in (etc...) on line 28743

**Comment by rafatriolo** [comment]
vai nesse caminho aqui app/code/community/PedroTeixeira/Correios/Block/Adminhtml/System/Config/Form/Button.php e veja se a class que esta dando erro esta faltando!

**Comment by pedrocaka** [comment]
parece que tá certin: 
class PedroTeixeira_Correios_Block_Adminhtml_System_Config_Form_Button extends Mage_Adminhtml_Block_System_Config_Form_Field

**Comment by rafatriolo** [comment]
Entao provavelmente vc instalou esse modulo com a compilação ligada, no admin do magento, vai em sistema > ferramentas> compilação , se estiver habilitada, vc desabilita, ai limpa o cache que deve funcionar.

**Comment by pedrocaka** [comment]
pronto! está funcionando! mas o pac e o sedex sem contrato não estão atualizados e o  botão atualizar não funciona...mas tá aparecendo no frontend o prazo, mas n aparece qual o método se é pac ou sedex!

**Comment by pedrocaka** [comment]
Eu sou cagado só pode! redei e rodei e agora tô no mesmo erro de antes de iniciar tudo! 
não aparece forma de envio no checkout! agradeço a quem me ajudar! :)

**Comment by jamersonlima** [comment]
@MrHerickS Obrigado mano sua solução me quebrou um galho muito grande !

**Comment by pedrocaka** [comment]
Galera eu tava com esse problema (não há métodos de envio) ai fui no magento connect e desinstalei a versão 4.7 e instalei a versão 4.8 mas ainda continuo com esse erro! esqueci de fazer alguma coisa?

**Comment by wiranunes** [comment]
Pessoal bom dia!

O que eu fiz e funcionou pra mim

Se você instalou a versão 4.8
Alterei a versão do módulo para 4.7.0 na tabela do MySQL core_resource
Limpei a tabela correios_post_methods
Apaguei todos os arquivos do módulo via FTP
Baixei novamente o plugin e instalei via FTP a versão 4.8

Antes de fazer esse procedimento eu instalei a versão 4.7.0
Subi a versão 4.7.0 na página de releases
Depois fiz o upgrade e deu certo conforme as orientações do @rafaelpatro

**Comment by willian10** [comment]
Ola  @MrHerickS  meu Magento e 1.8.1.0. Não entendo quase nada. 
É a mesmo. E pessoal onde baixo essa versão 4.8?

**Comment by willian10** [comment]
Coloquei os codigos no local "# "app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php". Mas ainda aparece a mensagem  "Informe seu CEP para calcular o valor da entrega", e somente quando coloco o numero do meu contrato e coloco SEDEX E PAC (com contrato) que aparece o valor.

**Comment by pedrocaka** [comment]
Refiz os passos e deu tudo certo! obrigado pessoal! sucesso para todos vocês!

**Comment by willian10** [comment]
OLA.... PROBLEMA MAIS QUE RESOLVIDO.
BAIXEI A ULTIMA VERSÃO PEDRO TEIXEIRA 4.8.0
E SOMENTE DESABILITEI O COPILADOR.

**Comment by fredbrunken** [comment]
O Magento connect não reconhece a atualização de 4.7.2 para 4.8.0? Tenho que instalar manualmente? Não entendi o que aconteceu, mas agora, com esse módulo do magento, eu não recebo mais uma chave como antes e sim tenho que efetuar uma compra, fazer o download e instalar.

De qualquer maneira, tentei instalar, limpei o cache, desabilitei o compilador e mesmo assim não funcionou.

Vou investigar mais, mas agradeceria a ajuda.

**Comment by fredbrunken** [comment]
A extensão:

http://connect20.magentocommerce.com/community/PedroTeixeira_Correios

Só tem a versão 4.7.2. Não seria possível atualizar para a nova?

**Comment by mvsucupira** [comment]
Pessoal, utilizo modman e ao fazer a atualização tudo fucionou perfeito. Agora preciso fazer um ajuste sobre a forma como as opções são apresentadas. Gostaria que aparecesse da forma como estava antes, figura abaixo.

![captura de tela 2017-05-19 as 19 05 59](https://cloud.githubusercontent.com/assets/18449669/26268575/3e8b8736-3cc6-11e7-9fec-482f48fa66a2.png)

Depois da atualização é informado todos os dados do contrato, vejam abaixo:

![captura de tela 2017-05-19 as 19 06 51](https://cloud.githubusercontent.com/assets/18449669/26268593/5476d820-3cc6-11e7-836b-ef19887adcc0.png)

Como posso ajustar isso? Não preciso mostrar as informações de código ou sem tem contrato ou não, apenas a modalidade.

Obrigado pela ajuda.

**Comment by mvsucupira** [comment]
Pessoal, descobri a solução. Basta editar o arquivo de tradução. No meu caso, o arquivo não estava com o link simbólico para a pasta de traduções.

Sugiro incluir no arquivo modman o link para o arquivo de tradução.
