### ISSUE TITLE
Atualização de código do correio

### ISSUE THREAD

**Issue by esxbr** [pedro-teixeira/correios#228]
Correio atualizou os códigos
SEDEX (sem contrato) = 04014
PAC (sem contrato) = 04510

Tentei atualizar diretamente no XML e PHP fazendo um replace, porem comecou a travar o site.

**Comment by kinfoxxx** [comment]
Boa tarde, alterei na tabela para esses código porem da ''Dimensões dos produtos fora do permitido pelos Correios. ''

**Comment by rafaelpatro** [comment]
@esxbr, se vc atualizar o módulo, poderá configurar os novos códigos diretamente na tabela _correios_postmethods_. Não esqueça de atualizar o [arquivo de tradução](https://github.com/pedro-teixeira/correios/blob/master/app/locale/pt_BR/PedroTeixeira_Correios.csv), e adicionar as regras de validação no [arquivo de configuração](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L147).

@kinfoxxx, sugiro desativar a opção _Validar Dimensões dos Produtos_ nas configurações do módulo. Ou se preferir pode adicionar as tags de validação no [arquivo de configuração](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L147)
