### ISSUE TITLE
Modulo parou de funcionar

### ISSUE THREAD

**Issue by golifter** [pedro-teixeira/correios#231]
O modulo parou de funcionar no dia 05/05 quando os correios mudaram os códigos do SEDEX e do PAC.
Ocorrei com mais alguém?

**Comment by lmarquine** [comment]
@golifter Algumas lojas pararam sim, o @pedro-teixeira e o @rafaelpatro já fizeram as correções no Git. #229

**Comment by castroadrien** [comment]
Obrigado pela colaboração @pedro-teixeira e @rafaelpatro
