### ISSUE TITLE
Meus novos Códigos de Serviços não aparecem

### ISSUE THREAD

**Issue by rafaelpatro** [pedro-teixeira/correios#233]
Pessoal, vi que muitos, mesmo após atualizar o módulo, não conseguiram ver os novos códigos de serviços.

Só esclarecendo que os Correios ainda não atualizaram o webservice para todos os clientes. Para alguns já funciona, e para outros não funciona, continua retornando os mesmos códigos antigos.
Segundo contato com os Correios, fui informado que isso é a nível nacional, e que pode levar 2 ou 3 dias para atualizar tudo.

Uma boa semana.

**Comment by pedro-teixeira** [comment]
Muito obrigado pelo update @rafaelpatro
