### ISSUE TITLE
Conexão

### ISSUE THREAD

**Issue by marlosgleite** [pedro-teixeira/correios#234]
Boa tarde, efetuei o download, e não estava funcionando, então ativei os logs e me vem a seguinte mensagem:
2017-05-08T19:56:39+00:00 DEBUG (7): pedroteixeira_correios [349]: URL Error - Unable to Connect to tcp://ws.correios.com.br:80. Error #110: Connection timed out

Estou hospedando no knghost, isso pode ser alguma configuração dentro do painel ou algo com a instalação? 

Obrigado e excelente trabalho!!

**Comment by rafaelpatro** [comment]
D´uma lida [neste tópico](https://github.com/pedro-teixeira/correios/issues/218#issuecomment-297576373), seu problema pode ser o mesmo.

**Comment by marlosgleite** [comment]
Obrigado pelo retorno Rafael.
Eu olhei o tópico e verifiquei que o meu está para verificar antes os Correios, não creio que o site dos correios esteja fora do ar, sobre o log eu vi que você não achava preciso, tem como fazer algum outro procedimento de teste para verificação?

Obrigado!

**Comment by marlosgleite** [comment]
Após algumas tentativas minhas ele da o seguinte erro:
pedroteixeira_correios [cache]: mode=0 status=write key=40010x41106x40215x40290x40045_35_16_91788102

Quando se faz a verificação das formas de envio, ele mostra como se não tivesse, ele está habilitado de acordo e aparecendo no admin.

**Comment by rafaelpatro** [comment]
@marlosgleite o log acima não caracteriza um erro. Mas sim, que os Correios retornaram uma cotação com sucesso, e o módulo salvou na cache.

**Comment by marlosgleite** [comment]
Beleza, então saber me dizer porquê não aparecem como opção para o frete? pode ser algo com a versão do magento?

**Comment by rafaelpatro** [comment]
Se ao mostrar esse log, não exibiu cotação, tenta ver se aparece algo no log do PHP.

**Comment by marlosgleite** [comment]
Nada.. tudo 100%

**Comment by rafaelpatro** [comment]
Certeza que está com os arquivos do último release?

**Comment by rafaelpatro** [comment]
Apresentar o log com sucesso, e não exibir o frete, nunca vi isso acontecer.
Cara, não faço ideia do que seja seu problema.
Você tem algum tipo de cache no frontend?

**Comment by marlosgleite** [comment]
Seguinte.. a cagada bem feita kkkk eu havia baixado do magento connect e sobre escrevi com os arquivos do github e deu crash, vou refazer a instalação da loja e pegar os arquivos direto aqui do gitrub, e volto a lhe comunicar, mas como deu crash, creio que os arquivos não estavam corretos mesmo.

**Comment by marlosgleite** [comment]
Refiz a loja e coloquei os arquivos do hub, e deu o mesmo erro


There has been an error processing your request

Exception printing is disabled by default for security reasons.

Error log record number: 723235334730

**Comment by marlosgleite** [comment]
esse erro de dá quando tento acessar o tipo de frete.

**Comment by rafaelpatro** [comment]
Posta aqui o conteúdo do arquivo _www/var/report/723235334730_

**Comment by marlosgleite** [comment]
Refiz novamente a loja e agora consegui colocar o plugin de vocês, mas continua como antes, sem aparecer as opções de frete e sem erros.

**Comment by marlosgleite** [comment]
Rafael, desculpa pelo seu tempo, agora consegui fazer funcionar... mas basicamente ele não se deu bem com outros plugins que eu havia colocado, ou talvez o modo como eu coloquei.

Obrigado pelo excelente trabalho!

**Comment by rafaelpatro** [comment]
👍 Agradeço se puder postar o nome desses plugins.
Certo que irá ajudar outros com o mesmo problema.

**Comment by marlosgleite** [comment]
Frete Fácil - discounted shipping SEDEX 
PagSeguro Transparente
theme jewelry do pagayo
