### ISSUE TITLE
Página em branco em Formas de Entrega após instalar versão 4.8

### ISSUE THREAD

**Issue by elsondinardo** [pedro-teixeira/correios#235]
Olá, após instalar a versão 4.8 está dando página em branco na aba Formas de Entrega.
![capturar](https://cloud.githubusercontent.com/assets/7572660/25836076/4c5a718e-345a-11e7-9f62-defd380ed9a0.PNG)
O que pode ser? Já limpei cachê, loguei e desloguei, atualizei indices, ativei e desativei o compilador e nada. Pior que não consigo nem mexer nos outros módulos de entrega pois tá página em branco pra todos eles com esse link:

https://www.minhaloja.com/index.php/redrum/system_config/edit/section/carriers/key/525f43d826fe9f06fad5592c25a46c89/

**Comment by rafaelpatro** [comment]
Você instalou o módulo pela primeira vez nessa loja? Ou já tinha o módulo antes?

Possivelmente a tabela _correios_postmethods_ não foi inserida na instalação. Mas seria melhor se pudesse enviar o log do PHP.

**Comment by elsondinardo** [comment]
Eu só usava ele. Aí parou de funcionar esses dias (to ligado que mudou os códigos) então resolvi desinstalar a versão anterior pelo connect e instalar a nova também pelo connect. Instalei pelo link;

http://connect20.magentocommerce.com/86842dae25fc03c2cef5b6e62f03adef/pedroteixeira+PedroTeixeira_Correios-4.8.0

Como faço pra gerar esse log aí? Meu log estava desligado no admin mas eu acabei de ligar.

**Comment by rafaelpatro** [comment]
O log do PHP depende da sua configuração no PHP (não no Magento).
Normalmente fica em /va/log/php_errors.log
Mas pode estar em outro local. Para descobrir o local do arquivo, tenta esse comando: `php --info | grep error`

**Comment by elsondinardo** [comment]
:5:{i:0;s:101:"Modelo base "pedroteixeira_correios/source_postMethods" não encontrado para o atributo "postmethods"";i:1;s:3226:"#0 /home/vuduloja/public_html/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(387): Mage::exception('Mage_Eav', 'Modelo base "pe...')
#1 /home/vuduloja/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(203): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()
#2 /home/vuduloja/public_html/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tab/Attributes.php(70): Mage_Adminhtml_Block_Widget_Form->_setFieldset(Array, Object(Varien_Data_Form_Element_Fieldset), Array)
#3 /home/vuduloja/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(144): Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Attributes->_prepareForm()
#4 /home/vuduloja/public_html/app/code/core/Mage/Core/Block/Abstract.php(922): Mage_Adminhtml_Block_Widget_Form->_beforeToHtml()
#5 /home/vuduloja/public_html/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tabs.php(79): Mage_Core_Block_Abstract->toHtml()
#6 /home/vuduloja/public_html/app/code/core/Mage/Core/Block/Abstract.php(297): Mage_Adminhtml_Block_Catalog_Product_Edit_Tabs->_prepareLayout()
#7 /home/vuduloja/public_html/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#8 /home/vuduloja/public_html/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'product_tabs')
#9 /home/vuduloja/public_html/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/catal...', 'product_tabs')

**Comment by rafaelpatro** [comment]
Então, o arquivo source dos serviços de postagem não foi encontrado. Ou vc
não instalou todos os arquivos do último release, ou faltou atualizar o
cache e recompilar. Dá uma conferida nisso

Em 9 de mai de 2017 10:25 AM, "elsondinardo" <notifications@github.com>
escreveu:

**Comment by elsondinardo** [comment]
Sincerelly... I dont know what i have to do :(
Im lost with this issue

**Comment by elsondinardo** [comment]
Sinceramente eu não sei o que fazer pois fiz tudo isso, atualizei cache, recompilei, desativei e ativei compilador, e pra piorar eu não consigo nem entrar nos meus produtos pelo backend pois da pagina em branco também. E eu nem manjo muito dessas paradas. Eu subi novamente os arquivos do modulo e agora mudou o log:

a:5:{i:0;s:192:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'vuduloja_mage.mg_correios_postmethods' doesn't exist, query was: SELECT main_table.* FROM mg_correios_postmethods AS main_table";i:1;s:3171:"#0 /home/vuduloja/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/vuduloja/public_html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/vuduloja/public_html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/vuduloja/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT main_ta...', Array)
#4 /home/vuduloja/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECTmain_ta...', Array)
#5 /home/vuduloja/public_html/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT main_ta...', Array)
#6 /home/vuduloja/public_html/lib/Varien/Data/Collection/Db.php(740): Zend_Db_Adapter_Abstract->fetchAll('SELECTmain_ta...', Array)
#7 /home/vuduloja/public_html/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)

**Comment by rafaelpatro** [comment]
Elson, pelo erro, sua instalação falhou, e não criou a tabela do módulo.
Verifique se existem os campos volume_altura, ...largura, etc. Se já
existem, altera o número da versão para 4.7.0 em core_resource.

Em 9 de mai de 2017 11:51 AM, "elsondinardo" <notifications@github.com>
escreveu:

**Comment by pedro-teixeira** [comment]
A nova versão, v4.8.1, deve ter corrigido esse problema.
