### ISSUE TITLE
Erro Página no ADMIN - Forma de Entrega

### ISSUE THREAD

**Issue by Andrefcp** [pedro-teixeira/correios#237]
Olá, Acabei de atualizar os arquivos da versão 4.8.0 (baixada pela loja Magento) e deu o seguinte erro ao acessar a "Forma de Entrega" dentro do ADMIN.
O que pode ser?

a:5:{i:0;s:187:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'turminha_mage1.correios_postmethods' doesn't exist, query was: SELECT main_table.* FROM correios_postmethods AS main_table";i:1;s:3607:"#0 /chroot/home/turminha/turminhakids.com.br/html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /chroot/home/turminha/turminhakids.com.br/html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /chroot/home/turminha/turminhakids.com.br/html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT main_ta...', Array) #4 /chroot/home/turminha/turminhakids.com.br/html/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECTmain_ta...', Array)
#5 /chroot/home/turminha/turminhakids.com.br/html/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT main_ta...', Array) #6 /chroot/home/turminha/turminhakids.com.br/html/lib/Varien/Data/Collection/Db.php(740): Zend_Db_Adapter_Abstract->fetchAll('SELECTmain_ta...', Array)
#7 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 /chroot/home/turminha/turminhakids.com.br/html/lib/Varien/Data/Collection/Db.php(572): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 /chroot/home/turminha/turminhakids.com.br/html/lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#10 /chroot/home/turminha/turminhakids.com.br/html/app/code/community/PedroTeixeira/Correios/Model/Source/PostMethods.php(26): Varien_Data_Collection->getIterator()
#11 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(463): PedroTeixeira_Correios_Model_Source_PostMethods->toOptionArray(true)
#12 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#13 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#14 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#15 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#16 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#17 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#18 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /chroot/home/turminha/turminhakids.com.br/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#20 /chroot/home/turminha/turminhakids.com.br/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#21 /chroot/home/turminha/turminhakids.com.br/html/index.php(83): Mage::run('', 'store')
#22 {main}";s:3:"url";s:99:"/index.php/turminha_admin/system_config/edit/section/carriers/key/db468938f0d85c7431e275ebc0ef0031/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by rafaelpatro** [comment]
@Andrefcp, a atualização não foi bem sucedida, provavelmente por que sua versão era diferente de 4.7.0.
O número da versão deve ser baixado para 4.7.0 na tabela _core_resource_.

**Comment by Andrefcp** [comment]
Olá Rafael, Grato pela resposta.
É um site novo. Eu tinha baixado há um mês atrás a versão anterior. E agora, o que devo fazer?  Instalar novamente a versão 4.7.0 ? Mas essa versão já contempla os novos serviços dos Correios?
Grato

**Comment by marcospaf** [comment]
@rafaelpatro beleza? rafael estou para fazer a instalação´. Acabei de ligar para o consultor ele disse que agora só vale os códigos novos, apesar de estar calculando com os antigos. A pergunta é estou com a versão 4.7.2 instalada, posso instalar por cima dela no ftp ou tenho que desinstalar tudo e instalar a 4.8.0.

No meu contrato está pegando tanto os códigos novos como os antigos já verifiquei.
Estou só nesta duvida de instalação, já que não tem como fazer o upgrade direto pelo Magento Connect.

**Comment by Andrefcp** [comment]
Olá rafael
Estou enviando por aqui pois é mais fácil de exmplicar;
Na página https://github.com/pedro-teixeira/correios/releases/tag/v4.8.0
tem 2 downloads

- Souce code (zip)
- Source code (tar.gz)

Eu instalei o primeiro. Agora eu abri o segundo e observei que tem  
alguns arquivos que o primeiro não tem. Exemplo:
- .gitignore
- .travis.yml
- CHANGELOG.md
- composer
- LICENSE
- modman
- outros

É correto ter instalado o primeiro ou eu deveria ter instalado esse  
segundo com esses arquivos?
Ou não faz diferença

Abços
André

Citando Rafael Patro <notifications@github.com>:

**Comment by rafaelpatro** [comment]
Não faz diferença.

Em 9 de mai de 2017 11:55 AM, "Andrefcp" <notifications@github.com>
escreveu:


Olá rafael
Estou enviando por aqui pois é mais fácil de exmplicar;
Na página https://github.com/pedro-teixeira/correios/releases/tag/v4.8.0
tem 2 downloads

- Souce code (zip)
- Source code (tar.gz)

Eu instalei o primeiro. Agora eu abri o segundo e observei que tem
alguns arquivos que o primeiro não tem. Exemplo:
- .gitignore
- .travis.yml
- CHANGELOG.md
- composer
- LICENSE
- modman
- outros

É correto ter instalado o primeiro ou eu deveria ter instalado esse
segundo com esses arquivos?
Ou não faz diferença

Abços
André

Citando Rafael Patro <notifications@github.com>:

> @Andrefcp, a atualização não foi bem sucedida, provavelmente por que
> sua versão era diferente de 4.7.0.
> O número da versão deve ser baixado para 4.7.0 na tabela _core_resource_.
>
> --

> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/pedro-teixeira/correios/issues/237#
issuecomment-300185477


—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pedro-teixeira/correios/issues/237#issuecomment-300191183>,
or mute the thread

**Comment by Andrefcp** [comment]
Ok.
E como eu devo proceder ?

Eu tenho que instalar essa versão 4.7 ?
Essa versão contém os produtos novos dos Correios?

Grato,
andré

**Comment by rafaelpatro** [comment]
@Andrefcp, se vc está com a versão 4.7.2, acesse o banco de dados, e altere o número da versão para 4.7.0 na tabela _core_resource_. Não acesse a loja, nem backend. Instale os arquivos do último release 4.8.0. E deve funcionar.

**Comment by Andrefcp** [comment]
Olá. Como eu já tinha instalado a versão nova. Ao acessar o BD, já consta a versão 4.8.0:
Sege cópia da linha do BD
 Edita -  Copiar - pedroteixeira_correios_setup - 4.8.0

Mesmo assim eu devo alterar para 4.7.0 e fazer a instalação novamente?

**Comment by rafaelpatro** [comment]
Exatamente!
