### ISSUE TITLE
Atualização do Sistema de Rastreamento de Objetos - SRO

### ISSUE THREAD

**Issue by willgoulding** [pedro-teixeira/correios#238]
Boa tarde a todos,

A duas semanas o meu rastreamento dentro da ordem no magento parou de funcionar. Quando clico em Acompanhar entrega sou direcionado para o seguinte link http://www.correios.com.br/para-voce/avisos/atualizacao-do-sistema-de-rastreamento-de-objetos-sro/

Como posso corrigir isso?

**Comment by rafaelpatro** [comment]
Qual a versão do módulo que está usando?

**Comment by willgoulding** [comment]
@rafaelpatro a ultima versão 8.0

**Comment by wdarking** [comment]
Eu não sei se o @rafaelpatro ou o @pedro-teixeira lançaram no ultimo release, mas se você precisa com urgência você pode copiar o arquivo `<theme>/shipping/tracking/popup.phtml` para o `custom` do seu tema e adicionar 
`<form method="POST" action="http://www2.correios.com.br/sistemas/rastreamento/resultado_semcontent.cfm">
                            <input readonly type="text" name="Objetos" value="<?php echo $this->escapeHtml($track->getTracking()); ?>">
                            <button type="submit">Rastrear</button>
                        </form>`

dentro do loop `foreach($_result as $track): ?>`

**Comment by rafaelpatro** [comment]
@willgoulding, a última versão é 4.8.0.

Esse link de tracking não existe mais. O rastreamento agora é feito via _soap_. Provavelmente seus arquivos estão desatualizados. Dá uma conferida nisso.

**Comment by willgoulding** [comment]
@rafaelpatro acabei de abaixar a ultima versão aqui novamente e subi para o servidor, continuou do mesmo jeito. você sabe qual aquivo devo verificar?

**Comment by rafaelpatro** [comment]
https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php#L589

**Comment by willgoulding** [comment]
@rafaelpatro 

O arquivos esta correto no servidor, o rastreamento automático e o aviso ao cliente estão corretos. O que estou tendo problema é no link da imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/12437790/25868717/bbbb897a-34cb-11e7-94d5-e9dd1099b059.png)

**Comment by rafaelpatro** [comment]
Não estou certo se estes links são gerados por esta extensão. Vc tem algum
outro módulo que possa estar por trás disso?

Em 9 de mai de 2017 4:25 PM, "willgoulding" <notifications@github.com>
escreveu:

**Comment by willgoulding** [comment]
@rafaelpatro Você tem toda razão, era outro modulo que estava gerando esse link, obrigado pela ajuda de qualquer forma.
