### ISSUE TITLE
tracking SRO não atualiza.

### ISSUE THREAD

**Issue by kinfoxxx** [pedro-teixeira/correios#240]
Boa noite, nosso servidor foi atualizado para a versão php 5.6 e depois disso não atualiza mais o tracking, da o erro abaixo no AOE SCHEDULER , não sei se tem haver com a atualização do PHP ou é coincidência, podem me ajudar? 

Erro abaixo:  

Status: 	
died
Created at: 	00:35:02
Scheduled at: 	00:40:00
Executed at: 	00:40:02
Finished at: 	00:40:02
Last seen at: 	00:40:02
Id: 	2180991
Pid: 	18120
Servidor: 	unix1.sagainternet.com.br
Mensagem:

TRIGGER: shutdown function
Last error: 
Array
(
    [type] => 1
    [message] => Class 'SoapClient' not found
    [file] => /var/www/clients/client4/web5/web/app/code/community/PedroTeixeira/Correios/Model/Sro.php
    [line] => 74
)

Backlog: 
exception 'Exception' in /var/www/clients/client4/web5/web/app/code/community/Aoe/Scheduler/Helper/GracefulDead.php:53
Stack trace:
#0 [internal function]: Aoe_Scheduler_Helper_GracefulDead::beforeDyingShutdown()
#1 {main}

**Comment by rafaelpatro** [comment]
Tenta instalar o Soap. Deve ter sido desinstalado na atualização.
`apt-get install php-soap`

**Comment by kinfoxxx** [comment]
Top, obrigado deu certo, soap que não estava ativo!
