### ISSUE TITLE
Após a atualização, o módulo parou de funcionar.

### ISSUE THREAD

**Issue by leandrotrick** [pedro-teixeira/correios#243]
Olá,

Atualizei o módulo do Pedro Teixeira em minha loja virtual através do Magento Connect e ele parou de funcionar.

A versão que estou é a 4.7.2 (stable)

Já limpei o cache do site todo e reinstalei umas 3x, mas ainda continua funcionando.

Não existe nenhuma mensagem de erro, o módulo simplesmente não funciona quando o cliente vai para o checkout.

minha loja: [www.middascachaca.com.br/loja](url)

Alguém poderia me ajudar?

**Comment by rafaelpatro** [comment]
@leandrotrick, sugiro reinstalar todos os arquivos do último release.
Em seguida acesse a tabela _core_resource_, e atualize o número da versão para 4.7.0.

**Comment by pedro-teixeira** [comment]
A nova versão, v4.8.1, deve ter corrigido esse problema.
