### ISSUE TITLE
Para produtos configuráveis, o plugin considera as dimensões do super produto, e não dos produtos específicos.

### ISSUE THREAD

**Issue by rlonghi** [pedro-teixeira/correios#244]
Bom dia pessoal!

Espero que possam me ajudar com esta questão.
Tenho uma loja que usa somente produtos configuráveis e estamos testando este plugin de Correios para o sistema. Após alguns testes, verificamos que os valores do frete não estavam de acordo com o cálculo dos correios.

Depois de quebrar a cabeça com configuração e etc, parti para o código e resolvi depurar alguns valores utilizados. Cheguei a conclusão que o plugin trabalha com os valores de dimensão do super produto e não dos sub produtos em um configurável.

Vou tentar detalhar melhor usando algumas imagens.

As imagens abaixos mostram a configuração do **super produto** e do **produto detalhado** respectivamente.
![super_product](https://cloud.githubusercontent.com/assets/6110227/25905242/d70b4cae-3577-11e7-825c-a8f86d6b3bce.png)

![sub_product](https://cloud.githubusercontent.com/assets/6110227/25905252/dd4f0be6-3577-11e7-9b27-f2abb3f4c8f6.png)

Abaixo uma imagem do carrinho com os produtos selecionados:
![cart](https://cloud.githubusercontent.com/assets/6110227/25905305/105fae5a-3578-11e7-9162-392603536e84.png)

Alterações no código realizadas para depuração:
![code](https://cloud.githubusercontent.com/assets/6110227/25905319/1b8547ae-3578-11e7-962e-f558a5984e38.png)

Resultado da depuração:
![debug](https://cloud.githubusercontent.com/assets/6110227/25905335/26585248-3578-11e7-8de6-8e0d4cb68c7b.png)

Podemos verificar na depuração que o plugin utilizou os valores padrão da configuração ao invés dos valores do sub produto, justamente porque os valores de dimensão são vazios no super produto.

Me desculpem a bagunça da issue, mas espero que possam me dar uma ajuda.

Muito obrigado!

**Comment by rafaelpatro** [comment]
@rlonghi, realmente a extensão pega sempre o produto pai, com exceção do _Pacote de Produtos_ (nesse caso pega todos os produtos filhos). Para carregar os produtos simples dos produtos configuráveis terá que fazer uma função em separado. Ex.:

```php
    protected function _loadConfigurableUsed($items)
    {
        $visibleAndConfigChildren = array();
        foreach ($items as $item) {
            $product = $item->getProduct();
            $isConfigurable = ($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE);
            if ($isConfigurable) {
                $usedCollection = $product->getTypeInstance()->getUsedProducts(null, $product);
                foreach ($usedCollection as $usedItem) {
                    $visibleAndConfigChildren[] = $usedItem;
                }
            } else {
                $visibleAndConfigChildren[] = $item;
            }
        }
        return $visibleAndConfigChildren;
    }
```

Infelizmente o exemplo ainda não funciona direito, os atributos não estão sendo carregados. Mas acho que esse é o caminho. Se encontrar uma solução por favor compartilhe.

**Comment by rafaelpatro** [comment]
@rlonghi, se ainda tiver interesse, segue a solução que desenvolvi para capturar os atributos do Produto Simples, em um Produto Configurável.

Adicionar o método abaixo na classe _PedroTeixeira_Correios_Model_Carrier_CorreiosMethod_
```php
    protected function _getProductAttribute($product, $attribute)
    {
        $type = $product->getTypeInstance(true);
        if ($type->getProduct($product)->hasCustomOptions() &&
            ($simpleProductOption = $type->getProduct($product)->getCustomOption('simple_product'))
        ) {
            $simpleProduct = $simpleProductOption->getProduct($product);
            if ($simpleProduct) {
                return $this->_getProductAttribute($simpleProduct, $attribute);
            }
        }
        return $type->getProduct($product)->getData($attribute);
    }
```

Substituir cada comando `$product->getData('nome_do_atributo')` por...
```php
$this->_getProductAttribute($product, 'nome_do_atributo');
```
