### ISSUE TITLE
Não instala tabela "correios_postmethods "

### ISSUE THREAD

**Issue by vhesquisato** [pedro-teixeira/correios#247]
Olá Pessoal, estou com versão 4.7.2 instalado e funcionando com uma mudança paliativa que sugeriram em outra issue depois das mudanças de códigos dos correios. Mas como já foi lançada a versão 4.8 fui tentar atualizar para não ficar com a gambiarra, porém quando instalo, (fiz via FTP) ao acessar as formas de entrega no admin o sistema acusa a falta da tabela "correios_postmethods". A dúvida é: as versões anteriores não utilizavam essa tabela? O que fazer para incluir essa tabela e fazer funcionar a versão 4.8?

**Comment by rafaelpatro** [comment]
O número da versão deve ser baixado manualmente para 4.7.0 na tabela _core_resource_

**Comment by vhesquisato** [comment]
@rafaelpatro não sei é por ter uma versão ainda mais antiga antes da 4.7.2 a minha tabela "core_resource" não tem nenhum registro relacionado ao módulo, será que se eu incluir a linha manualmente funciona? Obrigado!

**Comment by rafaelpatro** [comment]
@vhesquisato, não sei dizer. Nunca vi isso acontecer. Certeza que está olhando o banco certo? A tabela correta? O código do módulo é _pedroteixeira_correios_

**Comment by vhesquisato** [comment]
Verdade @rafaelpatro eu comi bola aqui, não vi que a tabela tinha mais registros. Agora funcionou, versão 4.8 instalada. Muito obrigado pela ajuda e paciência cara!

**Comment by pedro-teixeira** [comment]
A nova versão, v4.8.1, deve ter corrigido isso.
