### ISSUE TITLE
Nem consigo instalar versão 4.8

### ISSUE THREAD

**Issue by MasterLins** [pedro-teixeira/correios#250]
Já tentei baixar o plugin dos correios no Magento Connect e não funciona, atualizei para 4.7.2.

Baixei do GitHub e tentei instalar manualmente tanto o zip quanto o tar.gz deram erro. Aqui está a mensagem do zip (o tar.gz deu outra mensagem e falhou também):

CONNECT ERROR: Package file is invalid
Invalid package name, allowed: [a-zA-Z0-9_-] chars
Invalid version, should be like: x.x.x
Invalid stability
Invalid date, should be YYYY-DD-MM
Invalid channel URL
Empty authors section
Empty package contents section

Também já tentei baixar do Magento Marketplace mas o carrinho não deixa completar a transação com erro "Please specify payment method.", mas logo abaixo diz "No payment information required", e o campo para escolher payment method nem aparece. Site cheio de bugs aquele.

Alguém pode me dar uma direção? Há dias o site não consegue vender nada!

**Comment by MasterLins** [comment]
Segui a instrução novamente para instalar o tarball. Está tudo lá, mas o site não funciona, porém vou deixar esse aberto porque o problema no Magento Connect e no Magento Marketplace ainda estão acontecendo e talvez alguma resposta ajude alguém, porque instalar o tarball é coisa avançada.

**Comment by felipecatunda** [comment]
Olá MasterLins, conseguiria me ajudar em resolver? A minha versão é 4.3.0, gostaria de atualizar para 4.8.

**Comment by MasterLins** [comment]
@felipecatunda, segui as instruções no corpo da página https://github.com/pedro-teixeira/correios, onde diz Instalando Manualmente.

O problema é que a instrução está imprecisa quando diz "O tarball deve ser descompactado no public_html de sua loja" porque, se você colocar o arquivo .tar.gz no diretório public_html e descopactá-lo lá, os arquivos vão acabar nos diretórios errados, já que a estrutura interna do tarball é diferente da do public_html.

A melhor solução é descompactar o .tar.gz ou o .zip no seu computador e usar uma ferrameta de FTP para copiar os arquivos para as pastas certas no sevidor, buscando pelas pastas do mesmo nome.

Claro, fazendo um backup do que está no servidor antes, para poder voltar em caso de zebra.

**Comment by felipecatunda** [comment]
@MasterLins Obrigado pelo seu tempo. Eu fiz isso, todo o procedimento, porém quando entro no carrinho o site fica fora do ar. Um abraço!

**Comment by pedro-teixeira** [comment]
Acabei de fazer um release de uma nova versão que deve ter corrigido esse problem.

**Comment by bestdefense** [comment]
Olá estou com o mesmo problema. estou na versão 4.7.2 e baixei a ultima versão 4.9.0 hoje. eu desinstalei a versão 4.7.2 e quando fui subir a  pedroteixeira-PedroTeixeira_Correios-4.9.0. deu erro e o site ficou branco. dai eu reinstalei a 4.7.2 e o site voltou... normalmente.. mas preciso instalar a 7.9.0 por conta dos novos serviços... alguém pode me ajudar?
