### ISSUE TITLE
Versão 4.8.0 simplesmente não funciona

### ISSUE THREAD

**Issue by MasterLins** [pedro-teixeira/correios#251]
Site: www.oson.com.br

Escolha um produto vá para o checkout e clique em calcular frete. Antes da atualização e de os Correios mudarem os códigos, as opções de frete apareciam (Sedex, PAC, etc.). Agora não aparece nada. A tela pisca, e nada.

Nada nos logs:
[oson@web ~]$ less /var/log/system.log
/var/log/system.log: No such file or directory
[oson@web ~]$ less /var/log/exception.log
/var/log/exception.log: No such file or directory

Pelo amor de Deus, alguém tem alguma dica, ideia, pode ajudar? A loja está parada há dias.

Obrigado.

**Comment by rafaelpatro** [comment]
@MasterLins, creio que seu problema seja o mesmo de muitos aqui.
Acesse a tabela _core_resource_, e atualize o número da versão para 4.7.0.

**Comment by MasterLins** [comment]
Obrigado por tentar ajudar, @rafaelpatro. Fiz a alteração mas não adiantou nada.

![image](https://cloud.githubusercontent.com/assets/9764703/25976879/10b26778-368e-11e7-9f67-b2a2323c6554.png)

Pior, derrubou meu site:

![image](https://cloud.githubusercontent.com/assets/9764703/25977089/5d3edd00-368f-11e7-8269-11025e50fbc7.png)

**Comment by pedro-teixeira** [comment]
@rafaelpatro acho que tem algo de errado na migração, não?

**Comment by MasterLins** [comment]
Voltei a versão para 4.8.0 na tabela e o site voltou ao ar.
Como assim migração?

**Comment by rafaelpatro** [comment]
@MasterLins, pode ver no log do PHP se há algum erro ou alerta?

**Comment by MasterLins** [comment]
Posso, onde normalmente ficam o log do PHP e os alertas?

**Comment by MasterLins** [comment]
Achei, nas últimas horas só tem esse:

**Comment by rafaelpatro** [comment]
@MasterLins, ou os arquivos não foram todos copiados, ou vc não recompilou seu Magento, após instalar os arquivos. Verifique isso.

@pedro-teixeira, realmente faltou criar os mysql-updates para os releases 4.7.2 e 4.7.3.
Como esses releases não estão indexados no projeto, acabei não fazendo. Ficou só o update da 4.7.0.

**Comment by MasterLins** [comment]
Realmente não compilei o Magento, não vi esse passo nas instruções. Deixa eu ver como fazer isso aqui e retorno com um status pra vocês. Obrigado pela ajuda até agora.

**Comment by MasterLins** [comment]
Sistema recompilado, cache limpo, página recarregada, coloquei um produto no carrinho e cálculo do frete continua não funcionando.
Vou rever a cópia dos arquivos agora.

**Comment by rafaelpatro** [comment]
Verifica se os serviços estão selecionados nas configurações do módulo.
Se estiver usando os _Serviços por Produto_, certifique que os produtos tenham os serviços configurados.

**Comment by rafaelpatro** [comment]
Cara, esse negócio da compilação, é obrigatório na instalação de qualquer módulo (ou um arquivo que seja) no Magento:

1. Desligue o compilador
2. Instale os arquivos
3. Compile tudo
4. Limpe todas as Caches

Se não fizer isso sempre, corre o risco de derrubar o site.

**Comment by MasterLins** [comment]
Obrigado @rafaelpatro, sou novato em Magento apesar de experiente em outras coisas. Peguei esse site de outra pessoa que abandonou e é a primeira vez que atualizo, e foi emergência por causa da troca de códigos dos correios.

Os serviços estão selecionados e Serviços por Produto diz Não.
![image](https://cloud.githubusercontent.com/assets/9764703/25977660/5d1823c8-3693-11e7-943f-2266040b3d23.png)

**Comment by MasterLins** [comment]
Como posso debugar o processo, ver se os Correios estão retornando algum código de erro?

**Comment by MasterLins** [comment]
Os arquivos parece que estão todos copiados, todos têm a data de hoje.

**Comment by rafaelpatro** [comment]
Os códigos de serviço que vc selecionou são todos inválidos desde 05/05/2017.
Use os códigos 04510 e 04014

**Comment by MasterLins** [comment]
Haha isso era o que estava lá. Agora apareceu alguma coisa:

![image](https://cloud.githubusercontent.com/assets/9764703/25978116/aec56624-3696-11e7-9fa9-b787d2333cd6.png)

**Comment by MasterLins** [comment]
Obrigado @rafaelpatro e @pedro-teixeira pela incansáve ajuda. Acho que o problema está resolvido.
Acabei voltando para versão 4.7.0 no banco de dados também, recompilei, reindexei, limpei cache.

**Comment by MasterLins** [comment]
Só estou achando muito estranho o PAC estar com o mesmo preço do SEDEX.
Fiz uma simulação no site dos correios, o valor do PAC tá certo, mas o SEDEX obviamente é mais caro.

![image](https://cloud.githubusercontent.com/assets/9764703/25978423/5778dd54-3698-11e7-9cd6-3ec9356d97e5.png)

![image](https://cloud.githubusercontent.com/assets/9764703/25978436/69c3d298-3698-11e7-9d21-c906bd93bc80.png)

**Comment by rafaelpatro** [comment]
Testa os valores [neste link](http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=CalcPrecoPrazo) que é mais confiável.

**Comment by rafaelpatro** [comment]
![image](https://cloud.githubusercontent.com/assets/13813964/25978662/04c69932-369a-11e7-962d-335714eae48a.png)

**Comment by pedro-teixeira** [comment]
@rafaelpatro se tiver um tempo pode fazer uma pull request com as migrações que faltaram? Pode fazer um bump para a versão `4.8.1`.

**Comment by ratocuiara** [comment]
SEDEX e PAC estão dando o mesmo valor. Vejam
![preco](https://cloud.githubusercontent.com/assets/5223825/25981031/1af312a8-36a9-11e7-9e43-fd56bdaab722.jpg)

**Comment by kinsmaster** [comment]
Fala pessoal, estava com o mesmo problema em minha loja [www.sexuale.com.br](https://sexuale.com.br/)

Não conseguia fazer funcionar de nenhuma forma mesmo seguindo todas dicas. Abaixo segue os procedimentos que realizei antes de funcionar....espero que ajude!!

.

**1º Cenário dos procedimentos que fiz:**  (Módulo Não Funcionou)
- Versão do módulo 4.7.0, segui o passo a passo como @rafaelpatro sugere aqui [#227](https://github.com/pedro-teixeira/correios/issues/227#issuecomment-299593019) 
- O compilador estava ativado, então, desativei, instalei, recompilei e limpei os caches
- Selecionei os novos códigos de PAC e SEDEX sem contrato nas configurações do módulo

.

**2º Cenário:**  (Módulo Não Funcionou)
- Versão do módulo 4.8.0, segui o passo a passo sugerido para correção no banco aqui [#227](https://github.com/pedro-teixeira/correios/issues/227#issuecomment-299593019) 
- O compilador estava ativado, então, desativei, instalei, recompilei e limpei os caches

.

**3º Cenário:**  (Módulo Não Funcionou)
- Versão do módulo 4.8.0, segui o passo a passo sugerido para correção no banco aqui [#227](https://github.com/pedro-teixeira/correios/issues/227#issuecomment-299593019) 
- Compilador desativado, instalei e limpei os caches

.

**4º Cenário:**  (EUREKA!! Módulo Funcionou!!!!  =)
Segue ordem do que fiz exatamente...

**OBS:** Durante os procedimentos não acessei **Front End** nem **Back End**

1. Removi todos os arquivos do módulo via FTP
2. Limpei a tabela _correios_postmethods_
3. Alterei a versão do release de 4.8.0 para 4.7.0 na tabela _core_resource_
4. Desativei o compilador, Limpei os caches, Recompilei e atualizei os caches novamente.
5. Acessei Front e Back End, então Desativei o compilador (outra vez)
6. Instalei a versão 4.8.0 (subi os arquivos)
7. Recompilei, Reindexei e Limpei os Caches
8. Configurei novamente as Opções de entrega do Módulo, selecionando os novos códigos SEDEX e PAC

![novos-codigos](https://cloud.githubusercontent.com/assets/28638118/25981063/5114ebfe-36a9-11e7-8115-852f1b28a4e6.JPG)

9. Deixei as opções abaixo da seguinte forma:
![opcoes](https://cloud.githubusercontent.com/assets/28638118/25981089/7492f490-36a9-11e7-9c80-3fc45330a05e.JPG)

10. Salvei as configurações e DEU CERTO!!!

Sei que repeti ações que talvez nem fossem necessárias, porém como já havia tentado diversas vezes sem ter sucesso, fui mais que redundante no procedimento e funcionou para mim.

Espero que ajude outras pessoas!

E aproveito para deixar aqui meu muito obrigado ao @rafaelpatro e @pedro-teixeira por todo suporte! 

Grande abraço e Sucesso para nós!

**Comment by ratocuiara** [comment]
@kinsmaster  pode informar se o PAC e o SEDEX esta calculando corretamente. O meu está dando o mesmo valor para os dois.

**Comment by ratocuiara** [comment]
Resolvido o problema de valores iguais para cálculos de PAC e SEDEX.
 
editar o config.xml em:
app/code/community/PedroTeixeira/Correios/etc/config.xml

</serv_045104510> para </serv_04510>

Obrigado @pedro-teixeira  e a todos colaboradores.

**Comment by kinsmaster** [comment]
@ratocuiara aqui os valores estão calculando correto, e obrigado pela dica...vou ficar observando se não ocorre esse problema por aqui..

valeu!

**Comment by MasterLins** [comment]
O meu continua calculando o mesmo preço para PAC e SEDEX.

Editar o config.xml em app/code/community/PedroTeixeira/Correios/etc/config.xml
</serv_045104510> para </serv_04510>
não foi possível, pois meu arquivo não tem serv_045104510.

**Comment by MasterLins** [comment]
@rafaelpatro: por favor, qual seria a melhor opção para mim agora? Reinstalar 4.7.2 usando o Magento Connect e então fazer a instalação manual do último código disponível com essas atualizações?

**Comment by rafaelpatro** [comment]
@MasterLins, tente simular sua cotação [neste link](http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=CalcPrecoPrazo).

**Comment by MasterLins** [comment]
Obtive o esperado, valor mais barato para PAC.
PAC 16,10
SEDEX 17,20

```
<Servicos>
   <cServico>
      <Codigo>4014</Codigo>
      <Valor>18,24</Valor>
      <PrazoEntrega>1</PrazoEntrega>
      <ValorMaoPropria>0,00</ValorMaoPropria>
      <ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
      <ValorValorDeclarado>1,04</ValorValorDeclarado>
      <EntregaDomiciliar>S</EntregaDomiciliar>
      <EntregaSabado>S</EntregaSabado>
      <Erro>0</Erro>
      <MsgErro/>
      <ValorSemAdicionais>17,20</ValorSemAdicionais>
      <obsFim/>
   </cServico>
</Servicos>


<Servicos>
   <cServico>
   <Codigo>4510</Codigo>
      <Valor>17,14</Valor>
      <PrazoEntrega>5</PrazoEntrega>
      <ValorMaoPropria>0,00</ValorMaoPropria>
      <ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
      <ValorValorDeclarado>1,04</ValorValorDeclarado>
      <EntregaDomiciliar>S</EntregaDomiciliar>
      <EntregaSabado>N</EntregaSabado>
      <Erro>0</Erro>
      <MsgErro/>
      <ValorSemAdicionais>16,10</ValorSemAdicionais>
      <obsFim/>
   </cServico>
</Servicos>

```

**Comment by MasterLins** [comment]
Caramba, não mudei nada no sistema, apenas hoje entrei para testar de novo, e o resultado está diferente.

![image](https://cloud.githubusercontent.com/assets/9764703/26035426/31e1bb0e-38a2-11e7-8efd-c376f1d1409d.png)

Devia ser erro lá nos Correios e consertaram.

De qualquer forma é o fim desse problema, está resolvido. Muito obrigado novamente @rafaelpatro e @pedro-teixeira 

Se me permitem um feedback positivo e honesto: vocês foram demais, muito atenciosos e tenazes até o fim, parabéns! Muito obrigado por tudo.

Minha sugestão para melhorar ainda mais no futuro: antes de tentar o GitHub mandei mensagem no Magento Marketplace e diretamente no site pedroteixeira.io, e não recebi resposta. A melhor coisa que vocês podem fazer é avisar nesses lugares que vocês só respondem aqui, porque as pessoas não têm como saber.

Obrigado.
