### ISSUE TITLE
Erro ao calcular tarifa no SGPB

### ISSUE THREAD

**Issue by vitormcorrea** [pedro-teixeira/correios#255]
Amigos boa tarde.
Fizemos a atualização do módulo para versão 4.8.0 e as devidas configurações. Até hoje de manhã estava normal, consegui realizar os testes e estava calculando o frete normalmente. 
Acontece que de algumas horas pra cá esta retornando o seguinte erro:

Erro ao calcular tarifa no SGPB. Serviço adicional 024 requerido pelo serviço adicional 001 não informado(-1).

Verifiquei o erro (-1) e já me certifiquei junto aos Correios que os serviços de entrega estão corretos.

Link do produto: https://www.zenfit.com.br/index.php/default/body-797.html

Alguém enfrentou a mesma dificuldade?

Desde já agradeço.

**Comment by kinfoxxx** [comment]
Boa noite, acho que se estiver AR habilitado nas configurações e estiver pelo contrato esta dando esse erro pois os correis esta com problema para calcular o valor do AR .

**Comment by gucalvevs** [comment]
Bom dia, estou com o mesmo problema, vocês encontraram alguma solução?

obrigado
