### ISSUE TITLE
Meu módulo não está calculando o valor correto de frete

### ISSUE THREAD

**Issue by fotobolo** [pedro-teixeira/correios#259]
Estou tendo problemas com seu módulo. Ele está calculando um preço de frete menor que está no site do correios. 
Segue abaixo os prints e em anexo os prints da configuração.

![print sedex 5](https://cloud.githubusercontent.com/assets/28756217/26153476/d97579aa-3ae1-11e7-9c8e-15521bfde992.jpg)
![print sedex 6](https://cloud.githubusercontent.com/assets/28756217/26153483/dd87ae50-3ae1-11e7-8ef8-1bde4fb3212f.jpg)
![print sedex](https://cloud.githubusercontent.com/assets/28756217/26153456/c19a6bce-3ae1-11e7-8464-5da69e9c76c9.jpg)
![print sedex 2](https://cloud.githubusercontent.com/assets/28756217/26153462/c7200ae0-3ae1-11e7-9734-fe6ce43d2207.jpg)
![print sedex 3](https://cloud.githubusercontent.com/assets/28756217/26153465/cd17ed5a-3ae1-11e7-9d36-396b06c1baba.jpg)
![print sedex 4](https://cloud.githubusercontent.com/assets/28756217/26153472/d2e362dc-3ae1-11e7-80c7-6803ad518e75.jpg)

**Comment by alex-andrade** [comment]
@fotobolo é simples isso. Você está usando PAC(04669) e Sedex(04162) com contrato(CONTRATO AGENCIA). Os serviços de PAC(41106) e Sedex(40010) sem contrato não existem mais(não existe mais o codigo de serviço), e foram substituídos pelo PAC(04510) e Sedex(04014). No site dos Correios, usa PAC(04510) e Sedex(04014), que são sem contrato. No seu sistema, está calculando PAC(04669) e Sedex(04162) com contrato. Por isto a diferença!!!!

**Comment by fotobolo** [comment]
Obrigado, Alex!!
