### ISSUE TITLE
Indisponibilidade do PAC

### ISSUE THREAD

**Issue by iurimedeiros** [pedro-teixeira/correios#262]
Olá amigos, boa noite!

Nestes últimos tempos venho percebendo que muitas vezes o cálculo de frete somente retorna com a modalidade de envio SEDEX, o PAC não sei por qual motivo somente mostra quando quer, peço que se possível realizem o teste com alguns produtos em minha loja www.machinemotors.com.br.
Espero que seja algo simples, pois antes sempre funcionava certinho, se alguém tiver com este mesmo problema favor informar.

Abraço,
Iuri Medeiros
Equipe Machine Motors

**Comment by lecosas** [comment]
Olá Iuri, 

Após a mudança dos contratos dos Correios no início deste mês, o PAC foi extinto para envios considerados locais ou para cidades próximas. Sendo assim, o SEDEX tem o mesmo valor do PAC. 

Ai o PAC foi desativado. Pelo menos, é o que percebemos e a informação que nos foi fornecida pelos Correios.

**Comment by iurimedeiros** [comment]
Olá @lecosas, boa noite!

Eu to sabendo dessa alteração, atualizei o módulo pra ultima versão, mas sou do RS e clientes de SP ou qualquer outro estado estão recebendo a cotação somente do Sedex, meu CEP é o 96180-000 e simulei para 03040-000 entre outros e ocorre isso. Parece ser uma instabilidade pois em certos momentos aparece o PAC. 

Abraço,
Iuri Medeiros
Equipe Machine Motors

**Comment by lecosas** [comment]
Humm @iurimedeiros , então acho que deve ser outra coisa. Você chegou a testar hoje também? Porque me lembro no 1o dia que houve a alteração, estava acontecendo isso no meu também, as vezes mostrava, as vezes não. 

Ps.: Eu não estou usando o módulo com as alterações que foram feitas ai, como meu módulo já tinha sido muito modificado, eu mesmo alterei e não usei os códigos daqui.

**Comment by iurimedeiros** [comment]
Olá @lecosas, boa tarde!

Cara após quebrar cabeça e identificar que o problema somente ocorria em produtos grandes que trabalhamos e com valor alto constatei que foi realizada uma atualização no limite permitido para declaração de valor na modalidade PAC, desativei o valor declarado e tudo voltou a funcionar perfeitamente.

Peço que se alguém souber nos informar qual o limite de valor para declarar no PAC informe nesta issue para ficar registrado e ajudar alguém posteriormente.

Abraço,
Iuri Medeiros
Equipe Machine Motors

**Comment by lecosas** [comment]
@iurimedeiros  estava dando uma olhada nos meus e-mails, e em uma das comunicações está o seguinte:
Limite máximo para Declaração de Valor: SEDEX: R$ 10.000,00 PAC: R$ 3.000,00

Senão me engano, o PAC antes era R$10.000 ou R$5.000

**Comment by davirs** [comment]
Boa tarde a todos. O problema desse lance dos correios é que na grande maioria das vezes o cliente não sabe e acha que é o lojista que está impondo o tipo do frete..

**Teria como o módulo dos correios permitir um aviso para estes casos?
"O PAC foi extinto para envios considerados locais ou para cidades próximas"** 

Fica ai a sugestão simples para ajudar a melhorar o módulo

Abraço
