### ISSUE TITLE
CEP de origem invalido.

### ISSUE THREAD

**Issue by lmarquine** [pedro-teixeira/correios#263]
Log retorna erro de cep de origem inválido porém na loja está correto já tentei com e sem hífen alguém está com esse problema? 

Log - 2017-05-20T05:37:04+00:00 DEBUG (7): pedroteixeira_correios: Warning! There is no valid quotes, and no one error was throwed: CEP de origem invalido.

Teste no ws dos Correios

System.ArgumentException: Cannot convert  to System.Int32.
Parameter name: type ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Web.Services.Protocols.ScalarFormatter.FromString(String value, Type type)
   --- End of inner exception stack trace ---
   at System.Web.Services.Protocols.ScalarFormatter.FromString(String value, Type type)
   at System.Web.Services.Protocols.ValueCollectionParameterReader.Read(NameValueCollection collection)
   at System.Web.Services.Protocols.HttpServerProtocol.ReadParameters()
   at System.Web.Services.Protocols.WebServiceHandler.CoreProcessRequest()

**Comment by thelucasgarcia** [comment]
resolveu? estou com o mesmo problema

**Comment by rafaelpatro** [comment]
Esse problema apareceu hoje aqui tb

**Comment by philsouza2016** [comment]
Acabei de ter o mesmo problema na minha loja.

**Comment by wdarking** [comment]
Mesmo problema aqui: 
`pedroteixeira_correios: Warning! There is no valid quotes, and no one error was throwed: CEP de origem invalido.`

**Comment by philsouza2016** [comment]
Problema nos correios, com certeza, vou tetar uma requisição via soapUI aqui, vou aproveitar pra deixar pronto caso aconteça novamente.

**Comment by Rfrantz** [comment]
Looks like someone more is to facing the same problem...

> <Erro>-2</Erro>
<MsgErro>CEP de origem invalido.</MsgErro>

**Comment by rafaelpatro** [comment]
Não há oq fazer! É um problema no web service dos Correios.
Podem testar por aqui [CalcPrecoPrazo](http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=CalcPrecoPrazo).

**Comment by lokharth** [comment]
Tem varios sites com o calculo do correios funcionando.

Imagino que eles tenham um outro  WebService pro pessoal com contrato

**Comment by angelomarafelli** [comment]
Complicado em... nenhuma resposta dos Correios?

**Comment by rafaelpatro** [comment]
@lokharth, a maioria é cache, ou uma tabela fixa previamente cadastrada. Coloca um CEP com área de risco. Provavelmente o prazo estará incorreto.

**Comment by philsouza2016** [comment]
Um dos sites que atendo não usa contrato e está tendo problemas.

**Comment by mauroagr** [comment]
Aqui tive problema minutos atras de gerar PAC, via API do sigep, problema de https. Após alguns minutos resolveu

**Comment by lokharth** [comment]
@rafaelpatro realmente... não ta calculando o valor pra cidade especifica, ta dizendo 
"Interior de Santa Catarina"

Provavelmente alguma contingência pros casos em que o correios cai dessa forma...

**Comment by rafaelpatro** [comment]
Acabei de descobrir a função CalculaTarifaServico, escondidinha lá no webservice do [SIGEP](https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl). Testei aqui com o meu contrato, e adivinha só, tá funcionando.
Engraçado que nada consta no Manual de Integração.

**Comment by 3m0** [comment]
Correios vai corrigir só depois do jogo, certeza.

**Comment by mauroagr** [comment]
A api do sigep nao valida o cep na hora de gerar a PLP, tu acha que eles vao documentar algo??...hehehe

**Comment by fastcom2015** [comment]
Webservice correios fora ainda galera , alguém tem alguma info sobre 
https://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?wsdl

**Comment by marcosguerreiro** [comment]
Os correios estão fora do ar novamente, a loja parou de calcular, e o pior é que ficamos de mãos atadas sem ter o que fazer, não tem para quer recorrer, parece o Mercadolivre que não tem suporte,  

Para agora não tem solução, é só esperar, perder clientes, vendas e ganhar reclamações!

A meio prazo tem duas opções, desenvolver um módulo com tabela para caso de falhas e/ou utilizar o Mandaê.

**Comment by philsouza2016** [comment]
Aqui voltou a pouco.

**Comment by lokharth** [comment]
Pra mim fica só carregando, até o timeout

**Comment by philsouza2016** [comment]
Olá, tinha voltado a funcionar ontem, mas o problema segue hoje, vou verificar o log para verificar se é o mesmo erro.

**Comment by lokharth** [comment]
Parece que voltou agora, vamos ver quanto tempo fica no ar...
