### ISSUE TITLE
Código PAC e SEDEX não estão disponíveis

### ISSUE THREAD

**Issue by brunohrp** [pedro-teixeira/correios#264]
O código 04669 PAC na agencia e 04162 sedex na agencia não estão disponíveis para seleção.
Como posso adicionar esses novos códigos ??

**Comment by rafaelpatro** [comment]
Esses códigos estão disponíveis na [última versão](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/sql/pedroteixeira_correios_setup/upgrade-4.8.0-4.8.1.php#L99). Só precisa atualizar.

**Comment by brunohrp** [comment]
Funcionou
