### ISSUE TITLE
Não encontra alguns CEPs: "Informe seu CEP para calcular o valor da entrega"

### ISSUE THREAD

**Issue by davirs** [pedro-teixeira/correios#269]
Olá. O módulo não encontra alguns CEPS nos correios, porém conferindo no site dos correios o CEP é válido. Achei alguns erros nos LOGs

```
[01-Jun-2017 15:45:01 UTC] PHP Warning:  include(Correios/Rastro/BuscaEventos.php): failed to open stream: No such file or directory in /home/server/public_html/lib/Varien/Autoload.php on line 94

[01-Jun-2017 15:45:01 UTC] PHP Warning:  include(Correios/Rastro/BuscaEventos.php): failed to open stream: No such file or directory in /home/server/public_html/lib/Varien/Autoload.php on line 94

[01-Jun-2017 15:45:01 UTC] PHP Warning:  include(): Failed opening 'Correios/Rastro/BuscaEventos.php' for inclusion (include_path='/home/server/public_html/app/code/local:/home/server/public_html/app/code/community:/home/server/public_html/app/code/core:/home/server/public_html/lib:.:/usr/share/pear:/usr/share/php') in /home/server/public_html/lib/Varien/Autoload.php on line 94

[01-Jun-2017 15:45:01 UTC] PHP Fatal error:  Class 'Correios_Rastro_BuscaEventos' not found in /home/server/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 78
```

A mensagem que aparece no frontend é: Informe seu CEP para calcular o valor da entrega
Meu magento é 1.9.3.2
A versão do módulo é a última disponibilizada v4.9.0

O CEPs que eu testei aqui foram casos reais de clientes,  1321430 e 21765030
@pedro-teixeira  Se tiver um tempinho, preciso de ajuda com isso, Muito obrigado!!!

**Comment by DaviSiqueira** [comment]
Os CEPs que você informou são de área de risco, no momento o módulo só exibe a cotação e o aviso de área de risco se a opção **_Mostrar Método Mesmo se Não Aplicável_** estiver ativada.

Conversei com o @rafaelpatro sobre este problema na issue #254

**Comment by rafaelpatro** [comment]
@davirs os erros acusam a falta do arquivo [BuscaEventos.php](https://github.com/pedro-teixeira/correios/blob/master/app/lib/Correios/Rastro/BuscaEventos.php).
Dá uma conferida se todos os arquivos estão no servidor.

**Comment by davirs** [comment]
@rafaelpatro @DaviSiqueira tudo bem? eu reinstalei o módulo e conferi os arquivos. Achei estranho que o módulo cria uma pasta lib dentro de app/, então salvei dentro de /lib também para testar. O  erro continua.

Eu sempre deixo ativa a opção "aviso de área de risco", porém a opção Mostrar se não aplicável eu sempre usei desativado. Pare teste, ativando esta opção aparece:

![screenshot_19](https://cloud.githubusercontent.com/assets/4355062/26693178/a16fd79a-46d9-11e7-9d33-f474fbeb2ee8.png)

Será que haverá algum ajuste no módulo ou vou ter que deixar esta opção ativa? Ao meu ver se exibir um frete que de fato não pode ser aplicado vou acabar tendo prejuízo..

Obrigado!!!

**Comment by rafaelpatro** [comment]
@davirs está correto quanto a _lib_. Deveria estar na raiz do projeto, e deverá ser corrigido em breve.

**Comment by rafaelpatro** [comment]
Quanto ao aviso de _Área de Risco_, é uma mensagem originária dos Correios, para o CEP em questão. Significa que estão atendento **sim** aquela região, mas com prazo superior, devido as condições de risco.

 Se prefere omitir a mensagem, basta desativar a opção de _Exibir alerta de Área de Risco_.

**Comment by davirs** [comment]
@rafaelpatro A mensagem tudo bem quanto a isso é melhor avisar mesmo.. Mas eu não concordo em ter que habilitar a opção **Mostrar Método Mesmo se Não Aplicável**
Acredito que essa opção resolve o problema de exibir o frete da área de risco mas por outro lado cria um problema exibindo frete onde realmente não deveria...

Testei também na frenet, funciona certinho esses CEPs em questão

**Comment by rafaelpatro** [comment]
@davirs a opção _Mostrar Método Mesmo se Não Aplicável_ não exibe cotação de frete onde não deveria. Apenas exibe mensagens de erro que poderiam ser omitidas do cliente.

Todos os resultados de cotação de frete que vc viu são válidos.

**Comment by davirs** [comment]
Na verdade o título não é exatamente o que deveria ser por isto a confusão... Mas se funciona da forma que está falando tudo certo então

Obrigado!!!

**Comment by redati** [comment]
Precisa atualizar o arquivo modman com a nova pasta lib.
