### ISSUE TITLE
Locais de Estoque

### ISSUE THREAD

**Issue by jfcbxp** [pedro-teixeira/correios#274]
Quando meu ecommerce tem produtos que podem sair da cidade x e da cidade y como eu posso fazer? pois ele puxa o cep apenas do cadastro do sistema, não poderia puxar um cep no grupo de produtos ? ou por produto?

**Comment by rafaelpatro** [comment]
Infelizmente o módulo não suporta multiplas origens. Mas você pode resolver
isso criando multiplas stores no magento. O problema é precisaria
customizar o frontend, para o cliente navegar em 2 lojas, compartilhando a
mesma sessão.

Em 8 de jun de 2017 8:57 PM, "jfcbxp" <notifications@github.com> escreveu:

**Comment by jfcbxp** [comment]
obrigado pela resposta, mas a minha solução seria mais simples eu so precisava saber qual arquivo eu tenho que editar. Pois sou iniciante em magento.

eu criei um atributo no produto denominado Origem do estoque, Cidade X ou Cidade  Y  em um dropdown pois nunca vai acontecer do mesmo produto ser vendido nas duas lojas ao mesmo tempo.


qual arquivo do modulo que eu poderia acessar para adicionar um trecho de codigo antes de iniciar o calculo mais ou menos assim:

if (product.estoqueOrigem == "CidadeX"){
     System.Geral.ZipCode = "XXXXXXX"
}
if (product.estoqueOrigem == "CidadeY"){
     System.Geral.ZipCode = "YYYYYYY"
}

Inicio do calculo do frete no modulo.

**Comment by rafaelpatro** [comment]
@jfcbxp, seus produtos são nominais? Se a resposta for _não_, como vai garantir que o carrinho não tenha produtos de duas ou mais origens?

**Comment by jfcbxp** [comment]
eu ainda não conheço como o modulo trabalha, mas eu imagino que o calculo do frete seja feito em um loop por produto e somado a um total geral de frete, produto 1 loja x  frete 10, produto 2 loja y frete 20, total frete 30, tem possibilidade de inserir no carrinho produtos de lojas diferentes, mas 1 produto não será vendido em duas lojas ao mesmo tempo.

**Comment by rafaelpatro** [comment]
Se o módulo trabalhasse dessa forma, retornaria fretes muito caros.
Faça um teste no site dos Correios, enviar 1 pacote de 10 kg é absurdamente mais barato do que 10 pacotes de 1 kg.

Enfim, o módulo junta todo o carrinho, e faz uma única cotação.

**Comment by jfcbxp** [comment]
entendi então a solução seria realizar uma modificação maior no modulo para realizar 2 cotações para cada warehouse. varre o carrinho com produtos da loja 1, realiza a cotação e depois faz a da warehouse 2 e soma a cotação dos dois.

**Comment by rafaelpatro** [comment]
Exatamente!
Se pretende mergulhar nisso, sugiro começar [nesse método](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php#L866). Ali já é feita uma restrição de _Serviços por Produto_.

Se quiser contribuir com uma PR, seria uma boa deixar isso opcional nas configurações do módulo.

**Comment by jfcbxp** [comment]
muito obrigado pela atenção, estou realizando cursos de front end do magento depois vou realizar o de backend para iniciar essa modificação pois vou precisar mesmo. Muito obrigado
