### ISSUE TITLE
Problema com o "Acompanhar Pedido" no Backend.

### ISSUE THREAD

**Issue by FilipeSilvaCtba** [pedro-teixeira/correios#275]
Prezados, 

Começou recentemente após esta mudança de códigos do correio. Ao clicar em Acompanhar Pedido no backend, dentro do pedido do cliente, abre a janela para rastrear o pedido porém da o seguinte erro:

Unable to Connect to tcp://websro.correios.com.br:80. Error #110: Connection timed out

Mudou algo com esta url dos correios?

**Comment by rafaelpatro** [comment]
@FilipeSilvaCtba, o url de rastreamento foi atualizado há alguns meses. Verifique se [este arquivo](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L746) está igual em seu servidor.

**Comment by FilipeSilvaCtba** [comment]
@rafaelpatro Grato pela informação.

Resolvi aqui, era conflito com outro módulo de correios que tínhamos aqui. Removi o outro e atualizei o módulo aqui do PedroTeixeira. Tudo ok agora. 

Obrigado.
