### ISSUE TITLE
Fim E-sedex - 19/05

### ISSUE THREAD

**Issue by marcospaf** [pedro-teixeira/correios#278]
Pessoal agora parece que é definitivo.

Dia 19/05 não teremos mais E-sedex e vai complicar a coisa. recebi a noticia agora

**Comment by rafaelpatro** [comment]
Péssima notícia!
Também recebi a cartinha dos Correios, e já desativei o E-SEDEX ontem.
A partir de segunda-feira é só SEDEX.

**Comment by marcospaf** [comment]
Lascou geral mesmo. já tirei . complicou geral. minhas vendas despencaram. vai ser fogo

**Comment by boobebe** [comment]
Os valores do Sedex foram ajustados, em algumas regiões será o mesmo preço do antigo Esedex.
Sabem se a tabela de consulta do webservice será atualizada ou teremos que alterar a url para os novos valores?

**Comment by meganovidades** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ghermans@gmail.com
    Domain meganovidades.com has exceeded the max emails per hour (600/600 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:43003)
	by vps.meganovidades.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-6e7f-contato=meganovidades.com@sgmail.github.com>)
	id 1dMnRV-0001js-7e
	for contato@meganovidades.com; Mon, 19 Jun 2017 00:33:33 -0300
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=/SFL5aZAyXtaITQnKUZhNJb1HCM=; b=ahi3adecBlA+heYv
	9QzFbHYGS81tWj4cABwhpsYU5JY2t0U+sHM8Rt5TjhpwymUm0WAiWCcCIs3D9nBE
	Pp3cSuey8M6gxIkX85kuW9j/lixl9+JvbsiMwQecNAnrOZ4N44HvvCd+FWMAPLTV
	M1e2u+0W7kfbb8ovl+71+yxI6iQ=
Received: by filter0942p1mdw1.sendgrid.net with SMTP id filter0942p1mdw1-5145-594745E3-25
        2017-06-19 03:32:51.874320624 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id 3zsdkBdFTGWJXZ6ISSybDA
	for <contato@meganovidades.com>; Mon, 19 Jun 2017 03:32:51.831 +0000 (UTC)
Date: Sun, 18 Jun 2017 20:32:51 -0700

**Comment by marcospaf** [comment]
reajustado quando? cara minhas vendas despencaram com o fim do E-sedex !!! vergonha  !! essa cambada!!! me perdoem , sei que não é o local , mas como pode um monopólio tem prejuízo? R: MUITO LADrÃO!!

**Comment by marcospaf** [comment]
Só acrescentando Tb. Eu vendo tb no MercadoLivre, minhas vendas despencaram tb. A pergunta é será eu só foi comigo ?  Em tese, se vendemos menos, os correio faturam Menos e sendo assim o que já está ruim vai ficar pior ! A alegação sempre foi : "temos um serviço com preço de pac e com prazo de sedex" era muito mais simples fazer um e-sedex entre os dois e com prazo entre os dois .... agora que quero ver

**Comment by radamiBR** [comment]
Alguns CEP do estado de São Paulo não existe mais o PAC e enviado como SEDEX, no módulo colocando CEP de um local que não envia como PAC somente SEDEX, esta aparecendo o PAC, alguém esta com mesmo erro.

**Comment by rafaelpatro** [comment]
@radamiBR, consegue simular a consulta [neste link](http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=CalcPrecoPrazo)?

Manda print do formulário preenchido e da resposta.

**Comment by radamiBR** [comment]
@rafaelpatro 
ao preencher enviar da esses erro:
System.ArgumentException: Cannot convert caixa to System.Int32.
Parameter name: type ---> System.FormatException: Input string was not in a correct format.

Seque print do meu simulado e da nova tabela dos correios para SP
[http://imgur.com/a/tFrgD](url)

**Comment by rafaelpatro** [comment]
Manda um print do formulário, ocultando somente teu contrato e senha.
Deve estar preenchendo algum campo errado.

**Comment by radamiBR** [comment]
seque imagem gerada
[](http://imgur.com/a/5U3rA)

**Comment by rafaelpatro** [comment]
![image](https://user-images.githubusercontent.com/13813964/27548021-100e05e4-5a6e-11e7-9856-89cb3a388f11.png)

**Comment by radamiBR** [comment]
[http://imgur.com/a/JYToR](url)

**Comment by rafaelpatro** [comment]
Parece que sua requisição está funcionando agora.
Preencha com os códigos dos serviços que estão retornando iguais (PAC e SEDEX), separados por vírgula.
Ex.: 04669,04162

**Comment by radamiBR** [comment]
Serviço que uso dos correios são
Sedex com contrato 40096
Pac com contrato 41068
Esta com essa diferença de preço para São Paulo com CEP 01 até 09
Foi que eu recebi da agência tabela com novas diretrizes do correios de valores.

**Comment by rafaelpatro** [comment]
Cara acho q esses seus códigos foram extintos há algumas semanas.
Tenta simular com os códigos q mandei. Ou usa seu acesso ao Sigep para descobrir os códigos atualizados.
