### ISSUE TITLE
Erro no Calculo Peso Cubico

### ISSUE THREAD

**Issue by rafarockfoz** [pedro-teixeira/correios#28]
Boa tarde Pedro, tudo bem?

Tive um problema utilizando seu modulo com os seguintes dados no produto:

comprimento 105
altura 40
largura 50

nenhuma das medidas passaram de 105cm e o total não passa de 200cm

Apareceu o seguinte no log de erro:

2014-09-26T18:20:06+00:00 DEBUG (7): pedroteixeira_correios [159]: URL Error, all services return with error
2014-09-26T18:21:14+00:00 DEBUG (7): pedroteixeira_correios [107]: Dimension error

**Comment by pedro-teixeira** [comment]
@rafarockfoz, esse problema deve ser resolvido na versão `v4.4.0`, pode testar e se o problema persistir reabrir o ticket?

**Comment by rafarockfoz** [comment]
Oi tudo bem?
Atualizei e acredito que esta tudo OK, obrigado pelo modulo, esta muito bom!

Segue uma dica: eu tenho contrato com os correios, e mesmo com o limite de
dimensões sendo 105cm os correios aceitam eu enviar itens acima desse
limite, as vezes até 120cm.
Seria legal se tivesse como eu setar quais as medidas limite.

Um forte abraço,

Em 31 de março de 2015 15:55, Pedro Teixeira <notifications@github.com>
escreveu:
