### ISSUE TITLE
PAC e SEDEX valores iguais

### ISSUE THREAD

**Issue by felipecrf** [pedro-teixeira/correios#281]
Olá a todos! A algum tempo, mesmo após o módulo ser atualizado (banco de dados e arquivos apagados para realizar a atualização), o valor cotado para PAC e Sedex são iguais, com outros clientes não aconteceu isso. Já procurei possíveis conflitos, promoções, etc. e até o momento nada. Alguém poderia ajudar ou já passou por isso?

Screenshot abaixo:

![carrinho de compras](https://user-images.githubusercontent.com/15946986/27512219-fde39618-590f-11e7-95dd-3cd2273f7ad6.png)

Grato,

**Comment by tarsogarcia** [comment]
Qual o cep de origem e destino?

**Comment by felipecrf** [comment]
Origem: 24710-480
Destino: 25046-440

Independente do CEP de origem e destino, da o mesmo valor para serviços
diferentes (PAC e SEDEX)


Atenciosamente,
Felipe Antunes

2017-06-27 14:24 GMT-03:00 tarsogarcia <notifications@github.com>:

**Comment by tarsogarcia** [comment]
Aqui no RJ o serviço de PAC foi descontinuado quando tem a origem e destino RJ, pode ser isso. 
Teste com um CEP de outro estado.

**Comment by felipecrf** [comment]
Sério? Então só entrega via SEDEX quando for de RJ x RJ? Tem a condição
pronta ai pra eu adicionar no código? Testei com SP, e realmente foi
valores diferentes.


Atenciosamente,
Felipe Antunes

Em 27 de junho de 2017 15:26, tarsogarcia <notifications@github.com>
escreveu:

**Comment by felipecrf** [comment]
Pior de tudo é ver isso... Frete RJ x RJ, cep é do mesmo bairro, ruas
próximas... Segue screenshot.
Vai entender rs


Atenciosamente,
Felipe Antunes

Em 27 de junho de 2017 15:28, Felipe Antunes <f910511@gmail.com> escreveu:

**Comment by tarsogarcia** [comment]
Tive postagens com PAC rejeitadas, tive que gerar uma nova etiqueta por Sedex.

**Comment by felipecrf** [comment]
Como faz neste caso? Um site com CEP perto calcula preços diferentes para
PAC e SEDEX, outro site os preços são iguais.


Atenciosamente,
Felipe Antunes

Em 27 de junho de 2017 15:43, tarsogarcia <notifications@github.com>
escreveu:

**Comment by tarsogarcia** [comment]
Eu atualizei para a ultima versão e só aparece a opção Sedex.

**Comment by felipecrf** [comment]
Estranho... Pra mim, tanto no admin quanto no frontend continua
aparecendo...
É a versão do git mesmo que você está usando?

Abraço!


Atenciosamente,
Felipe Antunes

Em 27 de junho de 2017 17:34, tarsogarcia <notifications@github.com>
escreveu:

**Comment by tarsogarcia** [comment]
Sim a ultima versão.
Você fez o login com as suas credenciais do Sigepweb?

**Comment by tarsogarcia** [comment]
Usei o cep que forneceu, segue o print na minha loja.

http://prntscr.com/foxbxz

**Comment by felipecrf** [comment]
Estranho... Qual a sua URL pra eu testar outros CEPs? Pode me mandar link
da última versão? O meu update foi do próprio git, mas é estranho ser desta
forma. Seu CEP de origem também é Rio?


Atenciosamente,
Felipe Antunes

Em 27 de junho de 2017 18:33, tarsogarcia <notifications@github.com>
escreveu:

**Comment by tarsogarcia** [comment]
Sim, origem RJ, baixei a ultima versão aqui do git.

**Comment by felipecrf** [comment]
Você fez igual eu? Excluiu todos os arquivos e as tabelas do banco de dados para depois instalá-lo? Pois eu fiz desta forma.

**Comment by rafaelpatro** [comment]
Felipe, dá uma conferida na tabela core_resource e verifica se a versão do
módulo está correta.

Em 28/06/2017 13:06, "felipecrf" <notifications@github.com> escreveu:

**Comment by tarsogarcia** [comment]
Sim fiz assim, e depois fiz o login pelo modulo no sistema dos correios.

**Comment by felipecrf** [comment]
Opa! Obrigado a todos que estão aqui.

Rafael, segue versão: 4.9.0


Atenciosamente,
Felipe Antunes

Em 28 de junho de 2017 13:15, tarsogarcia <notifications@github.com>
escreveu:

**Comment by rafaelpatro** [comment]
Tem acesso ao SIGEP Web? Consegue cadastrar seu usuário e senha nas configurações do módulo?

**Comment by felipecrf** [comment]
Não sei se meu cliente tem, pois está em branco, se tiver, não preencheu.
Vou ver com ele. Obrigado a todos.


Atenciosamente,
Felipe Antunes

2017-06-28 15:06 GMT-03:00 Rafael Patro <notifications@github.com>:

**Comment by tarsogarcia** [comment]
Se esta em branco provavelmente ele nao preencheu, aconteceu comigo.

**Comment by felipecrf** [comment]
Opa! Sim, hoje ele me confirmou que não tem contrato com o Correios. No
caso, o PAC continuará aparecendo? Eu terei que criar uma condição?


Atenciosamente,
Felipe Antunes

Em 29 de junho de 2017 16:32, Tarso Garcia <notifications@github.com>
escreveu:
