### ISSUE TITLE
Correios naao aparece no cadastro do Produto

### ISSUE THREAD

**Issue by isanat** [pedro-teixeira/correios#285]
Ola, eu instalei a versao nova pelo connect e nao aparece na pagina de cadastrar o produto e colocar as dimensoes dele.

tanto na versao 1.9.2 como na versao 1.9.3 do magento

**Comment by rafaelpatro** [comment]
Bom dia @isanat
Desativou o compilador? Atualizou as caches?
Pode dar uma conferida na versão do módulo na tabela core_resource?

**Comment by isanat** [comment]
Sim, fiz tudo segue as fotos. Nao entendo o porque. se eu entrar nos produtos associados, la aparece correios.

www.tenissa.com.br . e todos os produtos consegue calcular frete e fazer a venda.

mas n
![caches](https://user-images.githubusercontent.com/26491746/27744775-44dbe544-5d97-11e7-8b32-a961e39409c9.jpg)
![cadastro n ao aparece correios](https://user-images.githubusercontent.com/26491746/27744776-44dd07c6-5d97-11e7-9039-11f550e7cf9a.jpg)
![compilador](https://user-images.githubusercontent.com/26491746/27744774-44db5a16-5d97-11e7-80e0-77bec9b6af1a.jpg)


ao consegue cadastrar novos produtos , porque nao aparece correios.

**Comment by isanat** [comment]
na tabela esta core_resource esta 4.9.0 .

**Comment by rafaelpatro** [comment]
Ok, confere também se os atributos do módulo existem no Magento, em _Catálogo > Atributos > Gerenciar Atributos_:

- volume_altura
- volume_largura
- volume_comprimento
- postmethods
- fit_size
- posting_days

Verifica tb se a tabela _correios_postmethods_ existe, e contem dados.

**Comment by isanat** [comment]
o PIOR É QUE TEM correios_postmethods na DB , e verifiquei que tem sim em atributos. 

Verifiquei tambem que se eu criar uma nova instalação do magento, e colocar o modulo, ele funciona, então me parece que o erro pod ser no magento. sei lá! estou desesperado porque não sei onde vou para consertar isso. o modulo funciona somente para produtos simples e outros, menos os configuraveis.

**Comment by marcospaf** [comment]
opa  @isanat , você já tentou reinstalar?  algo não deve ter ido em sua instalação , pois agora tem uma aba correios dentro de produtos

**Comment by isanat** [comment]
Puxa vida que Droga! é o modulo mesmo que esta ferrando com a BD e fazendo desaparecer o correios da pagina de cadastro do produto. FIZ ROLLBACK DO MEU SITE e configurei tudo , um traballão. e estava na versao 4.7.2 do modulo cadastrado. ai desinstalei para instalar esta praga de 4.9.0 e fudeu tudo de novo. é instalar na versão 1.9.3.3 do magento e ferrar com tudo.

**Comment by marcospaf** [comment]
@isanat , cara meu magento é o 1.7.0.2 e estou com a versão 4.9 do modulo , aqui está funcionando tranquilo. eu estava com a versão 4.7.2 e fiz a atualização para a 4.9 e ficou tranquilo. Você chegou a ver no tema default  do magento se funcionava? eu já peguei problema com tema... fogo

Pelo que eu me lembre era necessário ter a versão 4.7.0 e instalar a 4.9 por cima . Só o @rafael ou pedro pode dizer certo.

**Comment by isanat** [comment]
@marcospaf  e @rafaelpatro  e @pedro-teixeira , pois é, como disse fiz rollback do magento para um backup antigo, estava com a versao 4.7.2 , entao fiz todas atualizações no site e deixei a atualização do correios por ultimo, a minha versao que uso o magento é 1.9.3 , estava tudo certo o correios na pagina de cadastro do produto magento. e quando coloquei a versão 4.9 ja era. sumiu. gostaria de uma correção para isso, sem ter de eu dar outro rollback no magento, pois meu backup é muito antigo. e não gostaria de fazer tudo novamente. quem puder me ajudar. passo meu email aqui netlinkassist@gmail.com para contato.

**Comment by rickygomez** [comment]
Opa amigo tive um problema parecido, o que na verdade ocorreu e que alguns itens estavam setados como display: none e não apareciam

Antes
![antes](https://user-images.githubusercontent.com/17891262/28340494-6062f430-6be6-11e7-8886-522008ae1207.PNG)

fiz uma busca no arquivo onde estava configurado isso e comentei esse css

Depois:
![depois](https://user-images.githubusercontent.com/17891262/28340550-902da0a2-6be6-11e7-9c34-6ebad83988ab.PNG)

no meu caso isso estava em app/design/adminhtml/default/default/template/page/head.phtml

**Comment by lelo451** [comment]
Para mim os campos da aba do correios estão ocultas. Onde eu posso editar para desocupar esses campos? (Só aparece o comprimento, o resto fica com display: none)

**Comment by lelo451** [comment]
*desocultar

**Comment by isanat** [comment]
nada , não consegui resolver. fui no endereço e não encontrei nada.

> ?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<title><?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>

<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
    var BLANK_IMG = '<?php echo $this->getJsUrl() ?>spacer.gif';
    var BASE_URL = '<?php echo $this->getUrl('*') ?>';
    var SKIN_URL = '<?php echo $this->jsQuoteEscape($this->getSkinUrl()) ?>';
    var FORM_KEY = '<?php echo $this->getFormKey() ?>';
</script>

<?php echo $this->getCssJsHtml() ?>

<?php if($this->getCanLoadExtJs()): ?>
<script type="text/javascript">
    Ext.BLANK_IMAGE_URL = BLANK_IMG;
    Ext.UpdateManager.defaults.loadScripts = false;
    Ext.UpdateManager.defaults.disableCaching = true;
</script>
<?php endif; ?>

<?php if($this->getCanLoadTinyMce()): // TinyMCE is broken when loaded through index.php ?>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>tiny_mce/tiny_mce.js"></script>
<?php endif; ?>

<script type="text/javascript">
    Fieldset.addToPrefix(<?php echo Mage::helper('adminhtml')->getCurrentUserId() ?>);
</script>

<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getChildHtml('calendar'); ?>
<?php echo $this->getChildHtml('optional_zip_countries'); ?>

**Comment by isanat** [comment]
o problema acontece quando instalamos a extensão , 4.9 , dai em diante mesmo desistalando, e instalando uma antiga , não funciona mais.

**Comment by lelo451** [comment]
Como pode ser resolvido esse erro?

**Comment by isanat** [comment]
estou tentando vercomo funciona a dica do amigo ai acima mas, ta dificil

**Comment by rickygomez** [comment]
Opa amigo, quando você inspeciona o código via Chrome essas divs aparecer como display nome? No meu caso estava assim. Eu fiz uma varredura no código procurando essa class e encontrei no fim do arquivo que indiquei uma tag style.

Não sei se essa é a maneira correta mas foi como eu consegui fazer voltar a aparece.

**Comment by lelo451** [comment]
Boa noite. Você poderia postar o arquivo para ver como ficou depois da alteração?

**Comment by lelo451** [comment]
Ou indicar melhor que arquivo e que linha você alterou, pois do jeito que está mais acima não ficou muito claro como você fez para resolver.

**Comment by rickygomez** [comment]
O arquivo está em app/design/adminhtml/default/default/template/page/head.phtml
O meu ficou assim
-----------------------------


<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magento.com for more information.
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2016 X.commerce, Inc. and affiliates (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<title><?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>
  <script type="text/javascript" src="<?php echo $this->getJsUrl('jquery/jquery.min.js') ?>"></script>
<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
    var BLANK_IMG = '<?php echo $this->getJsUrl() ?>spacer.gif';
    var BASE_URL = '<?php echo $this->getUrl('*') ?>';
    var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';
    var FORM_KEY = '<?php echo $this->getFormKey() ?>';
</script>

<?php echo $this->getCssJsHtml() ?>

<?php if($this->getCanLoadExtJs()): ?>
<script type="text/javascript">
    Ext.BLANK_IMAGE_URL = BLANK_IMG;
    Ext.UpdateManager.defaults.loadScripts = false;
    Ext.UpdateManager.defaults.disableCaching = true;
</script>
<?php endif; ?>

<?php if($this->getCanLoadTinyMce()): // TinyMCE is broken when loaded through index.php ?>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>tiny_mce/tiny_mce.js"></script>
<?php endif; ?>

<script type="text/javascript">
    Fieldset.addToPrefix(<?php echo Mage::helper('adminhtml')->getCurrentUserId() ?>);
</script>

<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getChildHtml('calendar'); ?>
<?php echo $this->getChildHtml('optional_zip_countries'); ?>

<style>
	a#product_info_tabs_group_19,
	a#product_info_tabs_group_20,
	a#product_info_tabs_group_18,
	a#product_info_tabs_crosssell,
	a#product_info_tabs_upsell,
	a#product_info_tabs_related,
	a#product_info_tabs_tags,
	a#product_info_tabs_customers_tags,
	a#product_info_tabs_group_35,
	a#product_info_tabs_group_34
	{
	    /* comentei aqui para voltar a exibir as abas que estavam ocultas no gerenciador de produtos
		display: none;
		*/
	}
</style>

**Comment by lelo451** [comment]
Infelizmente para mim o código acima não se encontra no arquivo indicado. Mas valeu pela ajuda. Para solucionar o problema eu fiz um código javascript que quando a se clica na aba dos correios, se o id dela não mudar e continuar sendo 18 vai funcionar, ele pega os elementos tr e retira o display none;
Segue o código do arquivo page.phtml completo:
`
<?php
/* ... */
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<title><?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>

<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
    var BLANK_IMG = '<?php echo $this->getJsUrl() ?>spacer.gif';
    var BASE_URL = '<?php echo $this->getUrl('*') ?>';
    var SKIN_URL = '<?php echo $this->jsQuoteEscape($this->getSkinUrl()) ?>';
    var FORM_KEY = '<?php echo $this->getFormKey() ?>';
    window.onload = function() {
        var listen = document.getElementById('product_info_tabs_group_18');
        listen.onclick = function() {
	    var target = document.getElementById('group_fields18');
	    var fim = target.getElementsByTagName('tr');
	    for(j = 0; j < fim.length; j++) {
		fim[j].removeAttribute('style');
	    }
        }
    };
</script>

<?php echo $this->getCssJsHtml() ?>

<?php if($this->getCanLoadExtJs()): ?>
<script type="text/javascript">
    Ext.BLANK_IMAGE_URL = BLANK_IMG;
    Ext.UpdateManager.defaults.loadScripts = false;
    Ext.UpdateManager.defaults.disableCaching = true;
</script>
<?php endif; ?>

<?php if($this->getCanLoadTinyMce()): // TinyMCE is broken when loaded through index.php ?>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>tiny_mce/tiny_mce.js"></script>
<?php endif; ?>

<script type="text/javascript">
    Fieldset.addToPrefix(<?php echo Mage::helper('adminhtml')->getCurrentUserId() ?>);
</script>

<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getChildHtml('calendar'); ?>
<?php echo $this->getChildHtml('optional_zip_countries'); ?>
`
Caso a equipe de desenvolvimento queira adicionar o código ao projeto pode adicionar.
