### ISSUE TITLE
Correios Cache não funciona

### ISSUE THREAD

**Issue by ralg** [pedro-teixeira/correios#286]
Instalamos recentemente o módulo em um projeto e ativamos a opção: Modo de Prioridade da Cache - Consultar o Cache; e se falhar,  os Correios, porém, quando os Correios está fora do ar, o mesmo trás a seguinte mensagem: 
![131eb867-6121-4f39-8565-a7173cdcdae3](https://user-images.githubusercontent.com/13282708/27733747-258da70a-5d6e-11e7-9229-318e25098107.jpg)
Este método de envio está fora do ar. Por favor entre em contato conosco.

O cache já está ativo em Gerenciar Cache.

**Comment by rafaelpatro** [comment]
Rodrigo, a cache precisa ser previamente alimentada, com uma cotação idêntica, mesmo peso, cep, etc.

**Comment by ralg** [comment]
Como podemos alimentar essas informações por lá Rafael? Vc saberia informar? Att.

**Comment by rafaelpatro** [comment]
@ralg, a cache é alimentada quando o cliente faz uma cotação, e o Correios responde. É o mesmo conceito de cache de qualquer aplicação. Você guarda o resultado em uma memória rápida, para uma necessidade futura.
Enfim para alimentar a cache, terá q fazer diversas cotações, de diferentes pesos e CEPs.

**Comment by ralg** [comment]
Ou seja, a cada cotação, ele alimentará a base, é isso?

**Comment by rafaelpatro** [comment]
Exato

**Comment by ralg** [comment]
Ok Rafael, obrigado.
