### ISSUE TITLE
CEP com restrição de entrega

### ISSUE THREAD

**Issue by nataliaalves03** [pedro-teixeira/correios#29]
Uma sugestão de melhoria.
Caso o CEP seja com entrega restrita pelos correios (Área de risco, rural, não tem entrega domiciliar,...), poderia continuar o cálculo mas exibir um aviso que podem haver alterações na entrega por X motivos dos Correios.

Para solucionar isso, alterei o arquivo app/code/community/PedroTeixeira/Model/Carrier/CorreiosMethod.php linha 174:
if($errorId != 0){
para:
if($errorId != 0 && $errorId != 10){

E assim ignora o erro (cod. 10) quando se tratar de CEP com restrição, continuando o cálculo normalmente. O problema é que o usuário não fica sabendo que pode ter problemas na entrega.

Para saber mais sobre restrição de entrega:http://www.correios.com.br/para-voce/correios-de-a-a-z/areas-com-restricao-de-entrega-domiciliar

**Comment by brasofilo** [comment]
Oi @pedro-teixeira !
Não consigo encontrar no seu código qual chamada faz ao SIGEP pra saber se o CEP está em área de risco...
Pode me dar uma luz? Quero implementar isso no WooCommerce e até agora você foi o único que encontrei que sabe fazer isso :)
