### ISSUE TITLE
Template Rastreio

### ISSUE THREAD

**Issue by henriquemnr** [pedro-teixeira/correios#295]
Pessoal, algúem pode me detalhar como funciona a parte do e-mail que é enviado quando o tracking está ativo?

Qual template é usado? Consigo alterar?

Procurei algo e não achei.

Obrigado

**Comment by rafaelpatro** [comment]
_Sistema > Configuração > Email de Vendas > Comentários de Entrega_
![image](https://user-images.githubusercontent.com/13813964/28269464-87ba56a4-6ad8-11e7-9443-0207f375cbd5.png)

**Comment by henriquemnr** [comment]
@rafaelpatro ,

Para funcionar, basta habilitar a função no módulo e depois cadastrar o envio?

Ou é necessário fazer mais alguma alteração?

**Comment by rafaelpatro** [comment]
Sim, mas tem alguns detalhes que precisa saber.
Dá uma lida [neste post](https://github.com/pedro-teixeira/correios/pull/101#issue-96167891) e [neste outro](https://github.com/pedro-teixeira/correios/issues/170#issuecomment-231167266) para mais detalhes.

**Comment by henriquemnr** [comment]
@rafaelpatro obrigado pela ajuda. Consegui configurar 100%, mas ficou com um erro estranho.

Ele está monitorando e disparando os e-mails, mas ocorreu o seguite:
o cron está para rodar de 15 em 15 minutos.

Ao verificar que a encomenda saiu para entrega o sistema dispara o e-mail.

15 minutos depois, ele dispara o mesmo e-mail, informando que saiu para entrega... É isso mesmo o comportamento?

**Comment by henriquemnr** [comment]
Também não está sendo gravadas as informações na aba comentários.... Como apontado no post: #101

**Comment by rafaelpatro** [comment]
Não tenho certeza se entendi o problema.

O monitoramento automático só dispara o e-mail caso a situação da encomenda...

* Esteja entre as situações [listadas aqui](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L724)
e...
* Seja diferente da situação anterior (ocorreu alguma atualização)

Você pode [mudar aqui](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L1100) a frequência do monitoramento. Por padrão é 15 min.

**Comment by henriquemnr** [comment]
Então ele dispara somente nas situações apontas, mas dispara o e-mail a cada vez que o CRON roda...

Ou seja, ao mudar o status para Saiu para entrega, foi disparado o e-mail.

15 minutos depois, foi disparado novamente o e-mail
30 minutos depois, novamente e assim sucessivamente.

para resolver alterei o tempo do cron, mas queria deixa ela por volta de 60 minutos e não 4 horas como agora....

Sabe o que pode ter ocorrido?

Nos logs não marcou nada.

**Comment by rafaelpatro** [comment]
É provável que não esteja conseguindo salvar as informações após o rastreio.
Vai ter que verificar os logs _exception.log, system.log, cron.log_, e os logs do PHP (normalmente _/var/log/php_errors.log_).
Algum erro deve aparecer durante a execução do Cron.
