### ISSUE TITLE
Opções PAC e SEDEX com contrato não é exibida

### ISSUE THREAD

**Issue by fernandorp** [pedro-teixeira/correios#313]
Pessoa, boa tarde.
Fiz a configuração normalmente dentro do Magento e inclusive atualizei os serviços de envio pelo webservice, informando contrato, cartão de postagem, usuário e senha. Até assim tudo certo.

Mas seleciono o PAC e SEDEX com contrato na lista de serviços e nenhum deles aparecem na hora de fechar o pedido informando o CEP, aparece apenas a opção retirar na loja.

A opção Serviço por produto está desativada. 

Conseguem me ajudar?

Obrigado.

**Comment by rafaelpatro** [comment]
Conferiu se todos os produtos do carrinho estão com as dimensões e peso devidamente configurados? Atenção às unidades de medida!

Veja tb se há alguma informação no log do Magento.

**Comment by rafaelpatro** [comment]
Quais códigos de serviço está usando?

**Comment by fernandorp** [comment]
@rafaelpatro sim, as dimensões e peso estão corretos, tanto que o SEDEX e PAC sem contrato estão funcionando normalmente. Apenas o COM CONTRATO que não estão.
Estou utilizando os códigos 4162 e 4669

Alguém tem alguma ideia?

**Comment by rafaelpatro** [comment]
http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=CalcPrecoPrazo

Faz um teste nesse link, para saber se os serviços estão funcionando para o seu contrato.

**Comment by fernandorp** [comment]
Ele só me retorna esse erro:

System.ArgumentException: Cannot convert  to System.Int32.
Parameter name: type ---> System.FormatException: Input string was not
in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options,
NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style,
NumberFormatInfo info)
   at System.Convert.ChangeType(Object value, Type conversionType,
IFormatProvider provider)
   at System.Web.Services.Protocols.ScalarFormatter.FromString(String
value, Type type)
   --- End of inner exception stack trace ---
   at System.Web.Services.Protocols.ScalarFormatter.FromString(String
value, Type type)
   at System.Web.Services.Protocols.ValueCollectionParameterReader.Read(NameValueCollection
collection)
   at System.Web.Services.Protocols.HttpServerProtocol.ReadParameters()
   at System.Web.Services.Protocols.WebServiceHandler.CoreProcessRequest()



Em 11 de setembro de 2017 12:10, Rafael Patro <notifications@github.com>
escreveu:

**Comment by rafaelpatro** [comment]
Manda um print do formulário preenchido. Provavelmente está informando algum campo errado.

**Comment by fernandorp** [comment]
![captura de tela 2017-09-11 as 12 49 15](https://user-images.githubusercontent.com/31701152/30289727-79105dd6-9703-11e7-930c-455d2810ba18.png)
Segue anexo.

**Comment by rafaelpatro** [comment]
Precisa preencher todos os campos.
Pode preencher assim...

formato: 1
diametro: 0
mão própria: N
valor declarado: 0
aviso recebimento: N

**Comment by fernandorp** [comment]
Funcionando normalmente.

<Servicos>
<cServico>
<Codigo>4162</Codigo>
<Valor>18,07</Valor>
<PrazoEntrega>1</PrazoEntrega>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,00</ValorValorDeclarado>
<EntregaDomiciliar>S</EntregaDomiciliar>
<EntregaSabado>S</EntregaSabado>
<Erro>0</Erro>
<MsgErro/>
<ValorSemAdicionais>18,07</ValorSemAdicionais>
<obsFim/>
</cServico>
</Servicos>
</cResultado>

**Comment by fernandorp** [comment]
![captura de tela 2017-09-11 as 17 40 44](https://user-images.githubusercontent.com/31701152/30295824-5d4731d2-9718-11e7-9b9c-e03f72bf3ff7.png)

**Comment by fernandorp** [comment]
![captura de tela 2017-09-11 as 17 42 06](https://user-images.githubusercontent.com/31701152/30295883-919c8c34-9718-11e7-9fa1-6f0b79bd3eca.png)

**Comment by fernandorp** [comment]
Funcionoooou... rs!!! 
@rafaelpatro era um dado que estava errado, mude para os dados que utilizei no teste e funcionou na hora. hehehehehe...

Obrigado pela ajuda pessoal.

Abraço.
