### ISSUE TITLE
Ativar Monitoramento das Encomendas

### ISSUE THREAD

**Issue by radamiBR** [pedro-teixeira/correios#319]
Recebi usuário e senha do gerente da minha conta do Correios o SRO, coloquei no arquivo config.xml, agora estou vendo as movimentação das encomenda em rastreamento dos correios, funcionou.

Mas não esta atualização no comentários do pedido do cliente a movimentação da encomenda.

Esta habilitado SIM em "Ativar Monitoramento das Encomendas".

Como faço para a movimentação do rastreamento modificar o status do comentário do pedido do cliente e enviar e-mail para cliente como o texto que esta em "Ativar Monitoramento das Encomendas".

**Comment by rafaelpatro** [comment]
Bom dia @radamiBR 
Não sei se entendi a pergunta, mas para monitorar um pedido, este deve estar com status _Pedido em Transporte_.

**Comment by radamiBR** [comment]
Uso status pedido enviado - estado titulo complete.
Na relação do status do pedido no magento não tenho "pedido em transporte" tenho que criar e colocar qual estado do titulo.

**Comment by rafaelpatro** [comment]
A criação desse status é realizada pelo módulo. Consta em todas as versões e atualização, há mais de 2 anos.

Se o status realmente não existir, é possível que alguém tenha removido manualmente, na tela de configuração de status do Magento. Ou vc tenha passado por algum problema durante as atualizações do módulo.

De toda forma, vc ainda pode criar o status manualmente. É só cadastrar 2 status, com as seguintes características:

Nome: _Pedido em transporte_ (ou qualquer outra coisa)
Código: _complete_shipped_
Estado: _complete_

Nome: _Dificuldade de entrega_ (ou qualquer outra coisa)
Código: _complete_warned_
Estado: _complete_

**Importante! Nenhum destes status deve ser atribuído como padrão.**
Para que a encomenda seja monitorada, basta deixar o pedido em algum desses status acima. Assim q a encomenda for entregue, o pedido é colocado automaticamente no status _Transação Concluída_, e o monitoramento não é mais realizado.

**Comment by radamiBR** [comment]
Funcionou.
Muito obrigado rafaelpatro.

**Comment by radamiBR** [comment]
o que pode ser? obrigado

**Comment by rafaelpatro** [comment]
Bom dia @radamiBR 
Certeza que o status do pedido está como _Pedido em Transporte_?

**Comment by radamiBR** [comment]
Bom dia @rafaelpatro 

Sim, coloquei o pedido com o status "pedido em transporte" não alterou o status do rastreamento dos correios, seque print do status: https://imgur.com/a/NlK2X

**Comment by rafaelpatro** [comment]
Talvez seu Cron não esteja rodando. Consegue verificar isso?

**Comment by radamiBR** [comment]
Configuração do cron no magento:

Tarefas Agendadas do Cron – em minutos
Agendar execução = 1
Agendar com antecedência para = 1
Perdido se não rodar com = 15
Limpar histórico = 120
Histórico de Execução = 120
Falhas na Execução = 120

No cron executado pelo Cpanel esta dando essa informação:
Failed loading /opt/ioncube/ioncube_loader_lin_5.6.so:  /opt/ioncube/ioncube_loader_lin_5.6.so: cannot open shared object file: No such file or directory
Content-type: text/html; charset=UTF-8
<br />
<b>Fatal error</b>:  Call to undefined function simplexml_load_file() in <b>/home/XXX/public_html/app/Mage.php</b> on line <b>767</b><br />

error_log
America/Sao_Paulo] PHP Fatal error:  Call to undefined function simplexml_load_file() in /home/XXX/public_html/app/Mage.php on line 767

**Comment by rafaelpatro** [comment]
Então, aparentemente seu Cron está com problemas. Sugiro ajustar isso, pois algumas outras funcionalidades do Magento também precisam do Cron.

O erro parece estar relacionado ao Ioncube, recurso muito utilizado pela Cerebrum. Se for isso, vc tem algum módulo Mozg em conflito com seu sistema. Pode tentar resolver o conflito; ou desativar o(s) módulo(s), e o Ioncube.

**Comment by radamiBR** [comment]
@rafaelpatro na relação dos módulos instalados não tenho Cerebrum e Mozg.

Seque link do print dos módulos que tenho instalados e desativados no magento 1.9.0.1

https://imgur.com/a/ZNL2h

**Comment by rafaelpatro** [comment]
@radamiBR, provavelmente algum desses módulos usa o IonCube.
Mas estou apenas chutando algumas possibilidades. O erro que enviou não diz muita coisa. Talvez n seja nada disso.
Talvez seja melhor contatar o seu host para averiguar o erro

**Comment by radamiBR** [comment]
@rafaelpatro, entrei em contato com servidor foi feito ajuste no PHP para usar IonCube, os pedidos com status Pedido em Transporte esta sendo enviado e-mail para clientes, mas não alterou status do pedido dos clientes, o que poder ser? obrigado

**Comment by rafaelpatro** [comment]
@radamiBR, se os emails são enviados, e o status do pedido não é
modificado, talvez esteja ocorrendo algum erro durante a execução do
monitoramento.

Vc consegue enviar o arquivo de logs do Magento? Normalmente fica em
/www/var/log/system.log

É bom desativar o monitoramento nas configurações do módulo. Se for isso
mesmo, os clientes q já receberam a encomenda podem acabar vendo uns 70
e-mails por dia.

Manda o log, se for o caso eu envio uma correção rápida.

Em seg, 16 de out de 2017 10:30 AM, radamiBR <notifications@github.com>
escreveu:

**Comment by radamiBR** [comment]
@rafaelpatro no magento não tem o status Transação Concluída e os status que esta em"Pedido em transporte" estão ficando sem status depois da entrega dos correios, qual o código e estado para criar "Transação Concluída" pois no meu não tem esse status.

Seque link do system.log do magento: https://drive.google.com/file/d/0B6XBH6LZw-HdVmRVMEtjODQwc00/view?usp=sharing

Obrigado.

**Comment by rafaelpatro** [comment]
Isso depende do módulo de tradução do Magento.
No meu caso, o status _complete_ padrão é _Transação Concluída_. No seu caso é _Pedido Enviado_.

E pelo que pude ver no log, seu processo de monitoramento está executando sem nenhum erro aparente. A mensagem no final é _No tracking updates_. Ou seja, o status das encomendas n mudou nos últimos 15 min, e por isso n enviou e-mail.

O estranho é q a maioria das encomendas está entregue, e deveria constar como _Pedido Enviado_.
Verifica se seu arquivo _config.xml_ está de acordo com o repositório aqui.

**Comment by radamiBR** [comment]
@rafaelpatro fiz alguns ajustes no magento agora esta alterando o status do pedido quando movimento do rastreamento dos Correios.

O que não altera e o status do comentário, fiz copia CC para admin, recebo o e-mail da movimentação do correios.

**Comment by rafaelpatro** [comment]
Sim. Esse problema do status do comentário é conhecido. Isso ocorre pois o comentário/e-mail são enviados antes de salvar o status do pedido. Dá pra corrigir isso no arquivo Sro.php.

**Comment by radamiBR** [comment]
Ok, que local do arquivo Sro.php tem que corrigir para salvar no status do comentário a movimentação do correios. obrigado

**Comment by radamiBR** [comment]
no arquivo Sro.php na linha public function getComment($obj)

**Comment by radamiBR** [comment]
@rafaelpatro verifiquei e alterei algumas parte do Sro.php e não tive sucesso não registrou no comentário do status do pedido, tem alguma ideais. obrigado

**Comment by rafaelpatro** [comment]
@radamiBR só esclarecendo que a situação do objeto é registrada nos comentários da entrega (não do pedido). Se quiser algo diferente, terá q modificar o código.

Reescrevi o _Observer.php_ para salvar os pedidos, escrever nos comentários da **entrega**, e só então enviar os e-mails.

```php
<?php

/**
 * This source file is subject to the MIT License.
 * It is also available through http://opensource.org/licenses/MIT
 *
 * @category  PedroTeixeira
 * @package   PedroTeixeira_Correios
 * @author    Pedro Teixeira <hello@pedroteixeira.io>
 * @copyright 2015 Pedro Teixeira (http://pedroteixeira.io)
 * @license   http://opensource.org/licenses/MIT MIT
 * @link      https://github.com/pedro-teixeira/correios
 */
class PedroTeixeira_Correios_Model_Observer
{
    /**
     * Look for shipped trackings, and send notifications if available and enabled
     * 
     * @return string
     */
    public function sroTrackingJob()
    {
        $message = "SRO Tracking Job disabled.";
        if (Mage::helper('pedroteixeira_correios')->getConfigData('sro_tracking_job') == 0) {
            return $message;
        }
        
        $message = "Nothing to track";
        $count = 0;
        $countTrack = 0;
        $trackList = array();
        $sro = Mage::getModel('pedroteixeira_correios/sro')->init();
        $response = $sro->request();
        
        if ($response && $response->return->qtd > 0) {
            $tracksTxn = Mage::getModel('core/resource_transaction');
            $ordersTxn = Mage::getModel('core/resource_transaction');
            $shipmentsTxn = Mage::getModel('core/resource_transaction');
            foreach ($response->return->objeto as $obj) {
                if (isset($obj->erro)) {
                    Mage::log("{$obj->numero}: {$obj->erro}");
                    continue;
                }
                
                if ($track = $sro->getTrack($obj)) {
                    $savedId = $track->getDescription();
                    $eventId = $sro->getEventId($obj);
                    if ($eventId != $savedId) {
                        $status = $sro->getStatus($obj);
                        $tracksTxn->addObject(
                            $track->setDescription($eventId)
                        );
                        $ordersTxn->addObject(
                            $track->getShipment()->getOrder()->setStatus($status)
                        );
                        $shipmentsTxn->addObject(
                            $track->getShipment()
                        );
                        
                        // Save SRO tracking info
                        $track->setSroNotify( $sro->isNotify($obj) );
                        $track->setSroComment( $sro->getComment($obj) );
                        $track->setSroMailComment( $sro->getEmailComment($obj, $track) );
                        $trackList[] = $track;
                        
                        Mage::log("{$obj->numero}: saving scheduled");
                        $count++;
                    }
                }
                $countTrack++;
            }
            
            if ($count) {
                try {
                    $tracksTxn->save();
                    $ordersTxn->save();
                    $shipmentsTxn->save();
                    // Send tracking information by e-mail
                    foreach ($trackList as $track) {
                        $track->getShipment()
                            ->addComment($track->getSroComment(), $track->getSroNotify(), true)
                            ->sendUpdateEmail($track->getSroNotify(), $track->getSroMailComment());
                    }
                    $message = "Updated {$count} objects of {$countTrack} tracked.";
                } catch (Exception $e) {
                    $message = $e->getMessage();
                }
            }
        }
        
        Mage::log($message);
        return $message;
    }
}
```

**Comment by radamiBR** [comment]
@rafaelpatro funcionou esta inserindo as informações da movimentação na entregas.
Que pena que não coloca no comentário do pedido.
Obrigado

**Comment by rafaelpatro** [comment]
Então @radamiBR, como o Pedido pode ter várias Entregas, achei que faria
mais sentido registrar a movimentação na aba da Entrega. Lembrando q também
fica registrado na aba Histórico.

Mas se preferir pode comentar no Pedido facilmente, com uma ou duas linhas
de código. Não deve impactar no funcionamento do módulo.

Em sáb, 28 de out de 2017 9:54 AM, radamiBR <notifications@github.com>
escreveu:

**Comment by rafaeldesio** [comment]
Boa tarde.
Desculpe se minha pergunta for muito básica, mas consigo fazer com p status Pedido em Trasporte seja o default para uma entrega criada?
Sei que não é exatamente do módulo, mas se puderem me ajudar...
Obrigado

**Comment by rafaelpatro** [comment]
Não faça isso! Se estiver com o monitoramento automático ativo, pode ter sérios problemas.
Essa alteração é possível, sim, mas precisa de alguns ajustes no Observer.php antes. Senão pode acabar enviando 40-50 e-mails pra cada cliente, em um único dia. Estou na correria agora, mas ainda neste final de semana, devo enviar uma PR.

**Comment by rafaelpatro** [comment]
Se não usa o monitoramento automático, aí tudo bem. É só configurar o status padrão lá no backend do Magento. Coisa simples.

**Comment by rafaeldesio** [comment]
Obrigado Rafael. A ideia seria para após a criação da entrega, já monitorar automaticamente
Muito obrigado 
Abraço

**Comment by filimm** [comment]
@radamiBR você disse que colocou as informações do SRO no config.xml. Em qual linha exatamente? Obrigado!
