### ISSUE TITLE
Rastreio de encomenda em branco

### ISSUE THREAD

**Issue by andretx** [pedro-teixeira/correios#320]
Olá, estou com um problema o rastreio de encomenda em branco, alguém já teve um problema parecido?

a única informação que aparece é o código de rastreio!
segue imagem
https://imgur.com/BoGNee5

 Magento versão. 1.9.3.6 
módulo correios na versão mais recente.
OBS: habilitei o log e não está gerando nenhum erro. nem warnings

desde já agradeço a ajuda.

**Comment by rafaelpatro** [comment]
Desde junho os Correios estão cobrando um usuário e senha próprios para o SRO (Sistema de Rastreamento de Objetos).
Veja se preencheu corretamente o usuário e senha no [arquivo de configuração](https://github.com/pedro-teixeira/correios/blob/fa8e96645b38b42e7eb0f3a2aff960b129ecffb9/app/code/community/PedroTeixeira/Correios/etc/config.xml#L567).

**Comment by andretx** [comment]
Ja fiz o contato com os correios recebi os dados de acesso. o calculo de frete funciona muito bem mais o rastreio ainda continua com o erro..

quando clico em atualizar serviços aparece a mensagem de erro  "Cant receive postmethods! A autenticacao de SISCOESPOR falhou!" 

já verifiquei a tabela "correios_postmethods" e está tudo certo, os serviços estão cadastrados na tabela
como dica do post  https://github.com/pedro-teixeira/correios/issues/224 
e nada até agora....

**Comment by rafaelpatro** [comment]
@andretx, o usuario/senha para rastreamento são diferentes do usuário/senha para cálculo de frete. Como mencionei antes, veja se preencheu corretamente o usuário/senha (para rastreamento) no arquivo de configuração.

**Comment by andretx** [comment]
Pois é @rafaelpatro  fiz as configurações com user e senha passados pelo próprio correios relacionados ao serviço SRO (Sistema de Rastreamento de Objetos). adicionei no arquivo de configurações como havia citado no post acima mas o problema persiste. 

aparece apenas o numero do rastreio no resultado como havia citado no primeiro post.

agradeço a ajuda...

senha SRO enviada pelos correios - ok
senha SRO adicionada ao config - ok
senha cálculo de frete - ok 
limpeza de cache - ok

**Comment by rafaelpatro** [comment]
Veja se aparece alguma informação nos logs do magento.

Em sex, 3 de nov de 2017 7:31 PM, André Teixeira <notifications@github.com>
escreveu:

**Comment by andretx** [comment]
@rafaelpatro  já ativei os logs de erros, e nada aparece. atualizei o magento para a sua versão mais recente removi todos os erros, versão mais recente do módulo e senhas adicionadas.

agora fiz um teste no rastreio. desativei o módulo e cliquei no "Rastrear seu pedido" e a tela continua em branco então conclui que esse rastreio não está trabalhando com o módulo em questão.

"frontend/base/default/template/shipping/tracking/popup.phtml"

até agora não consegui uma solução para o problema, mais agradeço a ajuda.

**Comment by andretx** [comment]
Será que tem algo relacionado ao status do pedido?

precisa seguir uma nomenclatura exata?

**Comment by rafaelpatro** [comment]
Mas vc olhou os arquivos de log? system.log, exception.log

Ao adicionar o código de rastreamento vc selecionou o módulo correto
pedroteixeira...?

Em sáb, 4 de nov de 2017 2:21 PM, André Teixeira <notifications@github.com>
escreveu:

**Comment by andretx** [comment]
Fala @rafaelpatro queria agradecer a ajuda.

recisei tudo de novo, o módulo, a instalação do magento, fiz uma limpeza de módulos inativos relacionados a envios.

Cheguei a conclusão com sua ajuda. estava testando um número rastreador que já estava cadastrado e ralacionado a outro módulo de Informação de Rastreamento como você mesmo havia citado acima.

refiz uma compra e um novo cadastro de numero de rastreio relacionado ao módulo do Pedro e agora funcionou perfeitamente.


valeu mesmo a ajuda.

**Comment by andretx** [comment]
Bom vou postar a minha solução para o meu problema...

Eu estava usando o módulo https://github.com/willstorm/correios logo após a atualização dos correios mudei para o módulo Pedro Teixeira. minha loja já tinha mais de 900 codigos de rastreios cadastrados e relacionados ao módulo willstorm.

para alterar  é só editar a tabela "sales_flat_shipment_track" no mysql.
```
UPDATE `sales_flat_shipment_track` SET `carrier_code` = 'pedroteixeira_correios'
WHERE `carrier_code` =  'correios'
```
Esse UPDATE executado em seu banco faz com que todos os códigos de rastreios funcionem com o seu novo módulo pedroteixeira_correios..

valeu pela ajuda @rafaelpatro

**Comment by marciomaitan** [comment]
Olá @andretx tudo bem?

Estava exatamente com o seu problema. Usava o módulo willstorm e mudei para o do Pedro teixeira.

Mesmo sem muito conhecimento rodei o comendo que você passou no mysql e ele mudou todos os rastreamentos e ficou ótimo, todos passaram a exibir o rastreamento.

Porém, os novos pedidos ainda assumem o rastreamento do willstorm no rastreamento.

Você tem idéia de como resolver isso?

Obrigado!!!!

**Comment by andretx** [comment]
Olá @marciomaitan  tudo na paz e ai? 

pois então você chegou a remover o módulo willstorm ? ou mesmo desativar ele usando em 
https://github.com/willstorm/correios/blob/master/app/etc/modules/Storm_Correios.xml#L14
> correios/app/etc/modules/Storm_Correios.xml

**Comment by marciomaitan** [comment]
Tudo em paz =)

Eu tinha deletado todos arquivos do módulo mas a parte administrativa da
loja parou de funcionar e não acessava mais... então voltei os arquivos.

Vou experimentar deletar apenas esse .xml então.

Muito obrigado!

Abs
Marcio

Em qua, 7 de nov de 2018 às 11:30, André Teixeira <notifications@github.com>
escreveu:

**Comment by andretx** [comment]
@marciomaitan  não precisa deletar só alterar o "true" para "false"

**Comment by marciomaitan** [comment]
Ceu certo! Muito Obrigado @andretx

**Comment by marciomaitan** [comment]
Vixi @andretx , não deu certo não. O Magento está assumindo "Valor personalizado" em forma de entrega. Como será que faz para o do Pedro Texeira voltar a ser o padrão? Abs

![captura de tela 2018-11-08 as 10 43 40](https://user-images.githubusercontent.com/44773369/48199731-2ef6af00-e344-11e8-9c2a-20f1aba8e9e4.png)

**Comment by andretx** [comment]
@marciomaitan  dificil opinar mais a fundo sem analisar o real problema.

o que eu faria era revisar se ainda existe algum modulo sobressalente ativo em seu sistema, verificar o processo de instalação e configuração novamente.

Sobre o print em quentão em "Informações de Entrega e Rastreamento" quando você clica no botão "Incluir rastreador"  você tem a opção de selecionar que forma de entrega será cadastrada para rastreio..

![rastreio](https://user-images.githubusercontent.com/12993580/48220862-937f3180-e377-11e8-8b6b-195de87144cc.png)

espero ter ajudado..
