### ISSUE TITLE
Problema Soap

### ISSUE THREAD

**Issue by kinfoxxx** [pedro-teixeira/correios#323]
Boa noite, estou com problema abaixo

Last seen at: | 01:00:09
-- | --
Id: | 2964086
Pid: | 26861
Servidor: | unix1.sagainternet.com.br
Mensagem:
TRIGGER: shutdown function Last error:  Array (     [type] => 1     [message] => Class 'SoapClient' not found     [file] => /var/www/clients/client4/web11/web/lib/Correios/Rastro.php     [line] => 15 )  Backlog:  exception 'Exception' in /var/www/clients/client4/web11/web/app/code/community/Aoe/Scheduler/Helper/GracefulDead.php:53 Stack trace: #0 [internal function]: Aoe_Scheduler_Helper_GracefulDead::beforeDyingShutdown() #1 {main}

Diz SOAP not found , porem esta instalado o Soap no servidor, o que pode ser? Alguém pode me ajudar

**Comment by rafaelpatro** [comment]
Bom dia @kinfoxxx
Veja se o cron inicia o PHP correto. Tenta testar a classe SoapClient em um arquivo separado, chamando a mesma linha de comando usada pelo cron.
Outra coisa, a mensagem diz *SoapClient* not found (talvez Soap e SoapClient possam ser configurados separadamente).

**Comment by kinfoxxx** [comment]
Bom dia @rafaelpatro , rapaz é para quebrar a cabeça isso, até sexta feira estava funcionado perfeito, segue o print do php 
![screenshot-2017-11-14 phpinfo](https://user-images.githubusercontent.com/19422479/32779098-a28e05f8-c923-11e7-8f7d-46d31ea75aae.png)

o Cron esta iniciando todos os processos perfeitamente, só os correios que não, será que pode ser a configuração do cron ? 

Sou meio leigo no assunto, como que eu testaria a classe SoapClient em um arquivo separado? 

Desde já obrigado

**Comment by rafaelpatro** [comment]
Exemplo: Pode criar um arquivo /var/www/teste.php
```php
<?php
if ($obj = new SoapClient()) {
    echo "Success";
} else {
    echo "Fail";
}
```
Depois execute usando o mesmo comando do cron (verificar: _crontab -e_).
`/usr/bin/php7.0 -f /var/www/teste.php`

**Comment by rafaelpatro** [comment]
O shell exibe o resultado na tela. Se já executou, e não apareceu _Success_, provavelmente falhou lançando uma exceção. Pra certificar, testa assim...
```php
<?php
try {
    if ($obj = new SoapClient()) {
        echo "Success";
    } else {
        echo "Fail";
    }
} catch(Exception $e) {
    echo $e->getMessage();
}
```

**Comment by kinfoxxx** [comment]
Boa noite, da o erro 

PHP Fatal error:  Class 'SoapClient' not found in /var/www/clients/client4/web11/web/teste.php on line 3

**Comment by kinfoxxx** [comment]
Boa noite, acho que achei o problema, o servidor tem 3 php instalado, um deles é o nativo 5.4.16 esse esta sem o soap, depois tem o 7.0 , estou rodando o magento no 7.0 esse esta com o soap, porem não sei o porque o magento verifica o soap do php nativo 5.4.16, pedi para o administrador do servidor para instalar o soap no php nativo, assim que ele instalar posto aqui se teve solução.

**Comment by rafaelpatro** [comment]
Tlavez não haja necessidade de reinstalar o PHP.
Digite _crontab -e_ pra ver a linha de comando do cron.
Provavelmente estará usando apenas _php_, quando deveria chamar _php7_.
Ex.:
```
* * * * * php -f /var/www/cron.php

**Comment by kinfoxxx** [comment]
Bom dia @rafaelpatro  , deu certo, isso mesmo chamei o php70 no cron, obrigado mesmo pela paciência.

**Comment by kinfoxxx** [comment]
Bom dia, coloquei php70 na chamada do cron o cron funcionou porem mesmo erro, o pessoal da hospedagem instalou o soap no php nativo e deu certo, não sei o porque puxa o php nativo se não esta setado ele.
