### ISSUE TITLE
Valores Carta Registrada para pessoa Juridica

### ISSUE THREAD

**Issue by acm-junior** [pedro-teixeira/correios#329]
Olá, Boa noite! Nós utilizamos o modulo e funciona tudo perfeitamente, o único probleminha que temos e relacionado a carta registrada, pois como somos pessoa juridica (com contrato) o valor que vem no modulo nao e o mesmo que pagamos. Pois carta registrada para pessoa juridica tem tarifas mais caras do que para pessoa fisica. Como muitas vezes temos que enviar por carta registrada, gostaria de saber se tem como alterar esses valores através do codigo ou uma tabela ou se conseguimos conectar com os valores da carta registrada da pessoa juridica dos correios, a gente estava utilizando a opção de taxa de postagem do modulo para tentar amenizar, porem ele tambem adicionava essa taxa ao sedex e pac o que deixava mais caro... voces poderiam me ajudar? obrigado.

**Comment by acm-junior** [comment]
Complementando a duvida acima, o prazo por carta registrada tambem fica sempre o mesmo sendo de 5 dias uteis para qualquer estado, de RJ até Amazonas, o que teoricamente tambem nao seria certo, como somos do RJ um envio por carta registrada para o RJ e bem mais rapido do que para o Amazonas, ou pará por exemplo, existe alguma forma de corrigirmos isso tambem? obrigado.

**Comment by rafaelpatro** [comment]
A cotação de Carta não é oferecida pelos Correios, mas pela  própria extensão. Os valores e prazos podem ser alterados no arquivo etc/config.xml. É possível tb incluir novos serviços, com diferentes valores e prazos.

**Comment by acm-junior** [comment]
Muito obrigado @rafaelpatro! Melhor ainda sendo assim que conseguimos configurar manualmente, muito obrigado mesmo pela dica e pelo rapido retorno, vai nos ajudar bastante =)

**Comment by acm-junior** [comment]
Ah @rafaelpatro , preciso de uma outra ajudinha se voce puder, nao estou conseguindo restringir o envio por carta registrada para determinado produto se o peso for dentro do limite. Como eu faço para nao aparecer a carta registrada para determinado produto mesmo que ele se enquadre nos pesos e medidas possiveis para a carta registrada? Na diçao/criaçao dos produtos tem o menu"correios" com a opção "Serviços de Entrega" que lista, tentamos selecionar por ali mais nao adiantou tambem... tentamos criar um atributo novo para depois no codigo usar um "if" ou alguma forma de restriçao mas tambem nao adiantou... voce tem algum ideia de como posso fazer para determinado produto nao aparecer a opçao de carta registrada, mesmo ele estando no peso possivel? obrigado...

**Comment by rafaelpatro** [comment]
Para restringir um serviço que não existe é preciso cadastrar manualmente na tabela de serviços (acho q é correios_methods). Só então o serviço deve aparecer na tela de edição do produto.

Nas configurações do módulo, mantenha todos os serviços q quer trabalhar selecionados. Ative a opção de Filtrar Serviços por Produto. E edite cada produto com os serviços q quer em cada um.

Lembrando q os limites de peso e dimensões tb devem ser respeitados. No caso da Carta (serviço customizado), vc tb pode alterar os limites no arquivo /etc/config.xml

Enfim dá pra fazer td q vc quer, sem alterar qqr código PHP.

**Comment by acm-junior** [comment]
Obrigado Rafael, deu certo o que queriamos fazer, ativando esse botao filtrar serviços por produto. Porem ocorre um bug quando a gente exporta a planilha de produtos para atualizar estoque o campo postmethod sai vazio quando tem mais de uma opção selecionada, quando tem uma opçao so escolhida ele aparece com a opção... como fazemos para atualizar na planilha de importação para adicionar por exemplo pac, sedex e carta registrada pois ele so deixa enviar um campo? existe alguma forma? a gente tentou exportar as 3 separando por virgula mas ao conferirno páinel de controle so apareceu uma ou 2 selecionadas...

**Comment by acm-junior** [comment]
Olá @rafaelpatro outro bugzinho que reparei que voce pode me ajudar aonde alterar, consegui manualmente pelo painel adicionar as 3 formas para os produtos, carta registrda, sedex e pac... porem o que ocorre e que nos pedidos abaixo de 20,00 so aparece na estimativa do site carta registada como opção, o sedex e o pac so aparece na estimativa acima de 20 reais, mesmo estando todos 3 selecionados, nao tem haver com a largura,peso, nem nada assim, acredito que em algum lugar tenha essa opção para modificar pois ta limitando ao valor de 20,00 as formas que fazem contato com webservice do correios.. vou te dar um exemplo eu coloco um produto X com 3 quantidades que da 15,00 so aparece a opçao por carta registrada, se eu colocar 4 quantidades desse produto dando 20,00 aparece sedex pac e carta registrada... agora se eu adicionar no carrinho somente uma unidade de um outro produto Y com as mesmas especificaçoes de peso, etc.. porem com o valor de 25,00 aparece as 3 opções normalmente... estranho, voce pode me ajudar por favor???

**Comment by rafaelpatro** [comment]
Na tela de configurações do módulo há 3 campos para as medidas mínimas. Veja se estão corretamente preenchidos. Acho q é 16 x 11 x 2 cm.
Veja tb se está configurado o valor mínimo para o carrinho no magento.

**Comment by rafaelpatro** [comment]
Quanto a exportação, não sei qual módulo de importar/exportar está usando, mas há uma forma bem específica de buscar esse tipo de atributo no magento. Se der uma olhada no código vai entender como faz pra buscá-lo.

**Comment by acm-junior** [comment]
Oi Rafael, sobre as medidas minimas ja testei com o padrao (16x11x2) e tambem ja testei desativando a opçao "validar dimensões do produto" pois nesse caso desativando essa opçao ele baseia o valor do frete somente no peso correto? nao importa as dimensões... E isso que faz essa opção?
tambem o valor minimo ta configurado certinho.. o estranho que ele limita a partir de 20 reais para aparecer pac e sedex, nao importa se eu colocar 1 ou 100 produtos, se tiver abaixo de 20 reais nao aparece... voce nao tem ideia do que possa ser? no modulo tem algum valor de pedido minimo pre configurado para aparecer as opçoes de pac e sedex, qeu se comunicam com o webservice dos correios?
sobre importar/exportar uso o método do próprio magento...

**Comment by acm-junior** [comment]
@rafaelpatro

**Comment by rafaelpatro** [comment]
@acm-junior , veja se [essa variável](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L144) está com o valor correto 16 cm.
Mantenha a validação de dimensões desativada.
Envie o log do seu teste, pra eu dar uma olhada.

**Comment by acm-junior** [comment]
Oi @rafaelpatro obrigado pela resposta, no caso esta certinho sim a variavel no padrao correto... para tentar exemplificar o que to te falando vou mandar um exemplo abaixo, essa imagem por exemplo o pedido da 15,00 so aparece a opçao de careta registrada

![image](https://user-images.githubusercontent.com/35156953/34731819-9d066d8e-f54a-11e7-8788-ed8494482ad4.png)

ja quando ultrapassa o valor de 20,00 , aparecem todas as opçoes como essa imagem abaixo, o estranho que isso e para todos os produtos e nao importa quantidade, so o valor...

![image](https://user-images.githubusercontent.com/35156953/34731788-817de1b4-f54a-11e7-8696-298eb3da3746.png)

No caso como eu posso fazer para te mandar o log quando "estimo" o frete? aonde eu pego ele?
obrigado

**Comment by rafaelpatro** [comment]
O log normalmente fica em /var/log/system.log
Vc tb pode acessá-lo via SSH e monitorar pelo comando a seguir.

tail -f /var/log/system.log

...com o console aberto, realize uma cotação, e printa o resultado aq.

Pra subir algo aq é só arrastar com o mouse msm.

**Comment by acm-junior** [comment]
Oi @rafaelpatro , nao sei se fiz certo, mas fica aparecendo somente essa mensagem abaixo enquanto atualizava a estimativa com 15 reais e com mais de 20 reais para aparecer as outras opções..

![image](https://user-images.githubusercontent.com/35156953/34776318-9d861a30-f5fd-11e7-94d4-cd0e128783ac.png)

Esse arquivo abstract.php que ele fala na imagem, na linha 776 aparece o seguinte codigo:

![image](https://user-images.githubusercontent.com/35156953/34776391-defb5480-f5fd-11e7-98b5-979e02aa1091.png)

No log, teve um momento que apareceu isso tambem, mas nao sei se tem haver quando eu coloquei no carrinho de compras:

![image](https://user-images.githubusercontent.com/35156953/34776509-5844c0ec-f5fe-11e7-90ed-9ad5219f146b.png)

No arquivo Exception.log, apareceu tambem uma mensagem estranha de email do zend protocol, sei que nao deve ter muito haver, mas pode esta ligado, voce teria ideia do que possa ser:

![image](https://user-images.githubusercontent.com/35156953/34776677-cf29c216-f5fe-11e7-8448-2be9f9cd2101.png)

Desculpe essa mensagem longa, mas realmente sua ajuda vai ser muito importante para a gente conseguir adaptar o moldulo...

obrigado.

**Comment by acm-junior** [comment]
@rafaelpatro  desculpe, exclui ate minha ultima mensagem pois depois que postei vi que nao tinha nada haver rsrs...  Sobre o erro que so aparece o sedex e pac acima de 20 na verdade e acima de 18, descobrimos o que é! Fazendo o debug normal nao aparecia nada pois aparecia o metodo da carta registrada, mas quando tirei a carta registrada e deixei so o sedex e pac, apareceu a mensagem no debug!

![image](https://user-images.githubusercontent.com/35156953/34778839-9e2ca6a4-f605-11e7-9d77-ae080d7139e5.png)

como eu utilizo o serviço de valor declarado (marcando aquela opçao) ele limita o valor minimo de 18,00 quando desmarcamos a variavel ele funcionou normalmente aparecendo todas as opçoes de envio nao importando o valor, uhuuul =)
Mas gostaria de manter o valor declarado, Tem algum lugar que eu diminua essa variavel no codigo? Ou ela e automatica com webservice dos correios
Muito origado pela ajuda!!

**Comment by rafaelpatro** [comment]
Esse valor mínimo  de 18 reais é uma regra dos Correios. Pra ser sincero eu nem lembrava que havia essa restrição. Mas realmente existe. E o valor pode variar conforme a modalidade do serviço. Terá q consultar os Correios para saber mais detalhes.

Para contornar esse problema vc terá q realizar uma pequena alteração no código, onde é atribuído o valor declarado. Ou então pode desativar o valor declarado.

**Comment by acm-junior** [comment]
Muito obrigado @rafaelpatro pela ajuda e toda atenção, nós desativamos mesmo o valor declarado para funcionar, nao tem problema.. Agora ta rodando tudo certinho! valeu mesmo! =)

**Comment by rafaelpatro** [comment]
Pois eh, pensando bem nem vale a pena declarar valor para itens de baixo valor. A indenização dos Correios é de 50 reais.
