### ISSUE TITLE
Dimensões dos produtos fora do permitido pelos Correios

### ISSUE THREAD

**Issue by brazzil** [pedro-teixeira/correios#33]
O frete não é calculado quando é necessário "Validar Dimensões dos Produtos".  Sempre que calculo o envio retorna "Dimensões dos produtos fora do permitido pelos Correios", sendo que as dimensões informadas do produto são 12 x 15 x 20. Se desabilito "Validar Dimensões dos Produtos" o frete é calculado normalmente. Ja atualizei e cache, index mas não funciona. Instalei a versão mais recente e é uma instalação nova do magento e sem outras extensões instaladas.  Alguma luz?

Grato!

**Comment by jeanmorrison** [comment]
Estou com o mesmo problema, ja coloquei a altura de 5cm largura com 25cm e comprimento de 35cm e nao adianta persiste em aparecer este erro, já coloquei também as medidas minimas e nao funciona, podem me dar uma ajuda porque nao sei mais o que fazer. 

Obrigado.

**Comment by rafaelpatro** [comment]
No arquivo config.xml, veja se existe as tags de validação para seu código de serviço.

validate > serv_04162

**Comment by jeanmorrison** [comment]
Arquivo config do seguinte diretorio? app/etc/config.xml?

Se for nao tem essa validação

**Comment by rafaelpatro** [comment]
app/code/community/PedroTeixeira/Correios/etc/config.xml

**Comment by jeanmorrison** [comment]
Tinha encontrado esse diretorio e nao tem o validate > serv_04162 amigo

**Comment by rafaelpatro** [comment]
Então precisa adicionar. Dá uma olhada nas outras regras e copia.
