### ISSUE TITLE
Correios Instável ai ?

### ISSUE THREAD

**Issue by marcospaf** [pedro-teixeira/correios#331]
Aqui volta e meia o modulo exibe - Esse método de envio está fora do ar. Por favor entre em contato conosco.

está acontecendo por ai?

**Comment by ZamoraSOFT** [comment]
Olá **marcospaf**.

Sim, bastante instável o dia todo. Continua instável ainda, inclusive.

**Comment by marcospaf** [comment]
Tá uma merda e perdendo vendas , mas já resolvi !

Instalei aquela  app da frenet , mas tem muito bug no prazo de entra , mas pelo menos calcula. 

E acabei de testar o Correios OFFLINE da AVG5 - cara o site fica um foguete ! calculando offline , testei no meu site espelho , está perfeito !! demorou um pouco para baixar as tabelas , quero até comprar o light que custa R$ 150,00 ou o PRO  , mas o WhatsApp do desenvolvedor só de segunda a sexta. Chega de sofrer , vou por este ai, o offline FUNFA mesmo

Eu acho que é uma alternativa válida , não tem como ficar dependendo do webservice mais.

**Comment by fchiqueto** [comment]
Tá sempre caindo esse sistema dos Correios, @marcospaf você conseguiu instalar sem problemas o da AV5 já tentei uma vez mais não cotava o PAC 😑

Essa funcionabilidade não teria como implantar no do Pedro?

**Comment by marcospaf** [comment]
cara eu instalei hj o grátis off-line , demorou para baixar as planilhas .

Eu simulei direto aqui , calculou e que nem um foguete.

Ontem eu perdi vendas , porque esta bosta ficava dando que não tinha forma de envios disponíveis , mas hj ele simplesmente parou o webservice.

Instalei o freenet, mas ele apesar de calcular tem problemas com prazo de entrega , exibe valores doidos .

Eu acredito que o AV5 saiu do modulo do pedro Teixeira , porque o painel de configuração é praticamente o mesmo , ta rodando filé o off-line . Demorou pacas para baixar a planilha , mas já testei com vários fretes e calcula muito rápido

**Comment by fchiqueto** [comment]
Eu vou testar também, acredito que esse módulo não rastreie os pedidos igual do Pedro né?

**Comment by marcospaf** [comment]
A gratuita não , mas as pagas fazem isso

**Comment by ZamoraSOFT** [comment]
Pessoal, virou meia noite agora e está uma bala o Webservice. Por aí também?

**Comment by marcospaf** [comment]
agora voltou né

**Comment by marcospaf** [comment]
Eu cansei destes correios , comprei o modulo PRO da Av5 , o modulo do pedro e show , os correios que são um lixo, to cansado  mesmo.  Lixo e cheio de exigências.
Depois que eu testar dou um toque aqui . valeu

**Comment by marcospaf** [comment]
@fchiqueto , o modulo pro tem isso 

Módulo Magento AV5 Correio Offline PRO
Mantenha a tabela de preços dos serviços Correios dentro da sua loja, agilizando o tempo de cálculo de fretes e não perdendo mais vendas com a indisponibilidade dos serviços de cálculos dos Correios. O módulo AV5 Correios Offline PRO oferece também um painel de regras especiais para frete grátis, prazos de entrega especiais por faixa de CEP, desconto especial por faixa de CEP atribuído por valor fixo ou percentual, acréscimo especial por faixa de CEP atribuído por valor fixo ou percentual, com prazo de validade.
Características:
Serviços Correios suportados
Sedex
e-Sedex
Sedex 10
Sedex à Cobrar
PAC

Aceita contratos
Suporte a multisite e multilojas
Tratamento de áreas de risco
Particionamento de pacotes: Caso o peso do pacote seja maior que o peso limite permitido pelos Correios, o módulo irá particionar o pacote em vários pacotes e mostrar o valor da soma desses envios.
Regras de frete grátis
Painel de regras com
Agendamento (Data início e fim)
por faixa de CEP
por produtos
por categorias
Desconto por valor fixo ou percentual
Acréscimo por valor fixo ou percentual
Prazo de entrega personalizado

Atualização das tabelas de preços via CRON
Três modos de operação:
Apenas Online: nesse modo apenas a comunicação com os webservices dos Correios fica ativa, porém a cada nova consulta a tabela de preços offline é atualizada automaticamente;
Apenas Offline: nesse modo apenas a tabela de preços offline é usada. A atualização da tabela pode ser feita de forma manual ou via CRON
Automático (recomendado): nesse modo de operação a comunicação com os webservices dos Correios fica ativada por padrão, mas ao detectar a indisponibilidade do serviço o módulo automaticamente ativa o modo offline e exibe os preços registrados na tabela offline. A cada nova consulta a tabela de preços é atualizada automaticamente.

**Comment by marcospaf** [comment]
Eu aproveitei e perguntei sobre os novos códigos , está operando com os novos códigos e as tabelas do pro estão atualizadas para os novos critérios dos correios.

Eu falei para ele sobre a carta registrada , ele vai atualizar tb.

eu vou testar pra valer no meio da semana , ai vou avisando.

**Comment by InsomniumBR** [comment]
Aqui está uma porcaria hoje os Correios também.
Vou testar hoje a tarde o módulo sugerido pelo @marcospaf 
Não entendi bem ainda como ele baixa "todas as tabelas" usando contrato, e também não entendi bem o modo automático dele. Porque se ele verificar toda ver se está no ar o serviço, não irá demorar da mesma forma?

**Comment by marcospaf** [comment]
@InsomniumBR  cara para baixar as tabelas que são fodas , demora para cassete. rs

mas já baixei boa parte

**Comment by InsomniumBR** [comment]
@marcospaf aqui foi rápido até, só baixei uns 3 tipos de serviço dos correios, coisa de 10 min tava tudo pronto.

**Comment by phsilvaalves** [comment]
Pessoal o módulo parou de calcular aqui, vcs sabem se o problema com os Correios voltou?
