### ISSUE TITLE
Produto em Bundle / Pacote não calcula corretamente

### ISSUE THREAD

**Issue by redbio** [pedro-teixeira/correios#338]
Olá criei um kit usando pacote de produtos (Bundle Product). 

Fiz toda a configuração correta, adicionei um prazo maior de entrega e adicionei as medidas do kit e o peso. Marquei em peso fixed. Porém o calculo sai totalmente errado, tanto no prazo quanto em preço. 

Poderia me ajudar? Se estiver corrido indica só em qual arquivo é feito o calculo que tento olhar.

**Comment by redbio** [comment]
Olá pessoal resolvi aqui desabilitando o _loadBundleChildren em CorreiosMethod.php isso faz com que seja usado os pesos, prazo do bundle e não dos itens do bundle. 

Me corrijam se fiz errado.

**Comment by rafaelpatro** [comment]
Sim, é uma solução válida!
Desde a versão 4.9 os atributos de envio (altura, largura, etc) são habilitados apenas para produtos simples e agrupados.
Mas realmente, isso é uma particularidade de cada negócio. No meu caso, prefiro pegar os valores dos produtos simples.
Talvez a melhor forma de lidar com isso seja criar uma opção para ativar/desativar esse método __loadBundleChildren_.

**Comment by redbio** [comment]
@rafaelpatro  É verdade melhor saída estou adicionando uma opção para ativar e desativar.
