### ISSUE TITLE
Undefined property: stdClass::$evento

### ISSUE THREAD

**Issue by redbio** [pedro-teixeira/correios#339]
Notice: Undefined property: stdClass::$evento  in /var/www/html/mdagames.com/public_html/app/code/community/PedroTeixeira/Correios/Model/Sro.php on line 184

Alguém pode me ajudar com erro ? Alguma coisa relacionada com o tracking quando roda o cron.

**Comment by rafaelpatro** [comment]
@redbio, essa mensagem não chega a caracterizar um erro. É apenas um _notice_, provavelmente por causa de alguma inconsistência no rastreamento de uma das encomendas. Talvez alguma encomenda esteja com o código incorreto, ou com algum espaço, ou caractere em inválido, etc.

**Comment by redbio** [comment]
@rafaelpatro  Valeu Rafael pensei que poderia ser um erro, realmente tem pedidos com problemas. 

Obrigado pelo retorno.
