### ISSUE TITLE
Problema de peso nos produtos configuráveis 

### ISSUE THREAD

**Issue by emanoelqueiroz** [pedro-teixeira/correios#34]
Quando o produto é configuravel aparece o seguinte erro: 

**Lojista: O peso do produto deverá ser maior que zero. Se você está usando a media de peso como gramas, o peso mínimo é de 10 gramas.**

Penso que ele tenta pegar o peso do produto configuravel e não da opção selecionada.

Obrigado.

**Comment by thiagoromera** [comment]
Brother, tudo bem?
Resolveu isso?

**Comment by Dimebag03** [comment]
Opa thiago, beleza?

Então, quando abri assa issue não tinha percebido que o problema não era o modulo do correios do pedro teixeira e sim em outro modulo que eu usava para exibir o frete na pagina do produto chamado 
Product Page Shipping da EcomDev.
Se você estiver usando esse modulo e esta com esse problema posso tentar te ajudar :smile:

**Comment by thiagoromera** [comment]
Sim, é este módulo que estou usando.
Eu resolvi o problema mas alterando os arquivos do módulo dos correios, fazendo com que fosse pego o peso do produto filho, trantando-se de um produto configurável, mas no módulo dos correios.
Como você resolveu?


Date: Wed, 18 Nov 2015 05:32:52 -0800

**Comment by Dimebag03** [comment]
Eu resolvi alterando o arquivo EstimateController do modulo ProductPageShipping.
A alteração que fiz na antiga empresa que eu trabalhava está aqui: https://github.com/Ceicom/EcomDev_ProductPageShipping/blob/master/app/code/community/EcomDev/ProductPageShipping/controllers/EstimateController.php

**Comment by thiagoromera** [comment]
Obrigado por compartilhar. Vou analisar e dou um FB
Abs

Date: Wed, 18 Nov 2015 06:55:08 -0800

**Comment by Dimebag03** [comment]
Vlw Thiago, abraço!

**Comment by RenanBrenio** [comment]
Valeu, Dimebag03!!
Resolveu aqui alterando esse arquivo o/

**Comment by Dimebag03** [comment]
É noix meu irmão! kkkkkk o/

**Comment by lanapf** [comment]
Olá, será que vocês podem me auxiliar. No meu caso instalei o módulo no meu site o mesmo está funcionando nos produtos simples mas nem aparece na página do produto configurável. Sabem como posso resolver isso?

**Comment by Dimebag03** [comment]
Bah cara, pior que não estou mais trabalhando com Magento e não lembro muito bem das paradas kkkk, talvez seja alguma configuração na pagina do produto se pá, qualquer coisa a mais que eu possa ajudar peça ai bixo

**Comment by lanapf** [comment]
Os produto configuráveis tem uma página diferente? o arquivo dele é diferente do arquivo dos produtos simples?

**Comment by Dimebag03** [comment]
Se não me engano é na página do produto mesmo, quando você cria o produto tem que setar umas opções (que não lembro kkkk) pra ele virar configurável e tals...

Se você desabilita o módulo aparece as opções do produto configurável?

@joridos Ajuda noix KKKKK

**Comment by lanapf** [comment]
O produto configurável está aparecendo normalmente, o módulo do frete na página do produto que só aparece nos produtos simples vou enviar o link do meu site você vê.

Produto Simples:
http://houseofrock.com.br/acessorios/lenco/lenco-azulmarinho.html
Produto Configurável:
http://houseofrock.com.br/masculino/daytoremember-rosa.html

No produto simples aparece e calcula o frete normalmente, no configurável nem aparece na página do produto. Fiz tudo conforme informando no link: http://referenciamagento.blogspot.com.br/2013/06/frete-na-pagina-do-produto.html

**Comment by Dimebag03** [comment]
1º - Eu lembro de ter passado por esse mesmo problema mas não lembro como resolver :/, vamos ficar na esperança que nosso amigo @joridos (mito das galaxias brasileiras em terras alienígenas) veja e nos ajude nesse problema.

2º - Me manda uma camiseta do Exodus de graça :smiley:

**Comment by lanapf** [comment]
huahuauhauha, se você arrumar pra mim eu penso no caso, se paga o frete e te mando a camiseta de graça.

**Comment by Dimebag03** [comment]
weWAUEHWUEHUW tentarei ver pra vc a noite ;)

**Comment by lanapf** [comment]
Me add no WhatsApp: 014 98151-6720

**Comment by wdarking** [comment]
Olá!

Testei o módulo da EcomDev em uma instalação limpa do magento (1.9.3) e funcionou perfeitamente, tanto simples quanto configurável.

Recomendo ativar o template hints para verificar se o magento está usando o arquivo certo.
No tutorial, na 3 parte é feita uma alteração em um arquivo de template (**view.phtml**). Tenha certeza de editar o view.phtml que está dentro da pasta do seu tema. Para verificar qual seu tema, vá em **System ->General -> Design -> Package**.

Ex.: uso o tema ultimo:

o view.phtml que deve ser editado deveria estar em `app -> design -> frontend -> default -> **ultimo** -> template -> catalog -> product`

**Comment by lanapf** [comment]
Foi editado corretamente, tanto que nos produtos simples funcionou normal.
Só não funcionou nos configuráveis, por isso perguntei se os configuráveis carrega outra página não a view.phtml.

**Comment by wdarking** [comment]
![asdsa](https://cloud.githubusercontent.com/assets/14166369/23137497/1a3ba62a-f781-11e6-94e1-0a22e4aa8119.png)

O **template hints** mostra que o arquivo **view.phtml** é usado tanto para produto simples quanto para configuráveis.

Pode ser que você use um tema diferente, que renderiza outro arquivo para mostrar os produtos, ou tem algum módulo sobrescrevendo este arquivo.

**Comment by lanapf** [comment]
Vlw a todos ai que me deram uma força consegui fazer procurei com o template hits (eu n conhecia isso ainda rsrsrs sou nova nas técnica) e descobri que não sei se é o meu tema mas ele carregava várias página na página do produto configurável diferentes do simples. Consegui achar o arquivo e colocar o cod lá e funcionou apareceu na página do produto configurável. Porém agora está dando erro de calculo do frete diz que o peso do produto tem que ser maior que zero, ele deve estar buscando o peso no produto configurável e não nos simples.

**Comment by lanapf** [comment]
@Dimebag03 essa alteração que você fez no arquivo do modulo ProductPage como foi?

**Comment by Dimebag03** [comment]
Oi @lanapf, então, no arquivo ali pelo que vi, eu só verifico se é um produto configurável e "seto" ele pra pegar o peso dele e não do simples, acho que é isso se me lembro bem wEUHWAUEWE

**Comment by Dimebag03** [comment]
Obrigado por ajudar noix ai broder @wdarking :tada: :tada: :tada:

**Comment by lanapf** [comment]
@Dimebag03 eu pego o que você fez lá e acrescento no arquivo ProductPage?

**Comment by Dimebag03** [comment]
@lanapf oq eu fiz foi para corrigir um problema no modulo da **EcomDev**, a modificação que eu fiz foi no arquivo:

_EcomDev/ProductPageShipping/controllers/**EstimateController.php**_

:wink:

**Comment by lanapf** [comment]
Vou tentar fazer isso mais tarde, é só acrescentar o que você fez no arquivo. Depois falo se deu resultado.

**Comment by Dimebag03** [comment]
Beleuza :wink:

**Comment by jamersonlima** [comment]
Estou em 2017 e essa Topico salvou meu trampo vlws !

**Comment by Dimebag03** [comment]
Haha noix tiu o/o/
