### ISSUE TITLE
Erro caclulo de frete -  " Esse método de envio está fora do ar. Por favor entre em contato conosco."

### ISSUE THREAD

**Issue by andretx** [pedro-teixeira/correios#342]
A mensagem é a seguinte: " Esse método de envio está fora do ar. Por favor entre em contato conosco."

Nos logs aparece este resultado:
" 2018-03-10T15:07:31+00:00 DEBUG (7): pedroteixeira_correios [337]: URL Error - Unable to Connect to tcp://ws.correios.com.br:80. Error #110: Connection timed out "

Enfim já tentei de tudo, revisei o login passado pelos correios, refiz o processo de instalação do modulo, aumentei o timeout no config.xml do modulo. e nada.

até ontem a noite estava tudo ok.
adicionei o login e senha no config.xml e tudo mais. já li de tudo aqui no grupo.

alguém teria uma solução?
Um observação o rastreio de objetos funciona perfeitamente, apenas o calculo de frete no carrinho e no checkout não funciona e retorna a primeira mensagem!

**Comment by zerosete** [comment]
Mesma coisa aqui. Webservice dos Correios parece q tá off mesmo. 
O cache do módulo deveria entrar em ação nesses casos não? 
Aqui não está funcionando o cache.

**Comment by andretx** [comment]
@zerosete pois é o cache deveria retornar para os resultados que ele já tem em cache. mesmo assim iria ignorar os novos ceps buscados gerando o erro.

faz mais de 12 horas que está desse jeito.

**Comment by zerosete** [comment]
Aqui mesmo com CEPS q tenho certeza q deveria estar em cache, não retorna nenhum resultado.

**Comment by andretx** [comment]
Essa url não responde mais: " http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx "

**Comment by rafaelpatro** [comment]
@zerosete, não é só o CEP que precisa estar cacheado.
O cache é montado levando em consideração o serviço cotado, o CEP (8 díg.), o peso em kilos (1 díg. decimal), o lado (se é menor ou maior do q 40cm, o limite da cubagem padrão).
É possível ajustar a [precisão do CEP](https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L755) para que a cache seja mais assertiva.

Seria interessante como melhoria para o módulo, montar um script para gerar várias requisições, e popular o cache.

**Comment by rafaelpatro** [comment]
Só uma correção, ele faz a cache por requisição (e não por serviço).
Vc pode fazer uma requisição com SEDEX e PAC ativos, e esta ficar salva na cache. Se desativar o PAC para outro produto, ele acaba não encontrando a cache.

**Comment by andretx** [comment]
@rafaelpatro e sobre a primeira dúvida tem alguma ideia do que pode ser?

**Comment by rafaelpatro** [comment]
@andretx, o erro parece ser do lado dos Correios mesmo.

**Comment by andretx** [comment]
@rafaelpatro  os seus projetos estão funcionando ok com o módulo ?

**Comment by rafaelpatro** [comment]
Hoje está bem instável. Hora funciona, hora não funciona.

**Comment by rafaelpatro** [comment]
Se pra vc estiver sempre offline, talvez o problema seja outro. Tenta fazer uma requisição em um arquivo php isolado, pra ver se funciona. Eventualmente pode ser um bloqueio do servidor.

**Comment by andretx** [comment]
Pelo visto é instabilidade da braba nos correios. agora voltou depois de 10horas sem funcionar.
