### ISSUE TITLE
Modulo Offline 

### ISSUE THREAD

**Issue by marcospaf** [pedro-teixeira/correios#354]
pessoal, será que agente não consegue fazer uma "vaquinha" para alguém desenvolver um modulo Offline , nem que se pague um mensal , sei la. Tentei o AV5 , mas o rapaz está tendo alguns problemas , então não rolou!

Hoje essa bosta já está fora do ar !

@rafaelpatro qual é a possibilidade de desenvolver um modulo Offline dos correios? cara mata as vendas , mata tudo , qual a possibilidade ? 

Poxa vamos nos unir ai! Está fogo isso

**Comment by phsilvaalves** [comment]
Parou aqui também, vocês conhecem algum módulo pago que funciona bem?

**Comment by marcospaf** [comment]
Cara tá parado aqui já tem tempo . Um lixo esses correios

**Comment by rafaelpatro** [comment]
@marcospaf esse é um assunto bem polêmico, e acredito haver várias soluções, mas tudo demanda tempo e recursos.

Há algum tempo desenvolvi uma solução offline. Funciona bem mas requer o cadastro manual dos valores. Se tiver interesse entre em contato (rafaelpatro@gmail.com).

**Comment by marcospaf** [comment]
@rafaelpatro , então vou fazer contato sim. 

Eu vejo que hoje para magento 1.9 temos somente o Pedro ou Av5 que ainda não funciona legal e toda hora os correios caem , muito complicado. Tanta gente usa magento e seria ótimo uma solução para que resolvesse estes problemas . Um desenvolvimento para isso , galera podia se unir para resolver isso .

**Comment by phsilvaalves** [comment]
Pessoal eu achei aqui o módulo da cerebrum é pago mas tem algumas coisa a mais, alguém conhece ou já usou?

**Comment by elsondinardo** [comment]
Usem o Modulo gratuito da Frenet, os Correios fora do ar nunca mais será problema usando o deles. Recomendo.

**Comment by PauloBoaventura** [comment]
Então meus caros... 
Estou neste processo de questionamento junto aos desenvolvedores, que literalmente largaram as produções e não dão qualquer informação a respeito. 

Preciso muito, tanto quanto vocês... 

Olá @phsilvaalves bom sobre o CEREBRUM eu não tive boas respostas...
Obrigado @elsondinardo pela dica... Mas eles tem algumas limitações e tambem ocorrem erros...

**Comment by marcospaf** [comment]
o modulo da Frenet tem um problema grave. Ele resolve um problema , mas os prazos são exibidos totalmente errado , não sei se teve correção nisso , mas quando entra no off-line o prazo dá problema , tem pac que entrava com 1 dia útil . resolve-se um problema , mas cria-se outro.

**Comment by marcospaf** [comment]
Eu achava que tem tanta gente que usa o magento e quando essa bosta de correios cai, ninguém vende ! Não tem solução off-line , era mais fácil fazer uma "vaquinha" para desenvolver algo que funcione pelo menos o básico , porque já tá foda de vender e ainda essa bosta não funcionando .

Vale lembrar que nem chegamos no meio do ano e no final do ano vai cair direto , não tenha duvida

**Comment by marcospaf** [comment]
@elsondinardo eu já usei e no meu site tive problemas , ele exibia o prazo errado , tipo você calculava o prazo era um, depois calculava novamente era outro ... foi péssimo para mim . O pior é que não existe um valor mensal e depois você começa a pagar por calculo de frete exibido , fica complicado isso

**Comment by marcospaf** [comment]
Os correios pede um modulo Offline a tempos, deve ser bem complicado o desenvolvimento não sei , até agora só vi o freenet e o aV5 , ambos com problemas. O melhor calculo ainda é o do pedro, mas ao meu ver falta a ferramenta de calculo

**Comment by PauloBoaventura** [comment]
Olá @marcospaf 
Até que enfim alguém para falar claramente o que passamos tanto com as extensões, quanto pelos correios... 
Bom se fizer uma busca tenho mais de 45 solicitações de Upgrade em diversas ferramentas seja elas para magento ou não. E até o momento não obtive uma conclusão satisfatória infelizmente... 
Eu também já testei #Pedroteixeira #Av5 #Freenet 
E não obtive nenhum suporte ou solução...

Sobre fazer uma vaquinha com desenvolvedores... Sou de todo apoio... 
Entro em contato!

Abs!

**Comment by marcospaf** [comment]
Opa @PauloBoaventura , eu falei com o @rafaelpatro ele tem uma solução off-line , vou conversar com ele certinho para ver se resolve.

O problema que no meu caso e na maioria das lojas online tudo é enviado pelos correios e quando ele não funciona , já era !!

Então é preciso de algo que funcione mesmo.

Correios - Online 
Pedro -   pode ter sua limitações , mas em geral é o melhor para mim.

Av5 - O cara é maneiro , eu comprei o modulo, mas solicitei a devolução do pagamento porque não funcionava corretamente , o desenvolvedor devolveu o valor , compreendeu, ponto para ele.

Freenet - Problema grave (aconteceu comigo ) , entrou no off-line , os prazos ficaram malucos! , se você atualizar o frete , toda hora mudava o prazo, pode-se que tenha sido resolvido. O outro problema é que você não sabe quanto vai pagar , isso é horrível. 

Beleza @PauloBoaventura , vou entrar em contato com vc , vou conversar com o @rafaelpatro para saber se agente consegue levantar $$$$ para ter uma solução definitiva para isso, pois já vi que o @rafaelpatro manja dos "paranauê" kkkk

Cara sem correios , não tem venda. O problema que as pessoas querem ver o preço e o prazo , o prazo é primordial e quando os correios ficam fora do ar , o site fica lento , pois tenta calcular e não tem retorno. 

Farei contato. 

Se alguém tiver mais interesse ai na "vaquinha Correios" vai falando que vai ficando mais fácil!

**Comment by rafaelpatro** [comment]
Pessoal, quero dar uma sugestão q sei q é pouco viável, mas pode ser
interessante se vc tiver uma clientela regional.

O módulo do pedro possui cache. A cache é um recurso offline, mas precisa
ser alimentada. Vc pode alimentar a cache de forma estratégica, afim de
otimizar ao máximo seu trabalho.

1. Reduzir a precisão do CEP e peso. Procure pela tag cache_accuracy no
arquivo config.xml. Reduza o CEP para 5 dígitos. Acho q o peso já é
otimizado.
2. Criar um produto com peso de 1kg, e dimensões insignificantes (ex.
1×1×1).
3. Listar as 100 cidades q vc mais vende, pegando apenas um CEP válido de
cada cidade.
4. Coloque o item no carrinho, e comece a cotar, incrementando a qde até um
máximo de 30 unidades.
5. Fazer isso para cada CEP.

Ao final vc terá uma base em cache das 100 cidades q mais envia.
Otimize o processo reduzindo a qde para 15, caso suas vendas raramente
excedam 15kg.
Lembre-se de manter a cache na prioridade de consulta aos Correios, antes
de começar as cotações.
Se vc utiliza o Redis cache no magento, nem precisa reduzir o CEP para 5
dígitos.
Lembrando q esse processo é otimizado, e impreciso. Pode haver
discrepâncias. Mas é melhor do q nada.

Abraço e uma boa noite

Em qua, 9 de mai de 2018 1:56 PM, Marcos <notifications@github.com>
escreveu:

**Comment by PauloBoaventura** [comment]
Oi @marcospaf exatamente sem tirar nada. É precisamente o que passo...
Temos que solucionar isso...
Nenhum modulo para mim funciona de maneira correta.
Estou fazendo uma implementação para magento 2, para ver se funciona. 
E aproveito e já me estabilizo com a plataforma. Pq ficar sem vender e com o estoque cheio não dá...
Vamos mantendo contato!!!
Dou todo apoio e sobre custos podemos ver algo que seja favorável em médio prazo para nós...

Ahhh @rafaelpatro Obrigado pela dica... 
Mas não aguento, lidar com a extensão PedroTeixeira... Atualmente ela é resultado de um trauma...
Espero que possamos melhorar em breve.

Estou viabilizando junto alguns desenvolvedores algo que seja bom. Vamos ver como ficará o projeto sendo ele pago ou não...
Mando noticias em breve... 

Forte abraço!

**Comment by PauloBoaventura** [comment]
CORREIOS MUDA TAXAS NOVAMENTE 

Infelizmente apos abrir mais de 45 chamados em todos projetos que usam....
Vejo que o problema não é só dos correios.
As taxas mais uma vez mudaram de valor.... Agora os correios tem Seguro. O que esta gerando um calculo errado diante da consulta antiga.
E assim entendo os os desenvolvedores, que optaram por não se desgastar em atualizar ou melhor refazer o trabalho do zero. Com tantas mudanças e diversos problemas..
O que achei uma boa opção é trabalhar com Tabela. E colocar mais de uma opção para o cliente.
Dá trabalho, mas não tem tanta dor de cabeça...
Estou desenvolvendo uma implementação que funciona com tabela, consulta os correios e atualiza transportadoras.
Me desafiei a fazer este trabalho, cansativo afim de ter uma tranquilidade.
Espero que em breve possa compartilhar. Para ajudar a muitos.

As extensões de vocês estão funcionado?
E quais são estas?
Gostaria de saber se estão efetuando o valor correto...

Abraços

**Comment by radamiBR** [comment]
@rafaelpatro hoje 27/06 webserver dos correios esta fora do deste 7:00 da manha até momento 20:23 não voltou, tentei fazer esse metodo que você passou do cache correios não tive rodou, fiz desse jeito esta correto:

                <cache_timeout>31536000</cache_timeout>
                <cache_accuracy>
                    <weight>1</weight>
                    <zip>8</zip>
                    <size>0</size>
                </cache_accuracy>
                <cache_mode>0</cache_mode>

                
                <add_postmethods>
                    <add_method_0>
                        <code>10065</code>
                        <price>9.98</price>
                        <days>3</days>
                        <from>
                            <zip>01000000</zip>
                            <weight>0.050</weight>
                            <size>30</size>
                        </from>
                        <to>
                            <zip>06999999</zip>
                            <weight>0.920</weight>
                            <size>30</size>
                        </to>
                    </add_method_0>
                    <add_method_1>
                        <code>10065</code>
                        <price>15.95</price>
                        <days>3</days>
                        <from>
                            <zip>01000000</zip>
                            <weight>0.020</weight>
                            <size>30</size>
                        </from>
                        <to>
                            <zip>06999999</zip>
                            <weight>0.050</weight>
                            <size>30</size>
                        </to>
                    </add_method_1>

Deixei no admim Consultar o Cache; e, se falhar, os Correios

Obrigado

**Comment by rafaelpatro** [comment]
@radamiBR, o cache só funciona se estiver sendo alimentado.
Exemplo:
* Um cliente coloca 1kg no carrinho, e faz a cotação para o CEP 12345678.
* Se o Correios estiver online, o resultado será armazenado em cache, para futuros clientes que tenham 1kg no carrinho, e residam no CEP 12345678.

 _- Uau! Mas assim nunca vai funcionar. A chance de acertar a cache é muito baixa._
Concordo! Por isso vc pode otimizar alguns parâmetros em _cache_accuracy_.
* weight: 1 (considera o peso em kg, com 1 casa decimal, ou seja, de cem em cem gramas)
* zip: 8 (considera os 8 dígitos do CEP)
* size: 0 (não lembro - algo com o tamanho)

Você pode otimizar bastante colocando weight = 0, pois a partir de 1kg, o Correios varia o preço do frete, de quilo em quilo.
Você tb pode otimizar bastante colocando o zip = 5, pois 99% dos municípios possui os primeiros 5 dígitos únicos. E o Correios não costuma variar preço entre bairros.

Mas acima de tudo, é necessário que esta configuração esteja rodando por algum tempo, para que o cache seja alimentado. E então quando o Correios cair, vc tem uma cache de cotações bem alimentada.
