### ISSUE TITLE
Valor de frete divergente

### ISSUE THREAD

**Issue by higuoliveira98** [pedro-teixeira/correios#362]
Olá,

Alguns clientes meus vem relatando que o cálculo de frete em suas lojas, diverge do calculo feito direto na plataforma dos correios. Na loja o valor que apresenta é bem abaixo do contrato.

As simulações nos correios é feita utilizando as medidas do produto. Saberia me dizer qual o problema ?

**Comment by rafaelpatro** [comment]
@higuoliveira98, divergências podem ocorrer em diversas etapas da cotação.

Mas resumidamente quem calcula o frete é o Correios. O módulo do @pedro-teixeira apenas reúne as informações da mercadoria, e envia para o webservice dos Correios.

Segue o link do webservice: http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=CalcPrecoPrazo
Sugiro que realize seus testes comparativos através desse link, e evite utilizar a [página de cálculo](http://www2.correios.com.br/sistemas/precosPrazos/) do site dos Correios.

**Comment by higuoliveira98** [comment]
Ok, muito obrigado !

**Comment by PauloBoaventura** [comment]
Infelizmente apos abrir mais de 45 chamados em todos projetos que usam....
Vejo que o problema não é só dos correios.
As taxas mais uma vez mudaram de valor.... Agora os correios tem Seguro. O que esta gerando um calculo errado diante da consulta antiga.
E assim entendo os os desenvolvedores, que optaram por não se desgastar em atualizar ou melhor refazer o trabalho do zero. Com tantas mudanças e diversos problemas..
O que achei uma boa opção é trabalhar com Tabela. E colocar mais de uma opção para o cliente.
Dá trabalho, mas não tem tanta dor de cabeça...
Estou desenvolvendo uma implementação que funciona com tabela, consulta os correios e atualiza transportadoras.
Me desafiei a fazer este trabalho, cansativo afim de ter uma tranquilidade.
Espero que em breve possa compartilhar. Para ajudar a muitos.

As extensões de vocês estão funcionado?
E quais são estas?
Gostaria de saber se estão efetuando o valor correto...

Abraços
