### ISSUE TITLE
Correios está fora?

### ISSUE THREAD

**Issue by kinfoxxx** [pedro-teixeira/correios#372]
Bom dia, os correios está fora do ar para vocês?

**Comment by diogolast** [comment]
Bom dia, estou testando e realmente não informa nenhum frete e nenhum erro. =/

**Comment by philsouza2016** [comment]
Está sim, desde cedo.

**Comment by kinfoxxx** [comment]
Xii, aqui também calculo o frete não informa nada e só erro

**Comment by kinfoxxx** [comment]
www.kshopsa.com.br

**Comment by brothernet** [comment]
O erro retornado no log é CEP Inválido. Mas acho que o problema está no WebService dos Correios.

**Comment by kinfoxxx** [comment]
Boa noite, aqui nada ainda, conseguiram alguma solução ou alternativa?

**Comment by rcoelros** [comment]
Aqui nada também. Ainda está offline para vocês?

**Comment by brobsong** [comment]
Galera eu uso o módulo de Frete do Willstorm nele tem a opção de Frete grátis e frete fixo. O cálculo do valor e tempo de entrega quando seleciona essas opções não passa pelo webservice dos correios. Testem pra ver se pelo menos funciona dessa forma. Melhor dar um desconto do que ficar sem realizar as vendas.

**Comment by maoparaiso** [comment]
O módulo está funcionando se você mandar atualizar os serviços na configuração do módulo. Há um botão que aparentemente atualiza alguma informação. Entretanto somente retornou a opção de SEDEX. PAC não aparece. Não sei qual a razão. Alguém teve alguma outra evolução?
