### ISSUE TITLE
Preços exorbitantes

### ISSUE THREAD

**Issue by diegodcl** [pedro-teixeira/correios#376]
Quando o cliente preenche o CEP e calcula a estimativa estão aparecendo preços exorbitantes de fretes. R$4000, R$3000. Não acontece sempre, acontece em navegadores diferentes. Cálculo de frete sem contrato

**Comment by rafaelpatro** [comment]
Bom dia @diegodcl 
Consegue enviar os logs do Magento, no momento da cotação?
Se possível, envie tb um print das configurações do módulo, e um print do produto, com a aba Correios selecionada.

**Comment by diegodcl** [comment]
Qual pasta fica o log do plugin dos correios?

**Comment by rafaelpatro** [comment]
Não há um log específico para este módulo.
Pode enviar os logs do Magento, normalmente em _/public_html/var/log/system.log_.

**Comment by diegodcl** [comment]
Essas são as últimas entradas do LOG
> 2018-06-11T17:30:07+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T17:44:17+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T17:48:03+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T17:54:07+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T17:54:09+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T18:01:27+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T18:03:19+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T18:13:26+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T18:23:19+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T18:48:11+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T18:59:42+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T19:00:27+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T19:03:06+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 2018-06-11T19:08:16+00:00 ERR (3): Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  in /var/www/html/xxxxxxx.com.br/web/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 129
> 

A página de configuração dos plugins não tem erro. Ele funcionava bem, de repente começou o problema. E algumas vezes ele dá um preço correto.

**Comment by rafaelpatro** [comment]
Esse log não diz muito. Tenta ver o log exatamente após uma cotação no carrinho.

**Comment by diegodcl** [comment]
Fiz testes desde segunda e não apareceu nenhuma entrada no log

**Comment by rafaelpatro** [comment]
O _system.log_ deveria exibir ao menos o debug da cotação.
Verifique se o log está ativo no Magento, pois seu último registro foi há um mês.

**Comment by diegodcl** [comment]
Ativei o log e achei uma linha do plugin
2018-07-16T14:55:33+00:00 DEBUG (7): pedroteixeira_correios: Warning! There is no valid quotes, and no one error was throwed: O CEP de destino está temporariamente sem entrega domiciliar. A entrega será efetuada na agência indicada no Aviso de Chegada que será entregue no endereço do destinatário.

**Comment by diegodcl** [comment]
Descobri também que isso só acontece em alguns produtos, os mais antigos não acontece o problema. Existe alguma propriedado no cadastro do produto que pode influenciar?

**Comment by diegodcl** [comment]
Amigo, consegui descobrir. O cliente cadastrou o peso do produto errado. Sinto muito por ter aberto um tópico por isso. Desculpas
