### ISSUE TITLE
Integração SIGEP

### ISSUE THREAD

**Issue by filipenunes75** [pedro-teixeira/correios#387]
olá galera ! 
Já tenho o modulo @pedro-teixeira rodando no site! Versão 4.9.0 -
passei horas e horas a ler quase tudo aqui e , peço desculpas, mas não consegui saber como fazer para o módulo @pedro-teixeira funcionar com o SIGEP -
tem algum LUGAR - que se baixe o arquivo - faça o upload via FTP e pronto? 
fico no aguardo !

Magento 1.9.0.1 
Site: www.paintballonline.com.br

**Comment by rafaelpatro** [comment]
@filipenunes75, enviei a integração com o SigepWeb nessa PR #374, e lá coloquei o máximo de informações que recordo. Se puder testar e dar um feedback, será de grande ajuda.

Vc pode baixar o patch com as alterações [aqui](https://patch-diff.githubusercontent.com/raw/pedro-teixeira/correios/pull/374.patch).
_Obs.: Leia com atenção as informações na PR. E procure saber como instalar um patch, senão pode danificar seus arquivos, e comprometer sua loja._

Particularmente venho utilizando esse patch em produção, há quase 2 meses. Gero dezenas de etiquetas diariamente, com destinatário, remetente, rastreamento, cód de barras, logotipo da loja, etc. E tem funcionado muito bem. A agência dos Correios consegue identificar os objetos e PLP, e despachar rapidamente.

_Lembrando que essa integração ainda não foi aprovada pelos administradores aqui do repositório._

**Comment by filipenunes75** [comment]
@rafaelpatro , muito obrigado pelo pronto atendimento ! 
mas, pelo que vi, tem que saber muito mais em programação ....
meus conhecimento de magento acabou por aqui !hehehe! 
o que sei fazer - é copiar via FTP as pastas ! e fazer as configurações no backend! 
editar, criar arquivos e demais habilidades tecnicas igual as suas eu não tenho! 
vou ficar aqui torcendo para sair uma versao 5.0(hehe) que o utilizador possa fazer mais fácil! 
parabéns por compartilhar seus conhecimentos e suas esperiencias ... 
vida longa ao "magento":-)

**Comment by fernandoplanejar91** [comment]
Olá @rafaelpatro você pode por favor explicar como instala o Patch?

Tenho que abrir o ftp via SSH e digitar:

git https://patch-diff.githubusercontent.com/raw/pedro-teixeira/correios/pull/374.patch

É assim?

Abraço!

**Comment by rafaelpatro** [comment]
Antes de qualquer coisa, o patch só funciona para a versão original do repositório. Se modificou algum arquivo, é provável que o patch não funcione, ou acabe corrompendo seus arquivos.

Há mais de uma forma de aplicar patches. Eu costumo usar o comando `patch -p1 --dry-run < arquivo.patch`. O parâmetro dry-run testa o patch antes de aplicar. Remove, para aplicar o patch efetivamente.

**Comment by bes961** [comment]
@Aires2010 Bom dia!

Acredito que o erro da etiqueta seria no formato da caixa que vc está discriminando.
as Medidas seria o padrão mínimo
Comprimento (C)	16 cm	
Largura (L)               11 cm
Altura (A)                 2 cm



vc colocou 15x15x5 o que está errado é somente o comprimento que no mínimo seria 16 CM

**Comment by Aires2010** [comment]
Olá @bes961

Obrigado pelo retorno, fiz a alteração e o erro continua...
[cid:image003.png@01D4BC80.26EB5620]

Acredito que seja algum bug mesmo, o valor do peso não fica salvo no produto ao adicionar ao pacote.

________________________________
De: bes961 <notifications@github.com>
Enviado: Monday, February 4, 2019 11:46:26 AM
Para: pedro-teixeira/correios
Cc: Aires2010; Mention
Assunto: Re: [pedro-teixeira/correios] Integração SIGEP (#387)


@Aires2010<https://github.com/Aires2010> Bom dia!

Acredito que o erro da etiqueta seria no formato da caixa que vc está discriminando.
as Medidas seria o padrão mínimo
Comprimento (C) 16 cm
Largura (L) 11 cm
Altura (A) 2 cm

vc colocou 15x15x5 o que está errado é somente o comprimento que no mínimo seria 16 CM

**Comment by rafaelpatro** [comment]
Boa tarde @Aires2010
Pode postar o log do Magento para mais detalhes?

**Comment by rafaelpatro** [comment]
Esqueceu do arquivo

**Comment by Aires2010** [comment]
[exception.log](https://github.com/pedro-teixeira/correios/files/2829849/exception.log)

Segue log de erro... por algum motivo não veio direto pelo e-mail.

**Comment by rafaelpatro** [comment]
Só pode ser isso...
O log mostra que a PLP não passou na validação do _webservice_. Revisei meus commits aqui, e reparei que houve uma alteração na validação dos _serviços adicionais_, em 10/2018. Corrigi meus arquivos, mas esqueci de enviar para o repositório. Enviarei em breve, ok?! Acho q ainda hoje.

**Comment by Aires2010** [comment]
Ok!

Obrigado!

On Feb 4, 2019 7:55 PM, Rafael Patro <notifications@github.com> wrote:

Só pode ser isso...
O log mostra que a PLP não passou na validação do webservice. Revisei meus commits aqui, e reparei que houve uma alteração na validação dos serviços adicionais, em 10/2018. Corrigi meus arquivos, mas esqueci de enviar para o repositório. Enviarei em breve, ok?! Acho q ainda hoje.

**Comment by rafaelpatro** [comment]
Feito! Testa lá
Qualquer erro já posta o _system.log_ e _exception.log_.

**Comment by Aires2010** [comment]
[exception.log](https://github.com/pedro-teixeira/correios/files/2831904/exception.log)
[system.log](https://github.com/pedro-teixeira/correios/files/2831905/system.log)
Bom dia @rafaelpatro!

A mensagem de erro mudou no log,  mas no magento aparece o mesmo erro.

Segue arquivos para avaliação.

Obrigado!

**Comment by Aires2010** [comment]
Sim, e deu a mensagem de sucesso.

O problema pode ser em um ou mais arquivos, pois também não está salvando o peso ao "criar produtos" na geração de etiqueta.


________________________________
De: Rafael Patro <notifications@github.com>
Enviado: terça-feira, 5 de fevereiro de 2019 11:30
Para: pedro-teixeira/correios
Cc: Aires2010; Mention
Assunto: Re: [pedro-teixeira/correios] Integração SIGEP (#387)


Bom dia @Aires2010<https://github.com/Aires2010>
Vc atualizou os serviços, depois de salvar usuário e senha do SIGEPWEB?

[image]<https://user-images.githubusercontent.com/13813964/52276446-5c4dfb80-2939-11e9-8856-a90b05c1217b.png>

**Comment by rafaelpatro** [comment]
Bom dia @Aires2010 
Essa função em destaque emite um log com parâmetros, que não foi exibido no _system.log_.

![image](https://user-images.githubusercontent.com/13813964/52341348-75b67c80-29f9-11e9-8e09-5ee9152d377c.png)
![image](https://user-images.githubusercontent.com/13813964/52341424-aa2a3880-29f9-11e9-93a8-692fd4267f7b.png)


Consegue enviar esse log novamente, omitindo suas credenciais?

**Comment by Aires2010** [comment]
Boa tarde @rafaelpatro !

O log retornou isso:

2019-02-06T15:46:57+00:00 DEBUG (7): Correios_Sigep_SolicitaEtiquetas Object
(
    [tipoDestinatario] => C
    [identificador] => xxxxxxxx
    [idServico] => 
    [qtdEtiquetas] => 1
    [usuario] => xxxxxxx
    [senha] => xxxxxx
)

**Comment by rafaelpatro** [comment]
Parece um problema na atualização dos códigos de serviço. O _idServico_ é obrigatório, e está vazio.
Pode verificar se o código de serviço do pedido em questão consta na tabela _correios_postmethods_?

Lembra se ocorreu algum log quando aplicou o patch?
Vc chegou a executar o script SQL que postei na PR #374 ? _Importante! A execução desse script SQL é irreversível. Não aplique em produção antes de homologar._

**Comment by Aires2010** [comment]
Olá @rafaelpatro!

Obrigado pela ajuda! Foi possível detectar o que estava errado no ultimo log. Ocorre que idServiço fica vazio quando o pedido vem de uma fonte externa (por meio de um HUB ou de um marketplace). 
Ao criar um produto direto na loja virtual funcionou perfeitamente!
Se houvesse a possibilidade de selecionar ou confirmar o tipo de postagem antes de salvar a etiqueta, resolveria.
Você teria alguma sugestão para isso? Permitindo imprimir etiquetas em pedidos de fonte externa?

De qualqer forma agradeço a prontidão e insistência em ajudar :)

**Comment by rafaelpatro** [comment]
Chama pelo rafaelpatro@gmail.com

**Comment by LuizSantos1** [comment]
@filipenunes75 tudo bem?
Eu uso o checkout da Moip, que é muito bonito e tals...
Mas passei a ter problemas com o Google porque eles tornam os campos CPF, CNPJ e Razão Social 
como obrigatórios, e o Google passou a não aceitar. 

Vi no seu site o One Step Checkout e achei interessante

Poderia me dizer onde conseguiu? 

Desde já, obrigado.
