### ISSUE TITLE
Problema no cálculo do Frete

### ISSUE THREAD

**Issue by juemborges** [pedro-teixeira/correios#394]
Boa noite. Alguém está com problema no cálculo do frete? 
Meu site não está funcionando... mostra erro do tipo 503.
Obrigada

**Comment by rafaelpatro** [comment]
Sim aqui tb. Correios está com problemas hoje.

**Comment by juemborges** [comment]
Continua com o mesmo problema?
Obrigada!

**Comment by juemborges** [comment]
Alguém continua com esse problema?

**Comment by rafaelpatro** [comment]
Olá @juemborges 
O webservice teve uma queda agora às 20:26, e tb às 19:06. Mas foi coisa rápida. Aparentemente se manteve estável durante o restante do dia.

Se ainda estiver tendo problemas, pode ser que o cache tenha salvo alguma resposta com erro. Nesse caso tenta limpar o cache _PedroTeixeira_Correios_.

**Comment by rafaelpatro** [comment]
Essa extensão possui alguns campos no produto, relacionados às dimensões. Pode mandar um print de como preencheu?

**Comment by juemborges** [comment]
![alteracao](https://user-images.githubusercontent.com/28653998/45397090-cbd2ef80-b614-11e8-8346-9ad3500a955b.png)

@rafaelpatro Obrigada pelo retorno.
Agora a noite eu fiz a atualização para a versão 4.9... não mudou nada.

**Comment by rafaelpatro** [comment]
Reparei q o código dos seus serviços são um pouco diferentes 04367 e 04154.
Veja se as tags de validação estão configuradas para seus códigos de serviço.

https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml#L146

Senão é só adicionar as tags, limpar a cache de configurações, e vai funcionar.
Exemplo:
```xml
                    <serv_04367>
                        <max>
                            <size>70</size>
                            <sum>200</sum>
                            <weight>30</weight>
                            <volume_weight>50</volume_weight>
                        </max>
                        <zips>
                            <brasil>00000000,99999999</brasil>
                        </zips>
                    </serv_04367>
```

**Comment by juemborges** [comment]
Oi @rafaelpatro 
Bom dia. Tudo certo?
![alteracao2](https://user-images.githubusercontent.com/28653998/45425087-bee2ea00-b66e-11e8-9e13-d56e017482ec.png)
O peso do produto está configurado para 0.1
Obrigada pela sua atenção!

**Comment by juemborges** [comment]
Bingo! Era isso mesmo!
@rafaelpatro  Obrigada pelo apoio... não sabia mais para onde correr =)
