### ISSUE TITLE
Tabela Correios Fácil

### ISSUE THREAD

**Issue by zerosete** [pedro-teixeira/correios#401]
Olá, alguém já ta usando o novo contrato com os Correios? O [Correios fácil](https://apps.correios.com.br/correiosfacil/).

![image](https://user-images.githubusercontent.com/30726637/47921912-886a6400-de94-11e8-9df2-d1e393eab258.png)

Consegui carregar os novos códigos no admin, mas no carrinho está dando dando timeout na hora de calcular o frete.

Mais alguém com esse problema?

**Comment by rafaelpatro** [comment]
Bom dia @zerosete
Quaisquer códigos de serviço novos, vc precisa cadastrar os parâmetros de validação, no arquivo _etc/config.xml_.
Localize a tag _validation_, e faça os ajustes conforme o código do seu serviço de entrega.

**Comment by rafaelpatro** [comment]
Blz! Que bom que conseguiu.
Mesmo assim acho que isso vale uma PR. Acho que a validação não deveria ser um requisito, e sim uma opção.
Se não existir tags de validação, não validar, só isso.
