### ISSUE TITLE
Bling integração SIGEP Web + Modulo Correios

### ISSUE THREAD

**Issue by willgoulding** [pedro-teixeira/correios#405]
Olá,

Alguém poderia me ajudar  com essa questão?

Integrei o Magento com Bling e agora estou utilizando a integração do SIGEP Web do bling para gerar os envios. 

Mas o bling não esta puxando automaticamente do magento qual envio o cliente escolheu no magento.

O suporte do Bling que devo informa na configuração qual ALIAS o modulo do pedro-teixeira Correios utiliza assim o bling irá seleccionar automaticamente o método de envio no pedido dentro do bling. 

Eu tentei todos esses a baixo:

![image](https://user-images.githubusercontent.com/12437790/48943887-ce529f00-ef0b-11e8-86a9-4fcf86719118.png)

mas não esta funcionando.

Alguém sabe qual é o correto?

**Comment by rafaelpatro** [comment]
Tenta isso: pedroteixeira_correios_04669

Em sex, 23 de nov de 2018 10:42, willgoulding <notifications@github.com
escreveu:

**Comment by willgoulding** [comment]
@rafaelpatro Deu certo! Obrigado
