### ISSUE TITLE
Correios fora do ar desde ontem

### ISSUE THREAD

**Issue by marcospaf** [pedro-teixeira/correios#412]
Pessoal estão com problemas nos correios ? Desde o final da tarde ontem fora do ar! Voltou de madruga, mas já está fora ! Horrível. Alguém aqui usa frenet? Já testei uma vez, mas bugava o prazo de entrega, cada hora exibia um prazo doido, mas já tá horrível de vender e os Correios não funcionando é brincadeira !

**Comment by wdarking** [comment]
Aqui parece estar fora do ar também. Usamos o módulo [Quack_TntBrasil](https://github.com/rafaelpatro/Quack_TntBrasil) do @rafaelpatro como segunda opção de frete, que integra com a TNT.

Log:

```
2019-02-13T10:07:12+00:00 DEBUG (7): pedroteixeira_correios [socket]: Unable to Connect to tcp://ws.correios.com.br:80. Error #110: Connection timed out
2019-02-13T10:07:12+00:00 DEBUG (7): pedroteixeira_correios [socket]: Trying to write but we are not connected
2019-02-13T10:07:12+00:00 DEBUG (7): pedroteixeira_correios [351]: URL Error - Unable to read response, or response is empty
```

**Comment by rafaelpatro** [comment]
As vezes o Correios está lento, e o módulo só precisa aguardar mais alguns segundos.

Tenta aumentar o valor do parâmetro wstimeout no arquivo etc/config.xml

**Comment by marcospaf** [comment]
Tá nada Rafael , tá fora mesmo. Tenta aí

**Comment by marcospaf** [comment]
Eu fiquei bolado e coloquei o frenet, não é mais gratis, nunca foi , mas parece que agora funciona em fim !

**Comment by marcospaf** [comment]
E vem aumento dos correios aí !

**Comment by rafaelpatro** [comment]
Não percebi pois minha extensão está atualizada com a PR #374. Nessa PR foi implementado um fallback para cotação pelo SIGEP Web, para quando o webservice convencional estiver offline. E o SIGEP Web não caiu. Está retornando as cotações normalmente.

**Comment by marcospaf** [comment]
eu não instalei essas melhorias , como faço rafael ? já tem dentro a atualização do modulo ?

**Comment by rafaelpatro** [comment]
As mudanças ainda não foram amplamente homologadas, e tb não foram anexadas ao projeto. Então sugiro testar em um ambiente seguro, antes de instalar em produção.
Se estiver na versão master, é só baixar o patch, e prosseguir com a instalação.
Se não souber lidar com patches, sugiro contatar um desenvolvedor.
Boa sorte, e posta aqui qualquer erro que aparecer.

**Comment by marcospaf** [comment]
Hehehe . Tenso . Tem previsão para o Pedro por ? Vou esperar um pouco mais . Tem uma novidade . Quem imprimir já em plp vai ter 4% de desconto no PAC . Tá sabendo ?

**Comment by rafaelpatro** [comment]
Então @marcospaf... Acho que o @pedro-teixeira só está aguardando mais pessoas homologarem. É uma PR muito grande, e pode comprometer muitas lojas, se não for bem testada.

Onde vc viu sobre esse desconto no PAC? Oq quer dizer com _imprimir já em PLP_?

**Comment by marcospaf** [comment]
@rafaelpatro  cara eu recebi uma carta dos correios , tem um item assim:

Inclusão de redutores de preço de até 4% para PAC em contratos , desde que a pré-postagem seja feita de forma eletrônica.

O pessoal da agencia me informou que é a tal da PLP , porque isso adianta muito o serviço deles.

pelo que vi nessa atualização , tem muita coisa nova  inclusive a PLP né?


Rafael , queria até te perguntar . como faço para retornar no calculo do cep a palavra CEP INVÁLIDO, toda vez que o cliente colocar um cep errado. o doido meteu 89130000 , volta sem nenhum valor no modulo. valeu

**Comment by rafaelpatro** [comment]
> pelo que vi nessa atualização , tem muita coisa nova inclusive a PLP né?

Sim. Ao que tudo indica, a emissão de PLPs deve fazer parte da versão 4.10.

> como faço para retornar no calculo do cep a palavra CEP INVÁLIDO

Infelizmente todos os erros oriundos do webservice são tratados como _urlerror_. E o campo _Mensagem de URL Fora do Ar_ permite configurar uma mensagem para o usuário.
Nos casos onde o CEP for preenchido fora do padrão de 8 dígitos numéricos. Somente nesse caso, o campo para configurar a mensagem é _Mensagem de CEP Incorreto_.

**Comment by fredpiuma** [comment]
Essa questão do CEP você resolve usando o módulo de check-out OSC6 que
adiciona máscara no CEP e telefone. Ou simplesmente adicione a máscara com
Javascript.

**Comment by marcospaf** [comment]
@rafaelpatro  show , vou aguardar
