### ISSUE TITLE
Dimensões dos produtos fora do permitido pelos Correios.

### ISSUE THREAD

**Issue by ghost** [pedro-teixeira/correios#415]
Prezados, boa tarde. 

Desde a nova mudança dos contratos dos Correios estamos impossibilitados de calcular o frete em nossos pedidos nas novas modalidades PAC CONTRATO AGENCIA TA e SEDEX CONTRATO AGENCIA TA, recebemos a mensagem: Dimensões dos produtos fora do permitido pelos Correios.

Sempre conseguimos calcular o frete normalmente, mas desde a mudança toda vez que tentamos alterar as dimensões mesmo que para fins de teste, o erro persiste. Caso utilizemos "não" para a validação de dimensões, o cálculo fica em "loading eterno".

Já seguimos as orientações dos setores responsáveis nos Correios, não deu em nada, alguém sabe como podemos solucionar o caso? 

Nosso log exibe somente isso: 2019-03-15T18:23:41+00:00 DEBUG (7): pedroteixeira_correios [111]: Dimension error

**Comment by rafaelpatro** [comment]
Quais os códigos de serviço do seu contrato?
Veja se existe as tags de validação para seus códigos de serviço, no arquivo de configurações do módulo.
https://github.com/pedro-teixeira/correios/blob/bbfa63a26b687b8ba4ccbd38189174c541a78ec2/app/code/community/PedroTeixeira/Correios/etc/config.xml#L146

**Comment by ghost** [comment]
Olá Rafael! 

Grato pelo retorno, atualizamos nossos PAC (04669) e SEDEX (04162) para, respectivamente, 04596 e 04553. Nosso XML está sem os códigos...  Você sugere que realizemos a inclusão das tags para ambas modalidades? 

Abraços.

**Comment by rafaelpatro** [comment]
Exato! Pode copiar as tags dos serviços antigos.

**Comment by ghost** [comment]
Bom dia Rafael, 

Fizemos os ajustes, tudo certo. Muito obrigado.
