### ISSUE TITLE
Novos Serviços 04553 e 04596 - Retorno de erro - Dimensão

### ISSUE THREAD

**Issue by renanmoffa** [pedro-teixeira/correios#417]
Olá Ótimo dia!!

Acabei de efetuar a atualização do módulo e a atualização dos novos serviços. 04553 (Sedex) e o 04596(PAC), ambos estão retornando a mensagem: 
"Dimensões dos produtos fora do permitido pelos Correios."
A dimensão setada no módulo é :
Altura: 22cm
Comprimento: 16cm
Largura: 34

Para o produto a dimensão está em;
Altura: 3cm 
Comprimento: 30cm
Largura: 37

Alguém tem alguma noção do possivel gap?

**Comment by cesaroito** [comment]
Fiz este ajuste aqui e funcionou:
Mesmo tendo contrato e atualizando a lista de serviços eu continuei a receber os erros como "medidas incorretas" e oras com "produto inexistente". A solução foi adicionar o código abaixo manualmente no app/code/community/PedroTeixeira/Correios/etc/config.xml dentro do validate:

                <serv_04553>
                    <max>
                        <size>105</size>
                        <sum>200</sum>
                        <weight>30</weight>
                        <volume_weight>50</volume_weight>
                    </max>
                    <zips>
                        <brasil>00000000,99999999</brasil>
                    </zips>
                </serv_04553>
                <serv_04596>
                    <max>
                        <size>105</size>
                        <sum>200</sum>
                        <weight>30</weight>
                        <volume_weight>50</volume_weight>
                    </max>
                    <zips>
                        <brasil>00000000,99999999</brasil>
                    </zips>
                </serv_04596>
Funcionou perfeitamente no meu caso esta situação.

**Comment by renanmoffa** [comment]
Funcionou certinho aqui também, Valeu!!
