### ISSUE TITLE
Produto não calcula o frete, valor abaixo de R$18,00

### ISSUE THREAD

**Issue by murilosantana25** [pedro-teixeira/correios#421]
Estou calculando o frete de alguns produtos, mas se o valor é abaixo de R$ 18,00 ele não calcula, e nem retorna mensagem na tela.

Ja configurei no plugin para o valor minimo ser R$ 10,00 , mas o erro persiste.

**Comment by rafaelpatro** [comment]
Boa tarde @murilosantana25 
Há algum tempo, o Correios mudou as regras para valor declarado. E o módulo ainda não se atualizou.

Acho que o valor declarado mínimo é de 19 reais. E agora é obrigatório para todas as encomendas. Ou seja, a opção de _Utilizar Serviço de Valor Declarado_ tornou-se obsoleta.
Então vc vai precisar chamar um dev, para customizar esse trecho do código...
https://github.com/pedro-teixeira/correios/blob/c8667445d8716b0bf491706909039e45d9671324/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php#L307

**Comment by murilosantana25** [comment]
Funcionou cara, Obrigado!
