### ISSUE TITLE
Ajuda - Cálculo de frete muitos produtos no carrinho

### ISSUE THREAD

**Issue by JoaoGAR** [pedro-teixeira/correios#455]
Olá;
Estou tendo um problema em que eu coloco dois produtos com frete alto no carrinho, se eu colocar um produto pequeno, o preço do frete cai muito.
Exemplo: 2 produtos grandes 250 reais, adiciono um pequeno e o frete vai para 180 reais.
Onde posso ajustar isso no módulo? Eu teria que calcular o frete por produto do carrinho e depois somar?

**Comment by JoaoGAR** [comment]
Bom, descobri que começou após que eu fiz a mudança para somar os 79 reais.
O site está usando o ProductPageShipping e o valor nele está diferente do da página de carrinho.

**Comment by JoaoGAR** [comment]
Vi que uma "caixa" com todos os lados iguais é montada, com o propósito de otimização, mas se eu jogar um item muito pequeno o valor médio diminui proporcionalmente. Não acho que isso esteja correto, alguém pode me dar uma luz?

`
$itemAltura = $this->_getFitHeight($item);
            $pesoCubicoTotal += (($itemAltura * $itemLargura * $itemComprimento) *
                    $item->getTotalQty()) / $this->getConfigData('coeficiente_volume');
`

**Comment by rafaelpatro** [comment]
Oq pode estar ocorrendo é a divisão de pacotes.
O Correios tem certos limites de peso e tamanho; que, se excedidos, a api retorna erro.

Se habilitada a opção de dividir o pacote, o módulo diminui o pacote, para obter uma cotação válida, e sem erros. E em seguida o valor é reajustado, para 2 volumes ou mais.

_p.s. Para uma análise mais minuciosa, o ideal seria vc postar aqui as dimensões e peso de cada item no carrinho, bem como os códigos de serviço ativos, e um print das configurações do módulo._

**Comment by JoaoGAR** [comment]
A opção de dividir pacotes está desabilitada.
Produto 1
Peso Embalagem (Kg) - 9.9000
Largura (cm) - 56
Altura (cm) - 13
Comprimento (cm) - 87
FRETE SEDEX - 154,60

Produto 2
Peso Embalagem (Kg) - 3.7200
Largura (cm) - 43
Altura (cm) - 19
Comprimento (cm) - 71
FRETE SEDEX - 148,90

Produto 3
Peso Embalagem (Kg) - 0.5000
Largura (cm) - 10
Altura (cm) - 10
Comprimento (cm) - 8
FRETE SEDEX - 27,50

Os dois grandes frete igual a 211,60
Adiciono o pequeno e o frete vai para 111,60

Fotos das confs: https://drive.google.com/file/d/18SaDxtJqp7gFeH0UczZbyR4ETUy5JN-L/view?usp=sharing

**Comment by rafaelpatro** [comment]
Bom dia @JoaoGAR 
Infelizmente não foi possível identificar o problema.

Ao meu ver, como o `$pesoCubicoTotal` é **sempre** incrementado, a única possibilidade de reduzir seria ativando a divisão de pacotes. Então acho q vc vai precisar de um dev; comparar as versões; ver se há customizações no código; colocar uns logs nos lugares certos; para então então conseguir identificar o problema.

**Comment by JoaoGAR** [comment]
Eu sou o DEV rs, vou quebrar a cabeça aqui.
Muito obrigado

**Comment by rafaelpatro** [comment]
Ok, então segue algumas sugestões.

1. Vá em _editar produto_, e veja se os atributos de altura, largura, etc, que vc identificou são os mesmos utilizados pelo módulo (volume_altura, volume_largura, etc). Não é incomum ver sistemas utilizando atributos diferentes.
1. Verifique se o campo de _Encaixe_ está vazio, nos produtos que vc está testando.
1. Coloca um log após `$pesoCubicoTotal`, para verificar o comportamento após cada iteração.
1. Coloca um log no final do método, para identificar a saída. E teste com os 2 produtos, e depois com os 3 produtos.

**Comment by JoaoGAR** [comment]
Bom, foi bobeira minha. Peguei o código para adicionar os 79 reais aqui no git, mas fiz umas mudanças e deixei algumas linhas fora de um foreach, aí ele pegava só o frete do último produto adicionado ao carrinho.
Muito obrigado mesmo pela ajuda rs.
