### ISSUE TITLE
não atualiza o pedido quando só tem um código para monitorar

### ISSUE THREAD

**Issue by rebecapf** [pedro-teixeira/correios#462]
olá!
estou fazendo uma nova loja no magento e instalei o modulo do zero
já está tudo configurado, senha sro e tudo que precisa... 
mas estou fazendo um teste com um codigo e não está atualizando o status do pedido, ele continua como Pedido em Transporte... 
está gravando isso no log:

2019-12-18T19:48:02+00:00 DEBUG (7): 1 loaded
2019-12-18T19:48:02+00:00 DEBUG (7): 1 validated of 1 loaded
2019-12-18T19:48:02+00:00 DEBUG (7): OI473997999BR
2019-12-18T19:48:02+00:00 DEBUG (7): 1 sent of 1 validated of 1 loaded
2019-12-18T19:48:02+00:00 DEBUG (7): Cant locate track for 
2019-12-18T19:48:02+00:00 DEBUG (7): Cant locate track for 
2019-12-18T19:48:02+00:00 DEBUG (7): Cant locate track for 
2019-12-18T19:48:02+00:00 DEBUG (7): Cant locate track for 
2019-12-18T19:48:02+00:00 DEBUG (7): Cant locate track for 
2019-12-18T19:48:02+00:00 DEBUG (7): 0 identified of 1 sent of 1 validated of 1 loaded
2019-12-18T19:48:02+00:00 DEBUG (7): PedroTeixeira_Correios_Model_Sro_Object_Collection::save
2019-12-18T19:48:02+00:00 DEBUG (7): 0 saved of 0 identified of 1 sent of 1 validated of 1 loaded
2019-12-18T19:48:02+00:00 DEBUG (7): 0 notified of 0 saved of 0 identified of 1 sent of 1 validated of 1 loaded

o que será que pode ser?

**Comment by rafaelpatro** [comment]
Olá @rebecapf 
Suas credenciais de acesso ao SRO podem estar incorretas. Consegue validar em uma requisição isolada?

**Comment by rebecapf** [comment]
mas se tivessem incorretas traria o histórico pelo link de acompanhamento? 
essas credenciais eu uso em outra loja minha que tem uma versão desatualizada do módulo e funciona =/

**Comment by rafaelpatro** [comment]
Realmente, se o histórico funciona, as credenciais SRO devem estar corretas.

Pelo log aparentemente o objeto não está sendo identificado no SRO.

 _0 identified of 1 sent_ significa que vc enviou um objeto na requisição, e o SRO não retornou resultado. Por isso desconfiei das credenciais. Talvez algum outro parâmetro esteja errado.

Verifique os outros parâmetros SRO, no arquivo de configurações do módulo. Posta aqui o arquivo ../Correios/etc/config.xml

**Comment by rebecapf** [comment]
as configurações estão assim, em ambos os sites:

<sro_tracking_job>0</sro_tracking_job>
<sro_username>ECT</sro_username>
<sro_password>SRO</sro_password>
<sro_type>L</sro_type>
<sro_result>U</sro_result>
<sro_language>101</sro_language>

<url_sro_correios>http://webservice.correios.com.br/service/rastro/Rastro.wsdl</url_sro_correios>
<url_tracking>http://websro.correios.com.br/sro_bin/txect01$.QueryList</url_tracking>
<url_sigepweb>https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl</url_sigepweb>


o usuário e a senha estão no banco, q coloquei os campos lá nas configurações

eu consigo simular esse webservice (http://webservice.correios.com.br/service/rastro/Rastro.wsdl) direto só passando os parametros? conhece algum jeito?

**Comment by rebecapf** [comment]
Rafael, descobri que não notifica quando tem só um código pra monitorar. Coloquei mais um no mesmo pedido e deu certo.
sabe como arrumar?

parece que é nessa parte do codigo do arquivo Sro.php

if (isset($response->return) && $response->return->qtd > 0) {
            foreach ((array)$response->return->objeto as $obj) {
                $track = $trackList->getItemByColumnValue('number', $obj->numero);
                if ($track) {
                    $item = Mage::getModel('pedroteixeira_correios/sro_object');
                    $item->setTrack($track)
                        ->setInfo($obj);
                    $sroObjects->addItem($item);
                } else {
                    Mage::log("Cant locate track for {$obj->numero}");
                }
            }
        }


é como se ele não entrasse no "if ($track) {" quando só tem um código...

**Comment by rebecapf** [comment]
Fiz uma "leve" gambiarra hehe

```
 if (isset($response->return) && $response->return->qtd > 0) {


			$aReturn = (array)$response->return;
			if($response->return->qtd == 1){
				$objeto = $response->return->objeto;
				$aReturn[objeto]=null;
				$aReturn[objeto][0]=$objeto;
			}
            foreach ($aReturn[objeto] as $obj) {


                $track = $trackList->getItemByColumnValue('number', $obj->numero);
                if ($track) {
                    $item = Mage::getModel('pedroteixeira_correios/sro_object');
                    $item->setTrack($track)
                        ->setInfo($obj);
                    $sroObjects->addItem($item);
                } else {
                    Mage::log("Cant locate track for {$obj->numero}");
                }
            }
        }

```
quando tem só um código eu criei a coluna [0], já que não vem essa coluna no response, aí não tava conseguindo pegar o $obj->numero...

tem alguma forma melhor pra fazer isso?

**Comment by rafaelpatro** [comment]
Acho que nunca testei com um único objeto. E nesse caso _objeto_ não é uma lista.
Estou no celular agora, e não consigo testar; mas, se sua customização funcionou, manda uma PR. Obrigado pela contribuição.

**Comment by rebecapf** [comment]
pois é... eu tive que converter para array pra poder fazer a gambiarra, por isso perguntei se tinha uma forma melhor kkk
eu não sei fazer PR, mas quando descobrir eu mando lá 😀
