### ISSUE TITLE
Status ñ muda automaticamente de Complete para Closed

### ISSUE THREAD

**Issue by joao-github** [pedro-teixeira/correios#48]
Esse recurso antes funcionava na versão anterior (eu usava na versão 1.7 do Magento) mas parece que agora não tá mais funcionando. Isso é bug dos Correios ou do módulo? Se puder verificar seria ótimo, isso é fundamental na rotina de um ecommerce.

**Comment by pedro-teixeira** [comment]
@joao-github, você não está seguindo as regras para criação de issue: https://github.com/pedro-teixeira/correios/blob/master/CONTRIBUTING.md#como-contribuir

Não entendi qual o problema.

**Comment by joao-github** [comment]
Quando o pacote é dado como "Entrega efetuada" no site dos Correios, o status no Magento também não deveria mudar para "Closed" ou "Entregue" etc? Isso não está acontecendo.

**Comment by pedro-teixeira** [comment]
Essa feature não existe, por favor envie sua PR.

**Comment by joao-github** [comment]
Estranho, eu tinha a impressão que no Magento 1.7 usando a versão 4.2 do plugin que isso acontecia. Desculpe perguntar, mas, o que é "PR"?

**Comment by pedro-teixeira** [comment]
https://help.github.com/articles/using-pull-requests/

**Comment by joao-github** [comment]
Tem algum jeito de mudar de "Complete" pra "Closed" automaticamente? Já viu algum módulo que faça isso?

**Comment by pedro-teixeira** [comment]
Não conheço nenhum módulo, mas sim, é possível.

**Comment by pedro-teixeira** [comment]
Duplicado com https://github.com/pedro-teixeira/correios/issues/53.
