### ISSUE TITLE
erro no gerar entrega?

### ISSUE THREAD

**Issue by marceloza** [pedro-teixeira/correios#49]
Pedro boa tarde
eu recebo esse erro ao gerar um entrega
Fatal error: Call to a member function isShippingLabelsAvailable() on a non-object in /home/storage/4/3c/7f/bibliacor/public_html/app/code/core/Mage/Adminhtml/Block/Sales/Order/Shipment/Create/Items.php on line 132
eu vi que uma patch de correçao sua mas não acho em lugar algum?
pode me indicar o caminho?

**Comment by pedro-teixeira** [comment]
Por favor siga as regras para report de bug: https://github.com/pedro-teixeira/correios/blob/master/CONTRIBUTING.md
