### ISSUE TITLE
Dúvida em relação ao peso

### ISSUE THREAD

**Issue by carmolim** [pedro-teixeira/correios#52]
Na minha loja o peso está configurado para gramas, quando eu adiciono o peso de 58 eu salvo e quando volto a editar o produto ele aparece 58.000, preciso me preocupar com isso?

**Comment by pedro-teixeira** [comment]
@carmolim, o número está em formato americano,

**Comment by carmolim** [comment]
onde faço essa alteração?

**Comment by pedro-teixeira** [comment]
Não tem alteração para se fazer, é só o formato que o Magento escolheu para formatação de números.
