### ISSUE TITLE
Atualização de status da entrega

### ISSUE THREAD

**Issue by joao-github** [pedro-teixeira/correios#53]
Existe na estrutura de templates de email do Magento um modelo chamado "shipment_update" que é usado para notificar o cliente que houve uma atualização de entrega do pedido, pelo que pesquisei na internet. Não há possibilidade de aprimorar o módulo de maneira que esse template de email seja usado pra enviar um email ao cliente quando a remessa é dada como entregue lá no webservice dos Correios? Ele receberia um email do tipo "Olá Fulano, verificamos que seu pedido foi entregue!".  É uma rotina padrão da maioria dos ecommerces, e pro Magento também deveríamos ter esse recurso. Já foi pensado nisso para uma próxima versão? Trata-se de algo fundamental na rotina de vendas de uma loja, pois da forma que é hoje, temos que criar um status "Entregue", associá-lo ao estado "complete" e aí notificar manualmente o comprador sobre a conclusão da entrega. Já imaginaram se tivermos uns 50 pedidos por dia? Ficaria inviável. Espero que isso possa ser incluso em novas versões, é algo fundamental !

**Comment by pedro-teixeira** [comment]
Sim, é possível, só enviar sua pull requests com as mudanças.
