### ISSUE TITLE
CEP's com alguma restrição

### ISSUE THREAD

**Issue by FilippeQP** [pedro-teixeira/correios#54]
Tenho um problema e o erro está sendo apresentado para alguns CEP's de destino na loja.

"Esse método de envio está fora do ar. Por favor entre em contato conosco."

Pelo que percebi tem a ver com os CEP's com alguma restrição que agora o correios estão fazendo.
O mesmo CEP apresentam o erro no cálculo no site dos Correios que estão com alguma observação (prazo diferenciado, entrega restrita, etc).

Segue um cep para ser testado 08040150, este está apresentado o erro no meu cálculo.
Estamos perdendo vendas, pois o cliente muitas vezes não entra em contato com nosso atendimento.
Gostaríamos muito de saber se existe uma solução de maneira que o seu módulo  ainda continue calculando o frete. 

Magento versão. 1.6.2.0
Versão 4.2.0 do módulo
Ainda não tem contrato com os correios.

Cordialmente.

**Comment by pedro-teixeira** [comment]
@FilippeQP você não está usando a última versão.

**Comment by FilippeQP** [comment]
Obrigado Pedro Teixeira, mas você está dizendo a versão do módulo?

**Comment by pedro-teixeira** [comment]
Sim.

**Comment by FilippeQP** [comment]
Obrigado, vou providenciar atualização e depois comento aqui. abs.

**Comment by FilippeQP** [comment]
Deu certo... muito obrigado pela ajuda. Abs.
