### ISSUE TITLE
Nem sempre calcula o frete

### ISSUE THREAD

**Issue by MatNeves** [pedro-teixeira/correios#55]
Ao calcular frete do pedido, o método dos Correios só aparece as vezes. Quando não aparece, recebo o log abaixo.

### Logs

2015-02-19T15:29:05+00:00 DEBUG (7): pedroteixeira_correios [163]: URL Error, all services return with error

### Passos para reproduzir

1. Página do produto / Carrinho / Checkout
2. Inserir CEP para simulação
3. Calcular...

### Dados técnicos

* Versão do Magento: 1.7.0.2
* Versão do módulo: v4.3.0

**Comment by pedro-teixeira** [comment]
@MatNeves, isso provavelmente é uma instabilidade dos Correios, você consegue fazer uma chamada manual na API dos Correios para ver o resultado?

**Comment by MatNeves** [comment]
Pode me indicar como eu faço isso? Algum manual, etc...

**Comment by pedro-teixeira** [comment]
http://www.correios.com.br/para-voce/correios-de-a-a-z/pdf/calculador-remoto-de-precos-e-prazos/manual-de-implementacao-do-calculo-remoto-de-precos-e-prazos

**Comment by MatNeves** [comment]
Eu fiz um log do ```$content``` do CorreiosMethod.php e ele está retornando isso quando não carrega:

```
<?xml version="1.0" encoding="ISO-8859-1" ?>
<Servicos>
	<cServico>
		<Codigo>40010</Codigo>
		<Valor>0,00</Valor>
		<PrazoEntrega>0</PrazoEntrega>
		<ValorSemAdicionais>0,00</ValorSemAdicionais>
		<ValorMaoPropria>0,00</ValorMaoPropria>
		<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
		<ValorValorDeclarado>0,00</ValorValorDeclarado>
		<EntregaDomiciliar></EntregaDomiciliar>
		<EntregaSabado></EntregaSabado>
		<Erro>-5</Erro>
		<MsgErro><![CDATA[O Valor Declarado nao deve exceder R$ 10.000,00.]]></MsgErro>
	</cServico>
	<cServico>
		<Codigo>41106</Codigo>
		<Valor>0,00</Valor>
		<PrazoEntrega>0</PrazoEntrega>
		<ValorSemAdicionais>0,00</ValorSemAdicionais>
		<ValorMaoPropria>0,00</ValorMaoPropria>
		<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
		<ValorValorDeclarado>0,00</ValorValorDeclarado>
		<EntregaDomiciliar></EntregaDomiciliar>
		<EntregaSabado></EntregaSabado>
		<Erro>-5</Erro>
		<MsgErro><![CDATA[O Valor Declarado nao deve exceder R$ 10.000,00.]]></MsgErro>
	</cServico>
</Servicos>
```

Sendo que o valor declarado é de: 239,90 (exatamente com essa formatação).

**Comment by pedro-teixeira** [comment]
@MatNeves, como você pode ver no `$client->request()` o `nVlValorDeclarado` está correto, então só pode ser algum problema nos Correios.

Você conseguiu fazer a chamada manual usando os mesmos parâmetros?

**Comment by MatNeves** [comment]
Sim, consegui. Agora se eu setar um valor fixo em:
```$client->setParameterGet('nVlValorDeclarado', 200);```
ou colocar com a formatação:
```$client->setParameterGet('nVlValorDeclarado', number_format($this->_packageValue, 0, '', ''));```
funciona.

No caso, deixei com a seguinte configuração:
```$client->setParameterGet('nVlValorDeclarado', ceil(number_format($this->_packageValue, 0, '', '')));```

**Comment by MatNeves** [comment]
Não sei se cabe colocar na mesma Issue, mas o erro:
"O CEP de destino está temporariamente sem entrega domiciliar. A entrega será efetuada na agência indicada no Aviso de Chegada que será entregue no endereço do destinatário."
retorna valores e prazos no XML, mas não exibe na loja.

**Comment by pedro-teixeira** [comment]
Tem uma configuração com o número de erros que podem ser ignorados, só adicionar lá.

Estou fechando esse issue já que não é relacionado com o módulo.
