### ISSUE TITLE
Frete não atualiza valor total da compra

### ISSUE THREAD

**Issue by guztavoalves** [pedro-teixeira/correios#56]
Pedro, boa tarde.

Estou com um problema que não sei bem se é o meu OSC ou algo no módulo, quando troco de tipo de frete o total da compra não atualiza e nem troca o tipo de frete, para usuarios novos que não possuem endereço cadastrados e que digitam o endereço de entrega dentro do OSC o módulo não captura esses dados e gera os tipos de frete... veja imagem no link:

http://prntscr.com/6757fv

Vlw

**Comment by pedro-teixeira** [comment]
@guztavoalves, isso não tem relação com o módulo de frete.
