### ISSUE TITLE
erro ao calcular frete em alguns produtos

### ISSUE THREAD

**Issue by dsalvanhini** [pedro-teixeira/correios#57]
em alguns produtos da minha loja ao calcular o frete recebo a mensagem "Esse método de envio está fora do ar. Por favor entre em contato conosco" habilitei o log e no log é registrado

2015-02-21T13:44:20+00:00 DEBUG (7): pedroteixeira_correios [312]: URL Error - Bad XML [301]

pelo que percebi somente os produtos que estão com o nome maior estão dando esse problema.

produto dando erro

http://www.minhaloja.com.br/relogio-de-ponto/control-id-relogio-de-ponto-eletronico-biometrico-portaria-1510-rep-idx-completo-com-software-secullum-4-ate-200-funcionarios-bobina.html

produto que não da erro

http://www.minhaloja.com.br/kit-bastao-vigia-henry-10-ibutton-software-controle-de-ronda.html

o que podemos fazer para corrigir isso?

**Comment by pedro-teixeira** [comment]
@dsalvanhini, não acho que o nome do produto seja o problema, pelo erro me parece que os Correios estão instáveis.

**Comment by dsalvanhini** [comment]
Pedro, eu tb achei isso no inicio, mas os produtos com nome pequenos, ex de um link que voce pode verificar

http://www.imperiodocomputador.com.br/kit-bastao-vigia-henry-10-ibutton-software-controle-de-ronda.html

nesse link ele sempre traz os resultados dos calculos.

mas no link

http://www.imperiodocomputador.com.br/relogio-de-ponto-eletronico-biometrico-rep-portaria-1510-henry-prisma-super-facil-r02-biometria-1900-digitais-proximidade-software-secullum-4-ate-200-funcionarios-bobina.html

ou

http://www.imperiodocomputador.com.br/control-id-relogio-de-ponto-eletronico-biometrico-portaria-1510-rep-idx-completo-com-software-secullum-4-ate-200-funcionarios-bobina.html

ambos nunca fazem o calculo

e no log recebo.

2015-02-21T20:48:34+00:00 DEBUG (7): pedroteixeira_correios [312]: URL Error - Bad XML [301]
2015-02-21T20:48:35+00:00 DEBUG (7): pedroteixeira_correios [312]: URL Error - Bad XML [301]


se fosse alguma instabilidade não deveria reeber o log

DEBUG (7): pedroteixeira_correios [312]: URL Error - Unable to Connect to tcp://ws.correios.com.br:80. Error #110: Connection timed

**Comment by dsalvanhini** [comment]
???

**Comment by pedro-teixeira** [comment]
@dsalvanhini o log "Unable to Connect" e "Bad XML" significa que a API dos Correios não estava online ou respondeu um XML que não estava no formato.

Você pode debugar as chamadas para tentar pegar a resposta dos Correios e aí analisamos ela.

**Comment by dsalvanhini** [comment]
como faço para debugar? pode me ajudar?

**Comment by pedro-teixeira** [comment]
Você pode usar logs, print, var_dump, o que achar melhor.

**Comment by agusddt** [comment]
Pedro boa noite!
O log do Magento da "DEBUG (7): pedroteixeira_correios [337]: URL Error - Bad XML [326]" e no frontend sempre a mesma mensagem "Esse método de envio está fora do ar. Por favor entre em contato conosco." Por algum motivo não esta se ocmunicando com os correios. Sabe como posso fazer? obrigada!
