### ISSUE TITLE
erro na dimensões do correios

### ISSUE THREAD

**Issue by radamiBR** [pedro-teixeira/correios#58]
Parabéns Pedro Teixeira por esse módulo.

Tenho alguns produtos com tamanho inferior aos do correios por exemplo:
Comprimento: 5cm - Largura: 3cm - Altura: 2cm

Quando cliente coloca 10 unidades desse produto no carrinho e faz calculo do correios da erro de dimensões.
Exemplo: Comprimento: 50cm - Largura 30cm - Altura 20cm
Que da o padrão das dimensões do correios.

O que pode ser?

Obrigado

**Comment by pedro-teixeira** [comment]
@radamiBR, existem mínimos de dimensões: http://www.correios.com.br/para-voce/precisa-de-ajuda/limites-de-dimensoes-e-de-peso

E o cálculo para múltiplos produtos é feito por peso volumétrico, não dimensões somadas.

**Comment by radamiBR** [comment]
Como trabalho com pequenos objetos pensei que o calculo da dimensões tinha nesse modulo, pois tem diferença de valores pelo correios pois eles usam peso cubico nos seus calculos.

Vai ter na nova versões o calculo das dimensões?

**Comment by pedro-teixeira** [comment]
Não entendi a pergunta, hoje já é peso cúbico.

**Comment by radamiBR** [comment]
O peso cúbico não e calculado, pois se 10 produtos com diametros de Comprimento: 5cm - Largura: 3cm - Altura: 2cm, sai peso cúbico de Comprimento 50cm, largura 30cm, altura 20cm.

No módulo não da dimensão do correios pois não faz calculo dos 10 produtos, mas da uma caixa no limite das normas do correios do peso cúbico.

**Comment by pedro-teixeira** [comment]
Não, ele faz o cálculo do peso cúbico dos 10 produtos. O problema no seu caso é que ele também valida as dimensões de cada um deles individualmente, nada que você não posso remover no seu código.

**Comment by radamiBR** [comment]
Alguma dica como posso fazer isso Pedro.

**Comment by pedro-teixeira** [comment]
Você pode usar a opção no admin "Validar Dimensões dos Produtos"
