### ISSUE TITLE
Erro 99 Input string was not in a correct format.

### ISSUE THREAD

**Issue by jarjar123** [pedro-teixeira/correios#59]
Recentemente descobri um problema que retorna uma resposta inválida (não XML) dos Correios.
E ocorre na seguinte situação:
* Opção de enviar __Valor Declarado__ ativa
* Valor do pedido superior a mil reais

Nessa situação a loja simplesmente não exibe valor algum. Mas o retorno dos Correios é `99Input string was not in a correct format.`.

Não sei desde quando este problema ocorre. Mas descobri que a causa do erro é o campo __Valor Declarado__ ser enviado com separador de milhar.

A correção é bem simples. Assim que tiver tempo envio uma PR.

**Comment by pedro-teixeira** [comment]
Perfeito @jarjar123, fico no aguardo!
