### ISSUE TITLE
Problema de Bad_XML com produtos com valores acima de R$ 1000,00

### ISSUE THREAD

**Issue by RicardoHL3BR** [pedro-teixeira/correios#60]
Começou a alguns dias atras, quando o produto ou carrinho ultrapassa R$ 999,99 o frete não é calculado e apresenta o erro "Esse método de envio está fora do ar. Por favor entre em contato conosco.". Quando o produto tem valor abaixo disso, o frete é calculado normalmente.

### Log com Erro
2015-02-27T00:00:11+00:00 DEBUG (7): http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx
2015-02-27T00:00:11+00:00 DEBUG (7): Zend_Http_Client Object
(
    [config:protected] => Array
        (
            [maxredirects] => 5
            [strictredirects] => 
            [useragent] => Zend_Http_Client
            [timeout] => 60
            [adapter] => Zend_Http_Client_Adapter_Socket
            [httpversion] => 1.1
            [keepalive] => 
            [storeresponse] => 1
            [strict] => 1
            [output_stream] => 
            [encodecookies] => 1
            [rfc3986_strict] => 
        )

    [adapter:protected] => 
    [uri:protected] => Zend_Uri_Http Object
        (
            [_username:protected] => 
            [_password:protected] => 
            [_host:protected] => ws.correios.com.br
            [_port:protected] => 80
            [_path:protected] => /calculador/CalcPrecoPrazo.aspx
            [_query:protected] => 
            [_fragment:protected] => 
            [_regex:protected] => Array
                (
                    [escaped] => %[[:xdigit:]]{2}
                    [unreserved] => [A-Za-z0-9-_.!~*'()\[\]]
                    [segment] => (?:%[[:xdigit:]]{2}|[A-Za-z0-9-_.!~*'()\[\]:@&=+$,;])*
                    [path] => (?:\/(?:(?:%[[:xdigit:]]{2}|[A-Za-z0-9-_.!~*'()\[\]:@&=+$,;])*)?)+
                    [uric] => (?:%[[:xdigit:]]{2}|[A-Za-z0-9-_.!~*'()\[\];\/?:@&=+$,])
                )

            [_scheme:protected] => http
        )

    [headers:protected] => Array
        (
        )

    [method:protected] => GET
    [paramsGet:protected] => Array
        (
            [StrRetorno] => xml
            [nCdServico] => 40010,41106
            [nVlPeso] => 15.13
            [sCepOrigem] => 05512100
            [sCepDestino] => 04344080
            [nCdFormato] => 1
            [nVlComprimento] => 16
            [nVlAltura] => 2
            [nVlLargura] => 11
            [sCdMaoPropria] => N
            [sCdAvisoRecebimento] => S
            [nVlValorDeclarado] => 1.152,94
        )

    [paramsPost:protected] => Array
        (
        )

    [enctype:protected] => 
    [raw_post_data:protected] => 
    [auth:protected] => 
    [files:protected] => Array
        (
        )

    [cookiejar:protected] => 
    [last_request:protected] => 
    [last_response:protected] => 
    [redirectCounter:protected] => 0
)

2015-02-27T00:00:12+00:00 DEBUG (7): pedroteixeira_correios [315]: URL Error - Bad XML [304]

### Log do produto sem erro
2015-02-27T00:00:34+00:00 DEBUG (7): http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx
2015-02-27T00:00:34+00:00 DEBUG (7): Zend_Http_Client Object
(
    [config:protected] => Array
        (
            [maxredirects] => 5
            [strictredirects] => 
            [useragent] => Zend_Http_Client
            [timeout] => 60
            [adapter] => Zend_Http_Client_Adapter_Socket
            [httpversion] => 1.1
            [keepalive] => 
            [storeresponse] => 1
            [strict] => 1
            [output_stream] => 
            [encodecookies] => 1
            [rfc3986_strict] => 
        )

    [adapter:protected] => 
    [uri:protected] => Zend_Uri_Http Object
        (
            [_username:protected] => 
            [_password:protected] => 
            [_host:protected] => ws.correios.com.br
            [_port:protected] => 80
            [_path:protected] => /calculador/CalcPrecoPrazo.aspx
            [_query:protected] => 
            [_fragment:protected] => 
            [_regex:protected] => Array
                (
                    [escaped] => %[[:xdigit:]]{2}
                    [unreserved] => [A-Za-z0-9-_.!~*'()\[\]]
                    [segment] => (?:%[[:xdigit:]]{2}|[A-Za-z0-9-_.!~*'()\[\]:@&=+$,;])*
                    [path] => (?:\/(?:(?:%[[:xdigit:]]{2}|[A-Za-z0-9-_.!~*'()\[\]:@&=+$,;])*)?)+
                    [uric] => (?:%[[:xdigit:]]{2}|[A-Za-z0-9-_.!~*'()\[\];\/?:@&=+$,])
                )

            [_scheme:protected] => http
        )

    [headers:protected] => Array
        (
        )

    [method:protected] => GET
    [paramsGet:protected] => Array
        (
            [StrRetorno] => xml
            [nCdServico] => 40010,41106
            [nVlPeso] => 9.15
            [sCepOrigem] => 05512100
            [sCepDestino] => 04344080
            [nCdFormato] => 1
            [nVlComprimento] => 16
            [nVlAltura] => 2
            [nVlLargura] => 11
            [sCdMaoPropria] => N
            [sCdAvisoRecebimento] => S
            [nVlValorDeclarado] => 610,59
        )

    [paramsPost:protected] => Array
        (
        )

    [enctype:protected] => 
    [raw_post_data:protected] => 
    [auth:protected] => 
    [files:protected] => Array
        (
        )

    [cookiejar:protected] => 
    [last_request:protected] => 
    [last_response:protected] => 
    [redirectCounter:protected] => 0
)

### Passos para reproduzir

1. Adicionar um produto cadastrado com valor acima de R$ 1000,00 no carrinho
2. Tentar calcular o frete
3. Se for alterado o valor do produto (o mesmo que deu erro no primeiro passo) cadastrado para abaixo de R$ 999,99 o frete é calculado normalmente, se colocar em qualquer valor acima de 999,99 ele da erro no frete

OBS* pode ser alguma alteração no webservice dos Correios, pois começou recentemente (nunca deu erro). 

### Dados técnicos

* Versão do Magento: 1.7.0.1
* Versão do módulo: v4.2.0 e v4.3.0

**Comment by pedro-teixeira** [comment]
@RicardoHL3BR, muito obrigado pelo report do problema, está perfeito! Esse problema vai ser corrigido na PR https://github.com/pedro-teixeira/correios/pull/47

Você pode aplicar o fix enquanto não faço o merge. No arquivo `app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php` troque a linha:

`$client->setParameterGet('nVlValorDeclarado', number_format($this->_packageValue, 2, ',', '.'));`

Por:

`$client->setParameterGet('nVlValorDeclarado', number_format($this->_packageValue, 2, ',', ''));`

**Comment by pedro-teixeira** [comment]
Por favor me avise se o erro continua depois do fix.

**Comment by RicardoHL3BR** [comment]
Perfect. Resolvido com Sucesso. Muito obrigado pelo rápido auxilio e por ter desenvolvido esse magnifico modulo.

**Comment by ivanbauer** [comment]
Valeu Pedro! Funcionou aqui também. Muito obrigado!

**Comment by leovirgilio** [comment]
Ocorreu o mesmo comigo. E aqui também funcionou, obrigado!
