### ISSUE TITLE
Titulo no frete correios

### ISSUE THREAD

**Issue by radamiBR** [pedro-teixeira/correios#61]
Qual parte do código posso retirar () do resultado da consulta dos correios, exemplo abaixo:

ASSIM:
(Correios - PAC - Estimativa de entrega: 5 dia(s)) R$ 9,97

PARA:
Correios - PAC - Estimativa de entrega: 5 dia(s) R$ 9,97

Obrigado

**Comment by pedro-teixeira** [comment]
@radamiBR, essa não é a mensagem padrão, você já mudou ela. Fica nas configurações em `Mensagem que Exibe o Prazo de Entrega`.

**Comment by radamiBR** [comment]
sim já mudei, queria era tirar o parênteses da mensagem exemplo:

COM PARENTESE
(  Correios - PAC - Estimativa de entrega: 5 dia(s)   ) 

DEIXA ASSIM - SEM PARENTESE
Correios - PAC - Estimativa de entrega: 5 dia(s)

**Comment by pedro-teixeira** [comment]
A mensagem não é alterada dentro do módulo: https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php#L350

Talvez seja seu template.

**Comment by radamiBR** [comment]
Estou usando template default do magento, queria tirar somente os parêntese que fica na frase, como exemplo acima.

**Comment by pedro-teixeira** [comment]
Bom, se você não colocou eles na mensagem pode ver no código que não adiciono eles.

**Comment by radamiBR** [comment]
ok obrigado
