### ISSUE TITLE
Prazo do adicionais para cada serviços do correios, pac, sedex, e-sedex

### ISSUE THREAD

**Issue by radamiBR** [pedro-teixeira/correios#62]
Olá Pedro, tudo bem

Como posso adicionar ao prazo dos Correios (dias) para cada serviço do correios, exemplo:
Sedex = 4 dias
PAC = 5 dias
E-Sedex= 3 dias

Quando adicionado o prazo a mais 2 dias, vai para todos os envio do correios.
Aonde posso adicionar no código para cada serviços do corrreios individualmente.

Obrigado

**Comment by pedro-teixeira** [comment]
Essa feature não existe, você está convidado para enviar uma pull request.

**Comment by jarjar123** [comment]
Boa tarde @radamiBR e @pedro-teixeira 

Me ocorreu que esse recurso seria ainda melhor se fosse extensível ao catálogo de produtos.
É bem comum as lojas disponibilizarem itens para envio imediato, e outros itens com prazo (ou sob encomenda). Nesse caso a cotação só precisaria exibir o maior prazo. Enfim, configurar o prazo por serviço e por produto, seria uma melhora e tanto.

Trabalharei nisso assim q possível.

**Comment by carlosmarchi** [comment]
@jarjar123 acredito que o prazo adicional por produto (talvez através de um atributo) já resolva, sem necessidade de ainda ajustar por serviço.

Não sou programador, apenas me viro adaptando códigos aqui e ali, mas se eu puder contribuir de alguma forma para o desenvolvimento, tenho bastante interesse nesta feature.
