### ISSUE TITLE
Valor divergente.

### ISSUE THREAD

**Issue by Calkines** [pedro-teixeira/correios#64]
Estou encontrando problemas para validar uma dimensão...

Alguém pode me dar uma ajuda a descobrir o porquê o site do correios devolve um valor para as medidas (CxLxA) 48 x 23 x 47, enquanto o valor devolvido pelo módulo é outro ? O peso é 4 KG.

Agradeço à todos.

Descrição detalhada do problema.

### Logs

Não se aplica.

### Passos para reproduzir

1. Configurar dimensões (CxLxA) 48 x 23 x 47 para um produto.
2. Consultar site do correios (http://www2.correios.com.br/sistemas/precosPrazos/) e informar as mesmas dimensões.
3. Comparar o valor devolvido pelo site do correios com o valor devolvido pelo módulo.

### Dados técnicos

* Versão do Magento: 1.9.1.0
* Versão do módulo: v4.2.0

**Comment by jarjar123** [comment]
A cubagem do seu pacote é de 8kg. E o módulo envia o peso cubado no lugar do peso real.
Mas os Correios desconsideram qualquer cubagem até 10kg.
Resumindo os Correios considerariam 4kg, se o sistema não enviasse 8kg.
Esse problema será corrigido na PR #47

**Comment by pedro-teixeira** [comment]
@Calkines, esse problema deve estar resolvido na `v4.4.0`, pode testar? Se continuar sem resolução é só reabrir o ticket.
