### ISSUE TITLE
Esse método de envio está fora do ar. Por favor entre em contato conosco.

### ISSUE THREAD

**Issue by fernandogargula** [pedro-teixeira/correios#67]
ao utilizar a versão 4.3 está ocorrendo esse erro: Esse método de envio está fora do ar. Por favor entre em contato conosco.
como corrigi-lo?
muito obrigado.
abs.

**Comment by pedro-teixeira** [comment]
@fernandogargula, esse erro acontece quando os Correios estão fora do ar. Por favor siga as regras para reportar erros e envie os logs: https://github.com/pedro-teixeira/correios/blob/master/CONTRIBUTING.md

Você pode usar o app para iPhone para validar a API dos Correios: https://pedroteixeira.io/app-de-iphone-para-checar-se-os-correios-estao-online/
