### ISSUE TITLE
Selecionar serviços por produto

### ISSUE THREAD

**Issue by Veiote** [pedro-teixeira/correios#69]
Instalei essa versão 4.4.0 para testes no magento 1.9.1.0, atualmente uso uma versão anterior 4.2, selecionei apenas sedex em um produto, mas no calculo do frete do carrinho continuam aparecendo todos os outros serviços.

Alguem mais com este problema?

**Comment by pedro-teixeira** [comment]
Você precisa habilitar essa feature em "Habilitar Filtro de Serviços por Produto".
