### ISSUE TITLE
Atualizar a documentação para `Configurando o módulo`

### ISSUE THREAD

**Issue by pedro-teixeira** [pedro-teixeira/correios#70]
Remover campos que não existem mais e explicar novos campos.

**Comment by jarjar123** [comment]
Bom dia @pedro-teixeira 
Para que o `README.md` não fique tão grande, seria interessante habilitar o Wiki nas configurações do Github.

**Comment by pedro-teixeira** [comment]
@jarjar123, we realmente não gosto do Wiki, prefiro os markdowns que tem histórico, pull request e tudo mais. Podemos criar uma pasta `doc` e dividir a documentação.

**Comment by jarjar123** [comment]
Sim, melhor mesmo.
