### ISSUE TITLE
Retornar false para falta de método de envio em _removeInvalidServices

### ISSUE THREAD

**Issue by pedro-teixeira** [pedro-teixeira/correios#71]
Aparentemente se `_removeInvalidServices` não resultar em nenhum método não é retornado falso e não vai cair na validação: https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php#L105

O correto seria retornar falso e ter uma mensagem de erro para esse caso.

**Comment by pedro-teixeira** [comment]
@jarjar123, o que acha desse caso?

**Comment by jarjar123** [comment]
Olá Pedro. Esse método está funcionando da seguinte forma.

* Situação 1:
    Retorna uma lista de serviços de postagem, filtrada apenas com serviços válidos.
    Entra: 41068,40096,41300
    Sai: 40096,41300

* Situação 2:
    Retorna uma lista vazia de serviços de postagem, caso o usuário tenha de-selecionado todos os serviços, nas opções de configuração.
    Entra: Vazio
    Sai: Vazio

* Situação 3:
    Retorna erro (FALSE) caso todos os serviços de postagem tenham sido eliminados no processo de filtragem.
    Entra: 41068,40096,41300
    Sai: Vazio

Nas situações 1 e 2 o logista optou pelo resultado.
Já na situação 3, o logista é surpreendido por uma situação inesperada, onde foram eliminados todos os serviços.

Acredito que você esteja especulando a situação 2. Mas acho que esta situação não deveria acusar erro, pois não é inesperada. Nenhum serviço foi removido no processo de filtragem. O logista optou por não realizar cotação alguma.

**Comment by pedro-teixeira** [comment]
Estou falando da situação 3, que pode acontecer caso o `midSize` esteja fora dos limites ou a opção `check_dimensions` esteja desabilitada.

**Comment by jarjar123** [comment]
Ok. Mas mesmo nesse caso, `_removeInvalidServices` irá retornar FALSE, e lançar a Exceção.

**Comment by jarjar123** [comment]
Sempre que estiver fora dos limites, o midSize se divide, recursivamente.
Importante: A validação é aplicada somente para os limites superiores.
Logo, sempre encontraremos um midSize compatível.

**Comment by jarjar123** [comment]
Complementando...
Este trecho garante que há ao menos um serviço configurado para o carrinho, pelo logista.

    $isLoopBreakable = (count($this->_postMethodsExplode) > 0);

E não importa se midSize for igual 100cm, 1000cm ou 10000cm. Após sucessivas divisões, em algum momento, irá se encaixar nos limites do serviço.

**Comment by jarjar123** [comment]
Dei uma reanalisada no código, e segue algumas correções do que falei anteriormente...

* Só há uma única possibilidade dessa função retornar FALSE, e consequentemente lançar a exceção. Isso ocorrerá somente se a Divisão de Pacotes estiver desativada.

* Se a Divisão estiver ativada, sempre encontraremos um tamanho ideal (midSize) para o pacote.
