### ISSUE TITLE
Áreas de Risco

### ISSUE THREAD

**Issue by DaviSiqueira** [pedro-teixeira/correios#75]
Seria possível adicionar a informação de área de risco?

Por exemplo no site dos correios retorna esta mensagem:
"Pac - O CEP de destino está sujeito a condições especiais de entrega pela ECT e será realizada com o acréscimo de até 7 (sete) dias ao prazo regular."
E abaixo o prazo: "Dia da Postagem + 10 dias úteis"
![captura de tela 2015-04-07 as 18 44 59](https://cloud.githubusercontent.com/assets/4529729/7034208/5178f56c-dd56-11e4-8af3-236b475d66e2.png)

Neste módulo só da o prazo: "PAC - 10 dia(s) útil(eis) a partir da data de postagem"

O CEP que eu utilizei é o 04475-490

O módulo o willstorm tem esta "função" que retorna o aviso de área de risco (não utilizo ele pois acho este mais completo)
![captura de tela 2015-04-07 as 18 47 04](https://cloud.githubusercontent.com/assets/4529729/7034247/9cc2f20c-dd56-11e4-96f3-05b0dc1534c0.png)

Link do módulo do willstorm https://github.com/willstorm/correios/

Na minha opinião só falta isso pro módulo ficar 100%

**Comment by jarjar123** [comment]
Então @DaviSiqueira, também reparei na falta desse recurso há um tempo.
Implementei a solução a seguir, acredito que seja uma resolução mais adequada para o problema.
![image](https://cloud.githubusercontent.com/assets/3688798/7054342/5a568386-de12-11e4-95be-cf54c9270128.png)
Sempre que aparece um erro do tipo __soft_error__ (009, 010, 011), todos os serviços contemplam o mesmo erro. Logo, achei mais adequado não repetir a mensagem.
Postarei o código na minha PR em breve.

**Comment by pedro-teixeira** [comment]
Manda a PR @jarjar123
