### ISSUE TITLE
Não exibe conteúdo de rastreamento

### ISSUE THREAD

**Issue by rafaelharus** [pedro-teixeira/correios#76]
Reparei um problema recente ao clicar na parte de Vendas > Entregas, em qualquer um dos pedidos clicando no código de rastreio antes exibia um popup com uma tabela com a atual situação do objeto. Só que agora só exibe a frase: Informações de rastreamento não disponíveis no momento.
Percebi também que ao acessar a URL: websro.correios.com.br/sro_bin/txect01$.QueryList?P_LINGUA=001&P_TIPO=001&P_COD_UNI=CODIGO estou sendo redirecionado para http://www2.correios.com.br/sistemas/rastreamento/ sendo o possível causador do problema.

### Passos para reproduzir

1. Acessar o backend da loja
2. Ir em Vendas > Entregas
3. Selecionar um pedido que já esteja exibindo informações do objeto
4. No frame: Informações de Entrega e Rastreamento clique no código de rastreio ou em Monitorar esta entrega.

### Dados técnicos

* Versão do Magento: 1.7.0.2
* Versão do módulo: v4.3.0

**Comment by leovirgilio** [comment]
Estou com esse mesmo problema. Fazendo uma busca rápida, me disseram que s correios mudaram hoje de manhã o link deles para consultar rastreamento.

**Comment by rafaelharus** [comment]
Creio que seja algum problema que a empresa ainda irá reparar, pois os próprios postavam o link em sites como Reclame aqui, para clientes que estavam com problemas.

**Comment by rafaelharus** [comment]
Voltou a funcionar.
