### ISSUE TITLE
Rastreio

### ISSUE THREAD

**Issue by Veiote** [pedro-teixeira/correios#77]
Apenas informando que os Correios aparentemente acabaram com o link http://websro.correios.com.br/sro_bin... que eu já usava a anos e o modulo também utilizava para montar o rastreio.

Acredito que senão voltar o endereço a solução será utilizar o SRO XML http://www.correios.com.br/para-sua-empresa/comercio-eletronico/sistema-de-rastreamento-de-objetos

[]´s

**Comment by leovirgilio** [comment]
O complicado do SRO XML é que necessita de contrato.

**Comment by Veiote** [comment]
Para o uso do rastreio no modulo não importa porque pode usar o usuário teste que permite ate duas consultas na mesma requisição, e no modulo é sempre feita individualmente, se for contrato é possível fazer ate 50 consultas num único evento, o que para o modulo é impertinente.

**Comment by leovirgilio** [comment]
Uhn, entendi. Me parece que voltou ao normal, fiz uma consulta e me retornou certo.

**Comment by Veiote** [comment]
Ainda bem!

Ficam mexendo no que funciona, só pra piorar.

Vou fechar o Issue.

[]´s
