### ISSUE TITLE
Correios prestashop

### ISSUE THREAD

**Issue by maizuum** [pedro-teixeira/correios#79]
Pedro, parabens pela sua colaboração com seus modulos. Somente queria saber se pode fazer e contribuir com um dos correios no prestashop...nao conseguiria fazer um modulos desses de frete com contrato no prestashop???? poderia até cobrar uns 50,00, vai lucrar muito la, pois falta isso..Aguardo

**Comment by pedro-teixeira** [comment]
@maizuum, obrigado pela sugestão mas estou realmente sem disponibilidade para esse projeto.
