### ISSUE TITLE
Erro ao calcular frete

### ISSUE THREAD

**Issue by williangringo** [pedro-teixeira/correios#80]
Ao calcular o frete na página do carrinho (checkout/cart) a página fica em branco e trava o site inteiro.
Já no checkout (onestepchekout) funciona. Verifiquei o log do NGINX, e ele dá erro de exaustão de memoria alocada, eu aumento o limite de memoria e mesmo assim continua dando erro.

**Comment by pedro-teixeira** [comment]
@williangringo, por favor siga as regras ara abertura de issues: https://github.com/pedro-teixeira/correios/blob/master/CONTRIBUTING.md

**Comment by williangringo** [comment]
Descrição detalhada do problema.

### Logs
No log do magento não acontece nada

Já no do NGINX e PHP-FPM
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 112 bytes) in /usr/share/nginx/html/lib/Varien/Simplexml/Element.php on line 195
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 102 bytes) in /usr/share/nginx/html/lib/Zend/Db/Statement/Pdo.php on line 291
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /usr/share/nginx/html/lib/Zend/Db/Select.php on line 953

### Passos para reproduzir
1. Adicionar produto ao carrinho
2. Calcular o frete no carrinho

### Dados técnicos
* Versão do Magento: 1.9.0.1
* Versão do módulo: v4.4.0

**Comment by raulbcs** [comment]
Tem o stacktrace do erro?

**Comment by williangringo** [comment]
não tem.

**Comment by williangringo** [comment]
Já testei e tirei o módulo dos correios e ele funciona perfeitamente.

**Comment by williangringo** [comment]
Alguém sabe como me ajudar? Já tentei de tudo.

**Comment by raulbcs** [comment]
Qual o valor do `memory_limit` no php.ini?

**Comment by williangringo** [comment]
'memory_limit = 512M'

Não adianta o quanto eu aumente o 'memory_limit' ele continua processando até dar timeout

**Comment by williangringo** [comment]
Era a falta de uma biblioteca no servidor.

**Comment by lanapf** [comment]
pedro estou com um problema, o módulo estava funcionando perfeitamente.
Fiz a instalação do módulo One Step Checkout no sistema e infelizmente não deu certo apaguei ele completamente porém ocorreu um problema, o módulo do frete não está mais calculando o sedex o mesmo apresenta apenas o valor do pac no calculo e não vai o valor do frete para a finalização da compra, utilizo o módulo do Mercado Pago.
Obs. Já reinstalei o módulo do frete e o do Mercado Pago e mesmo assim não está dando certo sabe me informar o que pode ser e o que posso tentar fazer para solucionar?
