### ISSUE TITLE
Habilitar módulo para "Recurring Profiles"

### ISSUE THREAD

**Issue by matheusjardimb** [pedro-teixeira/correios#81]
Pretendo criar uma loja que tenha a opção de assinatura para alguns itens. Atualmente, o módulo não aparece nas opções de envio se o produto for um Recurring Profile.

[Feature request]

**Comment by matheusjardimb** [comment]
BTW, o módulo está muito bom :D

**Comment by matheusjardimb** [comment]
Olá @pedro-teixeira ,

Adicionei esse atributo de classe ```protected $_isFixed = true;``` em ```app/code/community/PedroTeixeira/Correios/Model/Carrier/CorreiosMethod.php``` e consegui habilitar o módulo para produtos com recurring profile. 

Porém, o peso está sendo considerado como '0' em algum momento, e por isso o usuário é impedido de usar a forma de entrega. Apenas por teste eu fiz a seguinte alteração:

```
+        $this->_packageWeight = 1;
         // Check weight zero
         if ($this->_packageWeight <= 0) {
             $this->_throwError('weightzeroerror', 'Weight zero', __LINE__);
             return $this->_result;
         }
```

E o peso foi calculado corretamente e pude efetuar a compra com este método de entrega (com produtos recurring profile e produtos tradicionais). Até o momento não identifiquei efeitos colaterais. 
Você pode me indicar como corrigir o problema do peso?

Grato! :smile:

**Comment by jarjar123** [comment]
Posso dar uma olhada futuramente, para entender o motivo do peso estar errado.
Por enquanto segue essa sugestão:
1. Adicionar o método a seguir:

    protected function _getNominalWeight()
    {
        $weight = 0;
        $quote = Mage::getSingleton('checkout/cart')->getQuote();
        if (count($quote->getAllVisibleItems()) == 0) {
            $quote = Mage::getSingleton('adminhtml/session_quote')->getQuote();
        }
        if ($quote->isNominal()) {
            foreach ($quote->getAllVisibleItems() as $item) {
                $product = Mage::getModel('catalog/product')->load($item->getProductId());
                $weight += $product->getWeight();
            }
        }
        return $weight;
    }

2. Localizar o comentário `// Fix weight` e adicionar o trecho a seguir:

        if ($this->_packageWeight == 0) {
            $this->_packageWeight = $this->_getNominalWeight();
        }

Importante: não foi testado!

**Comment by matheusjardimb** [comment]
Obrigado, @jarjar123! Sua sugestão corrigiu o problema. 

Não preciso mais deixar o peso fixo!

A minha alteração combinada com a sua fez com que o módulo se aplica-se à recurring profile tambem (além dos produtos comuns)!

**Comment by pedro-teixeira** [comment]
@matheusjardimb, pode enviar uma pull request com essas mudanças?

**Comment by matheusjardimb** [comment]
@pedro-teixeira claro!

**Comment by matheusjardimb** [comment]
https://github.com/pedro-teixeira/correios/pull/91 @pedro-teixeira @jarjar123
