### ISSUE TITLE
Solução para link no e-mail

### ISSUE THREAD

**Issue by jarjar123** [pedro-teixeira/correios#82]
Segue uma solução rápida para quem quer colocar o link no e-mail.
Esta modificação permite ao logista criar links customizados para qualquer tipo de transportador.

Copiar o arquivo track.phtml do tema base para o seu tema.
`app/design/frontend/base/default/template/email/order/shipment/track.phtml`

Substituir a linha a seguir:

            <td align="center" valign="top" style="padding:3px 9px"><?php echo $this->escapeHtml($_item->getNumber()) ?></td>

Pelo trecho abaixo:

            <?php $block = $this->getLayout()->createBlock('core/template') ?>
            <?php $block->addData(array('item' => $_item)) ?>
            <?php $block->setTemplate("{$_item->getCarrierCode()}/email_order_shipment_track_number.phtml") ?>
            <td align="center" valign="top" style="padding:3px 9px"><?php echo (empty($block->toHtml()) ? $this->escapeHtml($_item->getNumber()) : $block->toHtml()) ?></td>

Dessa forma o sistema estará pronto para ler o link de qualquer transportador. Você só precisa adicioná-lo ao seu tema.

Exemplo de template para os Correios:
`app/design/frontend/default/default/template/pedroteixeira_correios/email_order_shipment_track_number.phtml`

	<?php $_item = $this->getItem() ?>
	<a href="http://websro.correios.com.br/sro_bin/txect01$.QueryList?P_LINGUA=001&P_TIPO=001&P_COD_UNI=<?php echo $this->escapeHtml($_item->getNumber()) ?>">
		<?php echo $this->escapeHtml($_item->getNumber()) ?>
	</a>

Exemplo de template para MatrixRates (qualquer transportadora):
`app/design/frontend/default/default/template/matrixrate/email_order_shipment_track_number.phtml`

	<?php $_item = $this->getItem() ?>
	<?php $order = Mage::getModel('sales/order')->load($_item->getOrderId()) ?>
	<?php $merchantVatNumber = Mage::getStoreConfig('general/store_information/merchant_vat_number', Mage::app()->getStore()->getId()) ?>
	<?php if ($_item->getTitle() == 'TNT Mercúrio'): ?>
		<a href="http://app.tntbrasil.com.br/apps-site/consultarLocalizacaoMercadorias.action?tpCliente=R&nrIdentificacao=<?php echo $merchantVatNumber ?>&tpDocumento=N&method:buscar=Buscar&nrDocumento=<?php echo $this->escapeHtml($_item->getNumber()) ?>">
			<?php echo $this->escapeHtml($_item->getNumber()) ?>
		</a>
	<?php elseif ($_item->getTitle() == 'Rápido Transpaulo'): ?>
		<a href='http://portalweb.transpaulo.com.br/portalweb/hsinext2.aspx?<?php echo $merchantVatNumber ?>,<?php echo $order->getCustomerTaxvat() ?>,<?php echo $this->escapeHtml($_item->getNumber()) ?>'>
			<?php echo $this->escapeHtml($_item->getNumber()) ?>
		</a>
	<?php else: ?>
		<?php echo $this->escapeHtml($_item->getNumber()) ?>
	<?php endif ?>

Talvez a alteração não precise estar vinculada ao módulo de postagem, mas enfim espero que seja útil a comunidade.

**Comment by rafaelpatro** [comment]
UPDATE:
Exemplo de template para os Correios (agora via Rastro.wsdl):
`app/design/frontend/default/default/template/pedroteixeira_correios/email_order_shipment_track_number.phtml`

```php
<?php $_item = $this->getItem() ?>
<a href="<?php echo Mage::helper('shipping')->getTrackingPopupUrlBySalesModel($_item) ?>">
    <?php echo $this->escapeHtml($_item->getNumber()) ?>
</a>
```
