### ISSUE TITLE
Lojista: Para calcular esse serviço você precisa ter contrato com os Correios. 

### ISSUE THREAD

**Issue by dungol** [pedro-teixeira/correios#84]
Olá,
É a primeira vez que estou usando o magento e o módulo de correios. Eu configurei o meu frente com os métodos que não utilizam contrato, mas mesmo assim fico recebendo essa mensagem no carrinho de compras.
Lojista: Para calcular esse serviço você precisa ter contrato com os Correios. 
Por gentileza você pode me ajudar a encontrar a solução?
Obrigada,Cris

**Comment by pedro-teixeira** [comment]
Pode postar aqui um printscreen da seleção de métodos?
