### ISSUE TITLE
Erro após desistalação

### ISSUE THREAD

**Issue by TecSecret** [pedro-teixeira/correios#85]
Após realizar a desinstalação o mesmo apresenta este erro: 

Catalogo/gerenciar produtos/editar produto
Magento versão 1.9.1.1
Instalação realizada usando o magento conect

_______________________________________
a:5:{i:0;s:101:"Modelo base "pedroteixeira_correios/source_postMethods" não encontrado para o atributo "postmethods"";i:1;s:3948:"#0 /app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(387): Mage::exception('Mage_Eav', 'Modelo base "pe...')
#1 /var/sentora/hostdata/pequistore/public_html/pequistore_com/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(203): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()
#2 
/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tab/Attributes.php(70): Mage_Adminhtml_Block_Widget_Form->_setFieldset(Array, Object(Varien_Data_Form_Element_Fieldset), Array)
#3 
/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(144): Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Attributes->_prepareForm()
#4 
/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Form->_beforeToHtml()
#5 
/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tabs.php(79): Mage_Core_Block_Abstract->toHtml()
#6 
/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Adminhtml_Block_Catalog_Product_Edit_Tabs->_prepareLayout()
#7 
/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#8 
/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'product_tabs')
#9 
/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/catal...', 'product_tabs')
#10 
/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#11 
/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#12 
/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#13 
/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#14 
/app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(Array, true, true)
#15 
/app/code/core/Mage/Adminhtml/controllers/Catalog/ProductController.php(250): Mage_Adminhtml_Controller_Action->loadLayout(Array)
#16 
/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_ProductController->editAction()
#17 
/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#18 
/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 
/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#20 /var/sentora/hostdata/pequistore/public_html/pequistore_com/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#21 
/index.php(87): Mage::run('', 'store')
#22 {main}";s:3:"url";s:82:"/index.php/admin/catalog_product/edit/id/204/key/40c6e11036608e3d4b51bf7496c425ef/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by jarjar123** [comment]
Olá @TecSecret 
Isso é porque durante a instalação foram criados alguns novos atributos, para o catálogo de produtos.
Você pode desativar esses atributos pelo backend.

1. Acessa __Catálogo > Atributos > Gerenciar Grupo de Atributos__
2. Seleciona um __Grupo de Atributos__ da lista.
3. Na página seguinte, localiza o atributo `postmethods`, na lista de __Grupos__.
4. Arrasta o atributo `postmethods` para a lista de __Atributos Não Assinados__.
5. Salva a alteração, e faz o mesmo para cada __Grupo de Atributos__.

Não testei, mas acredito que isso vai resolver.

**Comment by caevv** [comment]
Não funciona: 
> Você não pode remover atributos do sistema deste grupo.

**Comment by caevv** [comment]
Uma solução seria:

Criar um arquivo executar.php:
```php
<?php
include 'app/Mage.php';
Mage::app();
$setup = Mage::getResourceModel('catalog/setup','catalog_setup');
$setup->removeAttribute('catalog_product','postmethods');
```

Depois execute esse arquivo: `php executar.php`

**Comment by ivanaugustobd** [comment]
A solução proposta pelo @caevv pode ser simplificada em 
```php
Mage::getResourceModel('catalog/setup','catalog_setup')->removeAttribute('catalog_product','postmethods')
```
executando no console do Magerun (`magerun dev:console`), e funciona de boas com o Magento 1.9.3.7! :D
