### ISSUE TITLE
Frete grátis com prazo de entrega dos correios

### ISSUE THREAD

**Issue by guztavoalves** [pedro-teixeira/correios#86]
Boa tarde Pedro,
é possivel ativar frete grátis usando seu módulo e exibir o prazo de entrega dos correios para essa forma de envio? Estou usando a v4.4 do módulo no Magento 1.9 e ativei o método frete grátis do próprio Magento, defini um valor minimo e no seu módulo ativei o PAC como forma de envio para Frete Grátis, porem não é exibido o prazo de entrega nessa opção.

Tentei criando uma regra para aplicar o frete grátis acima de determinado valor, porem sem sucesso.
Estou fazendo algo errado ou o módulo não possui mesmo essa funcionalidade de exibir o prazo de entrega para Frete Grátis.

Obrigado

**Comment by Wulfgar666** [comment]
Eu tambem estou precisando dessa informação! alguém tem alguma ideia?

**Comment by Wulfgar666** [comment]
Gustavo, acabei descobrindo. Crie uma REGRA DE PROMOÇÃO, e em açoes, coloque Frete gratis para produtos. E crie a regra de preço pelo subtotal.

**Comment by Jackcar** [comment]
@Wulfgar666 Eu preciso deixar o frete grátis apenas com PAC para todo o Brasil e preciso que apareça o prazo de entrega também, sabe me especificar como posso fazer isto?
Obrigado

**Comment by Wulfgar666** [comment]
@Jackcar , primeiro vc entra no modulo do Pedro, define o frete gratis como pac, Crie uma REGRA DE PROMOÇÃO, e em açoes, coloque Frete gratis para produtos... especifique o valor e pronto
