### ISSUE TITLE
Modulo Pagseguro Envio Facil

### ISSUE THREAD

**Issue by magnored** [pedro-teixeira/correios#87]
Seria possivel ativar a opcao do envio facil do pagseguro no modulo ?
tendo em vista  que eles utilizam e-sedex para fazer o  envio das mercadorias, a unica diferença, é que nao temos acesso ao codigo do correios para liberar a função e-sedex no magento

**Comment by Veiote** [comment]
O EnvioFacil é exclusivo para compras pelo PagSeguro e tambem acho que eles não possuem webservice para consulta.
