### ISSUE TITLE
Erro ao calcular frete no carrinho

### ISSUE THREAD

**Issue by danielverissimo** [pedro-teixeira/correios#90]
Ao calcular o frete na tela do carrinho de compras, gera um erro de estouro de memória.

![screen_shot_2015-07-07_at_12_08_59](https://cloud.githubusercontent.com/assets/7152354/8549517/89100320-24a1-11e5-87e1-b4eef5e92aa0.jpg)

### Logs

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 130968 bytes) in /Users/danyelsanches/Documents/Carisma/site/workspace/carismalembrancas/lib/Zend/Db/Select.php on line 281 

### Passos para reproduzir

1. Adiciono um produto no carrinho
2. Abro a tela para visualizar o carrinho
3. Em "Calcular Frete e Imposto", preencho o campo País, Estado e CEP e seleciono o botão "calcular".

### Dados técnicos

* Versão do Magento: 1.9.1.1
* Versão do módulo: v4.3.0

**Comment by jarjar123** [comment]
Olá @danielverissimo, não consegui reproduzir o erro.
Mas é estranho não conseguir alocar só 130 KB (tried to allocate 130968 bytes).

Sugestão:

* Tenta descobrir algum erro oculto em outros logs, e manda pra verificarmos.
* E dá uma conferida no teu servidor, limites de memória do apache, php, mysql, etc.
