### ISSUE TITLE
Erro: Por favor, corrija o CEP digitado, ele não está correto.

### ISSUE THREAD

**Issue by rafaballack** [pedro-teixeira/correios#92]
http://i.imgur.com/1bVAa8a.png

Logs

Por favor, corrija o CEP digitado, ele não está correto.

Passos para reproduzir

1 Apos cadastrar todos os dados como o cep apresenta a mesma mensagem.

Dados técnicos

Versão do Magento: 1.7.0.2 
Versão do módulo: v4.4.0

**Comment by pedro-teixeira** [comment]
@rafaballack, está me parecendo que é um problema em algum outro módulo que você está usando. No print screen também não consigo ver se o CEP está digitado ou não.

**Comment by rafaballack** [comment]
Entendo, Estou verificando que o modulo OSC 6 está instalado. E quando desabilito funciona normal mostrando as opções de frete. Ha alguma possibilidade da hospedagem está interferindo em algo? Algum bloqueio ?

**Comment by jarjar123** [comment]
Sugiro olhar os logs do php (ex.: /var/log/php_error.log), e do magento (ex.: /www/var/log/system.php,exception.php).

**Comment by rafaballack** [comment]
OS únicos erros foram:

015-04-11T01:10:38+00:00 DEBUG (7): pedroteixeira_correios [312]: URL Error - Unable to Connect to tcp://ws.correios.com.br:80. Error #110: Connection timed out


2015-04-11T01:13:43+00:00 DEBUG (7): pedroteixeira_correios [82]: Invalid Zip Code

**Comment by rafaballack** [comment]
O mais estranho é que baixei tudo para o localhost e funciona normal. Será que algo em minha hospedagem está bloqueando?

**Comment by pedro-teixeira** [comment]
@rafaballack, esses dois logs são de ações diferentes, eles tem mais de 3 minutos de diferença.

O primeiro simplesmente não consegue se conectar com os Correios e o segundo o CEP digitado não está no formato esperado.

**Comment by rafaballack** [comment]
Descobri o problema. É o anti virus que está alertando a mensagem: Failed to load resource: the server responded with a status of 499 (Request has been forbidden by antivirus)

E logo em seguida mostra o link http://www.MINHALOJA.com.br/onestepcheckout/ajax/saveAddress/

Quando eu clico no link vai para:


{"success":false,"messages":["Especifique o endere\u00e7o de cobran\u00e7a"],"blocks":[],"grand_total":""}


Estranho que nao tem essa pagina na raiz onestepcheckout 

Vou verificar com o pessoal do onestepcheckout porque isso acontece.
