### ISSUE TITLE
Contrato 40436

### ISSUE THREAD

**Issue by rafaeldesio** [pedro-teixeira/correios#98]
Bom dia Pedro, tudo bem?
Utilizo o módulo a bastante tempo, sempre perfeito, parabéns.
Gostaria ,se possível de uma luz. Meu contrato nos correios é o sedex 40436.
Consigo alterar o 40096 para fazer a consulta do 40436 no webservice dos correios?
Quais arquivos teria que alterar?
Muito obrigado

Rafael

**Comment by pedro-teixeira** [comment]
@rafaeldesio, você pode alterar o https://github.com/pedro-teixeira/correios/blob/master/app/code/community/PedroTeixeira/Correios/etc/config.xml

**Comment by jarjar123** [comment]
Tb uso esse contrato. Seria interessante adicioná-lo na próxima versão.

**Comment by pedro-teixeira** [comment]
Sim, seria ótimo.

**Comment by rafaeldesio** [comment]
Obrigado pela resposta Pedro
Substitui no arquivo as incidências do 40096 para  40436
No admin o 40096 manteve-se. Mesmo assim selecionei  o 40096 imaginando que
o módulo enviaria as informações do 40436
para o webservice, mas não deu certo.
 O sedex parou de responder no site. Só aparece e-sedex e pac.
Pelo meu usuário e senha não consigo utilizar o 40096. Tenho que selecionar
o sedex sem contrato, que acaba encarecendo muito o frete...
Obrigado novamente


2015-07-20 9:03 GMT-03:00 Pedro Teixeira <notifications@github.com>:

**Comment by rafaeldesio** [comment]
Substitui em todos arquivos e funcionou agora funcionou
Obrigado
