### ISSUE TITLE
Sedex x e-sedex

### ISSUE THREAD

**Issue by rafaeldesio** [pedro-teixeira/correios#99]
Segue uma sugestão de melhoria.
Verifico no dia a dia uma certa confusão de clientes pouco experiêntes com relação as nomenclaturas  sedex e  e-sedex.
Sugiro que quando o município possuir o "e-sedex", o "sedex" não seja apresentado. Como é o mesmo prazo e só o valor que muda, os clientes se perdem... 
Tenho vendas que os clientes escolhem o sedex, 15 reais mais caro, provavelmente por não entenderem oque é "e-sedex"...
Imagino que outros clientes simplesmente abandonem a compra por não entenderem.
A informação seria apresentada de maneira mais simples, ajudando na conversão.
obrigado, um abraço

Rafael Desio

**Comment by jarjar123** [comment]
Faz sentido.
Mas acho que seria melhor exibir o mais barato entre os dois métodos. Já vi alguns casos onde o SEDEX é mais barato mesmo.

**Comment by rafaeldesio** [comment]
Perfeito


Em 20 de julho de 2015 15:57, jarjar123 <notifications@github.com> escreveu:

**Comment by jarjar123** [comment]
Enquanto não sai a PR, vc pode alterar o nome do método no arquivo de configuração `config.xml`.

    <serv_81019>E-Sedex,3</serv_81019>

Se alterar o nome para _Sedex_, os clientes devem escolher o mais barato.

    <serv_81019>Sedex,3</serv_81019>

**Comment by aandrade1234** [comment]
Srs, notem que em alguns casos quando o produto é presado o ESEDEX sai mais caro que o SEDEX. Isso vai depender do contrato de SEDEX que possuir. É melhor deixar como está ou então colocar uma lógica para exibir o mais barato.

**Comment by rafaeldesio** [comment]
Com a regra do menor preço, ficaria perfeito.
Hoje tenho vários clientes que escolhem o sedex mais caro, provavelmente
por não entender oque é o e-sedex...
Imagino que vários escolham sair da loja. Assim o módulo ficaria melhor
ainda
parabens pelo trabalho de vcs

Em 23 de julho de 2015 19:00, André Gustavo de Andrade <
notifications@github.com> escreveu:
